package.path=package.path..";../Samples/ysscripts/lib/?.lua" --;"..package.path
require("utilfunc")

package.path=package.path..";../Samples/ysscripts/samples/?.lua" --;"..package.path
require("useCaseMuscle_gait1956_6steps")


useCases.full_same=deepCopyTable(useCases.gait1956_6steps)

useCases.full_same.optimizerMethod='Optimizer.methods.CMAes_ys'

useCases.full_same.endSegW=10
useCases.full_same.prec=.2

useCases.full_same.modelName='full_same'
useCases.full_same.grpName='full_same'
useCases.full_same.grpNames={'full_same'}

--useCases.full_same.ddqObjWeight=100000000*25
--useCases.full_same.aObjWeight=10000000000*62
--useCases.full_same.lambdaObjWeight=1000
--useCases.full_same.EEobjWeight=100000000
--useCases.full_same.EEobjWeightAngular=60000000
--useCases.full_same.momentumWeight=8000000

--useCases.full_same.ddqObjWeight=100000*(25-7)
--useCases.full_same.aObjWeight=1000000*62
--useCases.full_same.lambdaObjWeight=1
--useCases.full_same.EEobjWeight=1000000
--useCases.full_same.EEobjWeightAngular=100000
--useCases.full_same.momentumWeight=100000

--useCases.full_same.ddqObjWeight=20000000*(25-7)
--useCases.full_same.aObjWeight=100000000*62
--useCases.full_same.lambdaObjWeight=.1
--useCases.full_same.EEobjWeight=10000000
--useCases.full_same.EEobjWeightAngular=1000000
--useCases.full_same.momentumWeight=1000000

--useCases.full_same.ddqObjWeight=10000000*(25-7)
--useCases.full_same.aObjWeight=10000000*62
--useCases.full_same.lambdaObjWeight=.1
--useCases.full_same.EEobjWeight=1
--useCases.full_same.EEobjWeightAngular=1
--useCases.full_same.momentumWeight=1000000

--useCases.full_same.ddqObjWeight=10000000*(25-7)
--useCases.full_same.aObjWeight=100000000*62
--useCases.full_same.lambdaObjWeight=100
--useCases.full_same.EEobjWeight=10000000
--useCases.full_same.EEobjWeightAngular=100
--useCases.full_same.momentumWeight=10000000

--useCases.full_same.ddqObjWeight=100000*(25-7)
--useCases.full_same.aObjWeight=5000*62
--useCases.full_same.lambdaObjWeight=.0001
--useCases.full_same.EEobjWeight=100000
--useCases.full_same.EEobjWeightAngular=10
--useCases.full_same.momentumWeight=1000000

--useCases.full_same.ddqObjWeight=50000*(25-7)
--useCases.full_same.aObjWeight=5000*62
--useCases.full_same.lambdaObjWeight=.001
--useCases.full_same.EEobjWeight=100000
--useCases.full_same.EEobjWeightAngular=10
--useCases.full_same.momentumWeight=50000

--useCases.full_same.ddqObjWeight=50000*(25-7)
--useCases.full_same.aObjWeight=5000*62
--useCases.full_same.lambdaObjWeight=.0001
--useCases.full_same.EEobjWeight=1000
--useCases.full_same.EEobjWeightAngular=1
--useCases.full_same.momentumWeight=20000

--useCases.full_same.ddqObjWeight=200000*(25-7)
--useCases.full_same.aObjWeight=5000*62
--useCases.full_same.lambdaObjWeight=.0001
--useCases.full_same.EEobjWeight=10000
--useCases.full_same.EEobjWeightAngular=10
--useCases.full_same.momentumWeight=100000

useCases.full_same.ddqObjWeight=100000*(25-7)
useCases.full_same.aObjWeight=5000*62
useCases.full_same.lambdaObjWeight=.001
useCases.full_same.EEobjWeight=100000
useCases.full_same.EEobjWeightAngular=10
useCases.full_same.momentumWeight=1000000


--useCases.full_same.contactMargin=.005

-- the initial pendControlParam and pendOptimizationPath can be automatically generated by using createInitialPendControlParam.lua
useCases.full_same.pendControlParam=
{
['keyframe,0,pendDesiredVel,full_same,l,z']=0,['keyframe,0,pendDesiredVel,full_same,l,x']=1,['keyframe,0,pendDesiredVel,full_same,r,z']=0,['keyframe,0,pendDesiredVel,full_same,r,x']=1,['keyframe,0,pendDesiredVel,full_same,L1,z']=0,['keyframe,0,pendDesiredVel,full_same,L1,x']=1,['keyframe,0,pendDesiredVel,full_same,R1,z']=0,['keyframe,0,pendDesiredVel,full_same,R1,x']=1,['keyframe,0,pendDesiredVel,full_same,L2,z']=0,['keyframe,0,pendDesiredVel,full_same,L2,x']=1,['keyframe,0,pendDesiredVel,ignore,0,z']=0,['keyframe,0,pendDesiredVel,ignore,0,x']=1,['keyframe,0,pendDesiredVel,ignore,1,z']=0,['keyframe,0,pendDesiredVel,ignore,1,x']=1,
['keyframe,0,pendDesiredVel,ignore,0,x']=0.74880014577683, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.27116103631783, ['keyframe,0,pendDesiredVel,full_same,l,x']=0.88737043527708, ['keyframe,0,pendDesiredVel,full_same,l,z']=-0.11416295837202, ['keyframe,0,pendDesiredVel,full_same,r,x']=0.98020115547934, ['keyframe,0,pendDesiredVel,full_same,r,z']=-0.0059296383640206, ['keyframe,0,pendDesiredVel,full_same,L1,x']=1.0378897594248, ['keyframe,0,pendDesiredVel,full_same,L1,z']=0.034216650665077, ['keyframe,0,pendDesiredVel,full_same,R1,x']=1.0262612666646, ['keyframe,0,pendDesiredVel,full_same,R1,z']=0.043291432670681, ['keyframe,0,pendDesiredVel,full_same,L2,x']=1.0118368747056, ['keyframe,0,pendDesiredVel,full_same,L2,z']=0.017958840875873, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.99461027916552, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.0034491731929867, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.74878537473186, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.27119424660752, ['keyframe,0,pendDesiredVel,full_same,l,x']=0.88736689346762, ['keyframe,0,pendDesiredVel,full_same,l,z']=-0.11418522683857, ['keyframe,0,pendDesiredVel,full_same,r,x']=0.98020480273406, ['keyframe,0,pendDesiredVel,full_same,r,z']=-0.0059450126574085, ['keyframe,0,pendDesiredVel,full_same,L1,x']=1.03787852388, ['keyframe,0,pendDesiredVel,full_same,L1,z']=0.034202839340711, ['keyframe,0,pendDesiredVel,full_same,R1,x']=1.0262541904637, ['keyframe,0,pendDesiredVel,full_same,R1,z']=0.043272865357609, ['keyframe,0,pendDesiredVel,full_same,L2,x']=1.0118302340958, ['keyframe,0,pendDesiredVel,full_same,L2,z']=0.017955948697287, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.99461120591573, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.0034470410408646, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.74878317705678, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.27119917586908, ['keyframe,0,pendDesiredVel,full_same,l,x']=0.88736637468197, ['keyframe,0,pendDesiredVel,full_same,l,z']=-0.1141885262983, ['keyframe,0,pendDesiredVel,full_same,r,x']=0.98020535280917, ['keyframe,0,pendDesiredVel,full_same,r,z']=-0.0059472860310628, ['keyframe,0,pendDesiredVel,full_same,L1,x']=1.0378768529694, ['keyframe,0,pendDesiredVel,full_same,L1,z']=0.034200792962745, ['keyframe,0,pendDesiredVel,full_same,R1,x']=1.0262531364792, ['keyframe,0,pendDesiredVel,full_same,R1,z']=0.043270103293285, ['keyframe,0,pendDesiredVel,full_same,L2,x']=1.0118292441021, ['keyframe,0,pendDesiredVel,full_same,L2,z']=0.017955520125658, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.99461134417558, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.0034467225611953, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.55103072365768, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.47389612042309, ['keyframe,0,pendDesiredVel,full_same,l,x']=1.0952528065777, ['keyframe,0,pendDesiredVel,full_same,l,z']=0.048153740716962, ['keyframe,0,pendDesiredVel,full_same,r,x']=1.0626926372986, ['keyframe,0,pendDesiredVel,full_same,r,z']=0.086221078019802, ['keyframe,0,pendDesiredVel,full_same,L1,x']=1.0129457610499, ['keyframe,0,pendDesiredVel,full_same,L1,z']=0.013149804843574, ['keyframe,0,pendDesiredVel,full_same,R1,x']=0.96110921487485, ['keyframe,0,pendDesiredVel,full_same,R1,z']=-0.037828332305964, ['keyframe,0,pendDesiredVel,full_same,L2,x']=0.98603661346432, ['keyframe,0,pendDesiredVel,full_same,L2,z']=0.039082011455386, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.99059439850038, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.00093734740439972, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.5510546266821, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.47367161876198, ['keyframe,0,pendDesiredVel,full_same,l,x']=1.0951839385861, ['keyframe,0,pendDesiredVel,full_same,l,z']=0.048267130552062, ['keyframe,0,pendDesiredVel,full_same,r,x']=1.0627455632243, ['keyframe,0,pendDesiredVel,full_same,r,z']=0.086424135267191, ['keyframe,0,pendDesiredVel,full_same,L1,x']=1.0130030025796, ['keyframe,0,pendDesiredVel,full_same,L1,z']=0.013302189438479, ['keyframe,0,pendDesiredVel,full_same,R1,x']=0.96110432918996, ['keyframe,0,pendDesiredVel,full_same,R1,z']=-0.037744547433483, ['keyframe,0,pendDesiredVel,full_same,L2,x']=0.98601371211574, ['keyframe,0,pendDesiredVel,full_same,L2,z']=0.039063544993718, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.99059463647058, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.00093981704708983, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.551059213738, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.47362559267138, ['keyframe,0,pendDesiredVel,full_same,l,x']=1.0951711424087, ['keyframe,0,pendDesiredVel,full_same,l,z']=0.048291619239131, ['keyframe,0,pendDesiredVel,full_same,r,x']=1.0627557208846, ['keyframe,0,pendDesiredVel,full_same,r,z']=0.086465334690593, ['keyframe,0,pendDesiredVel,full_same,L1,x']=1.013014194968, ['keyframe,0,pendDesiredVel,full_same,L1,z']=0.01333308993033, ['keyframe,0,pendDesiredVel,full_same,R1,x']=0.96110342775144, ['keyframe,0,pendDesiredVel,full_same,R1,z']=-0.037727460524337, ['keyframe,0,pendDesiredVel,full_same,L2,x']=0.98600939273317, ['keyframe,0,pendDesiredVel,full_same,L2,z']=0.039060406048001, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.99059468236352, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.00094026922906751, 
}
useCases.full_same.pendOptimizationPath=
{
	firstFrames={1*4,21*4,41*4,61*4,81*4,101*4,121*4,139*4},
	segments={'ignore,0','full_same,l','full_same,r','full_same,L1','full_same,R1','full_same,L2','ignore,1'},
}
--useCases.full_same.measureOptCost=useCases.measureOptCost

useCases.full_same.segmentations=
{
	full_same={
		firstFrames={1*4,21*4,41*4,61*4,81*4,101*4,121*4,139*4},
		--        (blank)    L    R     L     R     L     (blank)
		names={             'l', 'r', 'L1', 'R1', 'L2',  },
		swingL={             0,   1,   0,    1,    0,    },
		swingR={             1,   0,   1,    0,    1,    },
		footRefL= "convertFromSwingL",
		footRefR= "convertFromSwingR",
		usePositionControl=false,
	},
}
useCases.full_same.graphParam=
{
	full_same={
		seg={            'l',  'r',  'L1', 'R1','L'},
		num_key={         3,    3,    3  ,  4,  4},
		key_first={       0,    0,    0  ,  0,  0},
		key_last={       'r', 'L1',  'R1', 'L', 'R1'},
	},
}
useCases.full_same.graph=
{
	{
		"addInterpolatedSegment",
		grpName="full_same",
		name="L",
		seg0={"full_same", "L2"},
		seg1={"full_same", "L1"},
		startWeight=0, endWeight=1
	},
	{"connectMulti", "full_same", "l", "r", "L1", "R1", "L", "R1"},
	--{"initialSegment", "full_same", "l"}
	--{"initialSegment", "full_same", "r"}
	{"initialSegment", "full_same", "R1"}
}
useCases.full_same.segNames=
{
	"l", "r", "L1", 'R1','L',
}

do 
	useCases.full_same.controlParam={
		['useCases,full_same,COMobjWeight']=0, 
		['useCases,full_same,conservativeW']=1, 
		--['useCases,full_same,contactMargin']=0.01, 
		['useCases,full_same,dotMomentumScale']=0.3, 
		['useCases,full_same,excludeRoot']=true, 
		['useCases,full_same,headControlWeight']=0, 
		['useCases,full_same,k_d_HEAD']=14, 
		['useCases,full_same,k_p_HEAD']=0, 
		['useCases,full_same,k_d_EE']=24, 
		['useCases,full_same,k_d_momentum']=10, 
		['useCases,full_same,k_p_EE']=120, 

		--['useCases,full_same,maxPenetratingVel']=0, 
		['useCases,full_same,momentumThr']=50, 
		['useCases,full_same,noComvelDependentFootAdjustment']=true, 
		['useCases,full_same,noIntersectionPrevenction']=true, 
		['useCases,full_same,numericalDerivDmot']=true, 
		['useCases,full_same,perClassContactMargin']=1, 
		['useCases,full_same,turnGain']=10, 
		['useCases,full_same,velMarginOffset']=0, 

		['useCases,full_same,actuationType']      = useCases.full_same.actuationType,
		['useCases,full_same,k_p_ID']             = useCases.full_same.k_p_ID,
		['useCases,full_same,k_d_ID']             = useCases.full_same.k_d_ID,
		['useCases,full_same,ddqObjWeight']       = useCases.full_same.ddqObjWeight,
		['useCases,full_same,tauObjWeight']       = useCases.full_same.tauObjWeight,
		['useCases,full_same,ftObjWeight']        = useCases.full_same.ftObjWeight,
		['useCases,full_same,aObjWeight']         = useCases.full_same.aObjWeight,
		['useCases,full_same,lambdaObjWeight']    = useCases.full_same.lambdaObjWeight,
		['useCases,full_same,EEobjWeight']        = useCases.full_same.EEobjWeight,
		['useCases,full_same,EEobjWeightAngular'] = useCases.full_same.EEobjWeightAngular,
		['useCases,full_same,momentumWeight']     = useCases.full_same.momentumWeight,
		['useCases,full_same,tauMax']             = useCases.full_same.tauMax,
		['useCases,full_same,ftMax']              = useCases.full_same.ftMax,
	}

	local function accumulate(cp_mod)
		local useCase=useCases.full_same
		useCases.accumulate(useCase, cp_mod)
	end

	accumulate({
		--['keyframe,0,footRmod,full_same,l,y']  = 0.,
		--['keyframe,1,footRmod,full_same,l,y']  = 0.05,
		--['keyframe,0,footLmod,full_same,r,y']  = 0.0,
		--['keyframe,1,footLmod,full_same,r,y']  = -0.4,
		--['keyframe,0,footLmod,full_same,r,x']  = -0.0,
		--['keyframe,1,footLmod,full_same,r,x']  = -0.4,
		--['keyframe,0,footRmod,full_same,L1,y'] = 0.0,
		--['keyframe,1,footRmod,full_same,L1,y'] = 0.2,
		--['map,0,swingFootMod,full_same,y']     = 0.1,
		--['map,1,swingFootMod,full_same,y']     = 0.2,
		--['map,2,swingFootMod,full_same,y']     = 0.1,

		----['keyframe,0,footLmod,full_same,l,y']  = 0.,
		----['keyframe,1,footLmod,full_same,l,y']  = 0.,
		--['keyframe,0,footRmod,full_same,r,y']  = 0.,
		--['keyframe,1,footRmod,full_same,r,y']  = .0,
		--['keyframe,0,footLmod,full_same,L1,y'] = 0.,
		--['keyframe,1,footLmod,full_same,L1,y'] = -.1,
		--['map,0,spprtFootMod,full_same,y']     = 0.,
		--['map,1,spprtFootMod,full_same,y']     = 0.,
		--['map,2,spprtFootMod,full_same,y']     = 0.,
	})
	useCases.unmapControlParam(useCases.full_same)

-------------------------------------------------
if g_mode=='default' then
	--iter:171 bestfvever:1.7263686888302e-06
	accumulate({['map,0,swingFootMod,full_same,x']= 0.73795196211407, ['map,0,swingFootMod,full_same,y']= -0.80327705446763, ['map,0,swingFootMod,full_same,z']= 0.50534496656882, ['map,1,swingFootMod,full_same,x']= -0.35825282098625, ['map,1,swingFootMod,full_same,y']= 0.48098979169708, ['map,1,swingFootMod,full_same,z']= 0.10442686220723, ['map,2,swingFootMod,full_same,x']= -0.054241346585369, ['map,2,swingFootMod,full_same,y']= -0.17226055154192, ['map,2,swingFootMod,full_same,z']= -0.1455859858063, ['map,0,spprtFootMod,full_same,x']= 0.20144960054259, ['map,0,spprtFootMod,full_same,y']= -1.7126290519574, ['map,0,spprtFootMod,full_same,z']= 0.40819371576194, ['map,1,spprtFootMod,full_same,x']= -0.21168780419606, ['map,1,spprtFootMod,full_same,y']= -0.47053443673874, ['map,1,spprtFootMod,full_same,z']= 0.22809161876505, ['map,2,spprtFootMod,full_same,x']= -0.29809033175791, ['map,2,spprtFootMod,full_same,y']= -1.0801637778325, ['map,2,spprtFootMod,full_same,z']= 0.40476289190896, })
end
-------------------------------------------------

useCases.unmapControlParam(useCases.full_same)
end


