package.path=package.path..";../Samples/ysscripts/lib/?.lua" --;"..package.path
require("utilfunc")

package.path=package.path..";../Samples/ysscripts/samples/?.lua" --;"..package.path
require("useMuscle_full_same")


useCases.full_srun=deepCopyTable(useCases.full_same)

useCases.full_srun.optimizerMethod='Optimizer.methods.CMAes_ys'

useCases.full_srun.endSegW=20
useCases.full_srun.prec=.2
--useCases.full_srun.endSegW=20
--useCases.full_srun.prec=.05

useCases.full_srun.modelName='full_srun'
useCases.full_srun.grpName='full_srun'
useCases.full_srun.grpNames={'full_srun'}

--useCases.full_srun.ddqObjWeight=20000000*(25-7)
--useCases.full_srun.aObjWeight=100000000*62
--useCases.full_srun.lambdaObjWeight=.1
--useCases.full_srun.EEobjWeight=10000000
--useCases.full_srun.EEobjWeightAngular=1000000
--useCases.full_srun.momentumWeight=1000000

-- the initial pendControlParam and pendOptimizationPath can be automatically generated by using createInitialPendControlParam.lua
useCases.full_srun.pendControlParam=
{
['keyframe,0,pendDesiredVel,full_srun,l,z']=0,['keyframe,0,pendDesiredVel,full_srun,l,x']=1,['keyframe,0,pendDesiredVel,full_srun,r,z']=0,['keyframe,0,pendDesiredVel,full_srun,r,x']=1,['keyframe,0,pendDesiredVel,full_srun,L1,z']=0,['keyframe,0,pendDesiredVel,full_srun,L1,x']=1,['keyframe,0,pendDesiredVel,full_srun,R1,z']=0,['keyframe,0,pendDesiredVel,full_srun,R1,x']=1,['keyframe,0,pendDesiredVel,full_srun,L2,z']=0,['keyframe,0,pendDesiredVel,full_srun,L2,x']=1,['keyframe,0,pendDesiredVel,ignore,0,z']=0,['keyframe,0,pendDesiredVel,ignore,0,x']=1,['keyframe,0,pendDesiredVel,ignore,1,z']=0,['keyframe,0,pendDesiredVel,ignore,1,x']=1,
['keyframe,0,pendDesiredVel,ignore,0,x']=-0.35767289006965, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.44807370212594, ['keyframe,0,pendDesiredVel,full_srun,l,x']=1.0180451856619, ['keyframe,0,pendDesiredVel,full_srun,l,z']=0.15805859147666, ['keyframe,0,pendDesiredVel,full_srun,r,x']=0.79124545399388, ['keyframe,0,pendDesiredVel,full_srun,r,z']=-0.02048408700085, ['keyframe,0,pendDesiredVel,full_srun,L1,x']=0.51916446242951, ['keyframe,0,pendDesiredVel,full_srun,L1,z']=0.020088927856808, ['keyframe,0,pendDesiredVel,full_srun,R1,x']=0.5098976587487, ['keyframe,0,pendDesiredVel,full_srun,R1,z']=-0.054098495157611, ['keyframe,0,pendDesiredVel,full_srun,L2,x']=0.74127062014114, ['keyframe,0,pendDesiredVel,full_srun,L2,z']=-0.11401430652775, ['keyframe,0,pendDesiredVel,ignore,1,x']=1.0238724760698, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.006035699085617, 
['keyframe,0,pendDesiredVel,ignore,0,x']=-0.35757018365303, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.44793704421198, ['keyframe,0,pendDesiredVel,full_srun,l,x']=1.0181028548675, ['keyframe,0,pendDesiredVel,full_srun,l,z']=0.15813427516858, ['keyframe,0,pendDesiredVel,full_srun,r,x']=0.79129845383915, ['keyframe,0,pendDesiredVel,full_srun,r,z']=-0.020432135478896, ['keyframe,0,pendDesiredVel,full_srun,L1,x']=0.51916845914068, ['keyframe,0,pendDesiredVel,full_srun,L1,z']=0.020091944372944, ['keyframe,0,pendDesiredVel,full_srun,R1,x']=0.50987611766569, ['keyframe,0,pendDesiredVel,full_srun,R1,z']=-0.054106190924225, ['keyframe,0,pendDesiredVel,full_srun,L2,x']=0.74126265991833, ['keyframe,0,pendDesiredVel,full_srun,L2,z']=-0.11401605309702, ['keyframe,0,pendDesiredVel,ignore,1,x']=1.0238737830602, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.0060359623776214, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.27155378679456, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.14833610764373, ['keyframe,0,pendDesiredVel,full_srun,l,x']=0.38808808718903, ['keyframe,0,pendDesiredVel,full_srun,l,z']=-0.10234962166034, ['keyframe,0,pendDesiredVel,full_srun,r,x']=0.51384026859666, ['keyframe,0,pendDesiredVel,full_srun,r,z']=-0.058252119384794, ['keyframe,0,pendDesiredVel,full_srun,L1,x']=0.59639208991231, ['keyframe,0,pendDesiredVel,full_srun,L1,z']=-0.037837555350624, ['keyframe,0,pendDesiredVel,full_srun,R1,x']=0.63640621329316, ['keyframe,0,pendDesiredVel,full_srun,R1,z']=-0.04705270971781, ['keyframe,0,pendDesiredVel,full_srun,L2,x']=0.64974520177864, ['keyframe,0,pendDesiredVel,full_srun,L2,z']=-0.064201187639779, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.65554627288268, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.072749144917743, 
['keyframe,0,pendDesiredVel,ignore,0,x']=-0.25307177642288, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.40514975687258, ['keyframe,0,pendDesiredVel,full_srun,l,x']=0.8211529225375, ['keyframe,0,pendDesiredVel,full_srun,l,z']=0.062546382226614, ['keyframe,0,pendDesiredVel,full_srun,r,x']=0.84923342933044, ['keyframe,0,pendDesiredVel,full_srun,r,z']=0.053526576066267, ['keyframe,0,pendDesiredVel,full_srun,L1,x']=0.5922852092562, ['keyframe,0,pendDesiredVel,full_srun,L1,z']=0.033181081682747, ['keyframe,0,pendDesiredVel,full_srun,R1,x']=0.50031526963899, ['keyframe,0,pendDesiredVel,full_srun,R1,z']=-0.070451814661557, ['keyframe,0,pendDesiredVel,full_srun,L2,x']=0.57337328382062, ['keyframe,0,pendDesiredVel,full_srun,L2,z']=-0.12059405900701, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.66429822132415, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.069250483859507, 
['keyframe,0,pendDesiredVel,ignore,0,x']=-0.25293561884076, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.40504152402282, ['keyframe,0,pendDesiredVel,full_srun,l,x']=0.82120563953325, ['keyframe,0,pendDesiredVel,full_srun,l,z']=0.062597344826014, ['keyframe,0,pendDesiredVel,full_srun,r,x']=0.84928643882301, ['keyframe,0,pendDesiredVel,full_srun,r,z']=0.05357584312519, ['keyframe,0,pendDesiredVel,full_srun,L1,x']=0.59229927711432, ['keyframe,0,pendDesiredVel,full_srun,L1,z']=0.033193133719518, ['keyframe,0,pendDesiredVel,full_srun,R1,x']=0.50029536837458, ['keyframe,0,pendDesiredVel,full_srun,R1,z']=-0.070452815258553, ['keyframe,0,pendDesiredVel,full_srun,L2,x']=0.57335847509539, ['keyframe,0,pendDesiredVel,full_srun,L2,z']=-0.12059397747416, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.66429937416347, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.069250582891468, 
['keyframe,0,pendDesiredVel,ignore,0,x']=-0.25292164737028, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.40503039533016, ['keyframe,0,pendDesiredVel,full_srun,l,x']=0.8212111709822, ['keyframe,0,pendDesiredVel,full_srun,l,z']=0.062602648740409, ['keyframe,0,pendDesiredVel,full_srun,r,x']=0.84929193569425, ['keyframe,0,pendDesiredVel,full_srun,r,z']=0.053580934046921, ['keyframe,0,pendDesiredVel,full_srun,L1,x']=0.59230078653118, ['keyframe,0,pendDesiredVel,full_srun,L1,z']=0.033194432322497, ['keyframe,0,pendDesiredVel,full_srun,R1,x']=0.50029341255496, ['keyframe,0,pendDesiredVel,full_srun,R1,z']=-0.070452875751183, ['keyframe,0,pendDesiredVel,full_srun,L2,x']=0.57335699439225, ['keyframe,0,pendDesiredVel,full_srun,L2,z']=-0.1205939577618, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.66429948838569, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.069250594462161, 
}
useCases.full_srun.pendOptimizationPath=
{
	firstFrames={1*4,11*4,21*4,31*4,41*4,51*4,61*4,71*4},
	segments={'ignore,0','full_srun,l','full_srun,r','full_srun,L1','full_srun,R1','full_srun,L2','ignore,1'},
}
--useCases.full_srun.measureOptCost=useCases.measureOptCost

useCases.full_srun.segmentations=
{
	full_srun={
		firstFrames={1*4,11*4,21*4,31*4,41*4,51*4,61*4,71*4},
		--        (blank)    L    R     L     R     L     (blank)
		names={             'l', 'r', 'L1', 'R1', 'L2',  },
		swingL={             0,   1,   0,    1,    0,    },
		swingR={             1,   0,   1,    0,    1,    },
		footRefL= "convertFromSwingL",
		footRefR= "convertFromSwingR",
		usePositionControl=false,
	},
}
useCases.full_srun.graphParam=
{
	full_srun={
		seg={            'l',  'r',  'L1', 'R1','L'},
		num_key={         3,    3,    3  ,  4,  4},
		key_first={       0,    0,    0  ,  0,  0},
		key_last={       'r', 'L1',  'R1', 'L', 'R1'},
	},
}
useCases.full_srun.graph=
{
	{
		"addInterpolatedSegment",
		grpName="full_srun",
		name="L",
		seg0={"full_srun", "L2"},
		seg1={"full_srun", "L1"},
		startWeight=0, endWeight=1
	},
	{"connectMulti", "full_srun", "l", "r", "L1", "R1", "L", "R1"},
	--{"initialSegment", "full_srun", "l"}
	{"initialSegment", "full_srun", "R1"}
}
useCases.full_srun.segNames=
{
	"l", "r", "L1", 'R1','L',
}

do 
	useCases.full_srun.controlParam={
		['useCases,full_srun,COMobjWeight']=0, 
		['useCases,full_srun,conservativeW']=1, 
		--['useCases,full_srun,contactMargin']=0.01, 
		['useCases,full_srun,dotMomentumScale']=0.3, 
		['useCases,full_srun,excludeRoot']=true, 
		['useCases,full_srun,headControlWeight']=0, 
		['useCases,full_srun,k_d_HEAD']=14, 
		['useCases,full_srun,k_p_HEAD']=0, 
		['useCases,full_srun,k_d_EE']=24, 
		['useCases,full_srun,k_d_momentum']=10, 
		['useCases,full_srun,k_p_EE']=120, 

		--['useCases,full_srun,maxPenetratingVel']=0, 
		['useCases,full_srun,momentumThr']=50, 
		['useCases,full_srun,noComvelDependentFootAdjustment']=true, 
		['useCases,full_srun,noIntersectionPrevenction']=true, 
		['useCases,full_srun,numericalDerivDmot']=true, 
		['useCases,full_srun,perClassContactMargin']=1, 
		['useCases,full_srun,turnGain']=10, 
		['useCases,full_srun,velMarginOffset']=0, 

		['useCases,full_srun,actuationType']      = useCases.full_srun.actuationType,
		['useCases,full_srun,k_p_ID']             = useCases.full_srun.k_p_ID,
		['useCases,full_srun,k_d_ID']             = useCases.full_srun.k_d_ID,
		['useCases,full_srun,ddqObjWeight']       = useCases.full_srun.ddqObjWeight,
		['useCases,full_srun,tauObjWeight']       = useCases.full_srun.tauObjWeight,
		['useCases,full_srun,ftObjWeight']        = useCases.full_srun.ftObjWeight,
		['useCases,full_srun,aObjWeight']         = useCases.full_srun.aObjWeight,
		['useCases,full_srun,lambdaObjWeight']    = useCases.full_srun.lambdaObjWeight,
		['useCases,full_srun,EEobjWeight']        = useCases.full_srun.EEobjWeight,
		['useCases,full_srun,EEobjWeightAngular'] = useCases.full_srun.EEobjWeightAngular,
		['useCases,full_srun,momentumWeight']     = useCases.full_srun.momentumWeight,
		['useCases,full_srun,tauMax']             = useCases.full_srun.tauMax,
		['useCases,full_srun,ftMax']              = useCases.full_srun.ftMax,
	}

	local function accumulate(cp_mod)
		local useCase=useCases.full_srun
		useCases.accumulate(useCase, cp_mod)
	end

	accumulate({
		----['keyframe,0,footRmod,full_srun,l,y']  = 0.,
		----['keyframe,1,footRmod,full_srun,l,y']  = 0.05,
		--['keyframe,0,footLmod,full_srun,r,y']  = 0.0,
		--['keyframe,1,footLmod,full_srun,r,y']  = 0.2,
		--['keyframe,0,footRmod,full_srun,L1,y'] = 0.0,
		--['keyframe,1,footRmod,full_srun,L1,y'] = 0.2,
		--['map,0,swingFootMod,full_srun,y']     = 0.1,
		--['map,1,swingFootMod,full_srun,y']     = 0.2,
		--['map,2,swingFootMod,full_srun,y']     = 0.1,

		----['keyframe,0,footLmod,full_srun,l,y']  = 0.,
		----['keyframe,1,footLmod,full_srun,l,y']  = 0.,
		--['keyframe,0,footRmod,full_srun,r,y']  = 0.,
		--['keyframe,1,footRmod,full_srun,r,y']  = -.1,
		--['keyframe,0,footLmod,full_srun,L1,y'] = 0.,
		--['keyframe,1,footLmod,full_srun,L1,y'] = -.1,
		--['map,0,spprtFootMod,full_srun,y']     = 0.,
		--['map,1,spprtFootMod,full_srun,y']     = 0.,
		--['map,2,spprtFootMod,full_srun,y']     = 0.,
	})
	useCases.unmapControlParam(useCases.full_srun)


-------------------------------------------------
if g_mode=='default' then
	--old weight
	----iter:380 bestfvever:2.6040196749138e-06
	--accumulate({['map,0,swingFootMod,full_srun,x']= -0.13513400644767, ['map,0,swingFootMod,full_srun,y']= 0.62502346263463, ['map,0,swingFootMod,full_srun,z']= -0.73644153582543, ['map,1,swingFootMod,full_srun,x']= 1.1350019459923, ['map,1,swingFootMod,full_srun,y']= 1.9190738922511, ['map,1,swingFootMod,full_srun,z']= -0.02321278068933, ['map,2,swingFootMod,full_srun,x']= -2.1390140687242, ['map,2,swingFootMod,full_srun,y']= -0.31199880837296, ['map,2,swingFootMod,full_srun,z']= -0.91053175242665, ['map,0,spprtFootMod,full_srun,x']= 2.2129085619938, ['map,0,spprtFootMod,full_srun,y']= 0.065994297444483, ['map,0,spprtFootMod,full_srun,z']= -0.58015897447808, ['map,1,spprtFootMod,full_srun,x']= 0.11168578295742, ['map,1,spprtFootMod,full_srun,y']= -2.0601935012565, ['map,1,spprtFootMod,full_srun,z']= -0.45716511433674, ['map,2,spprtFootMod,full_srun,x']= 0.91430219057822, ['map,2,spprtFootMod,full_srun,y']= -4.2918343598176, ['map,2,spprtFootMod,full_srun,z']= 1.1029619631515, })

	----iter:1039 bestfvever:241710.69512044
	--accumulate({['map,0,swingFootMod,full_srun,x']= -0.086070983031214, ['map,0,swingFootMod,full_srun,y']= 0.026692950633571, ['map,0,swingFootMod,full_srun,z']= -0.049999080564127, ['map,1,swingFootMod,full_srun,x']= 0.021925389888293, ['map,1,swingFootMod,full_srun,y']= 0.0837790807207, ['map,1,swingFootMod,full_srun,z']= 0.0025146198304996, ['map,2,swingFootMod,full_srun,x']= 0.074394270619146, ['map,2,swingFootMod,full_srun,y']= -0.20135422163548, ['map,2,swingFootMod,full_srun,z']= -0.02283719949721, ['map,0,spprtFootMod,full_srun,x']= 0.073177461286702, ['map,0,spprtFootMod,full_srun,y']= 0.063543675789653, ['map,0,spprtFootMod,full_srun,z']= -0.10797648670201, ['map,1,spprtFootMod,full_srun,x']= -0.21162411354595, ['map,1,spprtFootMod,full_srun,y']= 0.12932316453028, ['map,1,spprtFootMod,full_srun,z']= -0.17467454727702, ['map,2,spprtFootMod,full_srun,x']= -0.02593512239657, ['map,2,spprtFootMod,full_srun,y']= -0.13731056051266, ['map,2,spprtFootMod,full_srun,z']= -0.023106688452543, })

	----iter:737 bestfvever:205143.72223935
	--accumulate({['map,0,swingFootMod,full_srun,x']= 0.02971216017685, ['map,0,swingFootMod,full_srun,y']= -0.18493812240614, ['map,0,swingFootMod,full_srun,z']= 0.019268543362018, ['map,1,swingFootMod,full_srun,x']= -0.20634087142364, ['map,1,swingFootMod,full_srun,y']= 0.037460946834032, ['map,1,swingFootMod,full_srun,z']= -0.086511011414486, ['map,2,swingFootMod,full_srun,x']= -0.051385986715308, ['map,2,swingFootMod,full_srun,y']= 0.037004605248252, ['map,2,swingFootMod,full_srun,z']= -0.069852491998003, ['map,0,spprtFootMod,full_srun,x']= -0.072312065697885, ['map,0,spprtFootMod,full_srun,y']= 0.11843895208172, ['map,0,spprtFootMod,full_srun,z']= -0.12249574183805, ['map,1,spprtFootMod,full_srun,x']= 0.0049501518075811, ['map,1,spprtFootMod,full_srun,y']= 0.085218067252345, ['map,1,spprtFootMod,full_srun,z']= -0.097415271801237, ['map,2,spprtFootMod,full_srun,x']= 0.0048387231036842, ['map,2,spprtFootMod,full_srun,y']= 0.071085304996178, ['map,2,spprtFootMod,full_srun,z']= 0.0086876837506688, })

	--iter:166 bestfvever:1.6764019672714e-06
	accumulate({['map,0,swingFootMod,full_srun,x']= -2.73460709921, ['map,0,swingFootMod,full_srun,y']= -5.7469095391883, ['map,0,swingFootMod,full_srun,z']= -4.5748785057106, ['map,1,swingFootMod,full_srun,x']= 2.1975900482594, ['map,1,swingFootMod,full_srun,y']= -4.4468083627217, ['map,1,swingFootMod,full_srun,z']= -2.5175099734472, ['map,2,swingFootMod,full_srun,x']= -0.087309598329488, ['map,2,swingFootMod,full_srun,y']= 0.83939931605743, ['map,2,swingFootMod,full_srun,z']= 0.34126711515694, ['map,0,spprtFootMod,full_srun,x']= 0.20119449942198, ['map,0,spprtFootMod,full_srun,y']= -1.3118697288555, ['map,0,spprtFootMod,full_srun,z']= 0.78598036663736, ['map,1,spprtFootMod,full_srun,x']= -0.52095964667732, ['map,1,spprtFootMod,full_srun,y']= 2.4460993997492, ['map,1,spprtFootMod,full_srun,z']= -0.61871628189565, ['map,2,spprtFootMod,full_srun,x']= 1.6162618119662, ['map,2,spprtFootMod,full_srun,y']= -8.0696055111219, ['map,2,spprtFootMod,full_srun,z']= 0.14207744982692, })

elseif g_mode=='a_.1' then
	useCases.full_srun.aObjWeight = .1*useCases.full_srun.aObjWeight

elseif g_mode=='a_.01' then
	useCases.full_srun.aObjWeight = .01*useCases.full_srun.aObjWeight

elseif g_mode=='a_.1_mscl_2x' then
	useCases.full_srun.aObjWeight = .1*useCases.full_srun.aObjWeight
	useCases.full_srun.initMsclForceScale=2

elseif g_mode=='a_.01_mscl_2x' then
	useCases.full_srun.aObjWeight = .01*useCases.full_srun.aObjWeight
	useCases.full_srun.initMsclForceScale=2

	--iter:161 bestfvever:1.0986186314177e-06
	accumulate({['map,0,swingFootMod,full_srun,x']= 1.3446954752444, ['map,0,swingFootMod,full_srun,y']= -4.3721798043208, ['map,0,swingFootMod,full_srun,z']= -1.2086138721921, ['map,1,swingFootMod,full_srun,x']= -0.69427279001378, ['map,1,swingFootMod,full_srun,y']= -2.5228681004991, ['map,1,swingFootMod,full_srun,z']= -0.14072586032793, ['map,2,swingFootMod,full_srun,x']= -0.21620428704442, ['map,2,swingFootMod,full_srun,y']= 0.027939756902062, ['map,2,swingFootMod,full_srun,z']= 0.40111919709296, ['map,0,spprtFootMod,full_srun,x']= -0.3072192961747, ['map,0,spprtFootMod,full_srun,y']= -1.0415573685648, ['map,0,spprtFootMod,full_srun,z']= 1.2403112930827, ['map,1,spprtFootMod,full_srun,x']= 0.12101891252516, ['map,1,spprtFootMod,full_srun,y']= 1.6205364799719, ['map,1,spprtFootMod,full_srun,z']= -1.1197358183276, ['map,2,spprtFootMod,full_srun,x']= 0.38414246977294, ['map,2,spprtFootMod,full_srun,y']= -3.5948188892824, ['map,2,spprtFootMod,full_srun,z']= 0.3020150302106, })

end
-------------------------------------------------

useCases.full_srun.controlParam['useCases,full_srun,aObjWeight'] = useCases.full_srun.aObjWeight

useCases.unmapControlParam(useCases.full_srun)
end


