package.path=package.path..";../Samples/ysscripts/lib/?.lua" --;"..package.path
require("utilfunc")

package.path=package.path..";../Samples/ysscripts/samples/?.lua" --;"..package.path
require("useMuscle_g2592_gait")


useCases.g2592_ipnrun=deepCopyTable(useCases.g2592_gait)

useCases.g2592_ipnrun.optimizerMethod='Optimizer.methods.CMAes_ys'

useCases.g2592_ipnrun.endSegW=15
useCases.g2592_ipnrun.prec=.2

useCases.g2592_ipnrun.modelName='g2592_ipnrun'
useCases.g2592_ipnrun.grpName='g2592_ipnrun'
useCases.g2592_ipnrun.grpNames={'g2592_ipnrun'}

-- the initial pendControlParam and pendOptimizationPath can be automatically generated by using createInitialPendControlParam.lua
useCases.g2592_ipnrun.pendControlParam=
{
['keyframe,0,pendDesiredVel,g2592_ipnrun,l,z']=0,['keyframe,0,pendDesiredVel,g2592_ipnrun,l,x']=1,['keyframe,0,pendDesiredVel,g2592_ipnrun,r,z']=0,['keyframe,0,pendDesiredVel,g2592_ipnrun,r,x']=1,['keyframe,0,pendDesiredVel,g2592_ipnrun,L1,z']=0,['keyframe,0,pendDesiredVel,g2592_ipnrun,L1,x']=1,['keyframe,0,pendDesiredVel,g2592_ipnrun,R1,z']=0,['keyframe,0,pendDesiredVel,g2592_ipnrun,R1,x']=1,['keyframe,0,pendDesiredVel,g2592_ipnrun,L2,z']=0,['keyframe,0,pendDesiredVel,g2592_ipnrun,L2,x']=1,['keyframe,0,pendDesiredVel,ignore,0,z']=0,['keyframe,0,pendDesiredVel,ignore,0,x']=1,['keyframe,0,pendDesiredVel,ignore,1,z']=0,['keyframe,0,pendDesiredVel,ignore,1,x']=1,
['keyframe,0,pendDesiredVel,ignore,0,x']=-0.17735172913339, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.33965287312438, ['keyframe,0,pendDesiredVel,g2592_ipnrun,l,x']=-0.11175535491193, ['keyframe,0,pendDesiredVel,g2592_ipnrun,l,z']=-0.20509580349014, ['keyframe,0,pendDesiredVel,g2592_ipnrun,r,x']=-0.045611959285589, ['keyframe,0,pendDesiredVel,g2592_ipnrun,r,z']=-0.064245770504627, ['keyframe,0,pendDesiredVel,g2592_ipnrun,L1,x']=-0.023844434226709, ['keyframe,0,pendDesiredVel,g2592_ipnrun,L1,z']=0.011162735538263, ['keyframe,0,pendDesiredVel,g2592_ipnrun,R1,x']=-0.0056331521215652, ['keyframe,0,pendDesiredVel,g2592_ipnrun,R1,z']=0.026891966591253, ['keyframe,0,pendDesiredVel,g2592_ipnrun,L2,x']=-0.00010924919732216, ['keyframe,0,pendDesiredVel,g2592_ipnrun,L2,z']=0.018318335426283, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.013336381211348, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.0029906216517521, 
['keyframe,0,pendDesiredVel,ignore,0,x']=-0.17824080838936, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.3410809987529, ['keyframe,0,pendDesiredVel,g2592_ipnrun,l,x']=-0.11309968190758, ['keyframe,0,pendDesiredVel,g2592_ipnrun,l,z']=-0.20232834162019, ['keyframe,0,pendDesiredVel,g2592_ipnrun,r,x']=-0.045167096820206, ['keyframe,0,pendDesiredVel,g2592_ipnrun,r,z']=-0.066667016742514, ['keyframe,0,pendDesiredVel,g2592_ipnrun,L1,x']=-0.024279685963021, ['keyframe,0,pendDesiredVel,g2592_ipnrun,L1,z']=0.012917961706282, ['keyframe,0,pendDesiredVel,g2592_ipnrun,R1,x']=-0.0057723312734285, ['keyframe,0,pendDesiredVel,g2592_ipnrun,R1,z']=0.026046475207172, ['keyframe,0,pendDesiredVel,g2592_ipnrun,L2,x']=-0.0014349880582403, ['keyframe,0,pendDesiredVel,g2592_ipnrun,L2,z']=0.016707604628142, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.010394389636722, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.0015035794840436, 
['keyframe,0,pendDesiredVel,ignore,0,x']=-0.397279179851, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.82274789081989, ['keyframe,0,pendDesiredVel,g2592_ipnrun,l,x']=-0.1910192298709, ['keyframe,0,pendDesiredVel,g2592_ipnrun,l,z']=0.38718433951502, ['keyframe,0,pendDesiredVel,g2592_ipnrun,r,x']=0.14860475551525, ['keyframe,0,pendDesiredVel,g2592_ipnrun,r,z']=-0.080572405587164, ['keyframe,0,pendDesiredVel,g2592_ipnrun,L1,x']=-0.1010276534494, ['keyframe,0,pendDesiredVel,g2592_ipnrun,L1,z']=0.037894027131615, ['keyframe,0,pendDesiredVel,g2592_ipnrun,R1,x']=-0.05500537391832, ['keyframe,0,pendDesiredVel,g2592_ipnrun,R1,z']=-0.12241845390729, ['keyframe,0,pendDesiredVel,g2592_ipnrun,L2,x']=-0.038050607607384, ['keyframe,0,pendDesiredVel,g2592_ipnrun,L2,z']=0.080346028657179, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.012218459579621, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.0037180977593758, 
['keyframe,0,pendDesiredVel,ignore,0,x']=-0.3975079693686, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.82277135460157, ['keyframe,0,pendDesiredVel,g2592_ipnrun,l,x']=-0.19122548038973, ['keyframe,0,pendDesiredVel,g2592_ipnrun,l,z']=0.38723548696006, ['keyframe,0,pendDesiredVel,g2592_ipnrun,r,x']=0.14848274796588, ['keyframe,0,pendDesiredVel,g2592_ipnrun,r,z']=-0.080591733721695, ['keyframe,0,pendDesiredVel,g2592_ipnrun,L1,x']=-0.10114077401849, ['keyframe,0,pendDesiredVel,g2592_ipnrun,L1,z']=0.037933473140123, ['keyframe,0,pendDesiredVel,g2592_ipnrun,R1,x']=-0.055021577194304, ['keyframe,0,pendDesiredVel,g2592_ipnrun,R1,z']=-0.12237803749991, ['keyframe,0,pendDesiredVel,g2592_ipnrun,L2,x']=-0.038066635269741, ['keyframe,0,pendDesiredVel,g2592_ipnrun,L2,z']=0.080395541180602, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.012219208654909, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.0037199071894178, 
}
useCases.g2592_ipnrun.pendOptimizationPath=
{
	firstFrames={1*4,14*4,27*4,40*4,53*4,66*4,79*4,90*4},
	segments={'ignore,0','g2592_ipnrun,l','g2592_ipnrun,r','g2592_ipnrun,L1','g2592_ipnrun,R1','g2592_ipnrun,L2','ignore,1'},
}
--useCases.g2592_ipnrun.measureOptCost=useCases.measureOptCost

useCases.g2592_ipnrun.segmentations=
{
	g2592_ipnrun={
		firstFrames={1*4,14*4,27*4,40*4,53*4,66*4,79*4,90*4},
		--        (blank)    L    R     L     R     L     (blank)
		names={             'l', 'r', 'L1', 'R1', 'L2',  },
		swingL={             0,   1,   0,    1,    0,    },
		swingR={             1,   0,   1,    0,    1,    },
		footRefL= "convertFromSwingL",
		footRefR= "convertFromSwingR",
		usePositionControl=false,
	},
}
useCases.g2592_ipnrun.graphParam=
{
	g2592_ipnrun={
		seg={            'l',  'r',  'L1', 'R1','L'},
		num_key={         3,    3,    3  ,  4,  4},
		key_first={       0,    0,    0  ,  0,  0},
		key_last={       'r', 'L1',  'R1', 'L', 'R1'},
	},
}
useCases.g2592_ipnrun.graph=
{
	{
		"addInterpolatedSegment",
		grpName="g2592_ipnrun",
		name="L",
		seg0={"g2592_ipnrun", "L2"},
		seg1={"g2592_ipnrun", "L1"},
		startWeight=0, endWeight=1
	},
	{"connectMulti", "g2592_ipnrun", "l", "r", "L1", "R1", "L", "R1"},
	--{"initialSegment", "g2592_ipnrun", "l"}
	{"initialSegment", "g2592_ipnrun", "R1"}
}
useCases.g2592_ipnrun.segNames=
{
	"l", "r", "L1", 'R1','L',
}

do 
	useCases.g2592_ipnrun.controlParam={
		['useCases,g2592_ipnrun,COMobjWeight']=0, 
		['useCases,g2592_ipnrun,conservativeW']=1, 
		--['useCases,g2592_ipnrun,contactMargin']=0.01, 
		['useCases,g2592_ipnrun,dotMomentumScale']=0.3, 
		['useCases,g2592_ipnrun,excludeRoot']=true, 
		['useCases,g2592_ipnrun,headControlWeight']=0, 
		['useCases,g2592_ipnrun,k_d_HEAD']=14, 
		['useCases,g2592_ipnrun,k_p_HEAD']=0, 
		['useCases,g2592_ipnrun,k_d_EE']=24, 
		['useCases,g2592_ipnrun,k_d_momentum']=10, 
		['useCases,g2592_ipnrun,k_p_EE']=120, 

		--['useCases,g2592_ipnrun,maxPenetratingVel']=0, 
		['useCases,g2592_ipnrun,momentumThr']=50, 
		['useCases,g2592_ipnrun,noComvelDependentFootAdjustment']=true, 
		['useCases,g2592_ipnrun,noIntersectionPrevenction']=true, 
		['useCases,g2592_ipnrun,numericalDerivDmot']=true, 
		['useCases,g2592_ipnrun,perClassContactMargin']=1, 
		['useCases,g2592_ipnrun,turnGain']=10, 
		['useCases,g2592_ipnrun,velMarginOffset']=0, 

		['useCases,g2592_ipnrun,actuationType']      = useCases.g2592_ipnrun.actuationType,
		['useCases,g2592_ipnrun,k_p_ID']             = useCases.g2592_ipnrun.k_p_ID,
		['useCases,g2592_ipnrun,k_d_ID']             = useCases.g2592_ipnrun.k_d_ID,
		['useCases,g2592_ipnrun,ddqObjWeight']       = useCases.g2592_ipnrun.ddqObjWeight,
		['useCases,g2592_ipnrun,tauObjWeight']       = useCases.g2592_ipnrun.tauObjWeight,
		['useCases,g2592_ipnrun,ftObjWeight']        = useCases.g2592_ipnrun.ftObjWeight,
		['useCases,g2592_ipnrun,aObjWeight']         = useCases.g2592_ipnrun.aObjWeight,
		['useCases,g2592_ipnrun,lambdaObjWeight']    = useCases.g2592_ipnrun.lambdaObjWeight,
		['useCases,g2592_ipnrun,EEobjWeight']        = useCases.g2592_ipnrun.EEobjWeight,
		['useCases,g2592_ipnrun,EEobjWeightAngular'] = useCases.g2592_ipnrun.EEobjWeightAngular,
		['useCases,g2592_ipnrun,momentumWeight']     = useCases.g2592_ipnrun.momentumWeight,
		['useCases,g2592_ipnrun,tauMax']             = useCases.g2592_ipnrun.tauMax,
		['useCases,g2592_ipnrun,ftMax']              = useCases.g2592_ipnrun.ftMax,
	}

	local function accumulate(cp_mod)
		local useCase=useCases.g2592_ipnrun
		useCases.accumulate(useCase, cp_mod)
	end

	--accumulate({
		--------['keyframe,0,footRmod,g2592_ipnrun,l,y']  = 0.,
		--------['keyframe,1,footRmod,g2592_ipnrun,l,y']  = 0.05,
		----['keyframe,0,footLmod,g2592_ipnrun,r,y']  = 0.1,
		----['keyframe,1,footLmod,g2592_ipnrun,r,y']  = 0.4,
		----['keyframe,0,footRmod,g2592_ipnrun,L1,y'] = 0.1,
		----['keyframe,1,footRmod,g2592_ipnrun,L1,y'] = 0.3,
		--['map,0,swingFootMod,g2592_ipnrun,y']     = 0.0,
		--['map,1,swingFootMod,g2592_ipnrun,y']     = 0.0,
		--['map,2,swingFootMod,g2592_ipnrun,y']     = 0.0,
		--------['keyframe,0,footLmod,g2592_ipnrun,l,y']  = 0.,
		--------['keyframe,1,footLmod,g2592_ipnrun,l,y']  = 0.,
		------['keyframe,0,footRmod,g2592_ipnrun,r,y']  = 0.,
		------['keyframe,1,footRmod,g2592_ipnrun,r,y']  = -.4,
		------['keyframe,0,footLmod,g2592_ipnrun,L1,y'] = 0.,
		------['keyframe,1,footLmod,g2592_ipnrun,L1,y'] = -.4,
		--['map,0,spprtFootMod,g2592_ipnrun,y']     = 0.,
		--['map,1,spprtFootMod,g2592_ipnrun,y']     = 0.,
		--['map,2,spprtFootMod,g2592_ipnrun,y']     = -.5,
	--})
	--useCases.unmapControlParam(useCases.g2592_ipnrun)

-------------------------------------------------
if g_mode=='default' then

elseif g_mode=='a_.1' then
	useCases.g2592_ipnrun.aObjWeight = .1*useCases.g2592_ipnrun.aObjWeight

elseif g_mode=='a_.01' then
	useCases.g2592_ipnrun.aObjWeight = .01*useCases.g2592_ipnrun.aObjWeight

	----iter:420 bestfvever:154230.76930329
	--accumulate({['map,0,swingFootMod,g2592_ipnrun,x']= -0.46698446557158, ['map,0,swingFootMod,g2592_ipnrun,y']= 0.40950168755486, ['map,0,swingFootMod,g2592_ipnrun,z']= -0.11341992908938, ['map,1,swingFootMod,g2592_ipnrun,x']= 0.23144993836491, ['map,1,swingFootMod,g2592_ipnrun,y']= 0.21090611796002, ['map,1,swingFootMod,g2592_ipnrun,z']= 0.62476330217176, ['map,2,swingFootMod,g2592_ipnrun,x']= -0.088566187140629, ['map,2,swingFootMod,g2592_ipnrun,y']= -0.7806507077031, ['map,2,swingFootMod,g2592_ipnrun,z']= -0.054288869627726, ['map,0,spprtFootMod,g2592_ipnrun,x']= 0.34712193596693, ['map,0,spprtFootMod,g2592_ipnrun,y']= -0.63175951466819, ['map,0,spprtFootMod,g2592_ipnrun,z']= -0.44307451724835, ['map,1,spprtFootMod,g2592_ipnrun,x']= 0.55801079697286, ['map,1,spprtFootMod,g2592_ipnrun,y']= -0.18824227518583, ['map,1,spprtFootMod,g2592_ipnrun,z']= -0.8219154204827, ['map,2,spprtFootMod,g2592_ipnrun,x']= 0.070899421347603, ['map,2,spprtFootMod,g2592_ipnrun,y']= 0.13481093535341, ['map,2,spprtFootMod,g2592_ipnrun,z']= 0.2354549778836, })
	
	--iter:169 bestfvever:2.4610878799641e-06
	accumulate({['map,0,swingFootMod,g2592_ipnrun,x']= 0.20766493267091, ['map,0,swingFootMod,g2592_ipnrun,y']= -1.3019056968487, ['map,0,swingFootMod,g2592_ipnrun,z']= 0.31722516230121, ['map,1,swingFootMod,g2592_ipnrun,x']= 0.20619162144988, ['map,1,swingFootMod,g2592_ipnrun,y']= 1.3517841262999, ['map,1,swingFootMod,g2592_ipnrun,z']= 0.19468180359466, ['map,2,swingFootMod,g2592_ipnrun,x']= -0.14743539783719, ['map,2,swingFootMod,g2592_ipnrun,y']= -1.8774190748049, ['map,2,swingFootMod,g2592_ipnrun,z']= -0.064376597217846, ['map,0,spprtFootMod,g2592_ipnrun,x']= -0.80039876701291, ['map,0,spprtFootMod,g2592_ipnrun,y']= -0.047892993141805, ['map,0,spprtFootMod,g2592_ipnrun,z']= 0.08154493734851, ['map,1,spprtFootMod,g2592_ipnrun,x']= 0.050018268747889, ['map,1,spprtFootMod,g2592_ipnrun,y']= -1.5365086339538, ['map,1,spprtFootMod,g2592_ipnrun,z']= 0.25583173403786, ['map,2,spprtFootMod,g2592_ipnrun,x']= -0.20347078503007, ['map,2,spprtFootMod,g2592_ipnrun,y']= -1.4819371810772, ['map,2,spprtFootMod,g2592_ipnrun,z']= -0.12464086436891, })

elseif g_mode=='a_.01_mscl_2x' then
	useCases.g2592_ipnrun.aObjWeight = .01*useCases.g2592_ipnrun.aObjWeight
	useCases.g2592_ipnrun.initMsclForceScale=2

	--iter:205 bestfvever:6.3796667971776e-07
	accumulate({['map,0,swingFootMod,g2592_ipnrun,x']= -0.024597770686543, ['map,0,swingFootMod,g2592_ipnrun,y']= -0.12021125371074, ['map,0,swingFootMod,g2592_ipnrun,z']= 0.14819322504099, ['map,1,swingFootMod,g2592_ipnrun,x']= -0.075449682561451, ['map,1,swingFootMod,g2592_ipnrun,y']= 0.3993989919727, ['map,1,swingFootMod,g2592_ipnrun,z']= 0.22827906003139, ['map,2,swingFootMod,g2592_ipnrun,x']= 0.035262024242059, ['map,2,swingFootMod,g2592_ipnrun,y']= -0.96173213233724, ['map,2,swingFootMod,g2592_ipnrun,z']= -0.056835711599576, ['map,0,spprtFootMod,g2592_ipnrun,x']= 0.066266413124199, ['map,0,spprtFootMod,g2592_ipnrun,y']= -1.2144152355987, ['map,0,spprtFootMod,g2592_ipnrun,z']= 0.11263358207544, ['map,1,spprtFootMod,g2592_ipnrun,x']= -0.39764873074286, ['map,1,spprtFootMod,g2592_ipnrun,y']= -0.37311167377413, ['map,1,spprtFootMod,g2592_ipnrun,z']= 0.0025824061806861, ['map,2,spprtFootMod,g2592_ipnrun,x']= -0.053137184621767, ['map,2,spprtFootMod,g2592_ipnrun,y']= -0.22580269572928, ['map,2,spprtFootMod,g2592_ipnrun,z']= 0.065630514888523, })

end
-------------------------------------------------

useCases.g2592_ipnrun.controlParam['useCases,g2592_ipnrun,aObjWeight'] = useCases.g2592_ipnrun.aObjWeight

useCases.unmapControlParam(useCases.g2592_ipnrun)
end


