package.path=package.path..";../Samples/ysscripts/lib/?.lua" --;"..package.path
require("utilfunc")

useCases.gait1956_6steps={
	--endSegW = 10,
	--prec = .1,

	k_p_ID=120,
	k_d_ID=2.*math.sqrt(120),
	--k_p_ID=20,
	--k_d_ID=2.*math.sqrt(20),
	--ddqObjWeight=10000000,

	--actuationType = ActuationType.tau,
	--actuationType = ActuationType.ft,
	actuationType = ActuationType.a,
	--actuationType = ActuationType.u,

	--tauObjWeight=1,
	--ftObjWeight=1,
	--aObjWeight=100000000,
	--lambdaObjWeight=100,
	----lambdaObjWeight=10,

	----EEobjWeight=60000000, 
	--EEobjWeight=100000000, 
	--EEobjWeightAngular=60000000, 
	--momentumWeight=8000000, 

	excludeRoot = true,

	tauMax = 400,
	ftMax = 4000,

	initMsclForceScale=1,

	invFricCoef=.5,
	invAccConeCoef=.1,
	contactMargin=.001,
	velMarginStrength=1,
	maxPenetratingVel=0,

	scenario=scenarios.ETC, 
	modelName='gait1956_6steps',
	useAnalyticIK=true, 
	grpName='gait1956_6steps',
	grpNames={'gait1956_6steps'},
	useFootEncodingMethod2=
	{
		true,
		geom={
			L={ 
				--{"LeftFoot", vector3(0,-0.03,0.02)},
				--{"LeftToes", vector3(0,-0.03,0.02)},
				{"ankle_l", vector3(-.05,-.05,.0)},
				{"ankle_l", vector3(.1,-.05,.0)},
			},
			R={
				--{"RightFoot", vector3(0,-0.03,0.02)},
				--{"RightToes", vector3(0,-0.03,0.02)},
				{"ankle_r", vector3(-.05,-.05,.0)},
				{"ankle_r", vector3(.1,-.05,.0)},
			},
		}
	},
	lfootpos=vector3(.1,-.05,.0),
	rfootpos=vector3(.1,-.05,.0),
	useQPsolver=true,
	footPosFeedbackMethod=2,
	useMomentumPreservingIK=false,
	--mot_file=package.resourcePath.."woody/woody.dof",
	--mot_file=package.resourcePath.."opensim/gait19_6steps_120.dof",
	--mot_file_upsample=4,
	mot_file_upsample=1,
	desiredPos=vector3(0,0,0),

	--measureOptCost=useCases.measureOptCost,
	-- [[[[  이 괄호 사이 부분은 맨 처음에는 필요없음
	-- the initial pendControlParam and pendOptimizationPath can be automatically generated by using createInitialPendControlParam.lua
	--pendControlParam={
		---- set measureOptCost
		---- initial 
		--['keyframe,0,pendDesiredVel,gait1956_6steps,stand,z']=0,['keyframe,0,pendDesiredVel,gait1956_6steps,stand,x']=0,['keyframe,0,pendDesiredVel,gait1956_6steps,r,z']=0,['keyframe,0,pendDesiredVel,gait1956_6steps,r,x']=0,['keyframe,0,pendDesiredVel,gait1956_6steps,rl,z']=0,['keyframe,0,pendDesiredVel,gait1956_6steps,rl,x']=0,['keyframe,0,pendDesiredVel,gait1956_6steps,l1,z']=0,['keyframe,0,pendDesiredVel,gait1956_6steps,l1,x']=0,['keyframe,0,pendDesiredVel,gait1956_6steps,R1,z']=0,['keyframe,0,pendDesiredVel,gait1956_6steps,R1,x']=0,['keyframe,0,pendDesiredVel,gait1956_6steps,L,z']=0,['keyframe,0,pendDesiredVel,gait1956_6steps,L,x']=0,['keyframe,0,pendDesiredVel,gait1956_6steps,R2,z']=0,['keyframe,0,pendDesiredVel,gait1956_6steps,R2,x']=0,['keyframe,0,pendDesiredVel,gait1956_6steps,L2,z']=0,['keyframe,0,pendDesiredVel,gait1956_6steps,L2,x']=0,['keyframe,0,pendDesiredVel,gait1956_6steps,R3,z']=0,['keyframe,0,pendDesiredVel,gait1956_6steps,R3,x']=0,['keyframe,0,pendDesiredVel,ignore,0,z']=0,['keyframe,0,pendDesiredVel,ignore,0,x']=0,['keyframe,0,pendDesiredVel,ignore,1,z']=0,['keyframe,0,pendDesiredVel,ignore,1,x']=0,
		---- version 1
		--['keyframe,0,pendDesiredVel,ignore,0,x']= 0.22154095899262, ['keyframe,0,pendDesiredVel,ignore,0,z']= 0.12374745900388, ['keyframe,0,pendDesiredVel,gait1956_6steps,stand,x']= 0.081896894230442, ['keyframe,0,pendDesiredVel,gait1956_6steps,stand,z']= 0.45867652019114, ['keyframe,0,pendDesiredVel,gait1956_6steps,r,x']= -0.18919981011582, ['keyframe,0,pendDesiredVel,gait1956_6steps,r,z']= 0.86954784863563, ['keyframe,0,pendDesiredVel,gait1956_6steps,rl,x']= -0.63054803502385, ['keyframe,0,pendDesiredVel,gait1956_6steps,rl,z']= 1.2123317122603, ['keyframe,0,pendDesiredVel,gait1956_6steps,l1,x']= -1.0946197823256, ['keyframe,0,pendDesiredVel,gait1956_6steps,l1,z']= 1.4672241425229, ['keyframe,0,pendDesiredVel,gait1956_6steps,R1,x']= -1.3838896131346, ['keyframe,0,pendDesiredVel,gait1956_6steps,R1,z']= 1.3385965037194, ['keyframe,0,pendDesiredVel,gait1956_6steps,L,x']= -0.37602673967732, ['keyframe,0,pendDesiredVel,gait1956_6steps,L,z']= 1.7483617822658, ['keyframe,0,pendDesiredVel,gait1956_6steps,R2,x']= -1.0303636068848, ['keyframe,0,pendDesiredVel,gait1956_6steps,R2,z']= 2.0915496597027, ['keyframe,0,pendDesiredVel,gait1956_6steps,L2,x']= -0.17782375147038, ['keyframe,0,pendDesiredVel,gait1956_6steps,L2,z']= 1.9087868681886, ['keyframe,0,pendDesiredVel,gait1956_6steps,R3,x']= -0.3194872566732, ['keyframe,0,pendDesiredVel,gait1956_6steps,R3,z']= 2.1005094300003, ['keyframe,0,pendDesiredVel,ignore,1,x']= -0.34056005585347, ['keyframe,0,pendDesiredVel,ignore,1,z']= 2.0369144090182, 
		---- after unseting measureOptCost
		--['keyframe,0,pendDesiredVel,ignore,0,x']= -0.024147834489552, ['keyframe,0,pendDesiredVel,ignore,0,z']= 0.088058220724029, ['keyframe,0,pendDesiredVel,gait1956_6steps,stand,x']= 0.47702586798009, ['keyframe,0,pendDesiredVel,gait1956_6steps,stand,z']= 0.21738634149488, ['keyframe,0,pendDesiredVel,gait1956_6steps,r,x']= 0.082454494440415, ['keyframe,0,pendDesiredVel,gait1956_6steps,r,z']= 0.76256946171197, ['keyframe,0,pendDesiredVel,gait1956_6steps,rl,x']= -0.41628601520352, ['keyframe,0,pendDesiredVel,gait1956_6steps,rl,z']= 1.117483700001, ['keyframe,0,pendDesiredVel,gait1956_6steps,l1,x']= -0.88662253297003, ['keyframe,0,pendDesiredVel,gait1956_6steps,l1,z']= 1.0585948463187, ['keyframe,0,pendDesiredVel,gait1956_6steps,R1,x']= -1.6152592263785, ['keyframe,0,pendDesiredVel,gait1956_6steps,R1,z']= 0.8180735117367, ['keyframe,0,pendDesiredVel,gait1956_6steps,L,x']= -0.0092576995765089, ['keyframe,0,pendDesiredVel,gait1956_6steps,L,z']= 1.6213782087026, ['keyframe,0,pendDesiredVel,gait1956_6steps,R2,x']= -1.5542000709724, ['keyframe,0,pendDesiredVel,gait1956_6steps,R2,z']= 1.9723273437593, ['keyframe,0,pendDesiredVel,gait1956_6steps,L2,x']= -0.063231874702499, ['keyframe,0,pendDesiredVel,gait1956_6steps,L2,z']= 1.4480427841615, ['keyframe,0,pendDesiredVel,gait1956_6steps,R3,x']= -0.12838593211115, ['keyframe,0,pendDesiredVel,gait1956_6steps,R3,z']= 1.94867402162, ['keyframe,0,pendDesiredVel,ignore,1,x']= -0.36235906036003, ['keyframe,0,pendDesiredVel,ignore,1,z']= 2.0345378423826, 
		---- run driverExtract ... as many times as possible until perfect converge
		--['keyframe,0,pendDesiredVel,ignore,0,x']= -0.23121949769732, ['keyframe,0,pendDesiredVel,ignore,0,z']= 0.084247096936577, ['keyframe,0,pendDesiredVel,gait1956_6steps,stand,x']= 0.73154161677205, ['keyframe,0,pendDesiredVel,gait1956_6steps,stand,z']= 0.31793001592609, ['keyframe,0,pendDesiredVel,gait1956_6steps,r,x']= 0.42003639769944, ['keyframe,0,pendDesiredVel,gait1956_6steps,r,z']= 0.83411577489725, ['keyframe,0,pendDesiredVel,gait1956_6steps,rl,x']= -0.15815209233177, ['keyframe,0,pendDesiredVel,gait1956_6steps,rl,z']= 1.1356657426567, ['keyframe,0,pendDesiredVel,gait1956_6steps,l1,x']= -0.77155651361355, ['keyframe,0,pendDesiredVel,gait1956_6steps,l1,z']= 0.55103204387484, ['keyframe,0,pendDesiredVel,gait1956_6steps,R1,x']= -1.9260316729118, ['keyframe,0,pendDesiredVel,gait1956_6steps,R1,z']= 0.92282643547311, ['keyframe,0,pendDesiredVel,gait1956_6steps,L,x']= -0.22364959662651, ['keyframe,0,pendDesiredVel,gait1956_6steps,L,z']= 0.9044024634778, ['keyframe,0,pendDesiredVel,gait1956_6steps,R2,x']= -1.858956086035, ['keyframe,0,pendDesiredVel,gait1956_6steps,R2,z']= 0.9006203673195, ['keyframe,0,pendDesiredVel,gait1956_6steps,L2,x']= -0.02485055740681, ['keyframe,0,pendDesiredVel,gait1956_6steps,L2,z']= 0.97943601734244, ['keyframe,0,pendDesiredVel,gait1956_6steps,R3,x']= -0.085671478975374, ['keyframe,0,pendDesiredVel,gait1956_6steps,R3,z']= 1.5576173478345, ['keyframe,0,pendDesiredVel,ignore,1,x']= -0.36490782915166, ['keyframe,0,pendDesiredVel,ignore,1,z']= 2.0324766664308, 
		--['keyframe,0,pendDesiredVel,ignore,0,x']= -0.14616796369022, ['keyframe,0,pendDesiredVel,ignore,0,z']= 0.070939809591596, ['keyframe,0,pendDesiredVel,gait1956_6steps,stand,x']= 0.66073951245086, ['keyframe,0,pendDesiredVel,gait1956_6steps,stand,z']= 0.35159310919931, ['keyframe,0,pendDesiredVel,gait1956_6steps,r,x']= 0.39203876740031, ['keyframe,0,pendDesiredVel,gait1956_6steps,r,z']= 0.8640905254407, ['keyframe,0,pendDesiredVel,gait1956_6steps,rl,x']= -0.1975560223201, ['keyframe,0,pendDesiredVel,gait1956_6steps,rl,z']= 1.1494494168222, ['keyframe,0,pendDesiredVel,gait1956_6steps,l1,x']= -1.0064803800847, ['keyframe,0,pendDesiredVel,gait1956_6steps,l1,z']= 0.45919369130463, ['keyframe,0,pendDesiredVel,gait1956_6steps,R1,x']= -1.959754239147, ['keyframe,0,pendDesiredVel,gait1956_6steps,R1,z']= 0.91560857383856, ['keyframe,0,pendDesiredVel,gait1956_6steps,L,x']= -0.18225653086217, ['keyframe,0,pendDesiredVel,gait1956_6steps,L,z']= 0.88133961991468, ['keyframe,0,pendDesiredVel,gait1956_6steps,R2,x']= -1.8921874785144, ['keyframe,0,pendDesiredVel,gait1956_6steps,R2,z']= 0.9535517039276, ['keyframe,0,pendDesiredVel,gait1956_6steps,L2,x']= -0.0068408088095299, ['keyframe,0,pendDesiredVel,gait1956_6steps,L2,z']= 0.71798984286394, ['keyframe,0,pendDesiredVel,gait1956_6steps,R3,x']= -0.026602632717303, ['keyframe,0,pendDesiredVel,gait1956_6steps,R3,z']= 1.5864716456483, ['keyframe,0,pendDesiredVel,ignore,1,x']= -0.36502766516045, ['keyframe,0,pendDesiredVel,ignore,1,z']= 2.0233018545127, 
		--['keyframe,0,pendDesiredVel,ignore,0,x']= -0.13605228258474, ['keyframe,0,pendDesiredVel,ignore,0,z']= 0.03703005396104, ['keyframe,0,pendDesiredVel,gait1956_6steps,stand,x']= 0.65741541644869, ['keyframe,0,pendDesiredVel,gait1956_6steps,stand,z']= 0.35866445825076, ['keyframe,0,pendDesiredVel,gait1956_6steps,r,x']= 0.42063449382855, ['keyframe,0,pendDesiredVel,gait1956_6steps,r,z']= 0.88667655728368, ['keyframe,0,pendDesiredVel,gait1956_6steps,rl,x']= -0.18183055539947, ['keyframe,0,pendDesiredVel,gait1956_6steps,rl,z']= 1.1643452984976, ['keyframe,0,pendDesiredVel,gait1956_6steps,l1,x']= -1.0957891586835, ['keyframe,0,pendDesiredVel,gait1956_6steps,l1,z']= 0.39472750944181, ['keyframe,0,pendDesiredVel,gait1956_6steps,R1,x']= -1.0103870244407, ['keyframe,0,pendDesiredVel,gait1956_6steps,R1,z']= 0.61133539999822, ['keyframe,0,pendDesiredVel,gait1956_6steps,L,x']= -0.97775637155715, ['keyframe,0,pendDesiredVel,gait1956_6steps,L,z']= 0.87543103961231, ['keyframe,0,pendDesiredVel,gait1956_6steps,R2,x']= -1.0520696571352, ['keyframe,0,pendDesiredVel,gait1956_6steps,R2,z']= 0.95604422959571, ['keyframe,0,pendDesiredVel,gait1956_6steps,L2,x']= 0.014232952444131, ['keyframe,0,pendDesiredVel,gait1956_6steps,L2,z']= 0.6356003784466, ['keyframe,0,pendDesiredVel,gait1956_6steps,R3,x']= -0.058026345241046, ['keyframe,0,pendDesiredVel,gait1956_6steps,R3,z']= 1.5409017312702, ['keyframe,0,pendDesiredVel,ignore,1,x']= -0.3597000105511, ['keyframe,0,pendDesiredVel,ignore,1,z']= 2.0213963310874, 
		--['keyframe,0,pendDesiredVel,ignore,0,x']= -0.18578335275737, ['keyframe,0,pendDesiredVel,ignore,0,z']= 0.0058224316262488, ['keyframe,0,pendDesiredVel,gait1956_6steps,stand,x']= 0.69335441735726, ['keyframe,0,pendDesiredVel,gait1956_6steps,stand,z']= 0.36841991936563, ['keyframe,0,pendDesiredVel,gait1956_6steps,r,x']= 0.52603858729147, ['keyframe,0,pendDesiredVel,gait1956_6steps,r,z']= 0.94343878201881, ['keyframe,0,pendDesiredVel,gait1956_6steps,rl,x']= -0.090907786794304, ['keyframe,0,pendDesiredVel,gait1956_6steps,rl,z']= 1.2317235825874, ['keyframe,0,pendDesiredVel,gait1956_6steps,l1,x']= -1.0429640546855, ['keyframe,0,pendDesiredVel,gait1956_6steps,l1,z']= 0.58665304262518, ['keyframe,0,pendDesiredVel,gait1956_6steps,R1,x']= -1.8172046006695, ['keyframe,0,pendDesiredVel,gait1956_6steps,R1,z']= 0.3804760535131, ['keyframe,0,pendDesiredVel,gait1956_6steps,L,x']= -0.15268786639546, ['keyframe,0,pendDesiredVel,gait1956_6steps,L,z']= 0.78415311242481, ['keyframe,0,pendDesiredVel,gait1956_6steps,R2,x']= -1.7446021822076, ['keyframe,0,pendDesiredVel,gait1956_6steps,R2,z']= 1.0286682030914, ['keyframe,0,pendDesiredVel,gait1956_6steps,L2,x']= 0.25312513939494, ['keyframe,0,pendDesiredVel,gait1956_6steps,L2,z']= 0.62282672492172, ['keyframe,0,pendDesiredVel,gait1956_6steps,R3,x']= -0.16524259289654, ['keyframe,0,pendDesiredVel,gait1956_6steps,R3,z']= 1.448978296583, ['keyframe,0,pendDesiredVel,ignore,1,x']= -0.35169721982963, ['keyframe,0,pendDesiredVel,ignore,1,z']= 2.0212661219972, 
	--},
	--pendOptimizationPath=
	--{
		--firstFrames={4,80,148,172,192,248,320,392,460,528,596,672,},
		--segments={'ignore,0','turn,stand','turn,r','turn,rl','turn,l1','turn,R1','turn,L','turn,R2','turn,L2','turn,R3','ignore,1'},
	--},
	-- ]]]]
	
		-- the initial pendControlParam and pendOptimizationPath can be automatically generated by using createInitialPendControlParam.lua
	pendControlParam={['keyframe,0,pendDesiredVel,gait1956_6steps,l,z']=0,['keyframe,0,pendDesiredVel,gait1956_6steps,l,x']=1,['keyframe,0,pendDesiredVel,gait1956_6steps,r,z']=0,['keyframe,0,pendDesiredVel,gait1956_6steps,r,x']=1,['keyframe,0,pendDesiredVel,gait1956_6steps,L1,z']=0,['keyframe,0,pendDesiredVel,gait1956_6steps,L1,x']=1,['keyframe,0,pendDesiredVel,gait1956_6steps,R1,z']=0,['keyframe,0,pendDesiredVel,gait1956_6steps,R1,x']=1,['keyframe,0,pendDesiredVel,gait1956_6steps,L2,z']=0,['keyframe,0,pendDesiredVel,gait1956_6steps,L2,x']=1,['keyframe,0,pendDesiredVel,ignore,0,z']=0,['keyframe,0,pendDesiredVel,ignore,0,x']=1,['keyframe,0,pendDesiredVel,ignore,1,z']=0,['keyframe,0,pendDesiredVel,ignore,1,x']=1,
['keyframe,0,pendDesiredVel,ignore,0,x']=0.81834033110812, ['keyframe,0,pendDesiredVel,ignore,0,z']=0.044169459727862, ['keyframe,0,pendDesiredVel,gait1956_6steps,l,x']=0.24751193328977, ['keyframe,0,pendDesiredVel,gait1956_6steps,l,z']=-0.011257915517705, ['keyframe,0,pendDesiredVel,gait1956_6steps,r,x']=1.2657656176937, ['keyframe,0,pendDesiredVel,gait1956_6steps,r,z']=-0.013826279387685, ['keyframe,0,pendDesiredVel,gait1956_6steps,L1,x']=1.2426496309691, ['keyframe,0,pendDesiredVel,gait1956_6steps,L1,z']=0.012298433994094, ['keyframe,0,pendDesiredVel,gait1956_6steps,R1,x']=0.97147903748857, ['keyframe,0,pendDesiredVel,gait1956_6steps,R1,z']=0.0019102616757477, ['keyframe,0,pendDesiredVel,gait1956_6steps,L2,x']=0.94503742140242, ['keyframe,0,pendDesiredVel,gait1956_6steps,L2,z']=0.0065100778852472, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.9941021435833, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.0011067024071179, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.58891991844629, ['keyframe,0,pendDesiredVel,ignore,0,z']=0.0062407698080992, ['keyframe,0,pendDesiredVel,gait1956_6steps,l,x']=0.64294952378662, ['keyframe,0,pendDesiredVel,gait1956_6steps,l,z']=-0.0041877697095709, ['keyframe,0,pendDesiredVel,gait1956_6steps,r,x']=0.90535989718503, ['keyframe,0,pendDesiredVel,gait1956_6steps,r,z']=-0.0050615746393806, ['keyframe,0,pendDesiredVel,gait1956_6steps,L1,x']=1.0730338312282, ['keyframe,0,pendDesiredVel,gait1956_6steps,L1,z']=-0.0013624902908882, ['keyframe,0,pendDesiredVel,gait1956_6steps,R1,x']=1.1211388621008, ['keyframe,0,pendDesiredVel,gait1956_6steps,R1,z']=-0.0020764017878052, ['keyframe,0,pendDesiredVel,gait1956_6steps,L2,x']=1.0648232708165, ['keyframe,0,pendDesiredVel,gait1956_6steps,L2,z']=-0.0068461177356352, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.99475404358166, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.0093964215893864, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.47726516042625, ['keyframe,0,pendDesiredVel,ignore,0,z']=0.059456231534473, ['keyframe,0,pendDesiredVel,gait1956_6steps,l,x']=0.29996537754387, ['keyframe,0,pendDesiredVel,gait1956_6steps,l,z']=-0.01175252344223, ['keyframe,0,pendDesiredVel,gait1956_6steps,r,x']=1.2786628610905, ['keyframe,0,pendDesiredVel,gait1956_6steps,r,z']=-0.016150147797801, ['keyframe,0,pendDesiredVel,gait1956_6steps,L1,x']=1.1951551337332, ['keyframe,0,pendDesiredVel,gait1956_6steps,L1,z']=0.013330077171535, ['keyframe,0,pendDesiredVel,gait1956_6steps,R1,x']=0.97195017067857, ['keyframe,0,pendDesiredVel,gait1956_6steps,R1,z']=0.0010311475592667, ['keyframe,0,pendDesiredVel,gait1956_6steps,L2,x']=0.97767311587139, ['keyframe,0,pendDesiredVel,gait1956_6steps,L2,z']=0.0045328100882639, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.98813231755213, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.0073963256115185, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.38930983529361, ['keyframe,0,pendDesiredVel,ignore,0,z']=0.10187703195912, ['keyframe,0,pendDesiredVel,gait1956_6steps,l,x']=0.27070864782701, ['keyframe,0,pendDesiredVel,gait1956_6steps,l,z']=-0.012785838305748, ['keyframe,0,pendDesiredVel,gait1956_6steps,r,x']=1.3962070722898, ['keyframe,0,pendDesiredVel,gait1956_6steps,r,z']=0.00050715328366124, ['keyframe,0,pendDesiredVel,gait1956_6steps,L1,x']=1.0675910277498, ['keyframe,0,pendDesiredVel,gait1956_6steps,L1,z']=0.020225969987952, ['keyframe,0,pendDesiredVel,gait1956_6steps,R1,x']=0.94726509213239, ['keyframe,0,pendDesiredVel,gait1956_6steps,R1,z']=0.0010157435833168, 
['keyframe,0,pendDesiredVel,ignore,0,x']=-6.4904883448646, ['keyframe,0,pendDesiredVel,ignore,0,z']=0.019710657919054, ['keyframe,0,pendDesiredVel,gait1956_6steps,l,x']=2.5796710187361, ['keyframe,0,pendDesiredVel,gait1956_6steps,l,z']=-0.0086091424618707, 
['keyframe,0,pendDesiredVel,ignore,0,x']=-6.6339049992359, ['keyframe,0,pendDesiredVel,ignore,0,z']=0.0298468463624, ['keyframe,0,pendDesiredVel,gait1956_6steps,l,x']=1.798322884423, ['keyframe,0,pendDesiredVel,gait1956_6steps,l,z']=-0.013090595683396, ['keyframe,0,pendDesiredVel,gait1956_6steps,r,x']=0.93101573095498, ['keyframe,0,pendDesiredVel,gait1956_6steps,r,z']=-0.0083966969533526, ['keyframe,0,pendDesiredVel,gait1956_6steps,L1,x']=1.022529153836, ['keyframe,0,pendDesiredVel,gait1956_6steps,L1,z']=0.016182064539394, ['keyframe,0,pendDesiredVel,gait1956_6steps,R1,x']=1.0841846324159, ['keyframe,0,pendDesiredVel,gait1956_6steps,R1,z']=-0.0026320953278554, ['keyframe,0,pendDesiredVel,gait1956_6steps,L2,x']=1.0810887974972, ['keyframe,0,pendDesiredVel,gait1956_6steps,L2,z']=0.0050895495564027, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.9969461836698, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.007144778666157, 
['keyframe,0,pendDesiredVel,ignore,0,x']=-6.6336652542693, ['keyframe,0,pendDesiredVel,ignore,0,z']=0.029929295279593, ['keyframe,0,pendDesiredVel,gait1956_6steps,l,x']=1.7983609453946, ['keyframe,0,pendDesiredVel,gait1956_6steps,l,z']=-0.013226252857668, ['keyframe,0,pendDesiredVel,gait1956_6steps,r,x']=0.93095448765961, ['keyframe,0,pendDesiredVel,gait1956_6steps,r,z']=-0.0085542832465237, ['keyframe,0,pendDesiredVel,gait1956_6steps,L1,x']=1.0227484337823, ['keyframe,0,pendDesiredVel,gait1956_6steps,L1,z']=0.016100133438423, ['keyframe,0,pendDesiredVel,gait1956_6steps,R1,x']=1.0842891543663, ['keyframe,0,pendDesiredVel,gait1956_6steps,R1,z']=-0.0026943869375061, ['keyframe,0,pendDesiredVel,gait1956_6steps,L2,x']=1.0811274116513, ['keyframe,0,pendDesiredVel,gait1956_6steps,L2,z']=0.0050834940142483, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.9969467705405, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.0071432239236035, 
['keyframe,0,pendDesiredVel,ignore,0,x']=-6.6334708130054, ['keyframe,0,pendDesiredVel,ignore,0,z']=0.030000326636344, ['keyframe,0,pendDesiredVel,gait1956_6steps,l,x']=1.7983777090079, ['keyframe,0,pendDesiredVel,gait1956_6steps,l,z']=-0.013314495002798, ['keyframe,0,pendDesiredVel,gait1956_6steps,r,x']=0.93088994620175, ['keyframe,0,pendDesiredVel,gait1956_6steps,r,z']=-0.0086613437904225, ['keyframe,0,pendDesiredVel,gait1956_6steps,L1,x']=1.0229183527459, ['keyframe,0,pendDesiredVel,gait1956_6steps,L1,z']=0.016048371540156, ['keyframe,0,pendDesiredVel,gait1956_6steps,R1,x']=1.0843676901888, ['keyframe,0,pendDesiredVel,gait1956_6steps,R1,z']=-0.0027354286278155, ['keyframe,0,pendDesiredVel,gait1956_6steps,L2,x']=1.0811562830776, ['keyframe,0,pendDesiredVel,gait1956_6steps,L2,z']=0.0050822649969702, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.99694706532047, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.0071417114036663, 
['keyframe,0,pendDesiredVel,ignore,0,x']=-6.6332361141625, ['keyframe,0,pendDesiredVel,ignore,0,z']=0.030089406669974, ['keyframe,0,pendDesiredVel,gait1956_6steps,l,x']=1.7983867789531, ['keyframe,0,pendDesiredVel,gait1956_6steps,l,z']=-0.013403400865729, ['keyframe,0,pendDesiredVel,gait1956_6steps,r,x']=0.93080017168235, ['keyframe,0,pendDesiredVel,gait1956_6steps,r,z']=-0.0087737771057228, ['keyframe,0,pendDesiredVel,gait1956_6steps,L1,x']=1.0231169298727, ['keyframe,0,pendDesiredVel,gait1956_6steps,L1,z']=0.015997773275016, ['keyframe,0,pendDesiredVel,gait1956_6steps,R1,x']=1.0844572676959, ['keyframe,0,pendDesiredVel,gait1956_6steps,R1,z']=-0.0027773051838233, ['keyframe,0,pendDesiredVel,gait1956_6steps,L2,x']=1.081189060562, ['keyframe,0,pendDesiredVel,gait1956_6steps,L2,z']=0.0050837500006744, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.99694726796105, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.007139683632481, 
['keyframe,0,pendDesiredVel,ignore,0,x']=-6.6327864686625, ['keyframe,0,pendDesiredVel,ignore,0,z']=0.030266633879316, ['keyframe,0,pendDesiredVel,gait1956_6steps,l,x']=1.7983825125705, ['keyframe,0,pendDesiredVel,gait1956_6steps,l,z']=-0.013538941629056, ['keyframe,0,pendDesiredVel,gait1956_6steps,r,x']=0.93060497536922, ['keyframe,0,pendDesiredVel,gait1956_6steps,r,z']=-0.0089559567358303, ['keyframe,0,pendDesiredVel,gait1956_6steps,L1,x']=1.0234842447518, ['keyframe,0,pendDesiredVel,gait1956_6steps,L1,z']=0.015924326728306, ['keyframe,0,pendDesiredVel,gait1956_6steps,R1,x']=1.0846182185486, ['keyframe,0,pendDesiredVel,gait1956_6steps,R1,z']=-0.0028423930084533, ['keyframe,0,pendDesiredVel,gait1956_6steps,L2,x']=1.0812475788174, ['keyframe,0,pendDesiredVel,gait1956_6steps,L2,z']=0.0050924455844826, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.99694734038173, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.007135401749792, 
},
pendOptimizationPath=
{
	firstFrames={1,10,80,157,227,301,373,447,},
	segments={'ignore,0','gait1956_6steps,l','gait1956_6steps,r','gait1956_6steps,L1','gait1956_6steps,R1','gait1956_6steps,L2','ignore,1'},
},
	--
	conservativePrediction=1.0,
	muscleActiveness=0.8,
	keyframes={
		pendDesiredVel={numKey=1, default=vector3(1,0,0)},
		swingFootForce={numKey=3, default=vector3(0,10,0)},
		footLmod={numKey=3, numKeyFrom='key', default=vector3(0,0,0)},
		footRmod={numKey=3, numKeyFrom='key', default=vector3(0,0,0)},
		footLmocapMod={numKey=3, numKeyFrom='key', default=vector3(0,0,0)},
		footRmocapMod={numKey=3, numKeyFrom='key', default=vector3(0,0,0)},
		desiredHeadAcc={numKey=3, numKeyFrom='key', default=vector3(0,0,0)},
		desiredMomentum={numKey=3, numKeyFrom='key', default=vector3(0,0,0)},
		desiredDotMomentum={numKey=3, numKeyFrom='key', isContinuous=false,default=vector3(0,0,0)},
		desiredLeaning={numKey=1, isContinuous=false,default=vector3(0,0,0)},
		spprtImpL={numKey=2, default=1},
		spprtImpR={numKey=2, default=1},
		mocapCompensationCoef={numKey=1, default=vector3(1, 1.0, 1)},
	},
	segProperties={
		noCOPcontrol={default=false}
	},
}
useCases.gait1956_6steps.attachCamera=true

function useCases.gait1956_6steps:makeOptParam(numKey,...)
	local gtarget=array:new()
	--local prec=0.05
	local prec=self.prec
	for iid,id in ipairs({...}) do
		for i=0, numKey-1 do
			if string.sub(id,1,3)=="MAP" then
				gtarget:pushBack({"map,"..i..","..string.sub(id,4)..",x",prec})
				gtarget:pushBack({"map,"..i..","..string.sub(id,4)..",y",prec})
				gtarget:pushBack({"map,"..i..","..string.sub(id,4)..",z",prec})
			else
				gtarget:pushBack({"keyframe,"..i..","..id..",x",prec})
				gtarget:pushBack({"keyframe,"..i..","..id..",y",prec})
				gtarget:pushBack({"keyframe,"..i..","..id..",z",prec})
			end
		end
	end
	return gtarget
end
function useCases.gait1956_6steps:makeOptParamAxis(numKey,axis,...)
	local gtarget=array:new()
	--local prec=0.05
	local prec=self.prec
	local symmetricMapUsed=false
	for iid,id in ipairs({...}) do
		for i=0, numKey-1 do
			if string.sub(id,1,3)=="MAP" then
				gtarget:pushBack({"map,"..i..","..string.sub(id,4)..","..axis,prec})
				--symmetricMapUsed=true
			else
				gtarget:pushBack({"keyframe,"..i..","..id..","..axis,prec})
			end
		end
	end

	return gtarget
end

function useCases.gait1956_6steps:updateStageParam(stage, stageParam)
	gains={}
	local endSegW=self.endSegW
	local grpName=self.grpName
	local genOpt=function(starts, ends, ps, pe, name, axis, others)
		local out=useCases.genOpt(useCase, starts, ends, ps, pe, name, axis,others, grpName, path)
		assert(out)
		return out
	end
	local tgt_all={'footLmod','footRmod'}
	local tgt_L={'footLmod', }
	local tgt_R={'footRmod', }
	--if true and stage<11 then -- before starting to walk
	if false then
		local tbl={ 
			{1,2, {'footLmod', 'footRmod'}},
			{3,4, {'footLmod', 'footRmod'}},
			{2,2, {'footLmod', 'footRmod'}}, 
			{1,1, {'footLmod', 'footRmod'}},
			{3,3, {'footLmod', 'footRmod'}},
			{4,4, {'footLmod', 'footRmod'}}, 
			{3,4, {'footLmod'}}, 
			{3,4, {'footRmod'}}, 
			{1,2, {'footLmod', 'footRmod'}},
			{1,2, {'footLmod', 'footRmod'}},
			{1,2, {'footLmod'}},
			{3,4, {'footRmod'}},
		}

		local tb=tbl[stage]
		local endSegW=self.endSegW
		stageParam[stage]=genOpt( 1, endSegW, tb[1], tb[2],grpName, nil, tb[3])
	elseif false then
		-- doesn't assume symmetry
		local mod=math.mod(stage-1,4)
		if mod==0 then -- footall
			stageParam[stage]=genOpt( 8, endSegW, 6, 8,grpName, nil, {'footLmod_all','footRmod_all'})
		elseif mod==1 then
			stageParam[stage]=genOpt( 8, endSegW, 6, 8,grpName,{'x','y'})
		elseif mod==2 then
			stageParam[stage]=genOpt( 8, endSegW, 6, 8,grpName,{'x','z'})
		else
			stageParam[stage]=genOpt( 8, endSegW, 6, 8,grpName,{'y','z'})
		end
	else  -- optimize walk cycles (assuming symmetry)
		--local endSegW=stage+23
		local mod=math.mod(stage-1,4)
		if mod==0 then
			stageParam[stage]={startSeg=1, endSeg=endSegW, nvar=2,setStageFunc="setStage_param", param=self:makeOptParam(3,"MAPswingFootMod,"..grpName,"MAPspprtFootMod,"..grpName), objCost=objCost,baseStage=1}
		elseif mod==1 then
			stageParam[stage]={startSeg=1, endSeg=endSegW, nvar=2,setStageFunc="setStage_param", param=self:makeOptParamAxis(3,'z',"MAPswingFootMod,"..grpName,"MAPspprtFootMod,"..grpName), objCost=objCost,baseStage=1}
		elseif mod==2 then
			stageParam[stage]={startSeg=1, endSeg=endSegW, nvar=2,setStageFunc="setStage_param", param=self:makeOptParamAxis(3,'x',"MAPswingFootMod,"..grpName,"MAPspprtFootMod,"..grpName), objCost=objCost,baseStage=1}
		elseif mod==3 then
			stageParam[stage]={startSeg=1, endSeg=endSegW, nvar=2,setStageFunc="setStage_param", param=self:makeOptParamAxis(3,'y',"MAPswingFootMod,"..grpName,"MAPspprtFootMod,"..grpName), objCost=objCost,baseStage=1}
		end

		--TODO_muscle
		--concat 'muscle,' params to stageParam
		--testmw
		--dbg.console()
		
	end

	--stageParam[stage+1]={baseStage=1, startSeg=1}
end
function  useCases.gait1956_6steps:genStageParamInitial()
	local stageParam={}
	self:updateStageParam(1, stageParam)
	return stageParam
end

useCases.gait1956_6steps.mapControlParam=function(graph, title, param)
	local out={}

	assert(string.sub(title, 1,4)=="map,")
	local tokens=string.tokenize(title,',')
	local idx=tonumber(tokens[2])
	local name=tokens[3]

	local convertMap=function(name, mirror)
		local FootIdx=string.find(name, "Foot")
		local key=string.sub(name, 1, FootIdx+3)
		local id=string.lower(string.sub(name, FootIdx+4, FootIdx+4))..string.sub(name, FootIdx+5)
		local convertMap

		local firstFoot = useCases[tokens[4]].segNames[1]

		if mirror then
			if firstFoot == 'l' then
				convertMap=
				{
					swingFoot={',footR', ',L'}, 
					spprtFoot={',footL', ',L'},
				}
			else
				convertMap=
				{
					swingFoot={',footL', ',R'}, 
					spprtFoot={',footR', ',R'},
				}
			end
		else
			if firstFoot == 'l' then
				convertMap=
				{
					swingFoot={',footL', ',R1'}, 
					spprtFoot={',footR', ',R1'},
				}
			else
				convertMap=
				{
					swingFoot={',footR', ',L1'}, 
					spprtFoot={',footL', ',L1'},
				}
			end
		end
		return {convertMap[key][1]..id..",", convertMap[key][2],}
	end

	local grp=tokens[4]
	local axis=tokens[5]
	local cmap=convertMap(name)
	local cmapm=convertMap(name,true)
	local name2='keyframe,'..idx..cmap[1]..grp..cmap[2]
	local name2_mirror='keyframe,'..idx..cmapm[1]..grp..cmapm[2]

	if axis~=nil then
		array.pushBack(out, {name2..","..axis,param}) 

		--ys
		local mirrorAxis
		if g_nobugfix~=nil and g_nobugfix==true then
			mirrorAxis = 'x'
		else
			mirrorAxis = 'z'
		end

		--if axis=='x' then
		--if axis=='z' then	--ys
		if axis==mirrorAxis then
			array.pushBack(out, {name2_mirror..","..axis,param*-1}) 
		else
			array.pushBack(out, {name2_mirror..","..axis,param}) 
		end
	else
		local param2=param:copy()
		array.pushBack(out, {name2, param2})
		param2.x=param2.x*-1
		array.pushBack(out, {name2_mirror, param2})
	end

	return out
end

useCases.gait1956_6steps.funcUpdateConstraints=function(graph)
	useCases.defaultFuncUpdateConstraints(useCase, graph)
end

useCases.gait1956_6steps.registerContactPair=function(model, loader, floor, simulator)

	param=vectorn ()
	param:setValues(0.5,0.5, model.penaltyForceStiffness, model.penaltyForceDamp)
	for i=1,loader:numBone()-1 do

		local bone_i=loader:VRMLbone(i)
		if string.find(bone_i:name(), "Foot")
			or string.find(bone_i:name(), "Toe") then
			simulator:registerCollisionCheckPair(loader:name(),bone_i.NameId, floor:name(), floor:bone(1):name(), param)
		end
	end
end


useCases.gait1956_6steps.init_globals=function()
	outputSuperSample=1
	PDservoLatency=5-- for debugging. set 5 for normal use.
	IDservoLatency=0
	PredictionLatency=0
	model.simulationFrameRate=120

	--COPlatency=10
	--disableTouchDownFeedback=false
	--model.simulationSubTimesteps=1 -- has to be 1 for unknown reason
	--model.penaltyForceStiffness=20000
	--model.penaltyForceDamp=2000
	--model.k_p_ID=250
	--model.k_d_ID=25
	--model.k_p_PD=200
	--model.k_d_PD=15
	--model.k_ID_torque_scale=1
	----model.k_p_PD=10
	----model.k_d_PD=5
	--model.k_p_JTfoot=500
	--model.k_d_JTfoot=50
	--model.k_scale_active_pd.knee={0.5,0.5,1}
	--model.k_scale_id.knee={1,1,1}
	--model.k_scale_id.ankle={1,1,1}
	--model.k_scale_id.toes={1,1,1}
	--model.k_scale_id.shoulder={1,1,1}
	--model.initialHeight=0.0
end

--TODO:YSLEE
useCases.gait1956_6steps.segmentations=
{
	gait1956_6steps={
		--firstFrames={1*4,2*40,37*4,43*4,48*4,62*4,80*4,98*4,115*4,132*4,149*4,168*4},
		----                 b  r    d   L   R    L   R   L   R    L
		--names={          'stand','r','rl','l1', 'R1',  'L','R2','L2','R3'},
		--swingL={            0,    1,  0  ,  0 ,   1 ,   0,  1,  0,   1  },
		--swingR={            0,    0,  0  ,  1 ,   0 ,   1,  0,  1,   0  },
		firstFrames={1,   10,  80,  157,  227,  301,  373,  447, },
		--        (blank)    L    R    L     R     L     (blank)
		names={             'l', 'r', 'L1', 'R1', 'L2',  },
		swingL={             0,   1,   0,    1,    0,    },
		swingR={             1,   0,   1,    0,    1,    },
		footRefL= "convertFromSwingL",
		footRefR= "convertFromSwingR",
		usePositionControl=false,
	},
}
useCases.gait1956_6steps.graphParam={
	gait1956_6steps={
		--seg={          'stand','r','rl','l1','R1','L', 'R',},
		--num_key={         3,    3,  2,    3,  4  , 4,   4 , },
		--key_first={       0,    0, 'r',   0,  0  , 0,   0 , },
		--key_last={       'r', 'rl','l1','R1','L','R', 'L', },
		seg={            'l',  'r',  'L1', 'R1','L'},
		num_key={         3,    3,    3  ,  4,  4},
		key_first={       0,    0,    0  ,  0,  0},
		key_last={       'r', 'L1',  'R1', 'L', 'R1'},

	},
}
useCases.gait1956_6steps.graph={
	--{
		--"addInterpolatedSegment",
		--grpName="turn",
		--name="R",
		--seg0={"turn", "R2"},
		--seg1={"turn", "R1"},
		--startWeight=0, endWeight=1
	--},
	--{"connectMulti", "turn", "stand", "r", "rl", "l1",'R1', 'L', 'R', 'L'},
	--{"initialSegment", "turn", "stand"}
	{
		"addInterpolatedSegment",
		grpName="gait1956_6steps",
		name="L",
		seg0={"gait1956_6steps", "L2"},
		seg1={"gait1956_6steps", "L1"},
		startWeight=0, endWeight=1
	},
	{"connectMulti", "gait1956_6steps", "l", "r", "L1", "R1", "L", "R1"},
	{"initialSegment", "gait1956_6steps", "r"}
}
useCases.gait1956_6steps.segNames={
	"l", "r", "L1", 'R1','L',
}
--TODO:YSLEE

do 
	useCases.gait1956_6steps.controlParam={
		['useCases,gait1956_6steps,COMobjWeight']=0, 
		['useCases,gait1956_6steps,conservativeW']=1, 
		--['useCases,gait1956_6steps,contactMargin']=0.01, 
		['useCases,gait1956_6steps,dotMomentumScale']=0.3, 
		['useCases,gait1956_6steps,excludeRoot']=true, 
		['useCases,gait1956_6steps,headControlWeight']=0, 
		['useCases,gait1956_6steps,k_d_HEAD']=14, 
		['useCases,gait1956_6steps,k_p_HEAD']=0, 
		['useCases,gait1956_6steps,k_d_EE']=24, 
		['useCases,gait1956_6steps,k_d_momentum']=10, 
		['useCases,gait1956_6steps,k_p_EE']=120, 

		--['useCases,gait1956_6steps,maxPenetratingVel']=0, 
		['useCases,gait1956_6steps,momentumThr']=50, 
		['useCases,gait1956_6steps,noComvelDependentFootAdjustment']=true, 
		['useCases,gait1956_6steps,noIntersectionPrevenction']=true, 
		['useCases,gait1956_6steps,numericalDerivDmot']=true, 
		['useCases,gait1956_6steps,perClassContactMargin']=1, 
		['useCases,gait1956_6steps,turnGain']=10, 
		['useCases,gait1956_6steps,velMarginOffset']=0, 

		['useCases,gait1956_6steps,actuationType']      = useCases.gait1956_6steps.actuationType,
		['useCases,gait1956_6steps,k_p_ID']             = useCases.gait1956_6steps.k_p_ID,
		['useCases,gait1956_6steps,k_d_ID']             = useCases.gait1956_6steps.k_d_ID,
		['useCases,gait1956_6steps,ddqObjWeight']       = useCases.gait1956_6steps.ddqObjWeight,
		['useCases,gait1956_6steps,tauObjWeight']       = useCases.gait1956_6steps.tauObjWeight,
		['useCases,gait1956_6steps,ftObjWeight']        = useCases.gait1956_6steps.ftObjWeight,
		['useCases,gait1956_6steps,aObjWeight']         = useCases.gait1956_6steps.aObjWeight,
		['useCases,gait1956_6steps,lambdaObjWeight']    = useCases.gait1956_6steps.lambdaObjWeight,
		['useCases,gait1956_6steps,EEobjWeight']        = useCases.gait1956_6steps.EEobjWeight,
		['useCases,gait1956_6steps,EEobjWeightAngular'] = useCases.gait1956_6steps.EEobjWeightAngular,
		['useCases,gait1956_6steps,momentumWeight']     = useCases.gait1956_6steps.momentumWeight,
		['useCases,gait1956_6steps,tauMax']             = useCases.gait1956_6steps.tauMax,
		['useCases,gait1956_6steps,ftMax']              = useCases.gait1956_6steps.ftMax,
	}

	local function accumulate(cp_mod)
		local useCase=useCases.gait1956_6steps
		useCases.accumulate(useCase, cp_mod)
	end

	useCases.gait1956_6steps.noCOMjoint=true
	useCases.gait1956_6steps.spprtImpFromImp=true
	function modifySwingFoot(key, id, mod,inc,postfix)
		postfix=postfix or 'MocapMod'
		local useCase=useCases.walk3
		local c='map,'..key..',swingFoot'..postfix..','..id
		if inc then
			useCase.controlParam[c]=useCase.controlParam[c]+mod
		else
			useCase.controlParam[c]=mod
		end
	end

	--useCases.gait1956_6steps.useBulletColdet=true
	useCases.gait1956_6steps.useBulletColdet=false

	accumulate({
		--['keyframe,0,footRmod,gait1956_6steps,l,y']  = 0.,
		--['keyframe,1,footRmod,gait1956_6steps,l,y']  = 0.05,
		['keyframe,0,footLmod,gait1956_6steps,r,y']  = 0.0,
		['keyframe,1,footLmod,gait1956_6steps,r,y']  = 0.2,
		['keyframe,0,footRmod,gait1956_6steps,L1,y'] = 0.0,
		['keyframe,1,footRmod,gait1956_6steps,L1,y'] = 0.2,
		['map,0,swingFootMod,gait1956_6steps,y']     = 0.1,
		['map,1,swingFootMod,gait1956_6steps,y']     = 0.2,
		['map,2,swingFootMod,gait1956_6steps,y']     = 0.1,

		--['keyframe,0,footLmod,gait1956_6steps,l,y']  = 0.,
		--['keyframe,1,footLmod,gait1956_6steps,l,y']  = 0.,
		['keyframe,0,footRmod,gait1956_6steps,r,y']  = 0.,
		['keyframe,1,footRmod,gait1956_6steps,r,y']  = -.1,
		['keyframe,0,footLmod,gait1956_6steps,L1,y'] = 0.,
		['keyframe,1,footLmod,gait1956_6steps,L1,y'] = -.1,
		['map,0,spprtFootMod,gait1956_6steps,y']     = 0.,
		['map,1,spprtFootMod,gait1956_6steps,y']     = 0.,
		['map,2,spprtFootMod,gait1956_6steps,y']     = 0.,
	})

	useCases.unmapControlParam(useCases.gait1956_6steps)

--	------------------New optimization-------- [1e+100,-1e+100] -> oeval:116489.84818505 dim:18}) -- skipped oeval:116489.84818505 
--0.000 --0.000 --0.000 --0.000 --0.000 --0.000 --0.000 --0.000 --0.000 --0.000 
--Fri Dec 27 02:03:51 2013 setStage2 startSeg:1 endSeg:10 : [7.6990580555085e-07,130715.20029496] -> oeval:7.3470744879689e-07 dim:6}) -- skipped oeval:7.3470744879689e-07 
--accumulate({ ['map,0,swingFootMod,gait1956_6steps,x']= -0.077819050237286, ['map,0,swingFootMod,gait1956_6steps,y']= -0.30005161368114, ['map,0,swingFootMod,gait1956_6steps,z']= 0.054625692111398, ['map,1,swingFootMod,gait1956_6steps,x']= -0.11879545272157, ['map,1,swingFootMod,gait1956_6steps,y']= 0.36095339545557, ['map,1,swingFootMod,gait1956_6steps,z']= -0.022604369039572, ['map,2,swingFootMod,gait1956_6steps,x']= 0.29042416434641, ['map,2,swingFootMod,gait1956_6steps,y']= 0.20460022918898, ['map,2,swingFootMod,gait1956_6steps,z']= 0.022096212724781, ['map,0,spprtFootMod,gait1956_6steps,x']= 0.24986160843788, ['map,0,spprtFootMod,gait1956_6steps,y']= -0.014853854570615, ['map,0,spprtFootMod,gait1956_6steps,z']= -0.13357578088248, ['map,1,spprtFootMod,gait1956_6steps,x']= 0.19424430056833, ['map,1,spprtFootMod,gait1956_6steps,y']= -0.24992025856164, ['map,1,spprtFootMod,gait1956_6steps,z']= 0.063445844264148, ['map,2,spprtFootMod,gait1956_6steps,x']= -0.045003668528909, ['map,2,spprtFootMod,gait1956_6steps,y']= -0.25418555799844, ['map,2,spprtFootMod,gait1956_6steps,z']= -0.085658989848845, })
--0.981 --0.957 --0.957 --0.957 --prec=0.1

----	------------------New optimization-------- [1e+100,-1e+100] -> oeval:117334.91861655 dim:18}) -- skipped oeval:117334.91861655 
----0.000 --0.788 --0.000 --0.000 --0.000 --0.000 --0.000 --0.000 --0.000 --0.000 
----Mon Dec 30 21:05:04 2013 setStage2 startSeg:1 endSeg:10 : [1.0698466272821e-06,98039.1439594] -> oeval:1.019240495437e-06 dim:6}) -- skipped oeval:1.019240495437e-06 

--accumulate({ ['map,0,swingFootMod,gait1956_6steps,x']= -0.32786380515327, ['map,0,swingFootMod,gait1956_6steps,y']= -0.41492112470218, ['map,0,swingFootMod,gait1956_6steps,z']= -0.18116174910231, ['map,1,swingFootMod,gait1956_6steps,x']= 0.075281219835792, ['map,1,swingFootMod,gait1956_6steps,y']= 0.36720819876133, ['map,1,swingFootMod,gait1956_6steps,z']= 0.071350276234769, ['map,2,swingFootMod,gait1956_6steps,x']= 0.30335781509527, ['map,2,swingFootMod,gait1956_6steps,y']= 0.41585644008625, ['map,2,swingFootMod,gait1956_6steps,z']= -0.049968214495468, ['map,0,spprtFootMod,gait1956_6steps,x']= 0.45934362223231, ['map,0,spprtFootMod,gait1956_6steps,y']= -0.08005664075505, ['map,0,spprtFootMod,gait1956_6steps,z']= -0.24610908940733, ['map,1,spprtFootMod,gait1956_6steps,x']= -0.046078667831492, ['map,1,spprtFootMod,gait1956_6steps,y']= -0.16621408161752, ['map,1,spprtFootMod,gait1956_6steps,z']= 0.15704979416641, ['map,2,spprtFootMod,gait1956_6steps,x']= 0.069675797881987, ['map,2,spprtFootMod,gait1956_6steps,y']= -0.24655545790362, ['map,2,spprtFootMod,gait1956_6steps,z']= -0.0085933461429163, })
----1.032 --1.048 --1.048 --1.025 --1.025 --1.252 --1.044 --1.044 --1.044 --1.044 
----Mon Dec 30 22:47:40 2013 setStage3 startSeg:1 endSeg:10 : [1.0292906408039e-06,95363.087618846] -> oeval:1.0021972455181e-06 dim:6}) -- skipped oeval:1.0021972455181e-06 

--accumulate({ }) -- skipped iter :-1 ['map,0,swingFootMod,gait1956_6steps,z']= -0.13072513063458, ['map,1,swingFootMod,gait1956_6steps,z']= 0.14141148173709, ['map,2,swingFootMod,gait1956_6steps,z']= -0.059564358348985, ['map,0,spprtFootMod,gait1956_6steps,z']= -0.24201572822863, ['map,1,spprtFootMod,gait1956_6steps,z']= 0.17670721517513, ['map,2,spprtFootMod,gait1956_6steps,z']= -0.05288287123201, 
----1.032 --1.078 --1.024 --1.024 --1.043 --1.043 --1.043 --1.043 --1.043 --1.043 
----Tue Dec 31 00:31:04 2013 setStage4 startSeg:1 endSeg:10 : [1.0094799227208e-06,90574.355224918] -> oeval:9.8646941546697e-07 dim:6}) -- skipped oeval:9.8646941546697e-07 

--accumulate({ }) -- skipped iter :-1 ['map,0,swingFootMod,gait1956_6steps,x']= -0.33836763296628, ['map,1,swingFootMod,gait1956_6steps,x']= 0.082953437183878, ['map,2,swingFootMod,gait1956_6steps,x']= 0.28936448952506, ['map,0,spprtFootMod,gait1956_6steps,x']= 0.44714828821526, ['map,1,spprtFootMod,gait1956_6steps,x']= -0.038123657965452, ['map,2,spprtFootMod,gait1956_6steps,x']= 0.068778066449167, 
----1.434 --1.019 --1.025 --1.027 --1.112 /home/yslee/opt2/taesooLib_yslee/Samples/console


useCases.unmapControlParam(useCases.gait1956_6steps)

end


