require("subRoutines/Optimizer")

package.path=package.path..";../Samples/ysscripts/lib/?.lua" --;"..package.path
require("utilfunc")

package.path=package.path..";../Samples/ysscripts/samples/?.lua" --;"..package.path
require("useCaseMuscle_gait1956_6steps")


useCases.gait1956_adapt_tong_repeat=deepCopyTable(useCases.gait1956_6steps)

useCases.gait1956_adapt_tong_repeat.optimizerMethod='Optimizer.methods.CMAes_Adapt'

useCases.gait1956_adapt_tong_repeat.endSegW=10
--useCases.gait1956_adapt_tong_repeat.endSegW=4
useCases.gait1956_adapt_tong_repeat.prec=.2

useCases.gait1956_adapt_tong_repeat.modelName='gait1956_adapt_tong_repeat'
useCases.gait1956_adapt_tong_repeat.grpName='gait1956_adapt_tong_repeat'
useCases.gait1956_adapt_tong_repeat.grpNames={'gait1956_adapt_tong_repeat'}

useCases.gait1956_adapt_tong_repeat.k_p_ID=120
useCases.gait1956_adapt_tong_repeat.k_d_ID=2.*math.sqrt(120)
useCases.gait1956_adapt_tong_repeat.ddqObjWeight=10000000

--useCases.gait1956_adapt_tong_repeat.actuationType = ActuationType.tau
--useCases.gait1956_adapt_tong_repeat.actuationType = ActuationType.ft
--useCases.gait1956_adapt_tong_repeat.actuationType = ActuationType.a
useCases.gait1956_adapt_tong_repeat.actuationType = ActuationType.u

useCases.gait1956_adapt_tong_repeat.tauObjWeight=1
useCases.gait1956_adapt_tong_repeat.ftObjWeight=1
useCases.gait1956_adapt_tong_repeat.aObjWeight=10
useCases.gait1956_adapt_tong_repeat.lambdaObjWeight=10

useCases.gait1956_adapt_tong_repeat.EEobjWeight=60000000
useCases.gait1956_adapt_tong_repeat.EEobjWeightAngular=60000000
useCases.gait1956_adapt_tong_repeat.momentumWeight=8000000
useCases.gait1956_adapt_tong_repeat.headControlWeight=0

useCases.gait1956_adapt_tong_repeat.initMsclForceScale=1

-- the initial pendControlParam and pendOptimizationPath can be automatically generated by using createInitialPendControlParam.lua
useCases.gait1956_adapt_tong_repeat.pendControlParam=
{
['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,l,z']=0,['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,l,x']=1,['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,r,z']=0,['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,r,x']=1,['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L1,z']=0,['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L1,x']=1,['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,R1,z']=0,['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,R1,x']=1,['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L2,z']=0,['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L2,x']=1,['keyframe,0,pendDesiredVel,ignore,0,z']=0,['keyframe,0,pendDesiredVel,ignore,0,x']=1,['keyframe,0,pendDesiredVel,ignore,1,z']=0,['keyframe,0,pendDesiredVel,ignore,1,x']=1,
['keyframe,0,pendDesiredVel,ignore,0,x']=0.66962051405945, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.18381670796392, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,l,x']=0.94465402897006, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,l,z']=-0.08959452442499, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,r,x']=1.1448350461865, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,r,z']=-0.019028985186213, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L1,x']=1.219142677813, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L1,z']=0.018133702339633, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,R1,x']=1.1808840813187, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,R1,z']=0.014632311233628, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L2,x']=1.0726788728268, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L2,z']=0.0011759143402322, ['keyframe,0,pendDesiredVel,ignore,1,x']=1.001168258635, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.0066424642965002, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.66955164882083, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.18395009583681, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,l,x']=0.94456564368442, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,l,z']=-0.089717006277478, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,r,x']=1.1447995248424, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,r,z']=-0.019109379677296, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L1,x']=1.2190941359284, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L1,z']=0.018055826654249, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,R1,x']=1.1808449651169, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,R1,z']=0.014581646229227, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L2,x']=1.0727323072721, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L2,z']=0.0011579659018924, ['keyframe,0,pendDesiredVel,ignore,1,x']=1.0012439131541, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.0066446355153523, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.66953785718483, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.18397691858239, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,l,x']=0.94454776246108, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,l,z']=-0.089741636529682, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,r,x']=1.1447925066554, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,r,z']=-0.019125433335292, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L1,x']=1.219084330762, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L1,z']=0.018040139546162, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,R1,x']=1.1808370202132, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,R1,z']=0.014571400758833, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L2,x']=1.0727434218634, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L2,z']=0.0011543258372948, ['keyframe,0,pendDesiredVel,ignore,1,x']=1.0012596039332, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.0066450871502405, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.28846795527917, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.3336044680913, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,l,x']=1.2757760816674, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,l,z']=0.043149087391045, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,r,x']=1.3357383993046, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,r,z']=0.05160545920664, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L1,x']=1.1622595069635, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L1,z']=0.012067079789902, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,R1,x']=1.1042060703375, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,R1,z']=-0.038891802335703, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L2,x']=1.0753765034361, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L2,z']=-0.003411330346385, ['keyframe,0,pendDesiredVel,ignore,1,x']=1.0055423225754, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.005161361653873, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.28849458328745, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.33356796804292, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,l,x']=1.2757800942976, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,l,z']=0.043174649602597, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,r,x']=1.3357644301148, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,r,z']=0.051635916830859, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L1,x']=1.1622809761041, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L1,z']=0.012088236128798, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,R1,x']=1.1042081666204, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,R1,z']=-0.038881923137569, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L2,x']=1.0753708812512, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L2,z']=-0.0034113228487757, ['keyframe,0,pendDesiredVel,ignore,1,x']=1.0055416451873, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.0051615733179333, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.087115191889932, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.41522253170469, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,l,x']=1.7910940739155, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,l,z']=0.26340507761381, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,r,x']=1.3766624245191, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,r,z']=0.074682444481818, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.087002068435311, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.41530198454446, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,l,x']=1.7910702778853, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,l,z']=0.26338128720823, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,r,x']=1.3766428160885, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,r,z']=0.074676230458115, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.087000625549475, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.41530299845602, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,l,x']=1.7910699777259, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,l,z']=0.26338098520761, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,r,x']=1.3766425635445, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,r,z']=0.074676150596708, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.087000625328907, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.41530299861101, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,l,x']=1.79106997768, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,l,z']=0.26338098516145, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,r,x']=1.3766425635059, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,r,z']=0.074676150584499, 
['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,r,x']=0.97604333605472, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,r,z']=-0.10993662175825, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L1,x']=1.0965048647436, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L1,z']=-0.0094927135112825, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,R1,x']=1.2265946897683, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,R1,z']=0.011979514699824, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L2,x']=1.1671688578095, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L2,z']=0.039219866751207, ['keyframe,0,pendDesiredVel,ignore,1,x']=1.0112150711488, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.0026498233024977, 
['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,r,x']=0.97612313175009, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,r,z']=-0.10985623763177, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L1,x']=1.0965330046857, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L1,z']=-0.0094532307843218, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,R1,x']=1.2266175767892, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,R1,z']=0.012014621481885, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L2,x']=1.1671782422758, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L2,z']=0.039231074004354, ['keyframe,0,pendDesiredVel,ignore,1,x']=1.011214710477, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.0026497301332736, 
['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,r,x']=0.9761259498814, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,r,z']=-0.10985339500877, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L1,x']=1.0965340112712, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L1,z']=-0.0094518241647491, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,R1,x']=1.2266183905441, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,R1,z']=0.01201586424517, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L2,x']=1.1671785748589, ['keyframe,0,pendDesiredVel,gait1956_adapt_tong_repeat,L2,z']=0.03923147115995, ['keyframe,0,pendDesiredVel,ignore,1,x']=1.0112146980334, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.0026497266983117, 
}
useCases.gait1956_adapt_tong_repeat.pendOptimizationPath=
{
	firstFrames={1*4,18*4,35*4,52*4,69*4,86*4,103*4,118*4},
	segments={'ignore,0','gait1956_adapt_tong_repeat,l','gait1956_adapt_tong_repeat,r','gait1956_adapt_tong_repeat,L1','gait1956_adapt_tong_repeat,R1','gait1956_adapt_tong_repeat,L2','ignore,1'},
}
--useCases.gait1956_adapt_tong_repeat.measureOptCost=useCases.measureOptCost

useCases.gait1956_adapt_tong_repeat.segmentations=
{
	gait1956_adapt_tong_repeat={
		firstFrames={1*4,18*4,35*4,52*4,69*4,86*4,103*4,118*4},
		--        (blank)    L    R     L     R     L     (blank)
		names={             'l', 'r', 'L1', 'R1', 'L2',  },
		swingL={             0,   1,   0,    1,    0,    },
		swingR={             1,   0,   1,    0,    1,    },
		footRefL= "convertFromSwingL",
		footRefR= "convertFromSwingR",
		usePositionControl=false,
	},
}
useCases.gait1956_adapt_tong_repeat.graphParam=
{
	gait1956_adapt_tong_repeat={
		seg={            'l',  'r',  'L1', 'R1','L'},
		num_key={         3,    3,    3  ,  4,  4},
		key_first={       0,    0,    0  ,  0,  0},
		key_last={       'r', 'L1',  'R1', 'L', 'R1'},
	},
}
useCases.gait1956_adapt_tong_repeat.graph=
{
	{
		"addInterpolatedSegment",
		grpName="gait1956_adapt_tong_repeat",
		name="L",
		seg0={"gait1956_adapt_tong_repeat", "L2"},
		seg1={"gait1956_adapt_tong_repeat", "L1"},
		startWeight=0, endWeight=1
	},
	{"connectMulti", "gait1956_adapt_tong_repeat", "l", "r", "L1", "R1", "L", "R1"},
	--{"initialSegment", "gait1956_adapt_tong_repeat", "l"}
	{"initialSegment", "gait1956_adapt_tong_repeat", "R1"}
}
useCases.gait1956_adapt_tong_repeat.segNames=
{
	"l", "r", "L1", 'R1','L',
}

do 
	useCases.gait1956_adapt_tong_repeat.controlParam={
		['useCases,gait1956_adapt_tong_repeat,COMobjWeight']=0, 
		['useCases,gait1956_adapt_tong_repeat,conservativeW']=1, 
		--['useCases,gait1956_adapt_tong_repeat,contactMargin']=0.01, 
		['useCases,gait1956_adapt_tong_repeat,dotMomentumScale']=0.3, 
		['useCases,gait1956_adapt_tong_repeat,excludeRoot']=true, 
		['useCases,gait1956_adapt_tong_repeat,headControlWeight']=0, 
		['useCases,gait1956_adapt_tong_repeat,k_d_HEAD']=14, 
		['useCases,gait1956_adapt_tong_repeat,k_p_HEAD']=0, 
		['useCases,gait1956_adapt_tong_repeat,k_d_EE']=24, 
		['useCases,gait1956_adapt_tong_repeat,k_d_momentum']=10, 
		['useCases,gait1956_adapt_tong_repeat,k_p_EE']=120, 

		--['useCases,gait1956_adapt_tong_repeat,maxPenetratingVel']=0, 
		['useCases,gait1956_adapt_tong_repeat,momentumThr']=50, 
		['useCases,gait1956_adapt_tong_repeat,noComvelDependentFootAdjustment']=true, 
		['useCases,gait1956_adapt_tong_repeat,noIntersectionPrevenction']=true, 
		['useCases,gait1956_adapt_tong_repeat,numericalDerivDmot']=true, 
		['useCases,gait1956_adapt_tong_repeat,perClassContactMargin']=1, 
		['useCases,gait1956_adapt_tong_repeat,turnGain']=10, 
		['useCases,gait1956_adapt_tong_repeat,velMarginOffset']=0, 

		['useCases,gait1956_adapt_tong_repeat,actuationType']      = useCases.gait1956_adapt_tong_repeat.actuationType,
		['useCases,gait1956_adapt_tong_repeat,k_p_ID']             = useCases.gait1956_adapt_tong_repeat.k_p_ID,
		['useCases,gait1956_adapt_tong_repeat,k_d_ID']             = useCases.gait1956_adapt_tong_repeat.k_d_ID,
		['useCases,gait1956_adapt_tong_repeat,ddqObjWeight']       = useCases.gait1956_adapt_tong_repeat.ddqObjWeight,
		['useCases,gait1956_adapt_tong_repeat,tauObjWeight']       = useCases.gait1956_adapt_tong_repeat.tauObjWeight,
		['useCases,gait1956_adapt_tong_repeat,ftObjWeight']        = useCases.gait1956_adapt_tong_repeat.ftObjWeight,
		['useCases,gait1956_adapt_tong_repeat,aObjWeight']         = useCases.gait1956_adapt_tong_repeat.aObjWeight,
		['useCases,gait1956_adapt_tong_repeat,lambdaObjWeight']    = useCases.gait1956_adapt_tong_repeat.lambdaObjWeight,
		['useCases,gait1956_adapt_tong_repeat,EEobjWeight']        = useCases.gait1956_adapt_tong_repeat.EEobjWeight,
		['useCases,gait1956_adapt_tong_repeat,EEobjWeightAngular'] = useCases.gait1956_adapt_tong_repeat.EEobjWeightAngular,
		['useCases,gait1956_adapt_tong_repeat,momentumWeight']     = useCases.gait1956_adapt_tong_repeat.momentumWeight,
		['useCases,gait1956_adapt_tong_repeat,tauMax']             = useCases.gait1956_adapt_tong_repeat.tauMax,
		['useCases,gait1956_adapt_tong_repeat,ftMax']              = useCases.gait1956_adapt_tong_repeat.ftMax,
	}

	local function accumulate(cp_mod)
		local useCase=useCases.gait1956_adapt_tong_repeat
		useCases.accumulate(useCase, cp_mod)
	end

	accumulate({
		----['keyframe,0,footRmod,gait1956_adapt_tong_repeat,l,y']  = 0.,
		----['keyframe,1,footRmod,gait1956_adapt_tong_repeat,l,y']  = 0.05,
		--['keyframe,0,footLmod,gait1956_adapt_tong_repeat,r,y']  = 0.0,
		--['keyframe,1,footLmod,gait1956_adapt_tong_repeat,r,y']  = 0.2,
		--['keyframe,0,footRmod,gait1956_adapt_tong_repeat,L1,y'] = 0.0,
		--['keyframe,1,footRmod,gait1956_adapt_tong_repeat,L1,y'] = 0.2,
		--['map,0,swingFootMod,gait1956_adapt_tong_repeat,y']     = 0.1,
		--['map,1,swingFootMod,gait1956_adapt_tong_repeat,y']     = 0.2,
		--['map,2,swingFootMod,gait1956_adapt_tong_repeat,y']     = 0.1,

		----['keyframe,0,footLmod,gait1956_adapt_tong_repeat,l,y']  = 0.,
		----['keyframe,1,footLmod,gait1956_adapt_tong_repeat,l,y']  = 0.,
		--['keyframe,0,footRmod,gait1956_adapt_tong_repeat,r,y']  = 0.,
		--['keyframe,1,footRmod,gait1956_adapt_tong_repeat,r,y']  = -.1,
		--['keyframe,0,footLmod,gait1956_adapt_tong_repeat,L1,y'] = 0.,
		--['keyframe,1,footLmod,gait1956_adapt_tong_repeat,L1,y'] = -.1,
		--['map,0,spprtFootMod,gait1956_adapt_tong_repeat,y']     = 0.,
		--['map,1,spprtFootMod,gait1956_adapt_tong_repeat,y']     = 0.,
		--['map,2,spprtFootMod,gait1956_adapt_tong_repeat,y']     = 0.,
	})

	useCases.unmapControlParam(useCases.gait1956_adapt_tong_repeat)

----iter 83
--accumulate({['map,0,swingFootMod,gait1956_adapt_tong_repeat,x']= 0.40808920054402, ['map,0,swingFootMod,gait1956_adapt_tong_repeat,y']= 0.17542435568053, ['map,0,swingFootMod,gait1956_adapt_tong_repeat,z']= -0.13065606042498, ['map,1,swingFootMod,gait1956_adapt_tong_repeat,x']= -0.20290199908838, ['map,1,swingFootMod,gait1956_adapt_tong_repeat,y']= -0.19977654806704, ['map,1,swingFootMod,gait1956_adapt_tong_repeat,z']= -0.049786632091801, ['map,2,swingFootMod,gait1956_adapt_tong_repeat,x']= -0.026704666180159, ['map,2,swingFootMod,gait1956_adapt_tong_repeat,y']= -0.021295534858019, ['map,2,swingFootMod,gait1956_adapt_tong_repeat,z']= 0.18383780627229, ['map,0,spprtFootMod,gait1956_adapt_tong_repeat,x']= 0.12231576289984, ['map,0,spprtFootMod,gait1956_adapt_tong_repeat,y']= -1.593516666194, ['map,0,spprtFootMod,gait1956_adapt_tong_repeat,z']= 0.19348476805127, ['map,1,spprtFootMod,gait1956_adapt_tong_repeat,x']= -0.69116018973425, ['map,1,spprtFootMod,gait1956_adapt_tong_repeat,y']= -0.4311344806079, ['map,1,spprtFootMod,gait1956_adapt_tong_repeat,z']= -0.10658047024377, ['map,2,spprtFootMod,gait1956_adapt_tong_repeat,x']= 0.13727091791805, ['map,2,spprtFootMod,gait1956_adapt_tong_repeat,y']= -0.14930416766396, ['map,2,spprtFootMod,gait1956_adapt_tong_repeat,z']= -0.097252008191405, })
--local f_m_o = {2773.6822940991,1818.9792266234,1816.6668946464,4080.3901552156,923.36068016245,264.04091784964,3629.1900050315,499.64606869687,340.11943988118,200.31378880085,896.16853790547,1166.2215826092,714.3190259271,2418.0121417562,2271.9227459142,605.7530164692,223.07931257178,671.75008015011,2880.5129430697,10881.910629704,5225.9418934355,8117.6321017708,5179.3402285287,4422.2198493687,1882.6986257461,2541.7206840414,1752.097791665,1895.2687777902,4107.4680761983,972.19052320154,271.34191718586,3462.6233792212,464.69409546622,331.34794595869,202.44557123148,852.51650446086,1256.1753846519,750.76251877369,2269.8091895482,2281.4721884924,636.24746267199,227.18273223178,691.86535282038,2931.0722613965,10453.318419174,4894.3303931642,7709.1655377619,4965.9779881572,4228.4413597052,1848.5487958191,4315.8764160199,4271.7245427359,1633.2424152286,1663.6158350795,1460.2846984379,1461.0493648174}

----iter 477
--accumulate({['map,0,swingFootMod,gait1956_adapt_tong_repeat,x']= -0.18305557723813, ['map,0,swingFootMod,gait1956_adapt_tong_repeat,y']= 0.16155409221534, ['map,0,swingFootMod,gait1956_adapt_tong_repeat,z']= -0.26356576672036, ['map,1,swingFootMod,gait1956_adapt_tong_repeat,x']= 0.1591551204131, ['map,1,swingFootMod,gait1956_adapt_tong_repeat,y']= -0.063583357987585, ['map,1,swingFootMod,gait1956_adapt_tong_repeat,z']= 0.15261798944696, ['map,2,swingFootMod,gait1956_adapt_tong_repeat,x']= -0.16430313795718, ['map,2,swingFootMod,gait1956_adapt_tong_repeat,y']= 0.22652833405831, ['map,2,swingFootMod,gait1956_adapt_tong_repeat,z']= -0.0065473699436334, ['map,0,spprtFootMod,gait1956_adapt_tong_repeat,x']= -0.11937731070741, ['map,0,spprtFootMod,gait1956_adapt_tong_repeat,y']= -0.84364902175546, ['map,0,spprtFootMod,gait1956_adapt_tong_repeat,z']= 0.19124473064836, ['map,1,spprtFootMod,gait1956_adapt_tong_repeat,x']= -0.57881842969063, ['map,1,spprtFootMod,gait1956_adapt_tong_repeat,y']= -0.40902335484864, ['map,1,spprtFootMod,gait1956_adapt_tong_repeat,z']= -0.3894480717905, ['map,2,spprtFootMod,gait1956_adapt_tong_repeat,x']= 0.042113477989048, ['map,2,spprtFootMod,gait1956_adapt_tong_repeat,y']= -0.35652555939838, ['map,2,spprtFootMod,gait1956_adapt_tong_repeat,z']= 0.087298260805016, })
--local f_m_o = {4495.9296416828,2796.3286812942,2715.5789959758,4757.6098768216,953.66861819083,330.66672357391,4430.4339642653,691.50498943128,359.10687261546,211.07560451594,1085.9419294722,1313.9435719006,780.77813668028,3477.259663214,3177.6807142555,773.07434762636,246.86371635223,832.43641549822,4771.1197705453,17788.834011237,7369.7661137254,11296.592408623,6304.7475789514,5437.4444960067,2598.4126677708,4601.1610320823,2891.5257443497,2827.345130909,5240.6690750044,997.54942964626,352.20218036204,4111.5362504849,689.69886587236,345.98330407834,210.49462301447,1053.6343632161,1455.4119928647,819.56366527904,3424.8790449227,3341.6445648372,788.38709000939,248.55915750828,858.24332304473,5079.8088482709,17201.816998395,8056.408371526,13678.634451807,6563.4000175862,5845.3457830106,2672.5949456251,5883.9760967979,5926.2212885442,2091.894914556,2117.9631892302,1687.8706391768,1755.3266263464}

--useCases.gait1956_adapt_tong_repeat.f_m_o = f_m_o
useCases.unmapControlParam(useCases.gait1956_adapt_tong_repeat)
end


