package.path=package.path..";../Samples/ysscripts/lib/?.lua" --;"..package.path
require("utilfunc")

package.path=package.path..";../Samples/ysscripts/samples/?.lua" --;"..package.path
require("useMuscle_g2562_gait")


useCases.g2562_srun=deepCopyTable(useCases.g2562_gait)


useCases.g2562_srun.optimizerMethod='Optimizer.methods.CMAes_ys'

useCases.g2562_srun.endSegW=20
useCases.g2562_srun.prec=.2
--useCases.g2562_srun.endSegW=40
--useCases.g2562_srun.prec=.05

useCases.g2562_srun.modelName='g2562_srun'
useCases.g2562_srun.grpName='g2562_srun'
useCases.g2562_srun.grpNames={'g2562_srun'}

-- the initial pendControlParam and pendOptimizationPath can be automatically generated by using createInitialPendControlParam.lua
useCases.g2562_srun.pendControlParam=
{
['keyframe,0,pendDesiredVel,g2562_srun,l,z']=0,['keyframe,0,pendDesiredVel,g2562_srun,l,x']=1,['keyframe,0,pendDesiredVel,g2562_srun,r,z']=0,['keyframe,0,pendDesiredVel,g2562_srun,r,x']=1,['keyframe,0,pendDesiredVel,g2562_srun,L1,z']=0,['keyframe,0,pendDesiredVel,g2562_srun,L1,x']=1,['keyframe,0,pendDesiredVel,g2562_srun,R1,z']=0,['keyframe,0,pendDesiredVel,g2562_srun,R1,x']=1,['keyframe,0,pendDesiredVel,g2562_srun,L2,z']=0,['keyframe,0,pendDesiredVel,g2562_srun,L2,x']=1,['keyframe,0,pendDesiredVel,ignore,0,z']=0,['keyframe,0,pendDesiredVel,ignore,0,x']=1,['keyframe,0,pendDesiredVel,ignore,1,z']=0,['keyframe,0,pendDesiredVel,ignore,1,x']=1,
['keyframe,0,pendDesiredVel,ignore,0,x']=-0.35767289006965, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.44807370212594, ['keyframe,0,pendDesiredVel,g2562_srun,l,x']=1.0180451856619, ['keyframe,0,pendDesiredVel,g2562_srun,l,z']=0.15805859147666, ['keyframe,0,pendDesiredVel,g2562_srun,r,x']=0.79124545399388, ['keyframe,0,pendDesiredVel,g2562_srun,r,z']=-0.02048408700085, ['keyframe,0,pendDesiredVel,g2562_srun,L1,x']=0.51916446242951, ['keyframe,0,pendDesiredVel,g2562_srun,L1,z']=0.020088927856808, ['keyframe,0,pendDesiredVel,g2562_srun,R1,x']=0.5098976587487, ['keyframe,0,pendDesiredVel,g2562_srun,R1,z']=-0.054098495157611, ['keyframe,0,pendDesiredVel,g2562_srun,L2,x']=0.74127062014114, ['keyframe,0,pendDesiredVel,g2562_srun,L2,z']=-0.11401430652775, ['keyframe,0,pendDesiredVel,ignore,1,x']=1.0238724760698, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.006035699085617, 
['keyframe,0,pendDesiredVel,ignore,0,x']=-0.35757018365303, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.44793704421198, ['keyframe,0,pendDesiredVel,g2562_srun,l,x']=1.0181028548675, ['keyframe,0,pendDesiredVel,g2562_srun,l,z']=0.15813427516858, ['keyframe,0,pendDesiredVel,g2562_srun,r,x']=0.79129845383915, ['keyframe,0,pendDesiredVel,g2562_srun,r,z']=-0.020432135478896, ['keyframe,0,pendDesiredVel,g2562_srun,L1,x']=0.51916845914068, ['keyframe,0,pendDesiredVel,g2562_srun,L1,z']=0.020091944372944, ['keyframe,0,pendDesiredVel,g2562_srun,R1,x']=0.50987611766569, ['keyframe,0,pendDesiredVel,g2562_srun,R1,z']=-0.054106190924225, ['keyframe,0,pendDesiredVel,g2562_srun,L2,x']=0.74126265991833, ['keyframe,0,pendDesiredVel,g2562_srun,L2,z']=-0.11401605309702, ['keyframe,0,pendDesiredVel,ignore,1,x']=1.0238737830602, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.0060359623776214, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.27155378679456, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.14833610764373, ['keyframe,0,pendDesiredVel,g2562_srun,l,x']=0.38808808718903, ['keyframe,0,pendDesiredVel,g2562_srun,l,z']=-0.10234962166034, ['keyframe,0,pendDesiredVel,g2562_srun,r,x']=0.51384026859666, ['keyframe,0,pendDesiredVel,g2562_srun,r,z']=-0.058252119384794, ['keyframe,0,pendDesiredVel,g2562_srun,L1,x']=0.59639208991231, ['keyframe,0,pendDesiredVel,g2562_srun,L1,z']=-0.037837555350624, ['keyframe,0,pendDesiredVel,g2562_srun,R1,x']=0.63640621329316, ['keyframe,0,pendDesiredVel,g2562_srun,R1,z']=-0.04705270971781, ['keyframe,0,pendDesiredVel,g2562_srun,L2,x']=0.64974520177864, ['keyframe,0,pendDesiredVel,g2562_srun,L2,z']=-0.064201187639779, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.65554627288268, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.072749144917743, 
['keyframe,0,pendDesiredVel,ignore,0,x']=-0.25307177642288, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.40514975687258, ['keyframe,0,pendDesiredVel,g2562_srun,l,x']=0.8211529225375, ['keyframe,0,pendDesiredVel,g2562_srun,l,z']=0.062546382226614, ['keyframe,0,pendDesiredVel,g2562_srun,r,x']=0.84923342933044, ['keyframe,0,pendDesiredVel,g2562_srun,r,z']=0.053526576066267, ['keyframe,0,pendDesiredVel,g2562_srun,L1,x']=0.5922852092562, ['keyframe,0,pendDesiredVel,g2562_srun,L1,z']=0.033181081682747, ['keyframe,0,pendDesiredVel,g2562_srun,R1,x']=0.50031526963899, ['keyframe,0,pendDesiredVel,g2562_srun,R1,z']=-0.070451814661557, ['keyframe,0,pendDesiredVel,g2562_srun,L2,x']=0.57337328382062, ['keyframe,0,pendDesiredVel,g2562_srun,L2,z']=-0.12059405900701, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.66429822132415, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.069250483859507, 
['keyframe,0,pendDesiredVel,ignore,0,x']=-0.25293561884076, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.40504152402282, ['keyframe,0,pendDesiredVel,g2562_srun,l,x']=0.82120563953325, ['keyframe,0,pendDesiredVel,g2562_srun,l,z']=0.062597344826014, ['keyframe,0,pendDesiredVel,g2562_srun,r,x']=0.84928643882301, ['keyframe,0,pendDesiredVel,g2562_srun,r,z']=0.05357584312519, ['keyframe,0,pendDesiredVel,g2562_srun,L1,x']=0.59229927711432, ['keyframe,0,pendDesiredVel,g2562_srun,L1,z']=0.033193133719518, ['keyframe,0,pendDesiredVel,g2562_srun,R1,x']=0.50029536837458, ['keyframe,0,pendDesiredVel,g2562_srun,R1,z']=-0.070452815258553, ['keyframe,0,pendDesiredVel,g2562_srun,L2,x']=0.57335847509539, ['keyframe,0,pendDesiredVel,g2562_srun,L2,z']=-0.12059397747416, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.66429937416347, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.069250582891468, 
['keyframe,0,pendDesiredVel,ignore,0,x']=-0.25292164737028, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.40503039533016, ['keyframe,0,pendDesiredVel,g2562_srun,l,x']=0.8212111709822, ['keyframe,0,pendDesiredVel,g2562_srun,l,z']=0.062602648740409, ['keyframe,0,pendDesiredVel,g2562_srun,r,x']=0.84929193569425, ['keyframe,0,pendDesiredVel,g2562_srun,r,z']=0.053580934046921, ['keyframe,0,pendDesiredVel,g2562_srun,L1,x']=0.59230078653118, ['keyframe,0,pendDesiredVel,g2562_srun,L1,z']=0.033194432322497, ['keyframe,0,pendDesiredVel,g2562_srun,R1,x']=0.50029341255496, ['keyframe,0,pendDesiredVel,g2562_srun,R1,z']=-0.070452875751183, ['keyframe,0,pendDesiredVel,g2562_srun,L2,x']=0.57335699439225, ['keyframe,0,pendDesiredVel,g2562_srun,L2,z']=-0.1205939577618, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.66429948838569, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.069250594462161, 
}
useCases.g2562_srun.pendOptimizationPath=
{
	firstFrames={1*4,11*4,21*4,31*4,41*4,51*4,61*4,71*4},
	segments={'ignore,0','g2562_srun,l','g2562_srun,r','g2562_srun,L1','g2562_srun,R1','g2562_srun,L2','ignore,1'},
}
--useCases.g2562_srun.measureOptCost=useCases.measureOptCost

useCases.g2562_srun.segmentations=
{
	g2562_srun={
		firstFrames={1*4,11*4,21*4,31*4,41*4,51*4,61*4,71*4},
		--        (blank)    L    R     L     R     L     (blank)
		names={             'l', 'r', 'L1', 'R1', 'L2',  },
		swingL={             0,   1,   0,    1,    0,    },
		swingR={             1,   0,   1,    0,    1,    },
		footRefL= "convertFromSwingL",
		footRefR= "convertFromSwingR",
		usePositionControl=false,
	},
}
useCases.g2562_srun.graphParam=
{
	g2562_srun={
		seg={            'l',  'r',  'L1', 'R1','L'},
		num_key={         3,    3,    3  ,  4,  4},
		key_first={       0,    0,    0  ,  0,  0},
		key_last={       'r', 'L1',  'R1', 'L', 'R1'},
	},
}
useCases.g2562_srun.graph=
{
	{
		"addInterpolatedSegment",
		grpName="g2562_srun",
		name="L",
		seg0={"g2562_srun", "L2"},
		seg1={"g2562_srun", "L1"},
		startWeight=0, endWeight=1
	},
	{"connectMulti", "g2562_srun", "l", "r", "L1", "R1", "L", "R1"},
	--{"initialSegment", "g2562_srun", "l"}
	{"initialSegment", "g2562_srun", "R1"}
}
useCases.g2562_srun.segNames=
{
	"l", "r", "L1", 'R1','L',
}

do 
	useCases.g2562_srun.controlParam={
		['useCases,g2562_srun,COMobjWeight']=0, 
		['useCases,g2562_srun,conservativeW']=1, 
		--['useCases,g2562_srun,contactMargin']=0.01, 
		['useCases,g2562_srun,dotMomentumScale']=0.3, 
		['useCases,g2562_srun,excludeRoot']=true, 
		['useCases,g2562_srun,headControlWeight']=0, 
		['useCases,g2562_srun,k_d_HEAD']=14, 
		['useCases,g2562_srun,k_p_HEAD']=0, 
		['useCases,g2562_srun,k_d_EE']=24, 
		['useCases,g2562_srun,k_d_momentum']=10, 
		['useCases,g2562_srun,k_p_EE']=120, 

		--['useCases,g2562_srun,maxPenetratingVel']=0, 
		['useCases,g2562_srun,momentumThr']=50, 
		['useCases,g2562_srun,noComvelDependentFootAdjustment']=true, 
		['useCases,g2562_srun,noIntersectionPrevenction']=true, 
		['useCases,g2562_srun,numericalDerivDmot']=true, 
		['useCases,g2562_srun,perClassContactMargin']=1, 
		['useCases,g2562_srun,turnGain']=10, 
		['useCases,g2562_srun,velMarginOffset']=0, 

		['useCases,g2562_srun,actuationType']      = useCases.g2562_srun.actuationType,
		['useCases,g2562_srun,k_p_ID']             = useCases.g2562_srun.k_p_ID,
		['useCases,g2562_srun,k_d_ID']             = useCases.g2562_srun.k_d_ID,
		['useCases,g2562_srun,ddqObjWeight']       = useCases.g2562_srun.ddqObjWeight,
		['useCases,g2562_srun,tauObjWeight']       = useCases.g2562_srun.tauObjWeight,
		['useCases,g2562_srun,ftObjWeight']        = useCases.g2562_srun.ftObjWeight,
		['useCases,g2562_srun,aObjWeight']         = useCases.g2562_srun.aObjWeight,
		['useCases,g2562_srun,lambdaObjWeight']    = useCases.g2562_srun.lambdaObjWeight,
		['useCases,g2562_srun,EEobjWeight']        = useCases.g2562_srun.EEobjWeight,
		['useCases,g2562_srun,EEobjWeightAngular'] = useCases.g2562_srun.EEobjWeightAngular,
		['useCases,g2562_srun,momentumWeight']     = useCases.g2562_srun.momentumWeight,
		['useCases,g2562_srun,tauMax']             = useCases.g2562_srun.tauMax,
		['useCases,g2562_srun,ftMax']              = useCases.g2562_srun.ftMax,
	}

	local function accumulate(cp_mod)
		local useCase=useCases.g2562_srun
		useCases.accumulate(useCase, cp_mod)
	end

	accumulate({
		----['keyframe,0,footRmod,g2562_srun,l,y']  = 0.,
		----['keyframe,1,footRmod,g2562_srun,l,y']  = 0.05,
		--['keyframe,0,footLmod,g2562_srun,r,y']  = 0.0,
		--['keyframe,1,footLmod,g2562_srun,r,y']  = 0.2,
		--['keyframe,0,footRmod,g2562_srun,L1,y'] = 0.0,
		--['keyframe,1,footRmod,g2562_srun,L1,y'] = 0.2,
		--['map,0,swingFootMod,g2562_srun,y']     = 0.1,
		--['map,1,swingFootMod,g2562_srun,y']     = 0.2,
		--['map,2,swingFootMod,g2562_srun,y']     = 0.1,

		----['keyframe,0,footLmod,g2562_srun,l,y']  = 0.,
		----['keyframe,1,footLmod,g2562_srun,l,y']  = 0.,
		--['keyframe,0,footRmod,g2562_srun,r,y']  = 0.,
		--['keyframe,1,footRmod,g2562_srun,r,y']  = -.1,
		--['keyframe,0,footLmod,g2562_srun,L1,y'] = 0.,
		--['keyframe,1,footLmod,g2562_srun,L1,y'] = -.1,
		--['map,0,spprtFootMod,g2562_srun,y']     = 0.,
		--['map,1,spprtFootMod,g2562_srun,y']     = 0.,
		--['map,2,spprtFootMod,g2562_srun,y']     = 0.,
	})
	useCases.unmapControlParam(useCases.g2562_srun)


-------------------------------------------------
if g_mode=='default' then
	--iter:524 bestfvever:8.2926735742365e-07
	accumulate({['map,0,swingFootMod,g2562_srun,x']= 0.17067075313354, ['map,0,swingFootMod,g2562_srun,y']= -0.17258868411795, ['map,0,swingFootMod,g2562_srun,z']= -0.63486573067051, ['map,1,swingFootMod,g2562_srun,x']= 0.072713132056895, ['map,1,swingFootMod,g2562_srun,y']= -0.37273097627098, ['map,1,swingFootMod,g2562_srun,z']= -1.6860687202114, ['map,2,swingFootMod,g2562_srun,x']= 0.078271340476881, ['map,2,swingFootMod,g2562_srun,y']= 0.013445175581716, ['map,2,swingFootMod,g2562_srun,z']= 0.65113337774017, ['map,0,spprtFootMod,g2562_srun,x']= -0.34566923600003, ['map,0,spprtFootMod,g2562_srun,y']= -0.051698170852612, ['map,0,spprtFootMod,g2562_srun,z']= 0.41788543731402, ['map,1,spprtFootMod,g2562_srun,x']= 0.57707530636112, ['map,1,spprtFootMod,g2562_srun,y']= 0.24897081329931, ['map,1,spprtFootMod,g2562_srun,z']= -0.41237255313035, ['map,2,spprtFootMod,g2562_srun,x']= -0.57220721793378, ['map,2,spprtFootMod,g2562_srun,y']= -1.6630788900594, ['map,2,spprtFootMod,g2562_srun,z']= 0.88954649202911, })

elseif g_mode=='a_.1' then
	useCases.g2562_srun.aObjWeight = .1*useCases.g2562_srun.aObjWeight

elseif g_mode=='a_.01' then
	useCases.g2562_srun.aObjWeight = .01*useCases.g2562_srun.aObjWeight

	--iter:257 bestfvever:7.0677865795088e-07
	accumulate({['map,0,swingFootMod,g2562_srun,x']= -0.12807162247666, ['map,0,swingFootMod,g2562_srun,y']= -2.4017011897929, ['map,0,swingFootMod,g2562_srun,z']= -0.029377708761502, ['map,1,swingFootMod,g2562_srun,x']= -0.34798078057064, ['map,1,swingFootMod,g2562_srun,y']= -1.0608020006908, ['map,1,swingFootMod,g2562_srun,z']= -0.39531897600154, ['map,2,swingFootMod,g2562_srun,x']= -0.40366736378842, ['map,2,swingFootMod,g2562_srun,y']= 0.20333929018133, ['map,2,swingFootMod,g2562_srun,z']= 0.19298027446556, ['map,0,spprtFootMod,g2562_srun,x']= 0.099460373035038, ['map,0,spprtFootMod,g2562_srun,y']= -0.27401261059559, ['map,0,spprtFootMod,g2562_srun,z']= 0.17682911844129, ['map,1,spprtFootMod,g2562_srun,x']= -0.0022421375137319, ['map,1,spprtFootMod,g2562_srun,y']= 0.87516302759204, ['map,1,spprtFootMod,g2562_srun,z']= -0.10631743181491, ['map,2,spprtFootMod,g2562_srun,x']= 0.31589306423738, ['map,2,spprtFootMod,g2562_srun,y']= -2.4713804463467, ['map,2,spprtFootMod,g2562_srun,z']= 0.14391083741621, })

	useCases.g2562_srun.endSegW=40
	useCases.g2562_srun.prec=.05

	--iter:124 bestfvever:1.0367921962255e-06
	accumulate({['map,0,swingFootMod,g2562_srun,x']= -0.15480023593825, ['map,0,swingFootMod,g2562_srun,y']= -2.5764070718869, ['map,0,swingFootMod,g2562_srun,z']= -0.070433213445024, ['map,1,swingFootMod,g2562_srun,x']= -0.52873594277717, ['map,1,swingFootMod,g2562_srun,y']= -0.99944303481691, ['map,1,swingFootMod,g2562_srun,z']= -0.30002096242574, ['map,2,swingFootMod,g2562_srun,x']= 0.087723734054258, ['map,2,swingFootMod,g2562_srun,y']= 0.38695497631242, ['map,2,swingFootMod,g2562_srun,z']= 0.33545142181775, ['map,0,spprtFootMod,g2562_srun,x']= -0.1698623706665, ['map,0,spprtFootMod,g2562_srun,y']= -0.35316835978568, ['map,0,spprtFootMod,g2562_srun,z']= 0.096138142466136, ['map,1,spprtFootMod,g2562_srun,x']= 0.020861386322752, ['map,1,spprtFootMod,g2562_srun,y']= 0.92286009156089, ['map,1,spprtFootMod,g2562_srun,z']= -0.092410095131304, ['map,2,spprtFootMod,g2562_srun,x']= 0.47063935446475, ['map,2,spprtFootMod,g2562_srun,y']= -2.7527067022283, ['map,2,spprtFootMod,g2562_srun,z']= 0.35981268494882, })

elseif g_mode=='a_.1_mscl_2x' then
	useCases.g2562_srun.aObjWeight = .1*useCases.g2562_srun.aObjWeight
	useCases.g2562_srun.initMsclForceScale=2

elseif g_mode=='a_.01_mscl_2x' then
	useCases.g2562_srun.aObjWeight = .01*useCases.g2562_srun.aObjWeight
	useCases.g2562_srun.initMsclForceScale=2

	--iter:280 bestfvever:1.0509302761759e-06
	accumulate({['map,0,swingFootMod,g2562_srun,x']= -0.02760533776241, ['map,0,swingFootMod,g2562_srun,y']= -1.3069623005883, ['map,0,swingFootMod,g2562_srun,z']= 0.70192194680393, ['map,1,swingFootMod,g2562_srun,x']= -0.37444374160642, ['map,1,swingFootMod,g2562_srun,y']= 0.61173041286062, ['map,1,swingFootMod,g2562_srun,z']= 0.066040881380227, ['map,2,swingFootMod,g2562_srun,x']= 0.64908132398546, ['map,2,swingFootMod,g2562_srun,y']= -0.11649008381794, ['map,2,swingFootMod,g2562_srun,z']= 0.065904570032935, ['map,0,spprtFootMod,g2562_srun,x']= -0.43986011963792, ['map,0,spprtFootMod,g2562_srun,y']= -0.062782053883262, ['map,0,spprtFootMod,g2562_srun,z']= 0.3684404678236, ['map,1,spprtFootMod,g2562_srun,x']= 0.37186216342588, ['map,1,spprtFootMod,g2562_srun,y']= 0.29127636187218, ['map,1,spprtFootMod,g2562_srun,z']= -0.45646472010744, ['map,2,spprtFootMod,g2562_srun,x']= -0.30173990965654, ['map,2,spprtFootMod,g2562_srun,y']= -2.2079227644169, ['map,2,spprtFootMod,g2562_srun,z']= 0.85970325170672, })

end
-------------------------------------------------

useCases.g2562_srun.controlParam['useCases,g2562_srun,aObjWeight'] = useCases.g2562_srun.aObjWeight

useCases.unmapControlParam(useCases.g2562_srun)
end


