package.path=package.path..";../Samples/ysscripts/lib/?.lua" --;"..package.path
require("utilfunc")

package.path=package.path..";../Samples/ysscripts/samples/?.lua" --;"..package.path
require("useMuscle_g2562_gait")


useCases.g2562_frun=deepCopyTable(useCases.g2562_gait)

useCases.g2562_frun.optimizerMethod='Optimizer.methods.CMAes_ys'

useCases.g2562_frun.endSegW=30
useCases.g2562_frun.prec=.2
--useCases.g2562_frun.endSegW=20
--useCases.g2562_frun.prec=.05

useCases.g2562_frun.modelName='g2562_frun'
useCases.g2562_frun.grpName='g2562_frun'
useCases.g2562_frun.grpNames={'g2562_frun'}

-- the initial pendControlParam and pendOptimizationPath can be automatically generated by using createInitialPendControlParam.lua
useCases.g2562_frun.pendControlParam=
{
['keyframe,0,pendDesiredVel,g2562_frun,l,z']=0,['keyframe,0,pendDesiredVel,g2562_frun,l,x']=1,['keyframe,0,pendDesiredVel,g2562_frun,r,z']=0,['keyframe,0,pendDesiredVel,g2562_frun,r,x']=1,['keyframe,0,pendDesiredVel,g2562_frun,L1,z']=0,['keyframe,0,pendDesiredVel,g2562_frun,L1,x']=1,['keyframe,0,pendDesiredVel,g2562_frun,R1,z']=0,['keyframe,0,pendDesiredVel,g2562_frun,R1,x']=1,['keyframe,0,pendDesiredVel,g2562_frun,L2,z']=0,['keyframe,0,pendDesiredVel,g2562_frun,L2,x']=1,['keyframe,0,pendDesiredVel,ignore,0,z']=0,['keyframe,0,pendDesiredVel,ignore,0,x']=1,['keyframe,0,pendDesiredVel,ignore,1,z']=0,['keyframe,0,pendDesiredVel,ignore,1,x']=1,
--['keyframe,0,pendDesiredVel,ignore,0,x']=0.78969206185521, ['keyframe,0,pendDesiredVel,ignore,0,z']=0.0037966796006218, ['keyframe,0,pendDesiredVel,g2592_frun,l,x']=1.0430796578948, ['keyframe,0,pendDesiredVel,g2592_frun,l,z']=-0.0011786920508408, ['keyframe,0,pendDesiredVel,g2592_frun,r,x']=1.3005469324335, ['keyframe,0,pendDesiredVel,g2592_frun,r,z']=-0.01977300899313, ['keyframe,0,pendDesiredVel,g2592_frun,L1,x']=1.4551134126608, ['keyframe,0,pendDesiredVel,g2592_frun,L1,z']=-0.040110199156526, ['keyframe,0,pendDesiredVel,g2592_frun,R1,x']=1.5038643633942, ['keyframe,0,pendDesiredVel,g2592_frun,R1,z']=-0.070033182970951, ['keyframe,0,pendDesiredVel,g2592_frun,L2,x']=1.5039234606925, ['keyframe,0,pendDesiredVel,g2592_frun,L2,z']=-0.094113286737521, ['keyframe,0,pendDesiredVel,ignore,1,x']=1.5089191337407, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.10652833636798, 
--['keyframe,0,pendDesiredVel,ignore,0,x']=0.78743591798034, ['keyframe,0,pendDesiredVel,ignore,0,z']=0.005177370183111, ['keyframe,0,pendDesiredVel,g2592_frun,l,x']=1.0388898489663, ['keyframe,0,pendDesiredVel,g2592_frun,l,z']=-0.0010443230074479, ['keyframe,0,pendDesiredVel,g2592_frun,r,x']=1.2975924793186, ['keyframe,0,pendDesiredVel,g2592_frun,r,z']=-0.01819983355841, ['keyframe,0,pendDesiredVel,g2592_frun,L1,x']=1.4534288602378, ['keyframe,0,pendDesiredVel,g2592_frun,L1,z']=-0.040544995635961, ['keyframe,0,pendDesiredVel,g2592_frun,R1,x']=1.5048065952854, ['keyframe,0,pendDesiredVel,g2592_frun,R1,z']=-0.06917133123023, ['keyframe,0,pendDesiredVel,g2592_frun,L2,x']=1.504763393367, ['keyframe,0,pendDesiredVel,g2592_frun,L2,z']=-0.094278980662385, ['keyframe,0,pendDesiredVel,ignore,1,x']=1.5065816837531, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.1064148800435, 
--['keyframe,0,pendDesiredVel,ignore,0,x']=-0.74564965255283, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.051670596750029, ['keyframe,0,pendDesiredVel,g2592_frun,l,x']=2.6143648567767, ['keyframe,0,pendDesiredVel,g2592_frun,l,z']=-0.01736250466656, ['keyframe,0,pendDesiredVel,g2592_frun,r,x']=1.8917100722749, ['keyframe,0,pendDesiredVel,g2592_frun,r,z']=0.025516995124152, ['keyframe,0,pendDesiredVel,g2592_frun,L1,x']=1.4468202978879, ['keyframe,0,pendDesiredVel,g2592_frun,L1,z']=-0.063688434522029, ['keyframe,0,pendDesiredVel,g2592_frun,R1,x']=1.4846436926893, ['keyframe,0,pendDesiredVel,g2592_frun,R1,z']=0.08218050134498, ['keyframe,0,pendDesiredVel,g2592_frun,L2,x']=1.5248296749459, ['keyframe,0,pendDesiredVel,g2592_frun,L2,z']=-0.043533723326886, ['keyframe,0,pendDesiredVel,ignore,1,x']=1.5096746485813, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.12675166560342, 
--['keyframe,0,pendDesiredVel,ignore,0,x']=-0.74578794987764, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.051653597621573, ['keyframe,0,pendDesiredVel,g2592_frun,l,x']=2.6143524078372, ['keyframe,0,pendDesiredVel,g2592_frun,l,z']=-0.017346254274098, ['keyframe,0,pendDesiredVel,g2592_frun,r,x']=1.8916310902234, ['keyframe,0,pendDesiredVel,g2592_frun,r,z']=0.025528831459383, ['keyframe,0,pendDesiredVel,g2592_frun,L1,x']=1.4467891036114, ['keyframe,0,pendDesiredVel,g2592_frun,L1,z']=-0.063688055085196, ['keyframe,0,pendDesiredVel,g2592_frun,R1,x']=1.4846534207932, ['keyframe,0,pendDesiredVel,g2592_frun,R1,z']=0.082188146369084, ['keyframe,0,pendDesiredVel,g2592_frun,L2,x']=1.5248400901892, ['keyframe,0,pendDesiredVel,g2592_frun,L2,z']=-0.043533346136171, ['keyframe,0,pendDesiredVel,ignore,1,x']=1.5096737403336, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.1267528876476, 
--['keyframe,0,pendDesiredVel,ignore,0,x']=-0.74582340449904, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.05164924468044, ['keyframe,0,pendDesiredVel,g2592_frun,l,x']=2.6143497561951, ['keyframe,0,pendDesiredVel,g2592_frun,l,z']=-0.017342100386444, ['keyframe,0,pendDesiredVel,g2592_frun,r,x']=1.8916107667593, ['keyframe,0,pendDesiredVel,g2592_frun,r,z']=0.025531868850245, ['keyframe,0,pendDesiredVel,g2592_frun,L1,x']=1.4467811782517, ['keyframe,0,pendDesiredVel,g2592_frun,L1,z']=-0.063688012316576, ['keyframe,0,pendDesiredVel,g2592_frun,R1,x']=1.4846561241871, ['keyframe,0,pendDesiredVel,g2592_frun,R1,z']=0.082190129854152, ['keyframe,0,pendDesiredVel,g2592_frun,L2,x']=1.5248428621414, ['keyframe,0,pendDesiredVel,g2592_frun,L2,z']=-0.043533252663248, ['keyframe,0,pendDesiredVel,ignore,1,x']=1.5096734933469, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.1267532074067, 
--['keyframe,0,pendDesiredVel,ignore,0,x']=-0.74583278399582, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.051648093514899, ['keyframe,0,pendDesiredVel,g2592_frun,l,x']=2.614349092207, ['keyframe,0,pendDesiredVel,g2592_frun,l,z']=-0.017341002364294, ['keyframe,0,pendDesiredVel,g2592_frun,r,x']=1.8916053849555, ['keyframe,0,pendDesiredVel,g2592_frun,r,z']=0.025532672566848, ['keyframe,0,pendDesiredVel,g2592_frun,L1,x']=1.4467790865738, ['keyframe,0,pendDesiredVel,g2592_frun,L1,z']=-0.063688004807952, ['keyframe,0,pendDesiredVel,g2592_frun,R1,x']=1.4846568539115, ['keyframe,0,pendDesiredVel,g2592_frun,R1,z']=0.082190656212331, ['keyframe,0,pendDesiredVel,g2592_frun,L2,x']=1.5248436025333, ['keyframe,0,pendDesiredVel,g2592_frun,L2,z']=-0.043533228161453, ['keyframe,0,pendDesiredVel,ignore,1,x']=1.5096734270246, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.12675329244786, 
['keyframe,0,pendDesiredVel,ignore,0,x']=1.0633092549019, ['keyframe,0,pendDesiredVel,ignore,0,z']=0.016700625881945, ['keyframe,0,pendDesiredVel,g2562_frun,l,x']=1.2983430002093, ['keyframe,0,pendDesiredVel,g2562_frun,l,z']=0.0023433462100189, ['keyframe,0,pendDesiredVel,g2562_frun,r,x']=1.4463855078747, ['keyframe,0,pendDesiredVel,g2562_frun,r,z']=-0.027178517353351, ['keyframe,0,pendDesiredVel,g2562_frun,L1,x']=1.4828114732427, ['keyframe,0,pendDesiredVel,g2562_frun,L1,z']=-0.066755377686, ['keyframe,0,pendDesiredVel,g2562_frun,R1,x']=1.4527598831195, ['keyframe,0,pendDesiredVel,g2562_frun,R1,z']=-0.10893312406583, ['keyframe,0,pendDesiredVel,g2562_frun,L2,x']=1.4159428362603, ['keyframe,0,pendDesiredVel,g2562_frun,L2,z']=-0.14034323001042, ['keyframe,0,pendDesiredVel,ignore,1,x']=1.4062929502715, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.15000433361666, 
['keyframe,0,pendDesiredVel,ignore,0,x']=1.0633030319028, ['keyframe,0,pendDesiredVel,ignore,0,z']=0.016691656038625, ['keyframe,0,pendDesiredVel,g2562_frun,l,x']=1.2979017838116, ['keyframe,0,pendDesiredVel,g2562_frun,l,z']=0.0023360807847078, ['keyframe,0,pendDesiredVel,g2562_frun,r,x']=1.4460288140896, ['keyframe,0,pendDesiredVel,g2562_frun,r,z']=-0.027182020612269, ['keyframe,0,pendDesiredVel,g2562_frun,L1,x']=1.4827971342885, ['keyframe,0,pendDesiredVel,g2562_frun,L1,z']=-0.066751975129618, ['keyframe,0,pendDesiredVel,g2562_frun,R1,x']=1.4528008002395, ['keyframe,0,pendDesiredVel,g2562_frun,R1,z']=-0.10892702392693, ['keyframe,0,pendDesiredVel,g2562_frun,L2,x']=1.4159825233564, ['keyframe,0,pendDesiredVel,g2562_frun,L2,z']=-0.14034049252713, ['keyframe,0,pendDesiredVel,ignore,1,x']=1.4062828725539, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.15001068433712, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.4840074641654, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.050960073601218, ['keyframe,0,pendDesiredVel,g2562_frun,l,x']=2.5944583230346, ['keyframe,0,pendDesiredVel,g2562_frun,l,z']=0.19595477925364, ['keyframe,0,pendDesiredVel,g2562_frun,r,x']=1.8601215965131, ['keyframe,0,pendDesiredVel,g2562_frun,r,z']=-0.028288578592389, ['keyframe,0,pendDesiredVel,g2562_frun,L1,x']=1.2883493299382, ['keyframe,0,pendDesiredVel,g2562_frun,L1,z']=-0.0057249854638489, ['keyframe,0,pendDesiredVel,g2562_frun,R1,x']=1.273555706559, ['keyframe,0,pendDesiredVel,g2562_frun,R1,z']=-0.061292639825187, ['keyframe,0,pendDesiredVel,g2562_frun,L2,x']=1.4330648014912, ['keyframe,0,pendDesiredVel,g2562_frun,L2,z']=-0.15361157872375, ['keyframe,0,pendDesiredVel,ignore,1,x']=1.4073817471795, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.15006815630025, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.48389797465892, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.05147020564051, ['keyframe,0,pendDesiredVel,g2562_frun,l,x']=2.5945772088108, ['keyframe,0,pendDesiredVel,g2562_frun,l,z']=0.19579122141161, ['keyframe,0,pendDesiredVel,g2562_frun,r,x']=1.8601417699849, ['keyframe,0,pendDesiredVel,g2562_frun,r,z']=-0.028436651608126, ['keyframe,0,pendDesiredVel,g2562_frun,L1,x']=1.288431097148, ['keyframe,0,pendDesiredVel,g2562_frun,L1,z']=-0.0057867845316124, ['keyframe,0,pendDesiredVel,g2562_frun,R1,x']=1.2736320880702, ['keyframe,0,pendDesiredVel,g2562_frun,R1,z']=-0.061297605517661, ['keyframe,0,pendDesiredVel,g2562_frun,L2,x']=1.4330597257844, ['keyframe,0,pendDesiredVel,g2562_frun,L2,z']=-0.15361150603931, ['keyframe,0,pendDesiredVel,ignore,1,x']=1.4073805789694, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.15006798315441, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.48389363627599, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.051489630159108, ['keyframe,0,pendDesiredVel,g2562_frun,l,x']=2.5945820651736, ['keyframe,0,pendDesiredVel,g2562_frun,l,z']=0.19578507361443, ['keyframe,0,pendDesiredVel,g2562_frun,r,x']=1.8601426120444, ['keyframe,0,pendDesiredVel,g2562_frun,r,z']=-0.028442313730346, ['keyframe,0,pendDesiredVel,g2562_frun,L1,x']=1.2884344290615, ['keyframe,0,pendDesiredVel,g2562_frun,L1,z']=-0.0057891020116181, ['keyframe,0,pendDesiredVel,g2562_frun,R1,x']=1.2736351895457, ['keyframe,0,pendDesiredVel,g2562_frun,R1,z']=-0.061297758026277, ['keyframe,0,pendDesiredVel,g2562_frun,L2,x']=1.4330595191959, ['keyframe,0,pendDesiredVel,g2562_frun,L2,z']=-0.1536115127652, ['keyframe,0,pendDesiredVel,ignore,1,x']=1.4073805315415, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.15006797662989, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.48389346730574, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.051490385501364, ['keyframe,0,pendDesiredVel,g2562_frun,l,x']=2.594582254538, ['keyframe,0,pendDesiredVel,g2562_frun,l,z']=0.19578483467749, ['keyframe,0,pendDesiredVel,g2562_frun,r,x']=1.8601426449043, ['keyframe,0,pendDesiredVel,g2562_frun,r,z']=-0.028442533945614, ['keyframe,0,pendDesiredVel,g2562_frun,L1,x']=1.2884345589706, ['keyframe,0,pendDesiredVel,g2562_frun,L1,z']=-0.0057891920728952, ['keyframe,0,pendDesiredVel,g2562_frun,R1,x']=1.2736353104545, ['keyframe,0,pendDesiredVel,g2562_frun,R1,z']=-0.061297763898968, ['keyframe,0,pendDesiredVel,g2562_frun,L2,x']=1.4330595111415, ['keyframe,0,pendDesiredVel,g2562_frun,L2,z']=-0.15361151304174, ['keyframe,0,pendDesiredVel,ignore,1,x']=1.4073805296926, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.15006797637628, 
}
useCases.g2562_frun.pendOptimizationPath=
{
	--firstFrames={1*4,10*4,19*4,28*4,37*4,46*4,55*4,64*4},
	firstFrames={1*4,17*4,26*4,35*4,44*4,53*4,62*4,64*4},
	segments={'ignore,0','g2562_frun,l','g2562_frun,r','g2562_frun,L1','g2562_frun,R1','g2562_frun,L2','ignore,1'},
}
--useCases.g2562_frun.measureOptCost=useCases.measureOptCost

useCases.g2562_frun.segmentations=
{
	g2562_frun={
		--firstFrames={1*4,10*4,19*4,28*4,37*4,46*4,55*4,64*4},
		firstFrames={1*4,17*4,26*4,35*4,44*4,53*4,62*4,64*4},
		--        (blank)    L    R     L     R     L     (blank)
		names={             'l', 'r', 'L1', 'R1', 'L2',  },
		swingL={             0,   1,   0,    1,    0,    },
		swingR={             1,   0,   1,    0,    1,    },
		footRefL= "convertFromSwingL",
		footRefR= "convertFromSwingR",
		usePositionControl=false,
	},
}
useCases.g2562_frun.graphParam=
{
	g2562_frun={
		seg={            'l',  'r',  'L1', 'R1','L'},
		num_key={         3,    3,    3  ,  4,  4},
		key_first={       0,    0,    0  ,  0,  0},
		key_last={       'r', 'L1',  'R1', 'L', 'R1'},
	},
}
useCases.g2562_frun.graph=
{
	{
		"addInterpolatedSegment",
		grpName="g2562_frun",
		name="L",
		seg0={"g2562_frun", "L2"},
		seg1={"g2562_frun", "L1"},
		startWeight=0, endWeight=1
	},
	{"connectMulti", "g2562_frun", "l", "r", "L1", "R1", "L", "R1"},
	--{"initialSegment", "g2562_frun", "l"}
	{"initialSegment", "g2562_frun", "R1"}
}
useCases.g2562_frun.segNames=
{
	"l", "r", "L1", 'R1','L',
}

do 
	useCases.g2562_frun.controlParam={
		['useCases,g2562_frun,COMobjWeight']=0, 
		['useCases,g2562_frun,conservativeW']=1, 
		--['useCases,g2562_frun,contactMargin']=0.01, 
		['useCases,g2562_frun,dotMomentumScale']=0.3, 
		['useCases,g2562_frun,excludeRoot']=true, 
		['useCases,g2562_frun,headControlWeight']=0, 
		['useCases,g2562_frun,k_d_HEAD']=14, 
		['useCases,g2562_frun,k_p_HEAD']=0, 
		['useCases,g2562_frun,k_d_EE']=24, 
		['useCases,g2562_frun,k_d_momentum']=10, 
		['useCases,g2562_frun,k_p_EE']=120, 

		--['useCases,g2562_frun,maxPenetratingVel']=0, 
		['useCases,g2562_frun,momentumThr']=50, 
		['useCases,g2562_frun,noComvelDependentFootAdjustment']=true, 
		['useCases,g2562_frun,noIntersectionPrevenction']=true, 
		['useCases,g2562_frun,numericalDerivDmot']=true, 
		['useCases,g2562_frun,perClassContactMargin']=1, 
		['useCases,g2562_frun,turnGain']=10, 
		['useCases,g2562_frun,velMarginOffset']=0, 

		['useCases,g2562_frun,actuationType']      = useCases.g2562_frun.actuationType,
		['useCases,g2562_frun,k_p_ID']             = useCases.g2562_frun.k_p_ID,
		['useCases,g2562_frun,k_d_ID']             = useCases.g2562_frun.k_d_ID,
		['useCases,g2562_frun,ddqObjWeight']       = useCases.g2562_frun.ddqObjWeight,
		['useCases,g2562_frun,tauObjWeight']       = useCases.g2562_frun.tauObjWeight,
		['useCases,g2562_frun,ftObjWeight']        = useCases.g2562_frun.ftObjWeight,
		['useCases,g2562_frun,aObjWeight']         = useCases.g2562_frun.aObjWeight,
		['useCases,g2562_frun,lambdaObjWeight']    = useCases.g2562_frun.lambdaObjWeight,
		['useCases,g2562_frun,EEobjWeight']        = useCases.g2562_frun.EEobjWeight,
		['useCases,g2562_frun,EEobjWeightAngular'] = useCases.g2562_frun.EEobjWeightAngular,
		['useCases,g2562_frun,momentumWeight']     = useCases.g2562_frun.momentumWeight,
		['useCases,g2562_frun,tauMax']             = useCases.g2562_frun.tauMax,
		['useCases,g2562_frun,ftMax']              = useCases.g2562_frun.ftMax,
	}

	local function accumulate(cp_mod)
		local useCase=useCases.g2562_frun
		useCases.accumulate(useCase, cp_mod)
	end

	accumulate({
		----['keyframe,0,footRmod,g2562_frun,l,y']  = 0.,
		----['keyframe,1,footRmod,g2562_frun,l,y']  = 0.05,
		--['keyframe,0,footLmod,g2562_frun,r,y']  = 0.0,
		--['keyframe,1,footLmod,g2562_frun,r,y']  = 0.2,
		--['keyframe,0,footRmod,g2562_frun,L1,y'] = 0.0,
		--['keyframe,1,footRmod,g2562_frun,L1,y'] = 0.2,
		--['map,0,swingFootMod,g2562_frun,y']     = 0.1,
		--['map,1,swingFootMod,g2562_frun,y']     = 0.2,
		--['map,2,swingFootMod,g2562_frun,y']     = 0.1,

		----['keyframe,0,footLmod,g2562_frun,l,y']  = 0.,
		----['keyframe,1,footLmod,g2562_frun,l,y']  = 0.,
		--['keyframe,0,footRmod,g2562_frun,r,y']  = 0.,
		--['keyframe,1,footRmod,g2562_frun,r,y']  = -.1,
		--['keyframe,0,footLmod,g2562_frun,L1,y'] = 0.,
		--['keyframe,1,footLmod,g2562_frun,L1,y'] = -.1,
		--['map,0,spprtFootMod,g2562_frun,y']     = 0.,
		--['map,1,spprtFootMod,g2562_frun,y']     = 0.,
		--['map,2,spprtFootMod,g2562_frun,y']     = 0.,
	})
	useCases.unmapControlParam(useCases.g2562_frun)


-------------------------------------------------
if g_mode=='default' then
	--iter:1197 bestfvever:0.00020265225016573
	accumulate({['map,0,swingFootMod,g2562_frun,x']= -1.4889966994527, ['map,0,swingFootMod,g2562_frun,y']= -1.3957000353229, ['map,0,swingFootMod,g2562_frun,z']= 1.5194155982256, ['map,1,swingFootMod,g2562_frun,x']= 1.9283337817321, ['map,1,swingFootMod,g2562_frun,y']= -0.96762908582531, ['map,1,swingFootMod,g2562_frun,z']= 0.3131547076416, ['map,2,swingFootMod,g2562_frun,x']= 1.3715893649657, ['map,2,swingFootMod,g2562_frun,y']= 1.5648619937655, ['map,2,swingFootMod,g2562_frun,z']= 1.0893719294108, ['map,0,spprtFootMod,g2562_frun,x']= 1.7322525595307, ['map,0,spprtFootMod,g2562_frun,y']= 0.062852163208724, ['map,0,spprtFootMod,g2562_frun,z']= -0.40704696583412, ['map,1,spprtFootMod,g2562_frun,x']= 1.0543850836177, ['map,1,spprtFootMod,g2562_frun,y']= -1.894875253633, ['map,1,spprtFootMod,g2562_frun,z']= 0.92006427609259, ['map,2,spprtFootMod,g2562_frun,x']= 0.9371060413233, ['map,2,spprtFootMod,g2562_frun,y']= -0.89451727616295, ['map,2,spprtFootMod,g2562_frun,z']= 1.2262589085323, })

elseif g_mode=='a_.1' then
	useCases.g2562_frun.aObjWeight = .1*useCases.g2562_frun.aObjWeight

elseif g_mode=='a_.01' then
	useCases.g2562_frun.aObjWeight = .01*useCases.g2562_frun.aObjWeight

	--iter:321 bestfvever:3.1129373242804e-06
	accumulate({['map,0,swingFootMod,g2562_frun,x']= -0.41112669161806, ['map,0,swingFootMod,g2562_frun,y']= 0.32856550819379, ['map,0,swingFootMod,g2562_frun,z']= 0.088801728021303, ['map,1,swingFootMod,g2562_frun,x']= 0.19780990955915, ['map,1,swingFootMod,g2562_frun,y']= -0.071846511413899, ['map,1,swingFootMod,g2562_frun,z']= -0.18955582424636, ['map,2,swingFootMod,g2562_frun,x']= 0.32243532439563, ['map,2,swingFootMod,g2562_frun,y']= 0.7481894443408, ['map,2,swingFootMod,g2562_frun,z']= 0.11047516562263, ['map,0,spprtFootMod,g2562_frun,x']= 0.16921429180232, ['map,0,spprtFootMod,g2562_frun,y']= -1.0656090100817, ['map,0,spprtFootMod,g2562_frun,z']= 0.038546105011621, ['map,1,spprtFootMod,g2562_frun,x']= 0.47855140032307, ['map,1,spprtFootMod,g2562_frun,y']= -3.2627522636358, ['map,1,spprtFootMod,g2562_frun,z']= 0.89467225416298, ['map,2,spprtFootMod,g2562_frun,x']= -0.97432975817526, ['map,2,spprtFootMod,g2562_frun,y']= -0.63683866038817, ['map,2,spprtFootMod,g2562_frun,z']= -0.52929461002254, })

elseif g_mode=='a_.01_nost' then
	useCases.g2562_frun.aObjWeight = .01*useCases.g2562_frun.aObjWeight
	useCases.g2562_frun.noStride=true

	--iter:602 bestfvever:170277.77813655
	accumulate({['map,0,swingFootMod,g2562_frun,x']= -0.33538676430927, ['map,0,swingFootMod,g2562_frun,y']= 0.16526240167334, ['map,0,swingFootMod,g2562_frun,z']= 0.57068659486365, ['map,1,swingFootMod,g2562_frun,x']= -0.02076150276262, ['map,1,swingFootMod,g2562_frun,y']= 0.087859037134282, ['map,1,swingFootMod,g2562_frun,z']= 0.11487170833531, ['map,2,swingFootMod,g2562_frun,x']= -0.15211557143867, ['map,2,swingFootMod,g2562_frun,y']= -0.1251901678058, ['map,2,swingFootMod,g2562_frun,z']= 0.11703733640872, ['map,0,spprtFootMod,g2562_frun,x']= -0.22239380967907, ['map,0,spprtFootMod,g2562_frun,y']= -0.014569851137227, ['map,0,spprtFootMod,g2562_frun,z']= 0.31828334687904, ['map,1,spprtFootMod,g2562_frun,x']= -0.20258109783881, ['map,1,spprtFootMod,g2562_frun,y']= -0.60207804081225, ['map,1,spprtFootMod,g2562_frun,z']= -0.30757171849729, ['map,2,spprtFootMod,g2562_frun,x']= 0.72328443935333, ['map,2,spprtFootMod,g2562_frun,y']= 0.42182491182002, ['map,2,spprtFootMod,g2562_frun,z']= -0.26154696041452, })

elseif g_mode=='a_.1_mscl_2x' then
	useCases.g2562_frun.aObjWeight = .1*useCases.g2562_frun.aObjWeight
	useCases.g2562_frun.initMsclForceScale=2

elseif g_mode=='a_.01_mscl_2x' then
	useCases.g2562_frun.aObjWeight = .01*useCases.g2562_frun.aObjWeight
	useCases.g2562_frun.initMsclForceScale=2

	--iter:1069 bestfvever:163391.21883774
	accumulate({['map,0,swingFootMod,g2562_frun,x']= 0.39972482387463, ['map,0,swingFootMod,g2562_frun,y']= 0.093078192233261, ['map,0,swingFootMod,g2562_frun,z']= 0.076178678050089, ['map,1,swingFootMod,g2562_frun,x']= -0.22839493860601, ['map,1,swingFootMod,g2562_frun,y']= -0.081553174324661, ['map,1,swingFootMod,g2562_frun,z']= 0.066656484201857, ['map,2,swingFootMod,g2562_frun,x']= -0.20569463153037, ['map,2,swingFootMod,g2562_frun,y']= 0.082579147039332, ['map,2,swingFootMod,g2562_frun,z']= 0.20122885184437, ['map,0,spprtFootMod,g2562_frun,x']= -0.1519137224246, ['map,0,spprtFootMod,g2562_frun,y']= -0.34999464549014, ['map,0,spprtFootMod,g2562_frun,z']= 0.15760902551515, ['map,1,spprtFootMod,g2562_frun,x']= -0.26591744409852, ['map,1,spprtFootMod,g2562_frun,y']= 0.039298190159301, ['map,1,spprtFootMod,g2562_frun,z']= 0.23932594935743, ['map,2,spprtFootMod,g2562_frun,x']= 0.2830126865133, ['map,2,spprtFootMod,g2562_frun,y']= 0.1745989398956, ['map,2,spprtFootMod,g2562_frun,z']= -0.22291225120743, })

end
-------------------------------------------------

useCases.g2562_frun.controlParam['useCases,g2562_frun,aObjWeight'] = useCases.g2562_frun.aObjWeight

useCases.unmapControlParam(useCases.g2562_frun)
end


