package.path=package.path..";../Samples/ysscripts/lib/?.lua" --;"..package.path
require("utilfunc")

package.path=package.path..";../Samples/ysscripts/samples/?.lua" --;"..package.path
require("useMuscle_g2592_gait")


useCases.g2592_soldier=deepCopyTable(useCases.g2592_gait)

useCases.g2592_soldier.optimizerMethod='Optimizer.methods.CMAes_ys'

--useCases.g2592_soldier.endSegW=10
useCases.g2592_soldier.endSegW=15
useCases.g2592_soldier.prec=.2
--useCases.g2592_soldier.endSegW=20
--useCases.g2592_soldier.prec=.05

useCases.g2592_soldier.modelName='g2592_soldier'
useCases.g2592_soldier.grpName='g2592_soldier'
useCases.g2592_soldier.grpNames={'g2592_soldier'}

-- the initial pendControlParam and pendOptimizationPath can be automatically generated by using createInitialPendControlParam.lua
useCases.g2592_soldier.pendControlParam=
{
['keyframe,0,pendDesiredVel,g2592_soldier,l,z']=0,['keyframe,0,pendDesiredVel,g2592_soldier,l,x']=1,['keyframe,0,pendDesiredVel,g2592_soldier,r,z']=0,['keyframe,0,pendDesiredVel,g2592_soldier,r,x']=1,['keyframe,0,pendDesiredVel,g2592_soldier,L1,z']=0,['keyframe,0,pendDesiredVel,g2592_soldier,L1,x']=1,['keyframe,0,pendDesiredVel,g2592_soldier,R1,z']=0,['keyframe,0,pendDesiredVel,g2592_soldier,R1,x']=1,['keyframe,0,pendDesiredVel,g2592_soldier,L2,z']=0,['keyframe,0,pendDesiredVel,g2592_soldier,L2,x']=1,['keyframe,0,pendDesiredVel,ignore,0,z']=0,['keyframe,0,pendDesiredVel,ignore,0,x']=1,['keyframe,0,pendDesiredVel,ignore,1,z']=0,['keyframe,0,pendDesiredVel,ignore,1,x']=1,
['keyframe,0,pendDesiredVel,ignore,0,x']=0.36797409998736, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.3743257650133, ['keyframe,0,pendDesiredVel,g2592_soldier,l,x']=0.60098376615087, ['keyframe,0,pendDesiredVel,g2592_soldier,l,z']=-0.11983137019458, ['keyframe,0,pendDesiredVel,g2592_soldier,r,x']=0.6970461329397, ['keyframe,0,pendDesiredVel,g2592_soldier,r,z']=0.0190728158501, ['keyframe,0,pendDesiredVel,g2592_soldier,L1,x']=0.69671817442555, ['keyframe,0,pendDesiredVel,g2592_soldier,L1,z']=0.021068094069994, ['keyframe,0,pendDesiredVel,g2592_soldier,R1,x']=0.70480350690452, ['keyframe,0,pendDesiredVel,g2592_soldier,R1,z']=-0.00038642943420218, ['keyframe,0,pendDesiredVel,g2592_soldier,L2,x']=0.78749586761275, ['keyframe,0,pendDesiredVel,g2592_soldier,L2,z']=0.013450637700571, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.91299856606176, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.0071755012999322, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.36770240597161, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.37461271498011, ['keyframe,0,pendDesiredVel,g2592_soldier,l,x']=0.60066286946084, ['keyframe,0,pendDesiredVel,g2592_soldier,l,z']=-0.11993257619515, ['keyframe,0,pendDesiredVel,g2592_soldier,r,x']=0.69682266766094, ['keyframe,0,pendDesiredVel,g2592_soldier,r,z']=0.019076816222352, ['keyframe,0,pendDesiredVel,g2592_soldier,L1,x']=0.69661811123491, ['keyframe,0,pendDesiredVel,g2592_soldier,L1,z']=0.021264028964944, ['keyframe,0,pendDesiredVel,g2592_soldier,R1,x']=0.70466037325592, ['keyframe,0,pendDesiredVel,g2592_soldier,R1,z']=-0.00021003801599291, ['keyframe,0,pendDesiredVel,g2592_soldier,L2,x']=0.78733743417009, ['keyframe,0,pendDesiredVel,g2592_soldier,L2,z']=0.013519533223315, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.91265227416363, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.0071733182772124, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.17013109548502, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.61343524297257, ['keyframe,0,pendDesiredVel,g2592_soldier,l,x']=0.83615273787798, ['keyframe,0,pendDesiredVel,g2592_soldier,l,z']=0.10523851640355, ['keyframe,0,pendDesiredVel,g2592_soldier,r,x']=0.77512394105668, ['keyframe,0,pendDesiredVel,g2592_soldier,r,z']=0.096137646356837, ['keyframe,0,pendDesiredVel,g2592_soldier,L1,x']=0.6782086052256, ['keyframe,0,pendDesiredVel,g2592_soldier,L1,z']=-0.019918892518898, ['keyframe,0,pendDesiredVel,g2592_soldier,R1,x']=0.62069643362997, ['keyframe,0,pendDesiredVel,g2592_soldier,R1,z']=-0.077308356009735, ['keyframe,0,pendDesiredVel,g2592_soldier,L2,x']=0.70049989668891, ['keyframe,0,pendDesiredVel,g2592_soldier,L2,z']=0.058523298725177, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.89580110552067, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.0068700639779648, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.17001613124803, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.61349537114204, ['keyframe,0,pendDesiredVel,g2592_soldier,l,x']=0.83607661906976, ['keyframe,0,pendDesiredVel,g2592_soldier,l,z']=0.10525273702869, ['keyframe,0,pendDesiredVel,g2592_soldier,r,x']=0.77500314464263, ['keyframe,0,pendDesiredVel,g2592_soldier,r,z']=0.096103068969992, ['keyframe,0,pendDesiredVel,g2592_soldier,L1,x']=0.67815114990027, ['keyframe,0,pendDesiredVel,g2592_soldier,L1,z']=-0.019894266173977, ['keyframe,0,pendDesiredVel,g2592_soldier,R1,x']=0.62069400703745, ['keyframe,0,pendDesiredVel,g2592_soldier,R1,z']=-0.077262520575897, ['keyframe,0,pendDesiredVel,g2592_soldier,L2,x']=0.70050897926517, ['keyframe,0,pendDesiredVel,g2592_soldier,L2,z']=0.058570929718939, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.89579891625729, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.0068723085968423, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.042639978300676, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.89179870871487, ['keyframe,0,pendDesiredVel,g2592_soldier,l,x']=1.7339957091803, ['keyframe,0,pendDesiredVel,g2592_soldier,l,z']=1.4062236433716, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.042668135328741, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.89175593727717, ['keyframe,0,pendDesiredVel,g2592_soldier,l,x']=1.7339967897267, ['keyframe,0,pendDesiredVel,g2592_soldier,l,z']=1.4062242282835, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.10403568009082, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.78460886516167, ['keyframe,0,pendDesiredVel,g2592_soldier,l,x']=1.0772213211005, ['keyframe,0,pendDesiredVel,g2592_soldier,l,z']=0.50048360141665, ['keyframe,0,pendDesiredVel,g2592_soldier,r,x']=0.61926456581853, ['keyframe,0,pendDesiredVel,g2592_soldier,r,z']=-0.15346075692745, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.10462023045408, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.78461667357442, ['keyframe,0,pendDesiredVel,g2592_soldier,l,x']=1.0775196166594, ['keyframe,0,pendDesiredVel,g2592_soldier,l,z']=0.50042422515666, ['keyframe,0,pendDesiredVel,g2592_soldier,r,x']=0.61943388913173, ['keyframe,0,pendDesiredVel,g2592_soldier,r,z']=-0.15325745306113, 
['keyframe,0,pendDesiredVel,g2592_soldier,l,x']=1.0837488467948, ['keyframe,0,pendDesiredVel,g2592_soldier,l,z']=0.49837706667858, ['keyframe,0,pendDesiredVel,g2592_soldier,r,x']=0.57133585904306, ['keyframe,0,pendDesiredVel,g2592_soldier,r,z']=-0.29941965691001, ['keyframe,0,pendDesiredVel,g2592_soldier,L1,x']=0.67101942125617, ['keyframe,0,pendDesiredVel,g2592_soldier,L1,z']=-0.0036663175904419, 
['keyframe,0,pendDesiredVel,g2592_soldier,r,x']=0.55678577608473, ['keyframe,0,pendDesiredVel,g2592_soldier,r,z']=-0.26898615434944, ['keyframe,0,pendDesiredVel,g2592_soldier,L1,x']=0.73906694792772, ['keyframe,0,pendDesiredVel,g2592_soldier,L1,z']=0.083420196055189, ['keyframe,0,pendDesiredVel,g2592_soldier,R1,x']=0.67242095333062, ['keyframe,0,pendDesiredVel,g2592_soldier,R1,z']=-0.05341396397522, ['keyframe,0,pendDesiredVel,g2592_soldier,L2,x']=0.7052817338366, ['keyframe,0,pendDesiredVel,g2592_soldier,L2,z']=0.06373606010235, 
['keyframe,0,pendDesiredVel,g2592_soldier,r,x']=0.55673435392214, ['keyframe,0,pendDesiredVel,g2592_soldier,r,z']=-0.26908637666173, ['keyframe,0,pendDesiredVel,g2592_soldier,L1,x']=0.73904868802069, ['keyframe,0,pendDesiredVel,g2592_soldier,L1,z']=0.083390096411107, ['keyframe,0,pendDesiredVel,g2592_soldier,R1,x']=0.67241590490001, ['keyframe,0,pendDesiredVel,g2592_soldier,R1,z']=-0.053457542869858, ['keyframe,0,pendDesiredVel,g2592_soldier,L2,x']=0.70527899850295, ['keyframe,0,pendDesiredVel,g2592_soldier,L2,z']=0.063735365922591, 
['keyframe,0,pendDesiredVel,g2592_soldier,R1,x']=0.67267242228582, ['keyframe,0,pendDesiredVel,g2592_soldier,R1,z']=-0.087795073007373, ['keyframe,0,pendDesiredVel,g2592_soldier,L2,x']=0.69189820983181, ['keyframe,0,pendDesiredVel,g2592_soldier,L2,z']=0.16486909862468, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.8743110378427, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.0001058833697106, 
}
useCases.g2592_soldier.pendOptimizationPath=
{
	firstFrames={1*4,24*4,47*4,70*4,93*4,116*4,139*4,160*4},
	segments={'ignore,0','g2592_soldier,l','g2592_soldier,r','g2592_soldier,L1','g2592_soldier,R1','g2592_soldier,L2','ignore,1'},
}
--useCases.g2592_soldier.measureOptCost=useCases.measureOptCost

useCases.g2592_soldier.segmentations=
{
	g2592_soldier={
		firstFrames={1*4,24*4,47*4,70*4,93*4,116*4,139*4,160*4},
		--        (blank)    L    R     L     R     L     (blank)
		names={             'l', 'r', 'L1', 'R1', 'L2',  },
		swingL={             0,   1,   0,    1,    0,    },
		swingR={             1,   0,   1,    0,    1,    },
		footRefL= "convertFromSwingL",
		footRefR= "convertFromSwingR",
		usePositionControl=false,
	},
}
useCases.g2592_soldier.graphParam=
{
	g2592_soldier={
		seg={            'l',  'r',  'L1', 'R1','L'},
		num_key={         3,    3,    3  ,  4,  4},
		key_first={       0,    0,    0  ,  0,  0},
		key_last={       'r', 'L1',  'R1', 'L', 'R1'},
	},
}
useCases.g2592_soldier.graph=
{
	{
		"addInterpolatedSegment",
		grpName="g2592_soldier",
		name="L",
		seg0={"g2592_soldier", "L2"},
		seg1={"g2592_soldier", "L1"},
		startWeight=0, endWeight=1
	},
	{"connectMulti", "g2592_soldier", "l", "r", "L1", "R1", "L", "R1"},
	--{"initialSegment", "g2592_soldier", "l"}
	{"initialSegment", "g2592_soldier", "R1"}
}
useCases.g2592_soldier.segNames=
{
	"l", "r", "L1", 'R1','L',
}

do 
	useCases.g2592_soldier.controlParam={
		['useCases,g2592_soldier,COMobjWeight']=0, 
		['useCases,g2592_soldier,conservativeW']=1, 
		--['useCases,g2592_soldier,contactMargin']=0.01, 
		['useCases,g2592_soldier,dotMomentumScale']=0.3, 
		['useCases,g2592_soldier,excludeRoot']=true, 
		['useCases,g2592_soldier,headControlWeight']=0, 
		['useCases,g2592_soldier,k_d_HEAD']=14, 
		['useCases,g2592_soldier,k_p_HEAD']=0, 
		['useCases,g2592_soldier,k_d_EE']=24, 
		['useCases,g2592_soldier,k_d_momentum']=10, 
		['useCases,g2592_soldier,k_p_EE']=120, 

		--['useCases,g2592_soldier,maxPenetratingVel']=0, 
		['useCases,g2592_soldier,momentumThr']=50, 
		['useCases,g2592_soldier,noComvelDependentFootAdjustment']=true, 
		['useCases,g2592_soldier,noIntersectionPrevenction']=true, 
		['useCases,g2592_soldier,numericalDerivDmot']=true, 
		['useCases,g2592_soldier,perClassContactMargin']=1, 
		['useCases,g2592_soldier,turnGain']=10, 
		['useCases,g2592_soldier,velMarginOffset']=0, 

		['useCases,g2592_soldier,actuationType']      = useCases.g2592_soldier.actuationType,
		['useCases,g2592_soldier,k_p_ID']             = useCases.g2592_soldier.k_p_ID,
		['useCases,g2592_soldier,k_d_ID']             = useCases.g2592_soldier.k_d_ID,
		['useCases,g2592_soldier,ddqObjWeight']       = useCases.g2592_soldier.ddqObjWeight,
		['useCases,g2592_soldier,tauObjWeight']       = useCases.g2592_soldier.tauObjWeight,
		['useCases,g2592_soldier,ftObjWeight']        = useCases.g2592_soldier.ftObjWeight,
		['useCases,g2592_soldier,aObjWeight']         = useCases.g2592_soldier.aObjWeight,
		['useCases,g2592_soldier,lambdaObjWeight']    = useCases.g2592_soldier.lambdaObjWeight,
		['useCases,g2592_soldier,EEobjWeight']        = useCases.g2592_soldier.EEobjWeight,
		['useCases,g2592_soldier,EEobjWeightAngular'] = useCases.g2592_soldier.EEobjWeightAngular,
		['useCases,g2592_soldier,momentumWeight']     = useCases.g2592_soldier.momentumWeight,
		['useCases,g2592_soldier,tauMax']             = useCases.g2592_soldier.tauMax,
		['useCases,g2592_soldier,ftMax']              = useCases.g2592_soldier.ftMax,
	}

	local function accumulate(cp_mod)
		local useCase=useCases.g2592_soldier
		useCases.accumulate(useCase, cp_mod)
	end

	accumulate({
		----['keyframe,0,footRmod,g2592_soldier,l,y']  = 0.,
		----['keyframe,1,footRmod,g2592_soldier,l,y']  = 0.05,
		--['keyframe,0,footLmod,g2592_soldier,r,y']  = 0.0,
		--['keyframe,1,footLmod,g2592_soldier,r,y']  = 0.2,
		--['keyframe,0,footRmod,g2592_soldier,L1,y'] = 0.0,
		--['keyframe,1,footRmod,g2592_soldier,L1,y'] = 0.2,
		--['map,0,swingFootMod,g2592_soldier,y']     = 0.1,
		--['map,1,swingFootMod,g2592_soldier,y']     = 0.2,
		--['map,2,swingFootMod,g2592_soldier,y']     = 0.1,

		----['keyframe,0,footLmod,g2592_soldier,l,y']  = 0.,
		----['keyframe,1,footLmod,g2592_soldier,l,y']  = 0.,
		--['keyframe,0,footRmod,g2592_soldier,r,y']  = 0.,
		--['keyframe,1,footRmod,g2592_soldier,r,y']  = -.1,
		--['keyframe,0,footLmod,g2592_soldier,L1,y'] = 0.,
		--['keyframe,1,footLmod,g2592_soldier,L1,y'] = -.1,
		--['map,0,spprtFootMod,g2592_soldier,y']     = 0.,
		--['map,1,spprtFootMod,g2592_soldier,y']     = 0.,
		--['map,2,spprtFootMod,g2592_soldier,y']     = 0.,
	})
	useCases.unmapControlParam(useCases.g2592_soldier)


-------------------------------------------------
if g_mode=='default' then
	--iter:225 bestfvever:1.3655277553565e-06 endSegW:10
	accumulate({['map,0,swingFootMod,g2592_soldier,x']= 0.24003990914519, ['map,0,swingFootMod,g2592_soldier,y']= -0.12368339479711, ['map,0,swingFootMod,g2592_soldier,z']= 0.02136113958715, ['map,1,swingFootMod,g2592_soldier,x']= -0.031891334149188, ['map,1,swingFootMod,g2592_soldier,y']= -0.21085241341772, ['map,1,swingFootMod,g2592_soldier,z']= 0.16564760539388, ['map,2,swingFootMod,g2592_soldier,x']= -0.36186142848653, ['map,2,swingFootMod,g2592_soldier,y']= 0.41530056089472, ['map,2,swingFootMod,g2592_soldier,z']= 0.0081114542936341, ['map,0,spprtFootMod,g2592_soldier,x']= 0.27655627976873, ['map,0,spprtFootMod,g2592_soldier,y']= -0.36010175863619, ['map,0,spprtFootMod,g2592_soldier,z']= 0.13782555908073, ['map,1,spprtFootMod,g2592_soldier,x']= -0.13176172230921, ['map,1,spprtFootMod,g2592_soldier,y']= 0.1062974337502, ['map,1,spprtFootMod,g2592_soldier,z']= -0.5172169694751, ['map,2,spprtFootMod,g2592_soldier,x']= 0.29471213388624, ['map,2,spprtFootMod,g2592_soldier,y']= -0.36644647757761, ['map,2,spprtFootMod,g2592_soldier,z']= -0.27185441163652, })

elseif g_mode=='a1' then
	useCases.g2592_soldier.aObjWeight = 1*useCases.g2592_soldier.aObjWeight

	--iter:139 bestfvever:2.2489812651924e-06
	accumulate({['map,0,swingFootMod,g2592_soldier,x']= 0.092063592312579, ['map,0,swingFootMod,g2592_soldier,y']= -0.29319407755091, ['map,0,swingFootMod,g2592_soldier,z']= 0.15251385078501, ['map,1,swingFootMod,g2592_soldier,x']= -0.13419164862983, ['map,1,swingFootMod,g2592_soldier,y']= 0.050676104398982, ['map,1,swingFootMod,g2592_soldier,z']= 0.4337660996041, ['map,2,swingFootMod,g2592_soldier,x']= -0.35929217631103, ['map,2,swingFootMod,g2592_soldier,y']= 0.25913013899193, ['map,2,swingFootMod,g2592_soldier,z']= -0.10888840740314, ['map,0,spprtFootMod,g2592_soldier,x']= 0.2438780806738, ['map,0,spprtFootMod,g2592_soldier,y']= -0.33489871341527, ['map,0,spprtFootMod,g2592_soldier,z']= 0.032778088675643, ['map,1,spprtFootMod,g2592_soldier,x']= -0.16925679538279, ['map,1,spprtFootMod,g2592_soldier,y']= -0.26368286509303, ['map,1,spprtFootMod,g2592_soldier,z']= -0.43769585909696, ['map,2,spprtFootMod,g2592_soldier,x']= -0.22218219247411, ['map,2,spprtFootMod,g2592_soldier,y']= -0.3933431633849, ['map,2,spprtFootMod,g2592_soldier,z']= 0.016481566946485, })

elseif g_mode=='a_.1' then
	useCases.g2592_soldier.aObjWeight = .1*useCases.g2592_soldier.aObjWeight

	----iter:142 bestfvever:5.7152499225372e-07
	--accumulate({['map,0,swingFootMod,g2592_soldier,x']= -0.14391229571946, ['map,0,swingFootMod,g2592_soldier,y']= -0.070303199338832, ['map,0,swingFootMod,g2592_soldier,z']= -0.087000863721998, ['map,1,swingFootMod,g2592_soldier,x']= 0.039432962612877, ['map,1,swingFootMod,g2592_soldier,y']= -0.064862977459668, ['map,1,swingFootMod,g2592_soldier,z']= 0.036638260228075, ['map,2,swingFootMod,g2592_soldier,x']= -0.13216026453847, ['map,2,swingFootMod,g2592_soldier,y']= 0.25120998888914, ['map,2,swingFootMod,g2592_soldier,z']= -0.12956897552858, ['map,0,spprtFootMod,g2592_soldier,x']= 0.16747274212041, ['map,0,spprtFootMod,g2592_soldier,y']= -0.11500766499852, ['map,0,spprtFootMod,g2592_soldier,z']= 0.039473667621553, ['map,1,spprtFootMod,g2592_soldier,x']= 0.19300517095386, ['map,1,spprtFootMod,g2592_soldier,y']= 0.1110211748954, ['map,1,spprtFootMod,g2592_soldier,z']= -0.24020840439008, ['map,2,spprtFootMod,g2592_soldier,x']= -0.1571267245907, ['map,2,spprtFootMod,g2592_soldier,y']= -0.59079830727178, ['map,2,spprtFootMod,g2592_soldier,z']= -0.27597355058082, })

	--useCases.g2592_soldier.endSegW=20
	--useCases.g2592_soldier.prec=.05

	----iter:40 bestfvever:5.0634389895542e-07
	--accumulate({['map,0,swingFootMod,g2592_soldier,x']= -0.13921225686848, ['map,0,swingFootMod,g2592_soldier,y']= -0.064231143475674, ['map,0,swingFootMod,g2592_soldier,z']= -0.085917904878883, ['map,1,swingFootMod,g2592_soldier,x']= 0.013880602544788, ['map,1,swingFootMod,g2592_soldier,y']= -0.075262046389726, ['map,1,swingFootMod,g2592_soldier,z']= 0.062378662302985, ['map,2,swingFootMod,g2592_soldier,x']= -0.12997048971452, ['map,2,swingFootMod,g2592_soldier,y']= 0.24946044138521, ['map,2,swingFootMod,g2592_soldier,z']= -0.14067994791371, ['map,0,spprtFootMod,g2592_soldier,x']= 0.17930038748868, ['map,0,spprtFootMod,g2592_soldier,y']= -0.10642989321964, ['map,0,spprtFootMod,g2592_soldier,z']= 0.034646919274106, ['map,1,spprtFootMod,g2592_soldier,x']= 0.20923623149656, ['map,1,spprtFootMod,g2592_soldier,y']= 0.10045925162558, ['map,1,spprtFootMod,g2592_soldier,z']= -0.27519312036557, ['map,2,spprtFootMod,g2592_soldier,x']= -0.16908849304004, ['map,2,spprtFootMod,g2592_soldier,y']= -0.59478976586744, ['map,2,spprtFootMod,g2592_soldier,z']= -0.23521337011691, })
	
	--iter:125 bestfvever:6.6330542158609e-07
	accumulate({['map,0,swingFootMod,g2592_soldier,x']= 0.11972458212199, ['map,0,swingFootMod,g2592_soldier,y']= -0.37980591981617, ['map,0,swingFootMod,g2592_soldier,z']= 0.48411399540893, ['map,1,swingFootMod,g2592_soldier,x']= -0.024747501139378, ['map,1,swingFootMod,g2592_soldier,y']= -0.027650989636261, ['map,1,swingFootMod,g2592_soldier,z']= -0.092615566569568, ['map,2,swingFootMod,g2592_soldier,x']= -0.19019982434314, ['map,2,swingFootMod,g2592_soldier,y']= 0.34258241545261, ['map,2,swingFootMod,g2592_soldier,z']= -0.096589510735512, ['map,0,spprtFootMod,g2592_soldier,x']= 0.22158728585089, ['map,0,spprtFootMod,g2592_soldier,y']= -0.21783285667065, ['map,0,spprtFootMod,g2592_soldier,z']= 0.026413337559883, ['map,1,spprtFootMod,g2592_soldier,x']= 0.27586971393953, ['map,1,spprtFootMod,g2592_soldier,y']= 0.055171460742169, ['map,1,spprtFootMod,g2592_soldier,z']= -0.34541186794417, ['map,2,spprtFootMod,g2592_soldier,x']= -0.18252187946132, ['map,2,spprtFootMod,g2592_soldier,y']= -0.43678204444012, ['map,2,spprtFootMod,g2592_soldier,z']= 0.017685887937767, })

elseif g_mode=='a_.01' then
	useCases.g2592_soldier.aObjWeight = .01*useCases.g2592_soldier.aObjWeight

end
-------------------------------------------------

useCases.g2592_soldier.controlParam['useCases,g2592_soldier,aObjWeight'] = useCases.g2592_soldier.aObjWeight

useCases.unmapControlParam(useCases.g2592_soldier)

end



