package.path=package.path..";../Samples/ysscripts/lib/?.lua" --;"..package.path
require("utilfunc")

package.path=package.path..";../Samples/ysscripts/samples/?.lua" --;"..package.path
require("useMuscle_g2592_gait")


useCases.g2592_lean=deepCopyTable(useCases.g2592_gait)

useCases.g2592_lean.optimizerMethod='Optimizer.methods.CMAes_ys'

--useCases.g2592_lean.endSegW=10
useCases.g2592_lean.endSegW=15
useCases.g2592_lean.prec=.2
--useCases.g2592_lean.endSegW=20
--useCases.g2592_lean.prec=.05

useCases.g2592_lean.modelName='g2592_lean'
useCases.g2592_lean.grpName='g2592_lean'
useCases.g2592_lean.grpNames={'g2592_lean'}

-- the initial pendControlParam and pendOptimizationPath can be automatically generated by using createInitialPendControlParam.lua
useCases.g2592_lean.pendControlParam=
{
['keyframe,0,pendDesiredVel,g2592_lean,l,z']=0,['keyframe,0,pendDesiredVel,g2592_lean,l,x']=1,['keyframe,0,pendDesiredVel,g2592_lean,r,z']=0,['keyframe,0,pendDesiredVel,g2592_lean,r,x']=1,['keyframe,0,pendDesiredVel,g2592_lean,L1,z']=0,['keyframe,0,pendDesiredVel,g2592_lean,L1,x']=1,['keyframe,0,pendDesiredVel,g2592_lean,R1,z']=0,['keyframe,0,pendDesiredVel,g2592_lean,R1,x']=1,['keyframe,0,pendDesiredVel,g2592_lean,L2,z']=0,['keyframe,0,pendDesiredVel,g2592_lean,L2,x']=1,['keyframe,0,pendDesiredVel,ignore,0,z']=0,['keyframe,0,pendDesiredVel,ignore,0,x']=1,['keyframe,0,pendDesiredVel,ignore,1,z']=0,['keyframe,0,pendDesiredVel,ignore,1,x']=1,
['keyframe,0,pendDesiredVel,ignore,0,x']=0.49221236658979, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.0054183433195051, ['keyframe,0,pendDesiredVel,g2592_lean,l,x']=0.65157250045983, ['keyframe,0,pendDesiredVel,g2592_lean,l,z']=-0.015155085230071, ['keyframe,0,pendDesiredVel,g2592_lean,r,x']=0.71655843417388, ['keyframe,0,pendDesiredVel,g2592_lean,r,z']=0.013602984519031, ['keyframe,0,pendDesiredVel,g2592_lean,L1,x']=0.72777850080291, ['keyframe,0,pendDesiredVel,g2592_lean,L1,z']=0.0012751554227634, ['keyframe,0,pendDesiredVel,g2592_lean,R1,x']=0.75167607322418, ['keyframe,0,pendDesiredVel,g2592_lean,R1,z']=0.0042442928911984, ['keyframe,0,pendDesiredVel,g2592_lean,L2,x']=0.84822437118635, ['keyframe,0,pendDesiredVel,g2592_lean,L2,z']=0.0019809272886494, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.95788833475772, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.0022933968172409, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.49133593616463, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.0056032730252848, ['keyframe,0,pendDesiredVel,g2592_lean,l,x']=0.65042956157686, ['keyframe,0,pendDesiredVel,g2592_lean,l,z']=-0.014746146581524, ['keyframe,0,pendDesiredVel,g2592_lean,r,x']=0.71622136677421, ['keyframe,0,pendDesiredVel,g2592_lean,r,z']=0.013179046009638, ['keyframe,0,pendDesiredVel,g2592_lean,L1,x']=0.72775339291649, ['keyframe,0,pendDesiredVel,g2592_lean,L1,z']=0.0014843659503535, ['keyframe,0,pendDesiredVel,g2592_lean,R1,x']=0.75168439081034, ['keyframe,0,pendDesiredVel,g2592_lean,R1,z']=0.0040984155592843, ['keyframe,0,pendDesiredVel,g2592_lean,L2,x']=0.84768850640149, ['keyframe,0,pendDesiredVel,g2592_lean,L2,z']=0.0019755580995616, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.95664000871785, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.0023169285859117, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.48802705563885, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.013954315117401, ['keyframe,0,pendDesiredVel,g2592_lean,l,x']=0.6244062987454, ['keyframe,0,pendDesiredVel,g2592_lean,l,z']=0.010725430993183, ['keyframe,0,pendDesiredVel,g2592_lean,r,x']=0.73397785100005, ['keyframe,0,pendDesiredVel,g2592_lean,r,z']=-0.010850698481838, ['keyframe,0,pendDesiredVel,g2592_lean,L1,x']=0.75669671729001, ['keyframe,0,pendDesiredVel,g2592_lean,L1,z']=0.014076689497005, ['keyframe,0,pendDesiredVel,g2592_lean,R1,x']=0.76814774166426, ['keyframe,0,pendDesiredVel,g2592_lean,R1,z']=-0.0036664352612009, ['keyframe,0,pendDesiredVel,g2592_lean,L2,x']=0.81153560827322, ['keyframe,0,pendDesiredVel,g2592_lean,L2,z']=0.0011353640524627, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.86151119657935, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.0040746042475397, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.32826329649416, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.020361337351578, ['keyframe,0,pendDesiredVel,g2592_lean,l,x']=0.78980578851882, ['keyframe,0,pendDesiredVel,g2592_lean,l,z']=0.012594991591796, ['keyframe,0,pendDesiredVel,g2592_lean,r,x']=0.82464935644462, ['keyframe,0,pendDesiredVel,g2592_lean,r,z']=-0.017044485891922, ['keyframe,0,pendDesiredVel,g2592_lean,L1,x']=0.72807473607511, ['keyframe,0,pendDesiredVel,g2592_lean,L1,z']=0.019158322886792, ['keyframe,0,pendDesiredVel,g2592_lean,R1,x']=0.66823463956661, ['keyframe,0,pendDesiredVel,g2592_lean,R1,z']=-0.01967797231025, ['keyframe,0,pendDesiredVel,g2592_lean,L2,x']=0.74525381662103, ['keyframe,0,pendDesiredVel,g2592_lean,L2,z']=0.029616694904189, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.85394965549782, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.0024231764523249, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.32812626917668, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.020362836187669, ['keyframe,0,pendDesiredVel,g2592_lean,l,x']=0.78974011156082, ['keyframe,0,pendDesiredVel,g2592_lean,l,z']=0.012621619635358, ['keyframe,0,pendDesiredVel,g2592_lean,r,x']=0.82453552568791, ['keyframe,0,pendDesiredVel,g2592_lean,r,z']=-0.017013549388808, ['keyframe,0,pendDesiredVel,g2592_lean,L1,x']=0.72801863505382, ['keyframe,0,pendDesiredVel,g2592_lean,L1,z']=0.019209591407334, ['keyframe,0,pendDesiredVel,g2592_lean,R1,x']=0.66823749390296, ['keyframe,0,pendDesiredVel,g2592_lean,R1,z']=-0.019651544477381, ['keyframe,0,pendDesiredVel,g2592_lean,L2,x']=0.74526914597701, ['keyframe,0,pendDesiredVel,g2592_lean,L2,z']=0.029643127314895, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.85394883070678, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.0024275502981052, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.32811222428954, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.020363146345834, ['keyframe,0,pendDesiredVel,g2592_lean,l,x']=0.78973364097969, ['keyframe,0,pendDesiredVel,g2592_lean,l,z']=0.012624292523184, ['keyframe,0,pendDesiredVel,g2592_lean,r,x']=0.82452380445559, ['keyframe,0,pendDesiredVel,g2592_lean,r,z']=-0.017010364754889, ['keyframe,0,pendDesiredVel,g2592_lean,L1,x']=0.72801296566233, ['keyframe,0,pendDesiredVel,g2592_lean,L1,z']=0.01921495997783, ['keyframe,0,pendDesiredVel,g2592_lean,R1,x']=0.66823800490074, ['keyframe,0,pendDesiredVel,g2592_lean,R1,z']=-0.0196487788972, ['keyframe,0,pendDesiredVel,g2592_lean,L2,x']=0.7452708599926, ['keyframe,0,pendDesiredVel,g2592_lean,L2,z']=0.029645930886528, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.85394874547131, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.0024280180154946, 
}
useCases.g2592_lean.pendOptimizationPath=
{
	firstFrames={1*4,21*4,41*4,61*4,81*4,101*4,121*4,139*4},
	segments={'ignore,0','g2592_lean,l','g2592_lean,r','g2592_lean,L1','g2592_lean,R1','g2592_lean,L2','ignore,1'},
}
--useCases.g2592_lean.measureOptCost=useCases.measureOptCost

useCases.g2592_lean.segmentations=
{
	g2592_lean={
		firstFrames={1*4,21*4,41*4,61*4,81*4,101*4,121*4,139*4},
		--        (blank)    L    R     L     R     L     (blank)
		names={             'l', 'r', 'L1', 'R1', 'L2',  },
		swingL={             0,   1,   0,    1,    0,    },
		swingR={             1,   0,   1,    0,    1,    },
		footRefL= "convertFromSwingL",
		footRefR= "convertFromSwingR",
		usePositionControl=false,
	},
}
useCases.g2592_lean.graphParam=
{
	g2592_lean={
		seg={            'l',  'r',  'L1', 'R1','L'},
		num_key={         3,    3,    3  ,  4,  4},
		key_first={       0,    0,    0  ,  0,  0},
		key_last={       'r', 'L1',  'R1', 'L', 'R1'},
	},
}
useCases.g2592_lean.graph=
{
	{
		"addInterpolatedSegment",
		grpName="g2592_lean",
		name="L",
		seg0={"g2592_lean", "L2"},
		seg1={"g2592_lean", "L1"},
		startWeight=0, endWeight=1
	},
	{"connectMulti", "g2592_lean", "l", "r", "L1", "R1", "L", "R1"},
	--{"initialSegment", "g2592_lean", "l"}
	{"initialSegment", "g2592_lean", "R1"}
}
useCases.g2592_lean.segNames=
{
	"l", "r", "L1", 'R1','L',
}

do 
	useCases.g2592_lean.controlParam={
		['useCases,g2592_lean,COMobjWeight']=0, 
		['useCases,g2592_lean,conservativeW']=1, 
		--['useCases,g2592_lean,contactMargin']=0.01, 
		['useCases,g2592_lean,dotMomentumScale']=0.3, 
		['useCases,g2592_lean,excludeRoot']=true, 
		['useCases,g2592_lean,headControlWeight']=0, 
		['useCases,g2592_lean,k_d_HEAD']=14, 
		['useCases,g2592_lean,k_p_HEAD']=0, 
		['useCases,g2592_lean,k_d_EE']=24, 
		['useCases,g2592_lean,k_d_momentum']=10, 
		['useCases,g2592_lean,k_p_EE']=120, 

		--['useCases,g2592_lean,maxPenetratingVel']=0, 
		['useCases,g2592_lean,momentumThr']=50, 
		['useCases,g2592_lean,noComvelDependentFootAdjustment']=true, 
		['useCases,g2592_lean,noIntersectionPrevenction']=true, 
		['useCases,g2592_lean,numericalDerivDmot']=true, 
		['useCases,g2592_lean,perClassContactMargin']=1, 
		['useCases,g2592_lean,turnGain']=10, 
		['useCases,g2592_lean,velMarginOffset']=0, 

		['useCases,g2592_lean,actuationType']      = useCases.g2592_lean.actuationType,
		['useCases,g2592_lean,k_p_ID']             = useCases.g2592_lean.k_p_ID,
		['useCases,g2592_lean,k_d_ID']             = useCases.g2592_lean.k_d_ID,
		['useCases,g2592_lean,ddqObjWeight']       = useCases.g2592_lean.ddqObjWeight,
		['useCases,g2592_lean,tauObjWeight']       = useCases.g2592_lean.tauObjWeight,
		['useCases,g2592_lean,ftObjWeight']        = useCases.g2592_lean.ftObjWeight,
		['useCases,g2592_lean,aObjWeight']         = useCases.g2592_lean.aObjWeight,
		['useCases,g2592_lean,lambdaObjWeight']    = useCases.g2592_lean.lambdaObjWeight,
		['useCases,g2592_lean,EEobjWeight']        = useCases.g2592_lean.EEobjWeight,
		['useCases,g2592_lean,EEobjWeightAngular'] = useCases.g2592_lean.EEobjWeightAngular,
		['useCases,g2592_lean,momentumWeight']     = useCases.g2592_lean.momentumWeight,
		['useCases,g2592_lean,tauMax']             = useCases.g2592_lean.tauMax,
		['useCases,g2592_lean,ftMax']              = useCases.g2592_lean.ftMax,
	}

	local function accumulate(cp_mod)
		local useCase=useCases.g2592_lean
		useCases.accumulate(useCase, cp_mod)
	end

	accumulate({
		----['keyframe,0,footRmod,g2592_lean,l,y']  = 0.,
		----['keyframe,1,footRmod,g2592_lean,l,y']  = 0.05,
		--['keyframe,0,footLmod,g2592_lean,r,y']  = 0.0,
		--['keyframe,1,footLmod,g2592_lean,r,y']  = 0.2,
		--['keyframe,0,footRmod,g2592_lean,L1,y'] = 0.0,
		--['keyframe,1,footRmod,g2592_lean,L1,y'] = 0.2,
		--['map,0,swingFootMod,g2592_lean,y']     = 0.1,
		--['map,1,swingFootMod,g2592_lean,y']     = 0.2,
		--['map,2,swingFootMod,g2592_lean,y']     = 0.1,

		----['keyframe,0,footLmod,g2592_lean,l,y']  = 0.,
		----['keyframe,1,footLmod,g2592_lean,l,y']  = 0.,
		--['keyframe,0,footRmod,g2592_lean,r,y']  = 0.,
		--['keyframe,1,footRmod,g2592_lean,r,y']  = -.1,
		--['keyframe,0,footLmod,g2592_lean,L1,y'] = 0.,
		--['keyframe,1,footLmod,g2592_lean,L1,y'] = -.1,
		--['map,0,spprtFootMod,g2592_lean,y']     = 0.,
		--['map,1,spprtFootMod,g2592_lean,y']     = 0.,
		--['map,2,spprtFootMod,g2592_lean,y']     = 0.,
	})
	useCases.unmapControlParam(useCases.g2592_lean)


-------------------------------------------------
if g_mode=='default' then
	--iter:262 bestfvever:1.1289560015564e-06
	accumulate({['map,0,swingFootMod,g2592_lean,x']= 0.10708743346324, ['map,0,swingFootMod,g2592_lean,y']= -0.34407575037054, ['map,0,swingFootMod,g2592_lean,z']= -0.036254283401897, ['map,1,swingFootMod,g2592_lean,x']= 0.092825104528131, ['map,1,swingFootMod,g2592_lean,y']= 0.17047590518672, ['map,1,swingFootMod,g2592_lean,z']= 0.37604932036939, ['map,2,swingFootMod,g2592_lean,x']= -0.15958152136362, ['map,2,swingFootMod,g2592_lean,y']= 0.033923960017615, ['map,2,swingFootMod,g2592_lean,z']= -0.0073113362182508, ['map,0,spprtFootMod,g2592_lean,x']= 0.1577123150255, ['map,0,spprtFootMod,g2592_lean,y']= -0.11542088489669, ['map,0,spprtFootMod,g2592_lean,z']= 0.28344697309666, ['map,1,spprtFootMod,g2592_lean,x']= 0.11670462542706, ['map,1,spprtFootMod,g2592_lean,y']= 0.093563193982783, ['map,1,spprtFootMod,g2592_lean,z']= -0.24355358468517, ['map,2,spprtFootMod,g2592_lean,x']= -0.022121922573168, ['map,2,spprtFootMod,g2592_lean,y']= 0.013905943016905, ['map,2,spprtFootMod,g2592_lean,z']= -0.20763771244387, })

elseif g_mode=='a1' then
	useCases.g2592_lean.aObjWeight = 1*useCases.g2592_lean.aObjWeight

	--iter:157 bestfvever:1.8776296863742e-06
	accumulate({['map,0,swingFootMod,g2592_lean,x']= -0.14472283428941, ['map,0,swingFootMod,g2592_lean,y']= 0.085328906234598, ['map,0,swingFootMod,g2592_lean,z']= 0.081359027425055, ['map,1,swingFootMod,g2592_lean,x']= -0.04744614959009, ['map,1,swingFootMod,g2592_lean,y']= 0.14725820939314, ['map,1,swingFootMod,g2592_lean,z']= 0.17519258219535, ['map,2,swingFootMod,g2592_lean,x']= -0.1202710633973, ['map,2,swingFootMod,g2592_lean,y']= -0.035632883237542, ['map,2,swingFootMod,g2592_lean,z']= 0.079078282811564, ['map,0,spprtFootMod,g2592_lean,x']= 0.055651488082162, ['map,0,spprtFootMod,g2592_lean,y']= -0.21285326292077, ['map,0,spprtFootMod,g2592_lean,z']= 0.17470954071829, ['map,1,spprtFootMod,g2592_lean,x']= -0.055452802091274, ['map,1,spprtFootMod,g2592_lean,y']= 0.13988381932468, ['map,1,spprtFootMod,g2592_lean,z']= -0.090027064814816, ['map,2,spprtFootMod,g2592_lean,x']= 0.029762745081938, ['map,2,spprtFootMod,g2592_lean,y']= 0.028307571938215, ['map,2,spprtFootMod,g2592_lean,z']= -0.10010182486723, })

elseif g_mode=='a_.1' then
	useCases.g2592_lean.aObjWeight = .1*useCases.g2592_lean.aObjWeight

	----iter:161 bestfvever:2.8204009677441e-07
	--accumulate({['map,0,swingFootMod,g2592_lean,x']= 0.27476925858159, ['map,0,swingFootMod,g2592_lean,y']= -0.91064945753159, ['map,0,swingFootMod,g2592_lean,z']= 0.063759543566394, ['map,1,swingFootMod,g2592_lean,x']= 0.54571861529571, ['map,1,swingFootMod,g2592_lean,y']= 0.11859415945741, ['map,1,swingFootMod,g2592_lean,z']= 0.11753543340436, ['map,2,swingFootMod,g2592_lean,x']= -0.32523246352133, ['map,2,swingFootMod,g2592_lean,y']= 0.21876767986103, ['map,2,swingFootMod,g2592_lean,z']= 0.015957890004257, ['map,0,spprtFootMod,g2592_lean,x']= 0.24891221503654, ['map,0,spprtFootMod,g2592_lean,y']= -0.1976066025084, ['map,0,spprtFootMod,g2592_lean,z']= 0.13270373585091, ['map,1,spprtFootMod,g2592_lean,x']= 0.31836298458515, ['map,1,spprtFootMod,g2592_lean,y']= 0.070647159515265, ['map,1,spprtFootMod,g2592_lean,z']= -0.057401963558262, ['map,2,spprtFootMod,g2592_lean,x']= 0.187734131806, ['map,2,spprtFootMod,g2592_lean,y']= -0.14467866066311, ['map,2,spprtFootMod,g2592_lean,z']= -0.18208113559289, })

	useCases.g2592_lean.endSegW=20
	useCases.g2592_lean.prec=.05

	--iter:45 bestfvever:2.6818746653505e-07
	accumulate({['map,0,swingFootMod,g2592_lean,x']= 0.27974108846828, ['map,0,swingFootMod,g2592_lean,y']= -0.90269120313152, ['map,0,swingFootMod,g2592_lean,z']= 0.060168019572006, ['map,1,swingFootMod,g2592_lean,x']= 0.55195507370894, ['map,1,swingFootMod,g2592_lean,y']= 0.10653251808865, ['map,1,swingFootMod,g2592_lean,z']= 0.11657312148823, ['map,2,swingFootMod,g2592_lean,x']= -0.34523022669591, ['map,2,swingFootMod,g2592_lean,y']= 0.2445944420949, ['map,2,swingFootMod,g2592_lean,z']= -0.001099414541164, ['map,0,spprtFootMod,g2592_lean,x']= 0.23233572676851, ['map,0,spprtFootMod,g2592_lean,y']= -0.1908288032575, ['map,0,spprtFootMod,g2592_lean,z']= 0.13518605962203, ['map,1,spprtFootMod,g2592_lean,x']= 0.32918348039017, ['map,1,spprtFootMod,g2592_lean,y']= 0.058859144140685, ['map,1,spprtFootMod,g2592_lean,z']= -0.069017078180885, ['map,2,spprtFootMod,g2592_lean,x']= 0.20738502559498, ['map,2,spprtFootMod,g2592_lean,y']= -0.1360386251115, ['map,2,spprtFootMod,g2592_lean,z']= -0.16780086097796, })
	
	useCases.g2592_lean.endSegW=30

	--iter:46 bestfvever:3.4704867210196e-07
	accumulate({['map,0,swingFootMod,g2592_lean,x']= 0.28533193422871, ['map,0,swingFootMod,g2592_lean,y']= -0.90659322727179, ['map,0,swingFootMod,g2592_lean,z']= 0.081218077200648, ['map,1,swingFootMod,g2592_lean,x']= 0.54742283835578, ['map,1,swingFootMod,g2592_lean,y']= 0.10994912781188, ['map,1,swingFootMod,g2592_lean,z']= 0.12020754434537, ['map,2,swingFootMod,g2592_lean,x']= -0.32517375999681, ['map,2,swingFootMod,g2592_lean,y']= 0.2521067920561, ['map,2,swingFootMod,g2592_lean,z']= -0.0018296607768386, ['map,0,spprtFootMod,g2592_lean,x']= 0.21830558424445, ['map,0,spprtFootMod,g2592_lean,y']= -0.19627059350468, ['map,0,spprtFootMod,g2592_lean,z']= 0.13089911281201, ['map,1,spprtFootMod,g2592_lean,x']= 0.33490871641492, ['map,1,spprtFootMod,g2592_lean,y']= 0.055843259059153, ['map,1,spprtFootMod,g2592_lean,z']= -0.066865806716248, ['map,2,spprtFootMod,g2592_lean,x']= 0.20615759749208, ['map,2,spprtFootMod,g2592_lean,y']= -0.14565069376488, ['map,2,spprtFootMod,g2592_lean,z']= -0.19547559206392, })

elseif g_mode=='a_.01' then
	useCases.g2592_lean.aObjWeight = .01*useCases.g2592_lean.aObjWeight

	--iter:167 bestfvever:4.5232489144341e-07
	accumulate({['map,0,swingFootMod,g2592_lean,x']= 0.020713734629542, ['map,0,swingFootMod,g2592_lean,y']= -0.18046069804211, ['map,0,swingFootMod,g2592_lean,z']= -0.051145695925576, ['map,1,swingFootMod,g2592_lean,x']= 0.40499903735194, ['map,1,swingFootMod,g2592_lean,y']= -0.060223295669281, ['map,1,swingFootMod,g2592_lean,z']= 0.024258466374375, ['map,2,swingFootMod,g2592_lean,x']= -0.23205866413459, ['map,2,swingFootMod,g2592_lean,y']= 0.26528249066977, ['map,2,swingFootMod,g2592_lean,z']= 0.084197463077451, ['map,0,spprtFootMod,g2592_lean,x']= 0.11446899663451, ['map,0,spprtFootMod,g2592_lean,y']= -0.18309202385126, ['map,0,spprtFootMod,g2592_lean,z']= 0.19938441305126, ['map,1,spprtFootMod,g2592_lean,x']= 0.11218503837535, ['map,1,spprtFootMod,g2592_lean,y']= 0.082619673805037, ['map,1,spprtFootMod,g2592_lean,z']= -0.3049495136267, ['map,2,spprtFootMod,g2592_lean,x']= -0.019919310873391, ['map,2,spprtFootMod,g2592_lean,y']= -0.045133894230118, ['map,2,spprtFootMod,g2592_lean,z']= 0.011693547448455, })

end
-------------------------------------------------

useCases.g2592_lean.controlParam['useCases,g2592_lean,aObjWeight'] = useCases.g2592_lean.aObjWeight

useCases.unmapControlParam(useCases.g2592_lean)
end


