package.path=package.path..";../Samples/ysscripts/lib/?.lua" --;"..package.path
require("utilfunc")

package.path=package.path..";../Samples/ysscripts/samples/?.lua" --;"..package.path
require("useMuscle_g2592_gait")


useCases.g2592_srun=deepCopyTable(useCases.g2592_gait)

useCases.g2592_srun.optimizerMethod='Optimizer.methods.CMAes_ys'

useCases.g2592_srun.endSegW=20
useCases.g2592_srun.prec=.2
--useCases.g2592_srun.endSegW=20
--useCases.g2592_srun.prec=.05

useCases.g2592_srun.modelName='g2592_srun'
useCases.g2592_srun.grpName='g2592_srun'
useCases.g2592_srun.grpNames={'g2592_srun'}

-- the initial pendControlParam and pendOptimizationPath can be automatically generated by using createInitialPendControlParam.lua
useCases.g2592_srun.pendControlParam=
{
['keyframe,0,pendDesiredVel,g2592_srun,l,z']=0,['keyframe,0,pendDesiredVel,g2592_srun,l,x']=1,['keyframe,0,pendDesiredVel,g2592_srun,r,z']=0,['keyframe,0,pendDesiredVel,g2592_srun,r,x']=1,['keyframe,0,pendDesiredVel,g2592_srun,L1,z']=0,['keyframe,0,pendDesiredVel,g2592_srun,L1,x']=1,['keyframe,0,pendDesiredVel,g2592_srun,R1,z']=0,['keyframe,0,pendDesiredVel,g2592_srun,R1,x']=1,['keyframe,0,pendDesiredVel,g2592_srun,L2,z']=0,['keyframe,0,pendDesiredVel,g2592_srun,L2,x']=1,['keyframe,0,pendDesiredVel,ignore,0,z']=0,['keyframe,0,pendDesiredVel,ignore,0,x']=1,['keyframe,0,pendDesiredVel,ignore,1,z']=0,['keyframe,0,pendDesiredVel,ignore,1,x']=1,
['keyframe,0,pendDesiredVel,ignore,0,x']=-0.35767289006965, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.44807370212594, ['keyframe,0,pendDesiredVel,g2592_srun,l,x']=1.0180451856619, ['keyframe,0,pendDesiredVel,g2592_srun,l,z']=0.15805859147666, ['keyframe,0,pendDesiredVel,g2592_srun,r,x']=0.79124545399388, ['keyframe,0,pendDesiredVel,g2592_srun,r,z']=-0.02048408700085, ['keyframe,0,pendDesiredVel,g2592_srun,L1,x']=0.51916446242951, ['keyframe,0,pendDesiredVel,g2592_srun,L1,z']=0.020088927856808, ['keyframe,0,pendDesiredVel,g2592_srun,R1,x']=0.5098976587487, ['keyframe,0,pendDesiredVel,g2592_srun,R1,z']=-0.054098495157611, ['keyframe,0,pendDesiredVel,g2592_srun,L2,x']=0.74127062014114, ['keyframe,0,pendDesiredVel,g2592_srun,L2,z']=-0.11401430652775, ['keyframe,0,pendDesiredVel,ignore,1,x']=1.0238724760698, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.006035699085617, 
['keyframe,0,pendDesiredVel,ignore,0,x']=-0.35757018365303, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.44793704421198, ['keyframe,0,pendDesiredVel,g2592_srun,l,x']=1.0181028548675, ['keyframe,0,pendDesiredVel,g2592_srun,l,z']=0.15813427516858, ['keyframe,0,pendDesiredVel,g2592_srun,r,x']=0.79129845383915, ['keyframe,0,pendDesiredVel,g2592_srun,r,z']=-0.020432135478896, ['keyframe,0,pendDesiredVel,g2592_srun,L1,x']=0.51916845914068, ['keyframe,0,pendDesiredVel,g2592_srun,L1,z']=0.020091944372944, ['keyframe,0,pendDesiredVel,g2592_srun,R1,x']=0.50987611766569, ['keyframe,0,pendDesiredVel,g2592_srun,R1,z']=-0.054106190924225, ['keyframe,0,pendDesiredVel,g2592_srun,L2,x']=0.74126265991833, ['keyframe,0,pendDesiredVel,g2592_srun,L2,z']=-0.11401605309702, ['keyframe,0,pendDesiredVel,ignore,1,x']=1.0238737830602, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.0060359623776214, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.27155378679456, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.14833610764373, ['keyframe,0,pendDesiredVel,g2592_srun,l,x']=0.38808808718903, ['keyframe,0,pendDesiredVel,g2592_srun,l,z']=-0.10234962166034, ['keyframe,0,pendDesiredVel,g2592_srun,r,x']=0.51384026859666, ['keyframe,0,pendDesiredVel,g2592_srun,r,z']=-0.058252119384794, ['keyframe,0,pendDesiredVel,g2592_srun,L1,x']=0.59639208991231, ['keyframe,0,pendDesiredVel,g2592_srun,L1,z']=-0.037837555350624, ['keyframe,0,pendDesiredVel,g2592_srun,R1,x']=0.63640621329316, ['keyframe,0,pendDesiredVel,g2592_srun,R1,z']=-0.04705270971781, ['keyframe,0,pendDesiredVel,g2592_srun,L2,x']=0.64974520177864, ['keyframe,0,pendDesiredVel,g2592_srun,L2,z']=-0.064201187639779, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.65554627288268, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.072749144917743, 
['keyframe,0,pendDesiredVel,ignore,0,x']=-0.25307177642288, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.40514975687258, ['keyframe,0,pendDesiredVel,g2592_srun,l,x']=0.8211529225375, ['keyframe,0,pendDesiredVel,g2592_srun,l,z']=0.062546382226614, ['keyframe,0,pendDesiredVel,g2592_srun,r,x']=0.84923342933044, ['keyframe,0,pendDesiredVel,g2592_srun,r,z']=0.053526576066267, ['keyframe,0,pendDesiredVel,g2592_srun,L1,x']=0.5922852092562, ['keyframe,0,pendDesiredVel,g2592_srun,L1,z']=0.033181081682747, ['keyframe,0,pendDesiredVel,g2592_srun,R1,x']=0.50031526963899, ['keyframe,0,pendDesiredVel,g2592_srun,R1,z']=-0.070451814661557, ['keyframe,0,pendDesiredVel,g2592_srun,L2,x']=0.57337328382062, ['keyframe,0,pendDesiredVel,g2592_srun,L2,z']=-0.12059405900701, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.66429822132415, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.069250483859507, 
['keyframe,0,pendDesiredVel,ignore,0,x']=-0.25293561884076, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.40504152402282, ['keyframe,0,pendDesiredVel,g2592_srun,l,x']=0.82120563953325, ['keyframe,0,pendDesiredVel,g2592_srun,l,z']=0.062597344826014, ['keyframe,0,pendDesiredVel,g2592_srun,r,x']=0.84928643882301, ['keyframe,0,pendDesiredVel,g2592_srun,r,z']=0.05357584312519, ['keyframe,0,pendDesiredVel,g2592_srun,L1,x']=0.59229927711432, ['keyframe,0,pendDesiredVel,g2592_srun,L1,z']=0.033193133719518, ['keyframe,0,pendDesiredVel,g2592_srun,R1,x']=0.50029536837458, ['keyframe,0,pendDesiredVel,g2592_srun,R1,z']=-0.070452815258553, ['keyframe,0,pendDesiredVel,g2592_srun,L2,x']=0.57335847509539, ['keyframe,0,pendDesiredVel,g2592_srun,L2,z']=-0.12059397747416, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.66429937416347, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.069250582891468, 
['keyframe,0,pendDesiredVel,ignore,0,x']=-0.25292164737028, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.40503039533016, ['keyframe,0,pendDesiredVel,g2592_srun,l,x']=0.8212111709822, ['keyframe,0,pendDesiredVel,g2592_srun,l,z']=0.062602648740409, ['keyframe,0,pendDesiredVel,g2592_srun,r,x']=0.84929193569425, ['keyframe,0,pendDesiredVel,g2592_srun,r,z']=0.053580934046921, ['keyframe,0,pendDesiredVel,g2592_srun,L1,x']=0.59230078653118, ['keyframe,0,pendDesiredVel,g2592_srun,L1,z']=0.033194432322497, ['keyframe,0,pendDesiredVel,g2592_srun,R1,x']=0.50029341255496, ['keyframe,0,pendDesiredVel,g2592_srun,R1,z']=-0.070452875751183, ['keyframe,0,pendDesiredVel,g2592_srun,L2,x']=0.57335699439225, ['keyframe,0,pendDesiredVel,g2592_srun,L2,z']=-0.1205939577618, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.66429948838569, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.069250594462161, 
}
useCases.g2592_srun.pendOptimizationPath=
{
	firstFrames={1*4,11*4,21*4,31*4,41*4,51*4,61*4,71*4},
	segments={'ignore,0','g2592_srun,l','g2592_srun,r','g2592_srun,L1','g2592_srun,R1','g2592_srun,L2','ignore,1'},
}
--useCases.g2592_srun.measureOptCost=useCases.measureOptCost

useCases.g2592_srun.segmentations=
{
	g2592_srun={
		firstFrames={1*4,11*4,21*4,31*4,41*4,51*4,61*4,71*4},
		--        (blank)    L    R     L     R     L     (blank)
		names={             'l', 'r', 'L1', 'R1', 'L2',  },
		swingL={             0,   1,   0,    1,    0,    },
		swingR={             1,   0,   1,    0,    1,    },
		footRefL= "convertFromSwingL",
		footRefR= "convertFromSwingR",
		usePositionControl=false,
	},
}
useCases.g2592_srun.graphParam=
{
	g2592_srun={
		seg={            'l',  'r',  'L1', 'R1','L'},
		num_key={         3,    3,    3  ,  4,  4},
		key_first={       0,    0,    0  ,  0,  0},
		key_last={       'r', 'L1',  'R1', 'L', 'R1'},
	},
}
useCases.g2592_srun.graph=
{
	{
		"addInterpolatedSegment",
		grpName="g2592_srun",
		name="L",
		seg0={"g2592_srun", "L2"},
		seg1={"g2592_srun", "L1"},
		startWeight=0, endWeight=1
	},
	{"connectMulti", "g2592_srun", "l", "r", "L1", "R1", "L", "R1"},
	--{"initialSegment", "g2592_srun", "l"}
	{"initialSegment", "g2592_srun", "R1"}
}
useCases.g2592_srun.segNames=
{
	"l", "r", "L1", 'R1','L',
}

do 
	useCases.g2592_srun.controlParam={
		['useCases,g2592_srun,COMobjWeight']=0, 
		['useCases,g2592_srun,conservativeW']=1, 
		--['useCases,g2592_srun,contactMargin']=0.01, 
		['useCases,g2592_srun,dotMomentumScale']=0.3, 
		['useCases,g2592_srun,excludeRoot']=true, 
		['useCases,g2592_srun,headControlWeight']=0, 
		['useCases,g2592_srun,k_d_HEAD']=14, 
		['useCases,g2592_srun,k_p_HEAD']=0, 
		['useCases,g2592_srun,k_d_EE']=24, 
		['useCases,g2592_srun,k_d_momentum']=10, 
		['useCases,g2592_srun,k_p_EE']=120, 

		--['useCases,g2592_srun,maxPenetratingVel']=0, 
		['useCases,g2592_srun,momentumThr']=50, 
		['useCases,g2592_srun,noComvelDependentFootAdjustment']=true, 
		['useCases,g2592_srun,noIntersectionPrevenction']=true, 
		['useCases,g2592_srun,numericalDerivDmot']=true, 
		['useCases,g2592_srun,perClassContactMargin']=1, 
		['useCases,g2592_srun,turnGain']=10, 
		['useCases,g2592_srun,velMarginOffset']=0, 

		['useCases,g2592_srun,actuationType']      = useCases.g2592_srun.actuationType,
		['useCases,g2592_srun,k_p_ID']             = useCases.g2592_srun.k_p_ID,
		['useCases,g2592_srun,k_d_ID']             = useCases.g2592_srun.k_d_ID,
		['useCases,g2592_srun,ddqObjWeight']       = useCases.g2592_srun.ddqObjWeight,
		['useCases,g2592_srun,tauObjWeight']       = useCases.g2592_srun.tauObjWeight,
		['useCases,g2592_srun,ftObjWeight']        = useCases.g2592_srun.ftObjWeight,
		['useCases,g2592_srun,aObjWeight']         = useCases.g2592_srun.aObjWeight,
		['useCases,g2592_srun,lambdaObjWeight']    = useCases.g2592_srun.lambdaObjWeight,
		['useCases,g2592_srun,EEobjWeight']        = useCases.g2592_srun.EEobjWeight,
		['useCases,g2592_srun,EEobjWeightAngular'] = useCases.g2592_srun.EEobjWeightAngular,
		['useCases,g2592_srun,momentumWeight']     = useCases.g2592_srun.momentumWeight,
		['useCases,g2592_srun,tauMax']             = useCases.g2592_srun.tauMax,
		['useCases,g2592_srun,ftMax']              = useCases.g2592_srun.ftMax,
	}

	local function accumulate(cp_mod)
		local useCase=useCases.g2592_srun
		useCases.accumulate(useCase, cp_mod)
	end

	accumulate({
		----['keyframe,0,footRmod,g2592_srun,l,y']  = 0.,
		----['keyframe,1,footRmod,g2592_srun,l,y']  = 0.05,
		--['keyframe,0,footLmod,g2592_srun,r,y']  = 0.0,
		--['keyframe,1,footLmod,g2592_srun,r,y']  = 0.2,
		--['keyframe,0,footRmod,g2592_srun,L1,y'] = 0.0,
		--['keyframe,1,footRmod,g2592_srun,L1,y'] = 0.2,
		--['map,0,swingFootMod,g2592_srun,y']     = 0.1,
		--['map,1,swingFootMod,g2592_srun,y']     = 0.2,
		--['map,2,swingFootMod,g2592_srun,y']     = 0.1,

		----['keyframe,0,footLmod,g2592_srun,l,y']  = 0.,
		----['keyframe,1,footLmod,g2592_srun,l,y']  = 0.,
		--['keyframe,0,footRmod,g2592_srun,r,y']  = 0.,
		--['keyframe,1,footRmod,g2592_srun,r,y']  = -.1,
		--['keyframe,0,footLmod,g2592_srun,L1,y'] = 0.,
		--['keyframe,1,footLmod,g2592_srun,L1,y'] = -.1,
		--['map,0,spprtFootMod,g2592_srun,y']     = 0.,
		--['map,1,spprtFootMod,g2592_srun,y']     = 0.,
		--['map,2,spprtFootMod,g2592_srun,y']     = 0.,
	})
	useCases.unmapControlParam(useCases.g2592_srun)


-------------------------------------------------
if g_mode=='default' then
	--iter:421 bestfvever:7.8471144753429e-07
	accumulate({['map,0,swingFootMod,g2592_srun,x']= -0.95961481011978, ['map,0,swingFootMod,g2592_srun,y']= -0.3158263720969, ['map,0,swingFootMod,g2592_srun,z']= 0.0096411152482451, ['map,1,swingFootMod,g2592_srun,x']= -0.41353840980403, ['map,1,swingFootMod,g2592_srun,y']= -0.085217106724727, ['map,1,swingFootMod,g2592_srun,z']= -0.29997578371137, ['map,2,swingFootMod,g2592_srun,x']= 0.087952852771648, ['map,2,swingFootMod,g2592_srun,y']= 0.1377140824305, ['map,2,swingFootMod,g2592_srun,z']= 0.23801106999397, ['map,0,spprtFootMod,g2592_srun,x']= -0.15755520943269, ['map,0,spprtFootMod,g2592_srun,y']= -0.05608770739925, ['map,0,spprtFootMod,g2592_srun,z']= 0.24711944847929, ['map,1,spprtFootMod,g2592_srun,x']= 0.32955410555509, ['map,1,spprtFootMod,g2592_srun,y']= 0.27605787810156, ['map,1,spprtFootMod,g2592_srun,z']= -0.3048277224125, ['map,2,spprtFootMod,g2592_srun,x']= -0.040122135788974, ['map,2,spprtFootMod,g2592_srun,y']= -0.80586824121916, ['map,2,spprtFootMod,g2592_srun,z']= 0.381000868809, })

elseif g_mode=='a_.1' then
	useCases.g2592_srun.aObjWeight = .1*useCases.g2592_srun.aObjWeight

	--iter:186 bestfvever:3.654676604251e-06
	accumulate({['map,0,swingFootMod,g2592_srun,x']= -0.37069349769423, ['map,0,swingFootMod,g2592_srun,y']= -5.9812564827534, ['map,0,swingFootMod,g2592_srun,z']= 0.67190365410459, ['map,1,swingFootMod,g2592_srun,x']= 0.39106109104526, ['map,1,swingFootMod,g2592_srun,y']= 1.0191968784851, ['map,1,swingFootMod,g2592_srun,z']= -0.37797912886354, ['map,2,swingFootMod,g2592_srun,x']= -0.41529405109884, ['map,2,swingFootMod,g2592_srun,y']= -0.51822600343068, ['map,2,swingFootMod,g2592_srun,z']= -0.57242877472644, ['map,0,spprtFootMod,g2592_srun,x']= 0.92184652639079, ['map,0,spprtFootMod,g2592_srun,y']= 0.55557671792764, ['map,0,spprtFootMod,g2592_srun,z']= -1.4689154183811, ['map,1,spprtFootMod,g2592_srun,x']= -0.23057329828039, ['map,1,spprtFootMod,g2592_srun,y']= -0.35042195636551, ['map,1,spprtFootMod,g2592_srun,z']= 0.40739545971195, ['map,2,spprtFootMod,g2592_srun,x']= 2.132327374907, ['map,2,spprtFootMod,g2592_srun,y']= -4.2928835148154, ['map,2,spprtFootMod,g2592_srun,z']= -0.22223035695818, })

elseif g_mode=='a_.01' then
	useCases.g2592_srun.aObjWeight = .01*useCases.g2592_srun.aObjWeight

	--iter:186 bestfvever:1.13818023262e-06
	accumulate({['map,0,swingFootMod,g2592_srun,x']= -1.033940775579, ['map,0,swingFootMod,g2592_srun,y']= -1.1500882381692, ['map,0,swingFootMod,g2592_srun,z']= -0.67348255968222, ['map,1,swingFootMod,g2592_srun,x']= 0.21678347087352, ['map,1,swingFootMod,g2592_srun,y']= -0.33685773036728, ['map,1,swingFootMod,g2592_srun,z']= 0.32585396127017, ['map,2,swingFootMod,g2592_srun,x']= 0.13672346820304, ['map,2,swingFootMod,g2592_srun,y']= 0.22738422087992, ['map,2,swingFootMod,g2592_srun,z']= 0.3558637689424, ['map,0,spprtFootMod,g2592_srun,x']= -0.23344350460061, ['map,0,spprtFootMod,g2592_srun,y']= -0.19123836745205, ['map,0,spprtFootMod,g2592_srun,z']= 0.40226381431124, ['map,1,spprtFootMod,g2592_srun,x']= 0.12661832491228, ['map,1,spprtFootMod,g2592_srun,y']= 0.29727721127124, ['map,1,spprtFootMod,g2592_srun,z']= -0.44703178053082, ['map,2,spprtFootMod,g2592_srun,x']= 0.64786269941287, ['map,2,spprtFootMod,g2592_srun,y']= -1.8639418509145, ['map,2,spprtFootMod,g2592_srun,z']= 0.73212876035103, })

	useCases.g2592_srun.endSegW=40
	useCases.g2592_srun.prec=.05

	--iter:49 bestfvever:1.1695978779428e-06
	accumulate({['map,0,swingFootMod,g2592_srun,x']= -1.0540327254167, ['map,0,swingFootMod,g2592_srun,y']= -1.1889833071, ['map,0,swingFootMod,g2592_srun,z']= -0.67050959289041, ['map,1,swingFootMod,g2592_srun,x']= 0.24199321521689, ['map,1,swingFootMod,g2592_srun,y']= -0.34638359278552, ['map,1,swingFootMod,g2592_srun,z']= 0.30672320998787, ['map,2,swingFootMod,g2592_srun,x']= 0.12372421599908, ['map,2,swingFootMod,g2592_srun,y']= 0.19696752922756, ['map,2,swingFootMod,g2592_srun,z']= 0.41248296261435, ['map,0,spprtFootMod,g2592_srun,x']= -0.23168480310164, ['map,0,spprtFootMod,g2592_srun,y']= -0.18025361265147, ['map,0,spprtFootMod,g2592_srun,z']= 0.40907020116935, ['map,1,spprtFootMod,g2592_srun,x']= 0.10371125190509, ['map,1,spprtFootMod,g2592_srun,y']= 0.30446063534717, ['map,1,spprtFootMod,g2592_srun,z']= -0.43675767434208, ['map,2,spprtFootMod,g2592_srun,x']= 0.6768167896557, ['map,2,spprtFootMod,g2592_srun,y']= -1.8493659706343, ['map,2,spprtFootMod,g2592_srun,z']= 0.7272327833087, })

	--iter:96 bestfvever:1.246867537577e-06
	accumulate({['map,0,swingFootMod,g2592_srun,x']= -1.0687566132453, ['map,0,swingFootMod,g2592_srun,y']= -1.1795098988898, ['map,0,swingFootMod,g2592_srun,z']= -0.69276455074814, ['map,1,swingFootMod,g2592_srun,x']= 0.24325814719668, ['map,1,swingFootMod,g2592_srun,y']= -0.32171847800334, ['map,1,swingFootMod,g2592_srun,z']= 0.2728161187281, ['map,2,swingFootMod,g2592_srun,x']= 0.098996747263659, ['map,2,swingFootMod,g2592_srun,y']= 0.17165973549098, ['map,2,swingFootMod,g2592_srun,z']= 0.43961238542939, ['map,0,spprtFootMod,g2592_srun,x']= -0.25398401574296, ['map,0,spprtFootMod,g2592_srun,y']= -0.16241552908458, ['map,0,spprtFootMod,g2592_srun,z']= 0.38592652706255, ['map,1,spprtFootMod,g2592_srun,x']= 0.11288221078734, ['map,1,spprtFootMod,g2592_srun,y']= 0.29802637464397, ['map,1,spprtFootMod,g2592_srun,z']= -0.42110572400521, ['map,2,spprtFootMod,g2592_srun,x']= 0.6626800239388, ['map,2,spprtFootMod,g2592_srun,y']= -1.842789035947, ['map,2,spprtFootMod,g2592_srun,z']= 0.71754405618783, })

elseif g_mode=='a_.1_mscl_2x' then
	useCases.g2592_srun.aObjWeight = .1*useCases.g2592_srun.aObjWeight
	useCases.g2592_srun.initMsclForceScale=2

	--iter:206 bestfvever:1.0009794851924e-06
	accumulate({['map,0,swingFootMod,g2592_srun,x']= 1.5552932185844, ['map,0,swingFootMod,g2592_srun,y']= -2.9499669380896, ['map,0,swingFootMod,g2592_srun,z']= -0.90362036669659, ['map,1,swingFootMod,g2592_srun,x']= 0.44253484681285, ['map,1,swingFootMod,g2592_srun,y']= -0.83433478861423, ['map,1,swingFootMod,g2592_srun,z']= 1.3973194516383, ['map,2,swingFootMod,g2592_srun,x']= 0.42541885436598, ['map,2,swingFootMod,g2592_srun,y']= 0.17691717583969, ['map,2,swingFootMod,g2592_srun,z']= 0.46477375526899, ['map,0,spprtFootMod,g2592_srun,x']= -0.17747823207508, ['map,0,spprtFootMod,g2592_srun,y']= -0.28798333445944, ['map,0,spprtFootMod,g2592_srun,z']= 0.34841438269597, ['map,1,spprtFootMod,g2592_srun,x']= -0.0046244443316925, ['map,1,spprtFootMod,g2592_srun,y']= 0.68464277448928, ['map,1,spprtFootMod,g2592_srun,z']= -0.26669671227211, ['map,2,spprtFootMod,g2592_srun,x']= 0.34923316403398, ['map,2,spprtFootMod,g2592_srun,y']= -2.1046246543763, ['map,2,spprtFootMod,g2592_srun,z']= 0.3132300821723, })

elseif g_mode=='a_.01_mscl_2x' then
	useCases.g2592_srun.aObjWeight = .01*useCases.g2592_srun.aObjWeight
	useCases.g2592_srun.initMsclForceScale=2

	--iter:223 bestfvever:8.4930672634933e-07
	accumulate({['map,0,swingFootMod,g2592_srun,x']= -0.18869552638919, ['map,0,swingFootMod,g2592_srun,y']= -0.62634431187429, ['map,0,swingFootMod,g2592_srun,z']= -0.010218173992497, ['map,1,swingFootMod,g2592_srun,x']= 0.011005927035725, ['map,1,swingFootMod,g2592_srun,y']= 0.13135993407674, ['map,1,swingFootMod,g2592_srun,z']= 0.049364083123889, ['map,2,swingFootMod,g2592_srun,x']= 0.30395530193396, ['map,2,swingFootMod,g2592_srun,y']= 0.37813453330224, ['map,2,swingFootMod,g2592_srun,z']= -0.14257255889333, ['map,0,spprtFootMod,g2592_srun,x']= -0.28926718618392, ['map,0,spprtFootMod,g2592_srun,y']= -0.40172728496607, ['map,0,spprtFootMod,g2592_srun,z']= 0.21320058857424, ['map,1,spprtFootMod,g2592_srun,x']= 0.27867736854221, ['map,1,spprtFootMod,g2592_srun,y']= 0.86895237283713, ['map,1,spprtFootMod,g2592_srun,z']= -0.39071075436048, ['map,2,spprtFootMod,g2592_srun,x']= 0.0005058082285138, ['map,2,spprtFootMod,g2592_srun,y']= -1.5091406605927, ['map,2,spprtFootMod,g2592_srun,z']= 0.26889309104905, })

elseif g_mode=='a_.01_obj_dist' then
	useCases.g2592_srun.aObjWeight = .01*useCases.g2592_srun.aObjWeight
	useCases.g2592_srun.cmaDistWeight = 1e-1

	--iter:190 bestfvever:1.1302040569686e-05
	accumulate({['map,0,swingFootMod,g2592_srun,x']= -0.13336048441124, ['map,0,swingFootMod,g2592_srun,y']= -0.87964888922756, ['map,0,swingFootMod,g2592_srun,z']= -0.2842544341811, ['map,1,swingFootMod,g2592_srun,x']= 0.42013952570725, ['map,1,swingFootMod,g2592_srun,y']= -0.78715709979258, ['map,1,swingFootMod,g2592_srun,z']= -0.12454656048303, ['map,2,swingFootMod,g2592_srun,x']= -0.55620387686694, ['map,2,swingFootMod,g2592_srun,y']= 0.72461505539516, ['map,2,swingFootMod,g2592_srun,z']= 0.039665970318174, ['map,0,spprtFootMod,g2592_srun,x']= 0.087367928138671, ['map,0,spprtFootMod,g2592_srun,y']= -0.30451567498037, ['map,0,spprtFootMod,g2592_srun,z']= -0.57360039139228, ['map,1,spprtFootMod,g2592_srun,x']= -0.14719970709563, ['map,1,spprtFootMod,g2592_srun,y']= 0.94074083866388, ['map,1,spprtFootMod,g2592_srun,z']= 0.097522900105149, ['map,2,spprtFootMod,g2592_srun,x']= 0.86384291778622, ['map,2,spprtFootMod,g2592_srun,y']= -2.1146724610905, ['map,2,spprtFootMod,g2592_srun,z']= -0.26088207707119, })

elseif g_mode=='test' then
	useCases.g2592_srun.aObjWeight = .01*useCases.g2592_srun.aObjWeight
	useCases.g2592_srun.speedMod=vector3(2,0,0)

end
-------------------------------------------------

useCases.g2592_srun.controlParam['useCases,g2592_srun,aObjWeight'] = useCases.g2592_srun.aObjWeight

useCases.unmapControlParam(useCases.g2592_srun)
end


