package.path=package.path..";../Samples/ysscripts/lib/?.lua" --;"..package.path
require("utilfunc")

package.path=package.path..";../Samples/ysscripts/samples/?.lua" --;"..package.path
require("useMuscle_g2592_gait")


useCases.g2592_cmurun=deepCopyTable(useCases.g2592_gait)

useCases.g2592_cmurun.optimizerMethod='Optimizer.methods.CMAes_ys'

useCases.g2592_cmurun.endSegW=20
--useCases.g2592_cmurun.endSegW=30
useCases.g2592_cmurun.prec=.2

useCases.g2592_cmurun.modelName='g2592_cmurun'
useCases.g2592_cmurun.grpName='g2592_cmurun'
useCases.g2592_cmurun.grpNames={'g2592_cmurun'}

-- the initial pendControlParam and pendOptimizationPath can be automatically generated by using createInitialPendControlParam.lua
useCases.g2592_cmurun.pendControlParam=
{
['keyframe,0,pendDesiredVel,g2592_cmurun,l,z']=0,['keyframe,0,pendDesiredVel,g2592_cmurun,l,x']=1,['keyframe,0,pendDesiredVel,g2592_cmurun,r,z']=0,['keyframe,0,pendDesiredVel,g2592_cmurun,r,x']=1,['keyframe,0,pendDesiredVel,g2592_cmurun,L1,z']=0,['keyframe,0,pendDesiredVel,g2592_cmurun,L1,x']=1,['keyframe,0,pendDesiredVel,g2592_cmurun,R1,z']=0,['keyframe,0,pendDesiredVel,g2592_cmurun,R1,x']=1,['keyframe,0,pendDesiredVel,g2592_cmurun,L2,z']=0,['keyframe,0,pendDesiredVel,g2592_cmurun,L2,x']=1,['keyframe,0,pendDesiredVel,ignore,0,z']=0,['keyframe,0,pendDesiredVel,ignore,0,x']=1,['keyframe,0,pendDesiredVel,ignore,1,z']=0,['keyframe,0,pendDesiredVel,ignore,1,x']=1,
['keyframe,0,pendDesiredVel,ignore,0,x']=2.2318619005461, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.095407410253574, ['keyframe,0,pendDesiredVel,g2592_cmurun,l,x']=2.7678750123271, ['keyframe,0,pendDesiredVel,g2592_cmurun,l,z']=-0.061368741720551, ['keyframe,0,pendDesiredVel,g2592_cmurun,r,x']=3.3011852169168, ['keyframe,0,pendDesiredVel,g2592_cmurun,r,z']=-0.015136297543291, ['keyframe,0,pendDesiredVel,g2592_cmurun,L1,x']=3.6302852448288, ['keyframe,0,pendDesiredVel,g2592_cmurun,L1,z']=0.01650417761423, ['keyframe,0,pendDesiredVel,g2592_cmurun,R1,x']=3.7598068434712, ['keyframe,0,pendDesiredVel,g2592_cmurun,R1,z']=0.015362308353678, ['keyframe,0,pendDesiredVel,g2592_cmurun,L2,x']=3.7801788739257, ['keyframe,0,pendDesiredVel,g2592_cmurun,L2,z']=-0.009226057252668, ['keyframe,0,pendDesiredVel,ignore,1,x']=3.7825814926522, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.016415033036203, 
['keyframe,0,pendDesiredVel,ignore,0,x']=2.2280491976595, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.088334416890878, ['keyframe,0,pendDesiredVel,g2592_cmurun,l,x']=2.7676842006079, ['keyframe,0,pendDesiredVel,g2592_cmurun,l,z']=-0.061369060338836, ['keyframe,0,pendDesiredVel,g2592_cmurun,r,x']=3.3023092228997, ['keyframe,0,pendDesiredVel,g2592_cmurun,r,z']=-0.010252312507001, ['keyframe,0,pendDesiredVel,g2592_cmurun,L1,x']=3.6299763103984, ['keyframe,0,pendDesiredVel,g2592_cmurun,L1,z']=0.01951012776721, ['keyframe,0,pendDesiredVel,g2592_cmurun,R1,x']=3.7577808935224, ['keyframe,0,pendDesiredVel,g2592_cmurun,R1,z']=0.013677292680443, ['keyframe,0,pendDesiredVel,g2592_cmurun,L2,x']=3.7755220668929, ['keyframe,0,pendDesiredVel,g2592_cmurun,L2,z']=-0.006172512165371, ['keyframe,0,pendDesiredVel,ignore,1,x']=3.7770041827721, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.017762329855458, 
['keyframe,0,pendDesiredVel,ignore,0,x']=2.2281776438162, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.088730200740289, ['keyframe,0,pendDesiredVel,g2592_cmurun,l,x']=2.7678613981301, ['keyframe,0,pendDesiredVel,g2592_cmurun,l,z']=-0.061634204223223, ['keyframe,0,pendDesiredVel,g2592_cmurun,r,x']=3.3024663678636, ['keyframe,0,pendDesiredVel,g2592_cmurun,r,z']=-0.010526885436543, ['keyframe,0,pendDesiredVel,g2592_cmurun,L1,x']=3.6300670103101, ['keyframe,0,pendDesiredVel,g2592_cmurun,L1,z']=0.019354126724583, ['keyframe,0,pendDesiredVel,g2592_cmurun,R1,x']=3.7577412496886, ['keyframe,0,pendDesiredVel,g2592_cmurun,R1,z']=0.013638728014664, ['keyframe,0,pendDesiredVel,g2592_cmurun,L2,x']=3.7753804628986, ['keyframe,0,pendDesiredVel,g2592_cmurun,L2,z']=-0.006219430707284, ['keyframe,0,pendDesiredVel,ignore,1,x']=3.7768005250395, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.017745510619573, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.62882840834014, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.15106580431484, ['keyframe,0,pendDesiredVel,g2592_cmurun,l,x']=4.4998074301992, ['keyframe,0,pendDesiredVel,g2592_cmurun,l,z']=0.080356132886122, ['keyframe,0,pendDesiredVel,g2592_cmurun,r,x']=4.3947760945418, ['keyframe,0,pendDesiredVel,g2592_cmurun,r,z']=0.11536160475468, ['keyframe,0,pendDesiredVel,g2592_cmurun,L1,x']=3.495668268271, ['keyframe,0,pendDesiredVel,g2592_cmurun,L1,z']=0.069193858886544, ['keyframe,0,pendDesiredVel,g2592_cmurun,R1,x']=3.2151877932268, ['keyframe,0,pendDesiredVel,g2592_cmurun,R1,z']=0.046646359139735, ['keyframe,0,pendDesiredVel,g2592_cmurun,L2,x']=3.5440712987115, ['keyframe,0,pendDesiredVel,g2592_cmurun,L2,z']=-0.02413342467607, ['keyframe,0,pendDesiredVel,ignore,1,x']=3.789924492659, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.017538517535023, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.62339935492097, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.15083454049916, ['keyframe,0,pendDesiredVel,g2592_cmurun,l,x']=4.4997420601273, ['keyframe,0,pendDesiredVel,g2592_cmurun,l,z']=0.080452238752611, ['keyframe,0,pendDesiredVel,g2592_cmurun,r,x']=4.3929513519993, ['keyframe,0,pendDesiredVel,g2592_cmurun,r,z']=0.11533367667428, ['keyframe,0,pendDesiredVel,g2592_cmurun,L1,x']=3.4950463306335, ['keyframe,0,pendDesiredVel,g2592_cmurun,L1,z']=0.069175383845025, ['keyframe,0,pendDesiredVel,g2592_cmurun,R1,x']=3.2160236483514, ['keyframe,0,pendDesiredVel,g2592_cmurun,R1,z']=0.04678582882055, ['keyframe,0,pendDesiredVel,g2592_cmurun,L2,x']=3.5445944468053, ['keyframe,0,pendDesiredVel,g2592_cmurun,L2,z']=-0.024104713515993, ['keyframe,0,pendDesiredVel,ignore,1,x']=3.7899080392214, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.01753963332357, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.6192142800829, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.1507465524353, ['keyframe,0,pendDesiredVel,g2592_cmurun,l,x']=4.5012079167682, ['keyframe,0,pendDesiredVel,g2592_cmurun,l,z']=0.080644049398272, ['keyframe,0,pendDesiredVel,g2592_cmurun,r,x']=4.3918980089877, ['keyframe,0,pendDesiredVel,g2592_cmurun,r,z']=0.11532260911215, ['keyframe,0,pendDesiredVel,g2592_cmurun,L1,x']=3.4950033241516, ['keyframe,0,pendDesiredVel,g2592_cmurun,L1,z']=0.069186688911394, ['keyframe,0,pendDesiredVel,g2592_cmurun,R1,x']=3.2174903506433, ['keyframe,0,pendDesiredVel,g2592_cmurun,R1,z']=0.046973551588365, ['keyframe,0,pendDesiredVel,g2592_cmurun,L2,x']=3.5453521267926, ['keyframe,0,pendDesiredVel,g2592_cmurun,L2,z']=-0.024064154979138, ['keyframe,0,pendDesiredVel,ignore,1,x']=3.7898811723678, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.017541173647308, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.55283460618628, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.15711663908844, ['keyframe,0,pendDesiredVel,g2592_cmurun,l,x']=4.7488464244794, ['keyframe,0,pendDesiredVel,g2592_cmurun,l,z']=0.10783951655443, ['keyframe,0,pendDesiredVel,g2592_cmurun,r,x']=4.2630065034925, ['keyframe,0,pendDesiredVel,g2592_cmurun,r,z']=0.10828144311699, ['keyframe,0,pendDesiredVel,g2592_cmurun,L1,x']=3.4152909978718, ['keyframe,0,pendDesiredVel,g2592_cmurun,L1,z']=0.058145395623191, ['keyframe,0,pendDesiredVel,g2592_cmurun,R1,x']=3.2962950971963, ['keyframe,0,pendDesiredVel,g2592_cmurun,R1,z']=0.058085421973936, ['keyframe,0,pendDesiredVel,g2592_cmurun,L2,x']=3.5993420781121, ['keyframe,0,pendDesiredVel,g2592_cmurun,L2,z']=-0.023300156846818, ['keyframe,0,pendDesiredVel,ignore,1,x']=3.7884437338626, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.017545702393701, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.54364355131593, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.15707383557589, ['keyframe,0,pendDesiredVel,g2592_cmurun,l,x']=4.7541908508446, ['keyframe,0,pendDesiredVel,g2592_cmurun,l,z']=0.10826677472904, ['keyframe,0,pendDesiredVel,g2592_cmurun,r,x']=4.2621341425662, ['keyframe,0,pendDesiredVel,g2592_cmurun,r,z']=0.10806848701905, ['keyframe,0,pendDesiredVel,g2592_cmurun,L1,x']=3.4172939690748, ['keyframe,0,pendDesiredVel,g2592_cmurun,L1,z']=0.058110996818075, ['keyframe,0,pendDesiredVel,g2592_cmurun,R1,x']=3.3013524886021, ['keyframe,0,pendDesiredVel,g2592_cmurun,R1,z']=0.058518206664128, ['keyframe,0,pendDesiredVel,g2592_cmurun,L2,x']=3.6015009394661, ['keyframe,0,pendDesiredVel,g2592_cmurun,L2,z']=-0.023229118370598, ['keyframe,0,pendDesiredVel,ignore,1,x']=3.7883593185164, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.017547781331197, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.48316417746289, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.15750543563294, ['keyframe,0,pendDesiredVel,g2592_cmurun,l,x']=4.8454318558088, ['keyframe,0,pendDesiredVel,g2592_cmurun,l,z']=0.11731041963082, ['keyframe,0,pendDesiredVel,g2592_cmurun,r,x']=4.2613231600632, ['keyframe,0,pendDesiredVel,g2592_cmurun,r,z']=0.10732605236138, ['keyframe,0,pendDesiredVel,g2592_cmurun,L1,x']=3.4434812861152, ['keyframe,0,pendDesiredVel,g2592_cmurun,L1,z']=0.058658029433099, ['keyframe,0,pendDesiredVel,g2592_cmurun,R1,x']=3.3636100357193, ['keyframe,0,pendDesiredVel,g2592_cmurun,R1,z']=0.064410875587624, ['keyframe,0,pendDesiredVel,g2592_cmurun,L2,x']=3.6279534051323, ['keyframe,0,pendDesiredVel,g2592_cmurun,L2,z']=-0.022324600409984, ['keyframe,0,pendDesiredVel,ignore,1,x']=3.7873357593424, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.017577912047044, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.48259570844816, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.15751173646034, ['keyframe,0,pendDesiredVel,g2592_cmurun,l,x']=4.8457607226256, ['keyframe,0,pendDesiredVel,g2592_cmurun,l,z']=0.11734967581884, ['keyframe,0,pendDesiredVel,g2592_cmurun,r,x']=4.2605978295735, ['keyframe,0,pendDesiredVel,g2592_cmurun,r,z']=0.10727789889475, ['keyframe,0,pendDesiredVel,g2592_cmurun,L1,x']=3.443020973574, ['keyframe,0,pendDesiredVel,g2592_cmurun,L1,z']=0.058603910926428, ['keyframe,0,pendDesiredVel,g2592_cmurun,R1,x']=3.3636518290679, ['keyframe,0,pendDesiredVel,g2592_cmurun,R1,z']=0.06443152430521, ['keyframe,0,pendDesiredVel,g2592_cmurun,L2,x']=3.6280401423797, ['keyframe,0,pendDesiredVel,g2592_cmurun,L2,z']=-0.022328838910677, ['keyframe,0,pendDesiredVel,ignore,1,x']=3.7873351619043, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.017577677637707, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.48132522182074, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.15754724981374, ['keyframe,0,pendDesiredVel,g2592_cmurun,l,x']=4.846909437082, ['keyframe,0,pendDesiredVel,g2592_cmurun,l,z']=0.11747969969531, ['keyframe,0,pendDesiredVel,g2592_cmurun,r,x']=4.2586838895754, ['keyframe,0,pendDesiredVel,g2592_cmurun,r,z']=0.10714974661677, ['keyframe,0,pendDesiredVel,g2592_cmurun,L1,x']=3.4418038447514, ['keyframe,0,pendDesiredVel,g2592_cmurun,L1,z']=0.058457882999024, ['keyframe,0,pendDesiredVel,g2592_cmurun,R1,x']=3.3638277299061, ['keyframe,0,pendDesiredVel,g2592_cmurun,R1,z']=0.064494436062518, ['keyframe,0,pendDesiredVel,g2592_cmurun,L2,x']=3.6283016771568, ['keyframe,0,pendDesiredVel,g2592_cmurun,L2,z']=-0.022339969535381, ['keyframe,0,pendDesiredVel,ignore,1,x']=3.7873326242996, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.017577054368996, 
}
useCases.g2592_cmurun.pendOptimizationPath=
{
	--firstFrames={1*4,12*4,23*4,34*4,45*4,56*4,67*4,76*4},
	firstFrames={1*4,14*4,25*4,36*4,47*4,58*4,69*4,76*4},
	segments={'ignore,0','g2592_cmurun,l','g2592_cmurun,r','g2592_cmurun,L1','g2592_cmurun,R1','g2592_cmurun,L2','ignore,1'},
}
--useCases.g2592_cmurun.measureOptCost=useCases.measureOptCost

useCases.g2592_cmurun.segmentations=
{
	g2592_cmurun={
		--firstFrames={1*4,12*4,23*4,34*4,45*4,56*4,67*4,76*4},
		firstFrames={1*4,14*4,25*4,36*4,47*4,58*4,69*4,76*4},
		--        (blank)    L    R     L     R     L     (blank)
		names={             'l', 'r', 'L1', 'R1', 'L2',  },
		swingL={             0,   1,   0,    1,    0,    },
		swingR={             1,   0,   1,    0,    1,    },
		footRefL= "convertFromSwingL",
		footRefR= "convertFromSwingR",
		usePositionControl=false,
	},
}
useCases.g2592_cmurun.graphParam=
{
	g2592_cmurun={
		seg={            'l',  'r',  'L1', 'R1','L'},
		num_key={         3,    3,    3  ,  4,  4},
		key_first={       0,    0,    0  ,  0,  0},
		key_last={       'r', 'L1',  'R1', 'L', 'R1'},
	},
}
useCases.g2592_cmurun.graph=
{
	{
		"addInterpolatedSegment",
		grpName="g2592_cmurun",
		name="L",
		seg0={"g2592_cmurun", "L2"},
		seg1={"g2592_cmurun", "L1"},
		startWeight=0, endWeight=1
	},
	{"connectMulti", "g2592_cmurun", "l", "r", "L1", "R1", "L", "R1"},
	--{"initialSegment", "g2592_cmurun", "l"}
	{"initialSegment", "g2592_cmurun", "R1"}
}
useCases.g2592_cmurun.segNames=
{
	"l", "r", "L1", 'R1','L',
}

do 
	useCases.g2592_cmurun.controlParam={
		['useCases,g2592_cmurun,COMobjWeight']=0, 
		['useCases,g2592_cmurun,conservativeW']=1, 
		--['useCases,g2592_cmurun,contactMargin']=0.01, 
		['useCases,g2592_cmurun,dotMomentumScale']=0.3, 
		['useCases,g2592_cmurun,excludeRoot']=true, 
		['useCases,g2592_cmurun,headControlWeight']=0, 
		['useCases,g2592_cmurun,k_d_HEAD']=14, 
		['useCases,g2592_cmurun,k_p_HEAD']=0, 
		['useCases,g2592_cmurun,k_d_EE']=24, 
		['useCases,g2592_cmurun,k_d_momentum']=10, 
		['useCases,g2592_cmurun,k_p_EE']=120, 

		--['useCases,g2592_cmurun,maxPenetratingVel']=0, 
		['useCases,g2592_cmurun,momentumThr']=50, 
		['useCases,g2592_cmurun,noComvelDependentFootAdjustment']=true, 
		['useCases,g2592_cmurun,noIntersectionPrevenction']=true, 
		['useCases,g2592_cmurun,numericalDerivDmot']=true, 
		['useCases,g2592_cmurun,perClassContactMargin']=1, 
		['useCases,g2592_cmurun,turnGain']=10, 
		['useCases,g2592_cmurun,velMarginOffset']=0, 

		['useCases,g2592_cmurun,actuationType']      = useCases.g2592_cmurun.actuationType,
		['useCases,g2592_cmurun,k_p_ID']             = useCases.g2592_cmurun.k_p_ID,
		['useCases,g2592_cmurun,k_d_ID']             = useCases.g2592_cmurun.k_d_ID,
		['useCases,g2592_cmurun,ddqObjWeight']       = useCases.g2592_cmurun.ddqObjWeight,
		['useCases,g2592_cmurun,tauObjWeight']       = useCases.g2592_cmurun.tauObjWeight,
		['useCases,g2592_cmurun,ftObjWeight']        = useCases.g2592_cmurun.ftObjWeight,
		['useCases,g2592_cmurun,aObjWeight']         = useCases.g2592_cmurun.aObjWeight,
		['useCases,g2592_cmurun,lambdaObjWeight']    = useCases.g2592_cmurun.lambdaObjWeight,
		['useCases,g2592_cmurun,EEobjWeight']        = useCases.g2592_cmurun.EEobjWeight,
		['useCases,g2592_cmurun,EEobjWeightAngular'] = useCases.g2592_cmurun.EEobjWeightAngular,
		['useCases,g2592_cmurun,momentumWeight']     = useCases.g2592_cmurun.momentumWeight,
		['useCases,g2592_cmurun,tauMax']             = useCases.g2592_cmurun.tauMax,
		['useCases,g2592_cmurun,ftMax']              = useCases.g2592_cmurun.ftMax,
	}

	local function accumulate(cp_mod)
		local useCase=useCases.g2592_cmurun
		useCases.accumulate(useCase, cp_mod)
	end

	accumulate({
		----['keyframe,0,footRmod,g2592_cmurun,l,y']  = 0.,
		----['keyframe,1,footRmod,g2592_cmurun,l,y']  = 0.05,
		--['keyframe,0,footLmod,g2592_cmurun,r,y']  = 0.0,
		--['keyframe,1,footLmod,g2592_cmurun,r,y']  = 0.2,
		--['keyframe,0,footRmod,g2592_cmurun,L1,y'] = 0.0,
		--['keyframe,1,footRmod,g2592_cmurun,L1,y'] = 0.2,
		--['map,0,swingFootMod,g2592_cmurun,y']     = 0.1,
		--['map,1,swingFootMod,g2592_cmurun,y']     = 0.2,
		--['map,2,swingFootMod,g2592_cmurun,y']     = 0.1,

		----['keyframe,0,footLmod,g2592_cmurun,l,y']  = 0.,
		----['keyframe,1,footLmod,g2592_cmurun,l,y']  = 0.,
		--['keyframe,0,footRmod,g2592_cmurun,r,y']  = 0.,
		--['keyframe,1,footRmod,g2592_cmurun,r,y']  = -.1,
		--['keyframe,0,footLmod,g2592_cmurun,L1,y'] = 0.,
		--['keyframe,1,footLmod,g2592_cmurun,L1,y'] = -.1,
		--['map,0,spprtFootMod,g2592_cmurun,y']     = 0.,
		--['map,1,spprtFootMod,g2592_cmurun,y']     = 0.,
		--['map,2,spprtFootMod,g2592_cmurun,y']     = 0.,
	})
	useCases.unmapControlParam(useCases.g2592_cmurun)


-------------------------------------------------
if g_mode=='default' then

elseif g_mode=='test' then
	useCases.g2592_cmurun.speedMod=vector3(0,0,0)
	useCases.g2592_cmurun.aObjWeight = .01*useCases.g2592_cmurun.aObjWeight
	useCases.g2592_cmurun.initMsclForceScale=8

elseif g_mode=='a_.1' then
	useCases.g2592_cmurun.aObjWeight = .1*useCases.g2592_cmurun.aObjWeight


elseif g_mode=='a_.01' then
	useCases.g2592_cmurun.aObjWeight = .01*useCases.g2592_cmurun.aObjWeight

	--iter:1270 bestfvever:249562.75844928
	accumulate({['map,0,swingFootMod,g2592_cmurun,x']= 0.21384234297416, ['map,0,swingFootMod,g2592_cmurun,y']= 0.14685024462948, ['map,0,swingFootMod,g2592_cmurun,z']= 0.1173020509523, ['map,1,swingFootMod,g2592_cmurun,x']= 0.494970920882, ['map,1,swingFootMod,g2592_cmurun,y']= 0.23472852500348, ['map,1,swingFootMod,g2592_cmurun,z']= 0.36548228496999, ['map,2,swingFootMod,g2592_cmurun,x']= 0.10559212945504, ['map,2,swingFootMod,g2592_cmurun,y']= -0.57076932195815, ['map,2,swingFootMod,g2592_cmurun,z']= 0.15297197785516, ['map,0,spprtFootMod,g2592_cmurun,x']= -0.3363250171819, ['map,0,spprtFootMod,g2592_cmurun,y']= -0.87447076786007, ['map,0,spprtFootMod,g2592_cmurun,z']= -0.27750834446013, ['map,1,spprtFootMod,g2592_cmurun,x']= -0.21888631221497, ['map,1,spprtFootMod,g2592_cmurun,y']= -0.0042525049608267, ['map,1,spprtFootMod,g2592_cmurun,z']= 0.26707710691031, ['map,2,spprtFootMod,g2592_cmurun,x']= 0.39171719026759, ['map,2,spprtFootMod,g2592_cmurun,y']= -0.10192821399544, ['map,2,spprtFootMod,g2592_cmurun,z']= 0.039088287857364, })

	--useCases.g2592_cmurun.endSegW=40
	--useCases.g2592_cmurun.prec=.05

elseif g_mode=='a_.01_mscl_2x' then
	useCases.g2592_cmurun.aObjWeight = .01*useCases.g2592_cmurun.aObjWeight
	useCases.g2592_cmurun.initMsclForceScale=2

	--iter:709 bestfvever:206403.46672164
	accumulate({['map,0,swingFootMod,g2592_cmurun,x']= -1.4117760297987, ['map,0,swingFootMod,g2592_cmurun,y']= 0.2322248694865, ['map,0,swingFootMod,g2592_cmurun,z']= -0.68577530734278, ['map,1,swingFootMod,g2592_cmurun,x']= 0.98094970188248, ['map,1,swingFootMod,g2592_cmurun,y']= 0.065733187962526, ['map,1,swingFootMod,g2592_cmurun,z']= 0.50699926787463, ['map,2,swingFootMod,g2592_cmurun,x']= 0.5819238315702, ['map,2,swingFootMod,g2592_cmurun,y']= -2.5865428546415, ['map,2,swingFootMod,g2592_cmurun,z']= -1.1549095207196, ['map,0,spprtFootMod,g2592_cmurun,x']= -0.083270610162987, ['map,0,spprtFootMod,g2592_cmurun,y']= -3.2740374279596, ['map,0,spprtFootMod,g2592_cmurun,z']= 0.60379334876948, ['map,1,spprtFootMod,g2592_cmurun,x']= -1.6247512792981, ['map,1,spprtFootMod,g2592_cmurun,y']= -2.5995858525261, ['map,1,spprtFootMod,g2592_cmurun,z']= -2.6095140651253, ['map,2,spprtFootMod,g2592_cmurun,x']= 0.46127443070615, ['map,2,spprtFootMod,g2592_cmurun,y']= 0.67684266177438, ['map,2,spprtFootMod,g2592_cmurun,z']= 0.32162738499895, })

elseif g_mode=='a_.01_mscl_4x' then
	useCases.g2592_cmurun.aObjWeight = .01*useCases.g2592_cmurun.aObjWeight
	useCases.g2592_cmurun.initMsclForceScale=4

	--iter:930 bestfvever:200573.70628618
	accumulate({['map,0,swingFootMod,g2592_cmurun,x']= -0.21419459081425, ['map,0,swingFootMod,g2592_cmurun,y']= 0.1326469436795, ['map,0,swingFootMod,g2592_cmurun,z']= -0.057260466320157, ['map,1,swingFootMod,g2592_cmurun,x']= -0.059527508541676, ['map,1,swingFootMod,g2592_cmurun,y']= -0.15510027603705, ['map,1,swingFootMod,g2592_cmurun,z']= 0.40714810011838, ['map,2,swingFootMod,g2592_cmurun,x']= 0.28459486778496, ['map,2,swingFootMod,g2592_cmurun,y']= 0.13609517431914, ['map,2,swingFootMod,g2592_cmurun,z']= -0.055583668524135, ['map,0,spprtFootMod,g2592_cmurun,x']= 0.25215473919256, ['map,0,spprtFootMod,g2592_cmurun,y']= -0.42783557257446, ['map,0,spprtFootMod,g2592_cmurun,z']= 0.27564852649154, ['map,1,spprtFootMod,g2592_cmurun,x']= -0.14450673006631, ['map,1,spprtFootMod,g2592_cmurun,y']= -0.088609408069101, ['map,1,spprtFootMod,g2592_cmurun,z']= -0.0073529501145171, ['map,2,spprtFootMod,g2592_cmurun,x']= -0.3719345727596, ['map,2,spprtFootMod,g2592_cmurun,y']= -0.30987792429242, ['map,2,spprtFootMod,g2592_cmurun,z']= -0.022700125854584, })

elseif g_mode=='a_.01_mscl_8x' then
	useCases.g2592_cmurun.aObjWeight = .01*useCases.g2592_cmurun.aObjWeight
	useCases.g2592_cmurun.initMsclForceScale=8

	----0522
	----iter:324 bestfvever:2.3339571258649e-05
	--accumulate({['map,0,swingFootMod,g2592_cmurun,x']= 1.2034567968456, ['map,0,swingFootMod,g2592_cmurun,y']= -0.298841870529, ['map,0,swingFootMod,g2592_cmurun,z']= -0.067608640357215, ['map,1,swingFootMod,g2592_cmurun,x']= -0.1756058862163, ['map,1,swingFootMod,g2592_cmurun,y']= 0.02964202018397, ['map,1,swingFootMod,g2592_cmurun,z']= -0.090309211620692, ['map,2,swingFootMod,g2592_cmurun,x']= 1.0730017740064, ['map,2,swingFootMod,g2592_cmurun,y']= -0.436435018557, ['map,2,swingFootMod,g2592_cmurun,z']= 0.3022651884023, ['map,0,spprtFootMod,g2592_cmurun,x']= 1.1071423807113, ['map,0,spprtFootMod,g2592_cmurun,y']= -0.98717462982983, ['map,0,spprtFootMod,g2592_cmurun,z']= -0.40663357175194, ['map,1,spprtFootMod,g2592_cmurun,x']= 0.57631753429414, ['map,1,spprtFootMod,g2592_cmurun,y']= -0.50858553303908, ['map,1,spprtFootMod,g2592_cmurun,z']= -0.11470089200146, ['map,2,spprtFootMod,g2592_cmurun,x']= 0.45260772121551, ['map,2,spprtFootMod,g2592_cmurun,y']= 0.1143645219337, ['map,2,spprtFootMod,g2592_cmurun,z']= -0.10918314404501, })

	--0522 endSegW=20
	--iter:334 bestfvever:1.1970062857595e-05
	accumulate({['map,0,swingFootMod,g2592_cmurun,x']= 0.5484399714904, ['map,0,swingFootMod,g2592_cmurun,y']= 0.29700325728786, ['map,0,swingFootMod,g2592_cmurun,z']= 0.086737195070554, ['map,1,swingFootMod,g2592_cmurun,x']= -0.048253131893299, ['map,1,swingFootMod,g2592_cmurun,y']= -1.1072241508472, ['map,1,swingFootMod,g2592_cmurun,z']= 0.0073640568963139, ['map,2,swingFootMod,g2592_cmurun,x']= 2.4264979464594, ['map,2,swingFootMod,g2592_cmurun,y']= -3.4367582510106, ['map,2,swingFootMod,g2592_cmurun,z']= 0.80557088881845, ['map,0,spprtFootMod,g2592_cmurun,x']= 0.42245056475212, ['map,0,spprtFootMod,g2592_cmurun,y']= 0.12074923320238, ['map,0,spprtFootMod,g2592_cmurun,z']= 0.0015991513984482, ['map,1,spprtFootMod,g2592_cmurun,x']= -0.10943442392145, ['map,1,spprtFootMod,g2592_cmurun,y']= -1.61250081746, ['map,1,spprtFootMod,g2592_cmurun,z']= -0.54342257376298, ['map,2,spprtFootMod,g2592_cmurun,x']= 1.6921067510751, ['map,2,spprtFootMod,g2592_cmurun,y']= 0.15255257808716, ['map,2,spprtFootMod,g2592_cmurun,z']= -0.018532985571691, })

elseif g_mode=='a_.01_mscl_4x' then
	useCases.g2592_cmurun.aObjWeight = .01*useCases.g2592_cmurun.aObjWeight
	useCases.g2592_cmurun.initMsclForceScale=4

	--iter:582 bestfvever:192493.14033266
	accumulate({['map,0,swingFootMod,g2592_cmurun,x']= -0.17750228983951, ['map,0,swingFootMod,g2592_cmurun,y']= 0.028647764008412, ['map,0,swingFootMod,g2592_cmurun,z']= -0.20073423721509, ['map,1,swingFootMod,g2592_cmurun,x']= -0.0026484401086715, ['map,1,swingFootMod,g2592_cmurun,y']= -0.15690617473344, ['map,1,swingFootMod,g2592_cmurun,z']= 0.38272107984662, ['map,2,swingFootMod,g2592_cmurun,x']= 0.59322487016519, ['map,2,swingFootMod,g2592_cmurun,y']= 0.14006666918694, ['map,2,swingFootMod,g2592_cmurun,z']= -0.052047889279211, ['map,0,spprtFootMod,g2592_cmurun,x']= 0.48846060090173, ['map,0,spprtFootMod,g2592_cmurun,y']= -0.5220414915184, ['map,0,spprtFootMod,g2592_cmurun,z']= 0.45304243583712, ['map,1,spprtFootMod,g2592_cmurun,x']= -0.046586567877139, ['map,1,spprtFootMod,g2592_cmurun,y']= -0.19326228942749, ['map,1,spprtFootMod,g2592_cmurun,z']= 0.025723825294645, ['map,2,spprtFootMod,g2592_cmurun,x']= -0.37521253973857, ['map,2,spprtFootMod,g2592_cmurun,y']= -0.42593249559515, ['map,2,spprtFootMod,g2592_cmurun,z']= -0.030040126067357, })

elseif g_mode=='a_.01_mscl_2x' then
	useCases.g2592_cmurun.aObjWeight = .01*useCases.g2592_cmurun.aObjWeight
	useCases.g2592_cmurun.initMsclForceScale=2

end
-------------------------------------------------

useCases.g2592_cmurun.controlParam['useCases,g2592_cmurun,aObjWeight'] = useCases.g2592_cmurun.aObjWeight

useCases.unmapControlParam(useCases.g2592_cmurun)
end


