package.path=package.path..";../Samples/ysscripts/lib/?.lua" --;"..package.path
require("utilfunc")

package.path=package.path..";../Samples/ysscripts/samples/?.lua" --;"..package.path
require("useMuscle_g2562_gait")


useCases.g2562_ipfrun=deepCopyTable(useCases.g2562_gait)

useCases.g2562_ipfrun.optimizerMethod='Optimizer.methods.CMAes_ys'

--useCases.g2562_ipfrun.endSegW=80
useCases.g2562_ipfrun.endSegW=40
useCases.g2562_ipfrun.prec=.2

useCases.g2562_ipfrun.modelName='g2562_ipfrun'
useCases.g2562_ipfrun.grpName='g2562_ipfrun'
useCases.g2562_ipfrun.grpNames={'g2562_ipfrun'}

useCases.g2562_ipfrun.ddqObjWeight=500*(25-7)
useCases.g2562_ipfrun.lambdaObjWeight=.01
useCases.g2562_ipfrun.momentumWeight=100
useCases.g2562_ipfrun.EEobjWeight=200

-- the initial pendControlParam and pendOptimizationPath can be automatically generated by using createInitialPendControlParam.lua
useCases.g2562_ipfrun.pendControlParam=
{
['keyframe,0,pendDesiredVel,g2562_ipfrun,l,z']=0,['keyframe,0,pendDesiredVel,g2562_ipfrun,l,x']=1,['keyframe,0,pendDesiredVel,g2562_ipfrun,r,z']=0,['keyframe,0,pendDesiredVel,g2562_ipfrun,r,x']=1,['keyframe,0,pendDesiredVel,g2562_ipfrun,L1,z']=0,['keyframe,0,pendDesiredVel,g2562_ipfrun,L1,x']=1,['keyframe,0,pendDesiredVel,g2562_ipfrun,R1,z']=0,['keyframe,0,pendDesiredVel,g2562_ipfrun,R1,x']=1,['keyframe,0,pendDesiredVel,g2562_ipfrun,L2,z']=0,['keyframe,0,pendDesiredVel,g2562_ipfrun,L2,x']=1,['keyframe,0,pendDesiredVel,ignore,0,z']=0,['keyframe,0,pendDesiredVel,ignore,0,x']=1,['keyframe,0,pendDesiredVel,ignore,1,z']=0,['keyframe,0,pendDesiredVel,ignore,1,x']=1,
['keyframe,0,pendDesiredVel,ignore,0,x']=0.27454274916781, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.53368795449817, ['keyframe,0,pendDesiredVel,g2562_ipfrun,l,x']=0.26123059653128, ['keyframe,0,pendDesiredVel,g2562_ipfrun,l,z']=-0.53457953203496, ['keyframe,0,pendDesiredVel,g2562_ipfrun,r,x']=0.25674745821108, ['keyframe,0,pendDesiredVel,g2562_ipfrun,r,z']=-0.53334529543633, ['keyframe,0,pendDesiredVel,g2562_ipfrun,L1,x']=0.26524936015123, ['keyframe,0,pendDesiredVel,g2562_ipfrun,L1,z']=-0.53108313618634, ['keyframe,0,pendDesiredVel,g2562_ipfrun,R1,x']=0.27841741405833, ['keyframe,0,pendDesiredVel,g2562_ipfrun,R1,z']=-0.53092197199819, ['keyframe,0,pendDesiredVel,g2562_ipfrun,L2,x']=0.29426067785674, ['keyframe,0,pendDesiredVel,g2562_ipfrun,L2,z']=-0.52799421954717, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.30960864065891, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.52001606610877, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.2747737319032, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.53371901327057, ['keyframe,0,pendDesiredVel,g2562_ipfrun,l,x']=0.26204460034561, ['keyframe,0,pendDesiredVel,g2562_ipfrun,l,z']=-0.53383984874993, ['keyframe,0,pendDesiredVel,g2562_ipfrun,r,x']=0.25860850994182, ['keyframe,0,pendDesiredVel,g2562_ipfrun,r,z']=-0.53236852995563, ['keyframe,0,pendDesiredVel,g2562_ipfrun,L1,x']=0.26877061853418, ['keyframe,0,pendDesiredVel,g2562_ipfrun,L1,z']=-0.52846754364723, ['keyframe,0,pendDesiredVel,g2562_ipfrun,R1,x']=0.28277319247098, ['keyframe,0,pendDesiredVel,g2562_ipfrun,R1,z']=-0.52769844303582, ['keyframe,0,pendDesiredVel,g2562_ipfrun,L2,x']=0.29903331477888, ['keyframe,0,pendDesiredVel,g2562_ipfrun,L2,z']=-0.52434937986167, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.31531294014475, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.51556688644752, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.27465801101933, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.53360025303667, ['keyframe,0,pendDesiredVel,g2562_ipfrun,l,x']=0.26153402652936, ['keyframe,0,pendDesiredVel,g2562_ipfrun,l,z']=-0.5344403883127, ['keyframe,0,pendDesiredVel,g2562_ipfrun,r,x']=0.25741650709809, ['keyframe,0,pendDesiredVel,g2562_ipfrun,r,z']=-0.5328312074445, ['keyframe,0,pendDesiredVel,g2562_ipfrun,L1,x']=0.26622635254283, ['keyframe,0,pendDesiredVel,g2562_ipfrun,L1,z']=-0.53041950989239, ['keyframe,0,pendDesiredVel,g2562_ipfrun,R1,x']=0.27973181851696, ['keyframe,0,pendDesiredVel,g2562_ipfrun,R1,z']=-0.52993060952477, ['keyframe,0,pendDesiredVel,g2562_ipfrun,L2,x']=0.2958574474953, ['keyframe,0,pendDesiredVel,g2562_ipfrun,L2,z']=-0.52677695243413, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.31127522230611, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.51872814800921, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.70272519555154, ['keyframe,0,pendDesiredVel,ignore,0,z']=-1.490660229654, ['keyframe,0,pendDesiredVel,g2562_ipfrun,l,x']=-0.13577239950266, ['keyframe,0,pendDesiredVel,g2562_ipfrun,l,z']=1.200198628103, ['keyframe,0,pendDesiredVel,g2562_ipfrun,r,x']=-0.12903929043507, ['keyframe,0,pendDesiredVel,g2562_ipfrun,r,z']=-0.33220380266587, ['keyframe,0,pendDesiredVel,g2562_ipfrun,L1,x']=0.2154981244236, ['keyframe,0,pendDesiredVel,g2562_ipfrun,L1,z']=0.11737191850964, ['keyframe,0,pendDesiredVel,g2562_ipfrun,R1,x']=0.16598113346969, ['keyframe,0,pendDesiredVel,g2562_ipfrun,R1,z']=-0.68342176936861, ['keyframe,0,pendDesiredVel,g2562_ipfrun,L2,x']=0.2804132892824, ['keyframe,0,pendDesiredVel,g2562_ipfrun,L2,z']=0.010895822145381, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.34573564128018, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.78741299712662, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.70217126332524, ['keyframe,0,pendDesiredVel,ignore,0,z']=-1.4909459354114, ['keyframe,0,pendDesiredVel,g2562_ipfrun,l,x']=-0.13596173786766, ['keyframe,0,pendDesiredVel,g2562_ipfrun,l,z']=1.1999373440271, ['keyframe,0,pendDesiredVel,g2562_ipfrun,r,x']=-0.1289924042809, ['keyframe,0,pendDesiredVel,g2562_ipfrun,r,z']=-0.33264597956807, ['keyframe,0,pendDesiredVel,g2562_ipfrun,L1,x']=0.2154845021388, ['keyframe,0,pendDesiredVel,g2562_ipfrun,L1,z']=0.11732453075142, ['keyframe,0,pendDesiredVel,g2562_ipfrun,R1,x']=0.16595974914078, ['keyframe,0,pendDesiredVel,g2562_ipfrun,R1,z']=-0.68345138502836, ['keyframe,0,pendDesiredVel,g2562_ipfrun,L2,x']=0.28041915307207, ['keyframe,0,pendDesiredVel,g2562_ipfrun,L2,z']=0.011031318596234, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.34573981316746, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.78744833883463, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.70197367931722, ['keyframe,0,pendDesiredVel,ignore,0,z']=-1.4910424115089, ['keyframe,0,pendDesiredVel,g2562_ipfrun,l,x']=-0.13602655036884, ['keyframe,0,pendDesiredVel,g2562_ipfrun,l,z']=1.1998433795653, ['keyframe,0,pendDesiredVel,g2562_ipfrun,r,x']=-0.1289702719855, ['keyframe,0,pendDesiredVel,g2562_ipfrun,r,z']=-0.33281146774124, ['keyframe,0,pendDesiredVel,g2562_ipfrun,L1,x']=0.21548164148513, ['keyframe,0,pendDesiredVel,g2562_ipfrun,L1,z']=0.11730841712202, ['keyframe,0,pendDesiredVel,g2562_ipfrun,R1,x']=0.16595168960139, ['keyframe,0,pendDesiredVel,g2562_ipfrun,R1,z']=-0.68346241686814, ['keyframe,0,pendDesiredVel,g2562_ipfrun,L2,x']=0.28042081668763, ['keyframe,0,pendDesiredVel,g2562_ipfrun,L2,z']=0.011083272414338, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.34574117069349, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.78746241982738, 
}
useCases.g2562_ipfrun.pendOptimizationPath=
{
	--firstFrames={1*4,7*4,11*4,15*4,19*4,23*4,27*4,31*4},
	--firstFrames={1*4,8*4,12*4,16*4,20*4,24*4,28*4,31*4},
	firstFrames={1*4,7*4+3,11*4+3,15*4+3,19*4+3,23*4+3,27*4+3,31*4},
	segments={'ignore,0','g2562_ipfrun,l','g2562_ipfrun,r','g2562_ipfrun,L1','g2562_ipfrun,R1','g2562_ipfrun,L2','ignore,1'},
}
--useCases.g2562_ipfrun.measureOptCost=useCases.measureOptCost

useCases.g2562_ipfrun.segmentations=
{
	g2562_ipfrun={
		--firstFrames={1*4,7*4,11*4,15*4,19*4,23*4,27*4,31*4},
		--firstFrames={1*4,8*4,12*4,16*4,20*4,24*4,28*4,31*4},
		firstFrames={1*4,7*4+3,11*4+3,15*4+3,19*4+3,23*4+3,27*4+3,31*4},
		--        (blank)    L    R     L     R     L     (blank)
		names={             'l', 'r', 'L1', 'R1', 'L2',  },
		swingL={             0,   1,   0,    1,    0,    },
		swingR={             1,   0,   1,    0,    1,    },
		footRefL= "convertFromSwingL",
		footRefR= "convertFromSwingR",
		usePositionControl=false,
	},
}
useCases.g2562_ipfrun.graphParam=
{
	g2562_ipfrun={
		seg={            'l',  'r',  'L1', 'R1','L'},
		num_key={         3,    3,    3  ,  4,  4},
		key_first={       0,    0,    0  ,  0,  0},
		key_last={       'r', 'L1',  'R1', 'L', 'R1'},
	},
}
useCases.g2562_ipfrun.graph=
{
	{
		"addInterpolatedSegment",
		grpName="g2562_ipfrun",
		name="L",
		seg0={"g2562_ipfrun", "L2"},
		seg1={"g2562_ipfrun", "L1"},
		startWeight=0, endWeight=1
	},
	{"connectMulti", "g2562_ipfrun", "l", "r", "L1", "R1", "L", "R1"},
	--{"initialSegment", "g2562_ipfrun", "l"}
	{"initialSegment", "g2562_ipfrun", "R1"}
}
useCases.g2562_ipfrun.segNames=
{
	"l", "r", "L1", 'R1','L',
}

do 
	useCases.g2562_ipfrun.controlParam={
		['useCases,g2562_ipfrun,COMobjWeight']=0, 
		['useCases,g2562_ipfrun,conservativeW']=1, 
		--['useCases,g2562_ipfrun,contactMargin']=0.01, 
		['useCases,g2562_ipfrun,dotMomentumScale']=0.3, 
		['useCases,g2562_ipfrun,excludeRoot']=true, 
		['useCases,g2562_ipfrun,headControlWeight']=0, 
		['useCases,g2562_ipfrun,k_d_HEAD']=14, 
		['useCases,g2562_ipfrun,k_p_HEAD']=0, 
		['useCases,g2562_ipfrun,k_d_EE']=24, 
		['useCases,g2562_ipfrun,k_d_momentum']=10, 
		['useCases,g2562_ipfrun,k_p_EE']=120, 

		--['useCases,g2562_ipfrun,maxPenetratingVel']=0, 
		['useCases,g2562_ipfrun,momentumThr']=50, 
		['useCases,g2562_ipfrun,noComvelDependentFootAdjustment']=true, 
		['useCases,g2562_ipfrun,noIntersectionPrevenction']=true, 
		['useCases,g2562_ipfrun,numericalDerivDmot']=true, 
		['useCases,g2562_ipfrun,perClassContactMargin']=1, 
		['useCases,g2562_ipfrun,turnGain']=10, 
		['useCases,g2562_ipfrun,velMarginOffset']=0, 

		['useCases,g2562_ipfrun,actuationType']      = useCases.g2562_ipfrun.actuationType,
		['useCases,g2562_ipfrun,k_p_ID']             = useCases.g2562_ipfrun.k_p_ID,
		['useCases,g2562_ipfrun,k_d_ID']             = useCases.g2562_ipfrun.k_d_ID,
		['useCases,g2562_ipfrun,ddqObjWeight']       = useCases.g2562_ipfrun.ddqObjWeight,
		['useCases,g2562_ipfrun,tauObjWeight']       = useCases.g2562_ipfrun.tauObjWeight,
		['useCases,g2562_ipfrun,ftObjWeight']        = useCases.g2562_ipfrun.ftObjWeight,
		['useCases,g2562_ipfrun,aObjWeight']         = useCases.g2562_ipfrun.aObjWeight,
		['useCases,g2562_ipfrun,lambdaObjWeight']    = useCases.g2562_ipfrun.lambdaObjWeight,
		['useCases,g2562_ipfrun,EEobjWeight']        = useCases.g2562_ipfrun.EEobjWeight,
		['useCases,g2562_ipfrun,EEobjWeightAngular'] = useCases.g2562_ipfrun.EEobjWeightAngular,
		['useCases,g2562_ipfrun,momentumWeight']     = useCases.g2562_ipfrun.momentumWeight,
		['useCases,g2562_ipfrun,tauMax']             = useCases.g2562_ipfrun.tauMax,
		['useCases,g2562_ipfrun,ftMax']              = useCases.g2562_ipfrun.ftMax,
	}

	local function accumulate(cp_mod)
		local useCase=useCases.g2562_ipfrun
		useCases.accumulate(useCase, cp_mod)
	end

----------------------------
if g_mode=='default' then

elseif g_mode=='a_.01' then
	useCases.g2562_ipfrun.aObjWeight = .01*useCases.g2562_ipfrun.aObjWeight

	----iter:969 bestfvever:591875.00040617
	--accumulate({['map,0,swingFootMod,g2562_ipfrun,x']= -1.8091747494216, ['map,0,swingFootMod,g2562_ipfrun,y']= -2.3825911397383, ['map,0,swingFootMod,g2562_ipfrun,z']= -2.8362678887373, ['map,1,swingFootMod,g2562_ipfrun,x']= 0.67283022587586, ['map,1,swingFootMod,g2562_ipfrun,y']= -1.075673614699, ['map,1,swingFootMod,g2562_ipfrun,z']= 1.0121074035856, ['map,2,swingFootMod,g2562_ipfrun,x']= 1.0392507542606, ['map,2,swingFootMod,g2562_ipfrun,y']= 0.39627164982354, ['map,2,swingFootMod,g2562_ipfrun,z']= 2.8997888887737, ['map,0,spprtFootMod,g2562_ipfrun,x']= -1.8748170547378, ['map,0,spprtFootMod,g2562_ipfrun,y']= -1.6108308358599, ['map,0,spprtFootMod,g2562_ipfrun,z']= -2.5298539754554, ['map,1,spprtFootMod,g2562_ipfrun,x']= -3.3861444719833, ['map,1,spprtFootMod,g2562_ipfrun,y']= -0.74437901025328, ['map,1,spprtFootMod,g2562_ipfrun,z']= 7.5597841116149, ['map,2,spprtFootMod,g2562_ipfrun,x']= -1.579946165374, ['map,2,spprtFootMod,g2562_ipfrun,y']= -6.115152799303, ['map,2,spprtFootMod,g2562_ipfrun,z']= 4.4352278276726, })

elseif g_mode=='a_.01_mscl_2x' then
	useCases.g2562_ipfrun.aObjWeight = .01*useCases.g2562_ipfrun.aObjWeight
	useCases.g2562_ipfrun.initMsclForceScale=2

	--ddqObjWeight=10
	----iter:907 bestfvever:438750.00063095
	--accumulate({['map,0,swingFootMod,g2562_ipfrun,x']= -0.056920302306169, ['map,0,swingFootMod,g2562_ipfrun,y']= -0.073839865569829, ['map,0,swingFootMod,g2562_ipfrun,z']= -0.06804650669315, ['map,1,swingFootMod,g2562_ipfrun,x']= 0.2857356654204, ['map,1,swingFootMod,g2562_ipfrun,y']= -0.17368694615222, ['map,1,swingFootMod,g2562_ipfrun,z']= 0.057416713807131, ['map,2,swingFootMod,g2562_ipfrun,x']= 0.24622316937121, ['map,2,swingFootMod,g2562_ipfrun,y']= -0.16729044002034, ['map,2,swingFootMod,g2562_ipfrun,z']= -0.4493662099382, ['map,0,spprtFootMod,g2562_ipfrun,x']= 0.41793481352637, ['map,0,spprtFootMod,g2562_ipfrun,y']= 0.36506687886401, ['map,0,spprtFootMod,g2562_ipfrun,z']= 0.15345389308889, ['map,1,spprtFootMod,g2562_ipfrun,x']= 0.57599162212794, ['map,1,spprtFootMod,g2562_ipfrun,y']= 0.071951222481523, ['map,1,spprtFootMod,g2562_ipfrun,z']= 0.13907262344788, ['map,2,spprtFootMod,g2562_ipfrun,x']= -0.092563575965665, ['map,2,spprtFootMod,g2562_ipfrun,y']= -0.42069334262053, ['map,2,spprtFootMod,g2562_ipfrun,z']= 0.20268381918913, })

	----iter:800 bestfvever:473750.00007364
	--accumulate({['map,0,swingFootMod,g2562_ipfrun,x']= 1.5734678578872, ['map,0,swingFootMod,g2562_ipfrun,y']= 1.1689801655199, ['map,0,swingFootMod,g2562_ipfrun,z']= 2.5657217768434, ['map,1,swingFootMod,g2562_ipfrun,x']= -0.099910177288196, ['map,1,swingFootMod,g2562_ipfrun,y']= -4.8512657340507, ['map,1,swingFootMod,g2562_ipfrun,z']= 2.0888963370202, ['map,2,swingFootMod,g2562_ipfrun,x']= 3.8930313000417, ['map,2,swingFootMod,g2562_ipfrun,y']= -9.8237257419034, ['map,2,swingFootMod,g2562_ipfrun,z']= 3.1154859019876, ['map,0,spprtFootMod,g2562_ipfrun,x']= -1.80710695755, ['map,0,spprtFootMod,g2562_ipfrun,y']= 2.236312497992, ['map,0,spprtFootMod,g2562_ipfrun,z']= 5.1653710936674, ['map,1,spprtFootMod,g2562_ipfrun,x']= -0.90521706169997, ['map,1,spprtFootMod,g2562_ipfrun,y']= -0.26339150215874, ['map,1,spprtFootMod,g2562_ipfrun,z']= 0.027571940018963, ['map,2,spprtFootMod,g2562_ipfrun,x']= -3.7730684808976, ['map,2,spprtFootMod,g2562_ipfrun,y']= -7.4527307654124, ['map,2,spprtFootMod,g2562_ipfrun,z']= 2.0467641375785, })

	----iter:713 bestfvever:778125.00004573
	--accumulate({['map,0,swingFootMod,g2562_ipfrun,x']= -2.1195548035609, ['map,0,swingFootMod,g2562_ipfrun,y']= -1.0772069529055, ['map,0,swingFootMod,g2562_ipfrun,z']= -0.58198870345236, ['map,1,swingFootMod,g2562_ipfrun,x']= 0.93884851817238, ['map,1,swingFootMod,g2562_ipfrun,y']= 0.018719406461945, ['map,1,swingFootMod,g2562_ipfrun,z']= -0.25905731358877, ['map,2,swingFootMod,g2562_ipfrun,x']= 1.8452904946738, ['map,2,swingFootMod,g2562_ipfrun,y']= 1.2639819571154, ['map,2,swingFootMod,g2562_ipfrun,z']= -0.61105646032042, ['map,0,spprtFootMod,g2562_ipfrun,x']= -0.53795863843395, ['map,0,spprtFootMod,g2562_ipfrun,y']= 0.66766548330378, ['map,0,spprtFootMod,g2562_ipfrun,z']= 1.4811779653098, ['map,1,spprtFootMod,g2562_ipfrun,x']= 1.2569703568778, ['map,1,spprtFootMod,g2562_ipfrun,y']= 0.48601403447403, ['map,1,spprtFootMod,g2562_ipfrun,z']= 0.11387674896398, ['map,2,spprtFootMod,g2562_ipfrun,x']= -1.0122582242393, ['map,2,spprtFootMod,g2562_ipfrun,y']= -1.5006536523449, ['map,2,spprtFootMod,g2562_ipfrun,z']= -0.85577785631605, })

	--useCases.g2562_ipfrun.endSegW=40
	--useCases.g2562_ipfrun.prec=.2

	----iter:659 bestfvever:376250.00004515
	--accumulate({['map,0,swingFootMod,g2562_ipfrun,x']= -2.2474340949531, ['map,0,swingFootMod,g2562_ipfrun,y']= -0.97476803012073, ['map,0,swingFootMod,g2562_ipfrun,z']= -0.73941253545672, ['map,1,swingFootMod,g2562_ipfrun,x']= 0.95078501277749, ['map,1,swingFootMod,g2562_ipfrun,y']= -0.079804113701305, ['map,1,swingFootMod,g2562_ipfrun,z']= -0.2174468621736, ['map,2,swingFootMod,g2562_ipfrun,x']= 1.8567550259683, ['map,2,swingFootMod,g2562_ipfrun,y']= 1.2099352189628, ['map,2,swingFootMod,g2562_ipfrun,z']= -0.59196716643224, ['map,0,spprtFootMod,g2562_ipfrun,x']= -0.64746068838792, ['map,0,spprtFootMod,g2562_ipfrun,y']= 0.6787238775998, ['map,0,spprtFootMod,g2562_ipfrun,z']= 1.5988677381115, ['map,1,spprtFootMod,g2562_ipfrun,x']= 1.2416016763932, ['map,1,spprtFootMod,g2562_ipfrun,y']= 0.4633090075668, ['map,1,spprtFootMod,g2562_ipfrun,z']= -0.31997015718586, ['map,2,spprtFootMod,g2562_ipfrun,x']= -0.70648332158835, ['map,2,spprtFootMod,g2562_ipfrun,y']= -1.5719009623425, ['map,2,spprtFootMod,g2562_ipfrun,z']= -0.70264330380612, })

	--useCases.g2562_ipfrun.EEobjWeight=200

	----iter:1348 bestfvever:681250.00043304
	--accumulate({['map,0,swingFootMod,g2562_ipfrun,x']= -1.0394775755898, ['map,0,swingFootMod,g2562_ipfrun,y']= -0.1180545352061, ['map,0,swingFootMod,g2562_ipfrun,z']= -0.19190090115375, ['map,1,swingFootMod,g2562_ipfrun,x']= 0.72315103219866, ['map,1,swingFootMod,g2562_ipfrun,y']= 0.04807096652101, ['map,1,swingFootMod,g2562_ipfrun,z']= -0.17907649774936, ['map,2,swingFootMod,g2562_ipfrun,x']= 0.61405969232793, ['map,2,swingFootMod,g2562_ipfrun,y']= 0.27338601223189, ['map,2,swingFootMod,g2562_ipfrun,z']= -0.13092350041019, ['map,0,spprtFootMod,g2562_ipfrun,x']= 0.49434266539247, ['map,0,spprtFootMod,g2562_ipfrun,y']= -0.11460173370871, ['map,0,spprtFootMod,g2562_ipfrun,z']= 0.59848330451532, ['map,1,spprtFootMod,g2562_ipfrun,x']= 0.22786502727631, ['map,1,spprtFootMod,g2562_ipfrun,y']= 0.08566425378704, ['map,1,spprtFootMod,g2562_ipfrun,z']= -0.098530333915438, ['map,2,spprtFootMod,g2562_ipfrun,x']= 0.12515083209947, ['map,2,spprtFootMod,g2562_ipfrun,y']= -0.11633333198697, ['map,2,spprtFootMod,g2562_ipfrun,z']= -0.26688847993038, })

	----iter:521 bestfvever:803125.00004672
	--accumulate({['map,0,swingFootMod,g2562_ipfrun,x']= -0.056087813032931, ['map,0,swingFootMod,g2562_ipfrun,y']= -0.15786328676385, ['map,0,swingFootMod,g2562_ipfrun,z']= 0.12382717923159, ['map,1,swingFootMod,g2562_ipfrun,x']= 0.1161955172298, ['map,1,swingFootMod,g2562_ipfrun,y']= -0.085121789874366, ['map,1,swingFootMod,g2562_ipfrun,z']= 0.076690244351384, ['map,2,swingFootMod,g2562_ipfrun,x']= 0.28939905382823, ['map,2,swingFootMod,g2562_ipfrun,y']= 0.073143593158758, ['map,2,swingFootMod,g2562_ipfrun,z']= 0.0046663243203086, ['map,0,spprtFootMod,g2562_ipfrun,x']= 0.27941412291137, ['map,0,spprtFootMod,g2562_ipfrun,y']= 0.12427975978284, ['map,0,spprtFootMod,g2562_ipfrun,z']= -0.068267238925322, ['map,1,spprtFootMod,g2562_ipfrun,x']= 0.030814475093162, ['map,1,spprtFootMod,g2562_ipfrun,y']= -0.11148078628896, ['map,1,spprtFootMod,g2562_ipfrun,z']= 0.10900042109091, ['map,2,spprtFootMod,g2562_ipfrun,x']= -0.16800688346613, ['map,2,spprtFootMod,g2562_ipfrun,y']= -0.29214885315834, ['map,2,spprtFootMod,g2562_ipfrun,z']= 0.20591006076122, })

	--iter:592 bestfvever:253125.00046825
	accumulate({['map,0,swingFootMod,g2562_ipfrun,x']= -0.2245301453189, ['map,0,swingFootMod,g2562_ipfrun,y']= -0.059630536694596, ['map,0,swingFootMod,g2562_ipfrun,z']= -0.019324685921695, ['map,1,swingFootMod,g2562_ipfrun,x']= -0.00533106180522, ['map,1,swingFootMod,g2562_ipfrun,y']= 0.17540202244565, ['map,1,swingFootMod,g2562_ipfrun,z']= -0.045432505234159, ['map,2,swingFootMod,g2562_ipfrun,x']= 0.024756721591932, ['map,2,swingFootMod,g2562_ipfrun,y']= 0.0054824660266516, ['map,2,swingFootMod,g2562_ipfrun,z']= -0.11682271397335, ['map,0,spprtFootMod,g2562_ipfrun,x']= -0.052505526836968, ['map,0,spprtFootMod,g2562_ipfrun,y']= -0.2154361216982, ['map,0,spprtFootMod,g2562_ipfrun,z']= -0.16174633774041, ['map,1,spprtFootMod,g2562_ipfrun,x']= 0.16144336765176, ['map,1,spprtFootMod,g2562_ipfrun,y']= 0.087572937369842, ['map,1,spprtFootMod,g2562_ipfrun,z']= 0.07165949983726, ['map,2,spprtFootMod,g2562_ipfrun,x']= -0.17202923234072, ['map,2,spprtFootMod,g2562_ipfrun,y']= 0.15174244413128, ['map,2,spprtFootMod,g2562_ipfrun,z']= -0.20592831639287, })

elseif g_mode=='a_.1_mscl_2x' then
	useCases.g2562_ipfrun.aObjWeight = .1*useCases.g2562_ipfrun.aObjWeight
	useCases.g2562_ipfrun.initMsclForceScale=2

	useCases.g2562_ipfrun.ddqObjWeight=500*(25-7)
	useCases.g2562_ipfrun.lambdaObjWeight=.01
	useCases.g2562_ipfrun.momentumWeight=100
	useCases.g2562_ipfrun.EEobjWeight=200

	----iter:607 bestfvever:791875.0000888
	--accumulate({['map,0,swingFootMod,g2562_ipfrun,x']= -0.2095691888647, ['map,0,swingFootMod,g2562_ipfrun,y']= -0.36699382730642, ['map,0,swingFootMod,g2562_ipfrun,z']= -0.48202486870998, ['map,1,swingFootMod,g2562_ipfrun,x']= 0.15523077199773, ['map,1,swingFootMod,g2562_ipfrun,y']= -0.081870674464285, ['map,1,swingFootMod,g2562_ipfrun,z']= 0.22164412480267, ['map,2,swingFootMod,g2562_ipfrun,x']= 0.96770366472219, ['map,2,swingFootMod,g2562_ipfrun,y']= 0.3429318486918, ['map,2,swingFootMod,g2562_ipfrun,z']= -0.31039444465737, ['map,0,spprtFootMod,g2562_ipfrun,x']= -0.013347039476483, ['map,0,spprtFootMod,g2562_ipfrun,y']= 0.083994632144715, ['map,0,spprtFootMod,g2562_ipfrun,z']= 0.31250668459012, ['map,1,spprtFootMod,g2562_ipfrun,x']= -0.051455709177421, ['map,1,spprtFootMod,g2562_ipfrun,y']= 0.073143100260377, ['map,1,spprtFootMod,g2562_ipfrun,z']= 0.11847042662709, ['map,2,spprtFootMod,g2562_ipfrun,x']= -0.23926305222968, ['map,2,spprtFootMod,g2562_ipfrun,y']= -0.34540762655814, ['map,2,spprtFootMod,g2562_ipfrun,z']= 0.18806402375055, })

	--iter:424 bestfvever:213750.00004081
	accumulate({['map,0,swingFootMod,g2562_ipfrun,x']= -0.86225994095412, ['map,0,swingFootMod,g2562_ipfrun,y']= 0.38556531504321, ['map,0,swingFootMod,g2562_ipfrun,z']= 0.47895921744043, ['map,1,swingFootMod,g2562_ipfrun,x']= -0.37442777062248, ['map,1,swingFootMod,g2562_ipfrun,y']= -0.063551447698346, ['map,1,swingFootMod,g2562_ipfrun,z']= -0.025143756383533, ['map,2,swingFootMod,g2562_ipfrun,x']= 0.60370952557314, ['map,2,swingFootMod,g2562_ipfrun,y']= 0.064826054933704, ['map,2,swingFootMod,g2562_ipfrun,z']= -0.062738170365857, ['map,0,spprtFootMod,g2562_ipfrun,x']= 0.6531322932473, ['map,0,spprtFootMod,g2562_ipfrun,y']= 0.53135646268406, ['map,0,spprtFootMod,g2562_ipfrun,z']= -0.3923333563527, ['map,1,spprtFootMod,g2562_ipfrun,x']= 0.39062515498985, ['map,1,spprtFootMod,g2562_ipfrun,y']= -0.095023141590752, ['map,1,spprtFootMod,g2562_ipfrun,z']= -0.44266569305536, ['map,2,spprtFootMod,g2562_ipfrun,x']= -0.44125715011797, ['map,2,spprtFootMod,g2562_ipfrun,y']= -0.21192250329905, ['map,2,spprtFootMod,g2562_ipfrun,z']= -0.32817138152488, })

elseif g_mode=='a_1_mscl_2x' then
	useCases.g2562_ipfrun.aObjWeight = 1*useCases.g2562_ipfrun.aObjWeight
	useCases.g2562_ipfrun.initMsclForceScale=2

	useCases.g2562_ipfrun.ddqObjWeight=500*(25-7)
	useCases.g2562_ipfrun.lambdaObjWeight=.01
	useCases.g2562_ipfrun.momentumWeight=100
	useCases.g2562_ipfrun.EEobjWeight=200

	----iter:701 bestfvever:786250.00005034
	--accumulate({['map,0,swingFootMod,g2562_ipfrun,x']= -0.73487392802546, ['map,0,swingFootMod,g2562_ipfrun,y']= -1.0427724003707, ['map,0,swingFootMod,g2562_ipfrun,z']= -0.13296106777566, ['map,1,swingFootMod,g2562_ipfrun,x']= 0.43808545955734, ['map,1,swingFootMod,g2562_ipfrun,y']= 0.24059510441817, ['map,1,swingFootMod,g2562_ipfrun,z']= -0.38155743813185, ['map,2,swingFootMod,g2562_ipfrun,x']= 1.0198877760667, ['map,2,swingFootMod,g2562_ipfrun,y']= 0.70576574689344, ['map,2,swingFootMod,g2562_ipfrun,z']= 0.69919617083066, ['map,0,spprtFootMod,g2562_ipfrun,x']= 0.28413122051332, ['map,0,spprtFootMod,g2562_ipfrun,y']= 0.76952886980216, ['map,0,spprtFootMod,g2562_ipfrun,z']= 0.27481559253022, ['map,1,spprtFootMod,g2562_ipfrun,x']= -0.95491002629656, ['map,1,spprtFootMod,g2562_ipfrun,y']= -0.40651576708752, ['map,1,spprtFootMod,g2562_ipfrun,z']= -0.17394409360123, ['map,2,spprtFootMod,g2562_ipfrun,x']= 0.44380221332716, ['map,2,spprtFootMod,g2562_ipfrun,y']= -1.2277711532558, ['map,2,spprtFootMod,g2562_ipfrun,z']= 1.0157415444055, })

	--iter:565 bestfvever:245625.00049674
	accumulate({['map,0,swingFootMod,g2562_ipfrun,x']= -0.11315872986333, ['map,0,swingFootMod,g2562_ipfrun,y']= -0.13673282658941, ['map,0,swingFootMod,g2562_ipfrun,z']= 0.16351793702893, ['map,1,swingFootMod,g2562_ipfrun,x']= 0.0079073582094315, ['map,1,swingFootMod,g2562_ipfrun,y']= -0.032504128393302, ['map,1,swingFootMod,g2562_ipfrun,z']= -0.18788686380251, ['map,2,swingFootMod,g2562_ipfrun,x']= -0.16391797176979, ['map,2,swingFootMod,g2562_ipfrun,y']= -0.0083292323913452, ['map,2,swingFootMod,g2562_ipfrun,z']= -0.071132823942115, ['map,0,spprtFootMod,g2562_ipfrun,x']= -0.022946305924233, ['map,0,spprtFootMod,g2562_ipfrun,y']= -0.039477227192641, ['map,0,spprtFootMod,g2562_ipfrun,z']= 0.11499841300486, ['map,1,spprtFootMod,g2562_ipfrun,x']= 0.0075559294454451, ['map,1,spprtFootMod,g2562_ipfrun,y']= 0.053164282471489, ['map,1,spprtFootMod,g2562_ipfrun,z']= -0.13660309819696, ['map,2,spprtFootMod,g2562_ipfrun,x']= 0.14584325329376, ['map,2,spprtFootMod,g2562_ipfrun,y']= 0.057072303245799, ['map,2,spprtFootMod,g2562_ipfrun,z']= 0.24930446823262, })

elseif g_mode=='a_.01_mscl_2x_4' then
	useCases.g2562_ipfrun.aObjWeight = .01*useCases.g2562_ipfrun.aObjWeight
	useCases.g2562_ipfrun.initMsclForceScale=2

	useCases.g2562_ipfrun.ddqObjWeight=1000*(25-7)
	useCases.g2562_ipfrun.lambdaObjWeight=.01
	useCases.g2562_ipfrun.momentumWeight=100
	useCases.g2562_ipfrun.EEobjWeight=200

	----iter:444 bestfvever:783750.00018781
	--accumulate({['map,0,swingFootMod,g2562_ipfrun,x']= -0.059990658818723, ['map,0,swingFootMod,g2562_ipfrun,y']= 0.12238350063086, ['map,0,swingFootMod,g2562_ipfrun,z']= -0.33598805193117, ['map,1,swingFootMod,g2562_ipfrun,x']= -0.081945407635181, ['map,1,swingFootMod,g2562_ipfrun,y']= -0.49326411809863, ['map,1,swingFootMod,g2562_ipfrun,z']= 0.064241847182152, ['map,2,swingFootMod,g2562_ipfrun,x']= 1.2802959983534, ['map,2,swingFootMod,g2562_ipfrun,y']= 0.019148004782251, ['map,2,swingFootMod,g2562_ipfrun,z']= -0.51230489106376, ['map,0,spprtFootMod,g2562_ipfrun,x']= 0.012388912813102, ['map,0,spprtFootMod,g2562_ipfrun,y']= -0.17065246400937, ['map,0,spprtFootMod,g2562_ipfrun,z']= 0.20608338057677, ['map,1,spprtFootMod,g2562_ipfrun,x']= -0.059696328096023, ['map,1,spprtFootMod,g2562_ipfrun,y']= 0.18757043000813, ['map,1,spprtFootMod,g2562_ipfrun,z']= -0.52095564845807, ['map,2,spprtFootMod,g2562_ipfrun,x']= -0.90568217686788, ['map,2,spprtFootMod,g2562_ipfrun,y']= -0.29582149806189, ['map,2,spprtFootMod,g2562_ipfrun,z']= 0.47111438807073, })

	--iter:416 bestfvever:176875.00002479
	accumulate({['map,0,swingFootMod,g2562_ipfrun,x']= -0.26746802511216, ['map,0,swingFootMod,g2562_ipfrun,y']= -0.17841052900168, ['map,0,swingFootMod,g2562_ipfrun,z']= 0.14269491174342, ['map,1,swingFootMod,g2562_ipfrun,x']= -0.17294768623597, ['map,1,swingFootMod,g2562_ipfrun,y']= 0.68713713370864, ['map,1,swingFootMod,g2562_ipfrun,z']= 0.58511157803284, ['map,2,swingFootMod,g2562_ipfrun,x']= 0.75749186543134, ['map,2,swingFootMod,g2562_ipfrun,y']= 1.036980092975, ['map,2,swingFootMod,g2562_ipfrun,z']= -0.64697639797718, ['map,0,spprtFootMod,g2562_ipfrun,x']= 0.14352147638011, ['map,0,spprtFootMod,g2562_ipfrun,y']= 0.61995837567529, ['map,0,spprtFootMod,g2562_ipfrun,z']= -0.35320803641786, ['map,1,spprtFootMod,g2562_ipfrun,x']= 0.19108806924653, ['map,1,spprtFootMod,g2562_ipfrun,y']= -0.58479484197424, ['map,1,spprtFootMod,g2562_ipfrun,z']= 0.22517861991867, ['map,2,spprtFootMod,g2562_ipfrun,x']= -0.71951173337646, ['map,2,spprtFootMod,g2562_ipfrun,y']= -0.1161729961016, ['map,2,spprtFootMod,g2562_ipfrun,z']= -0.52175839853191, })

	useCases.g2562_ipfrun.endSegW=40
	useCases.g2562_ipfrun.prec=.1

	--iter:364 bestfvever:174375.00002484
	accumulate({['map,0,swingFootMod,g2562_ipfrun,x']= -0.30428865922015, ['map,0,swingFootMod,g2562_ipfrun,y']= -0.12673445680634, ['map,0,swingFootMod,g2562_ipfrun,z']= 0.14656279768671, ['map,1,swingFootMod,g2562_ipfrun,x']= -0.057911192203201, ['map,1,swingFootMod,g2562_ipfrun,y']= 0.60114750094017, ['map,1,swingFootMod,g2562_ipfrun,z']= 0.62575174285175, ['map,2,swingFootMod,g2562_ipfrun,x']= 0.8286706539239, ['map,2,swingFootMod,g2562_ipfrun,y']= 1.0580625138537, ['map,2,swingFootMod,g2562_ipfrun,z']= -0.56814417528934, ['map,0,spprtFootMod,g2562_ipfrun,x']= 0.14491408567316, ['map,0,spprtFootMod,g2562_ipfrun,y']= 0.57160014738445, ['map,0,spprtFootMod,g2562_ipfrun,z']= -0.36259300275207, ['map,1,spprtFootMod,g2562_ipfrun,x']= 0.17415477118333, ['map,1,spprtFootMod,g2562_ipfrun,y']= -0.64371842798167, ['map,1,spprtFootMod,g2562_ipfrun,z']= 0.21745865027617, ['map,2,spprtFootMod,g2562_ipfrun,x']= -0.66037060070421, ['map,2,spprtFootMod,g2562_ipfrun,y']= -0.19227443152222, ['map,2,spprtFootMod,g2562_ipfrun,z']= -0.4807097627107, })

elseif g_mode=='a_.01_mscl_2x_5' then
	useCases.g2562_ipfrun.aObjWeight = .01*useCases.g2562_ipfrun.aObjWeight
	useCases.g2562_ipfrun.initMsclForceScale=2

	useCases.g2562_ipfrun.ddqObjWeight=500*(25-7)
	useCases.g2562_ipfrun.lambdaObjWeight=.01
	useCases.g2562_ipfrun.momentumWeight=10
	useCases.g2562_ipfrun.EEobjWeight=200

	--done!
	--iter:438 bestfvever:176250.00002389
	accumulate({['map,0,swingFootMod,g2562_ipfrun,x']= 0.48716800886564, ['map,0,swingFootMod,g2562_ipfrun,y']= -0.17474581592461, ['map,0,swingFootMod,g2562_ipfrun,z']= -0.072671280002036, ['map,1,swingFootMod,g2562_ipfrun,x']= -0.75444187983136, ['map,1,swingFootMod,g2562_ipfrun,y']= 0.16929266938655, ['map,1,swingFootMod,g2562_ipfrun,z']= -0.022269784485577, ['map,2,swingFootMod,g2562_ipfrun,x']= 0.97750521770622, ['map,2,swingFootMod,g2562_ipfrun,y']= 1.2897678331522, ['map,2,swingFootMod,g2562_ipfrun,z']= 0.038132397379213, ['map,0,spprtFootMod,g2562_ipfrun,x']= 0.48194597473069, ['map,0,spprtFootMod,g2562_ipfrun,y']= 0.36245016736701, ['map,0,spprtFootMod,g2562_ipfrun,z']= 0.16956673146288, ['map,1,spprtFootMod,g2562_ipfrun,x']= 0.25187247562675, ['map,1,spprtFootMod,g2562_ipfrun,y']= 0.89591667352316, ['map,1,spprtFootMod,g2562_ipfrun,z']= 0.023030862707135, ['map,2,spprtFootMod,g2562_ipfrun,x']= -0.95786494419055, ['map,2,spprtFootMod,g2562_ipfrun,y']= -0.23782074304522, ['map,2,spprtFootMod,g2562_ipfrun,z']= -0.15381458304491, })

	useCases.g2562_ipfrun.prec=.05

	--iter:374 bestfvever:2.1346816170105e-05
	accumulate({['map,0,swingFootMod,g2562_ipfrun,x']= 0.48612443100111, ['map,0,swingFootMod,g2562_ipfrun,y']= -0.16875208822758, ['map,0,swingFootMod,g2562_ipfrun,z']= -0.06363417055741, ['map,1,swingFootMod,g2562_ipfrun,x']= -0.76117068713442, ['map,1,swingFootMod,g2562_ipfrun,y']= 0.15694631267824, ['map,1,swingFootMod,g2562_ipfrun,z']= -0.0020020423022582, ['map,2,swingFootMod,g2562_ipfrun,x']= 0.97964930371198, ['map,2,swingFootMod,g2562_ipfrun,y']= 1.2777398358614, ['map,2,swingFootMod,g2562_ipfrun,z']= 0.021510526032292, ['map,0,spprtFootMod,g2562_ipfrun,x']= 0.46920952814359, ['map,0,spprtFootMod,g2562_ipfrun,y']= 0.35797602401926, ['map,0,spprtFootMod,g2562_ipfrun,z']= 0.17679505310162, ['map,1,spprtFootMod,g2562_ipfrun,x']= 0.26143832675584, ['map,1,spprtFootMod,g2562_ipfrun,y']= 0.91191329950625, ['map,1,spprtFootMod,g2562_ipfrun,z']= 0.011624563340656, ['map,2,spprtFootMod,g2562_ipfrun,x']= -0.96203482909531, ['map,2,spprtFootMod,g2562_ipfrun,y']= -0.23275813384331, ['map,2,spprtFootMod,g2562_ipfrun,z']= -0.15137231871047, })

	--iter:629 bestfvever:146250.00010111
	accumulate({['map,0,swingFootMod,g2562_ipfrun,x']= 0.45880641323988, ['map,0,swingFootMod,g2562_ipfrun,y']= -0.1291111108994, ['map,0,swingFootMod,g2562_ipfrun,z']= -0.096704761784029, ['map,1,swingFootMod,g2562_ipfrun,x']= -0.778971945004, ['map,1,swingFootMod,g2562_ipfrun,y']= 0.15637120345237, ['map,1,swingFootMod,g2562_ipfrun,z']= -0.002428359677106, ['map,2,swingFootMod,g2562_ipfrun,x']= 0.94512143881308, ['map,2,swingFootMod,g2562_ipfrun,y']= 1.3414534628463, ['map,2,swingFootMod,g2562_ipfrun,z']= 0.03186792034512, ['map,0,spprtFootMod,g2562_ipfrun,x']= 0.46149881552859, ['map,0,spprtFootMod,g2562_ipfrun,y']= 0.31105231223101, ['map,0,spprtFootMod,g2562_ipfrun,z']= 0.088967688262173, ['map,1,spprtFootMod,g2562_ipfrun,x']= 0.35554984332219, ['map,1,spprtFootMod,g2562_ipfrun,y']= 0.82320128914269, ['map,1,spprtFootMod,g2562_ipfrun,z']= -0.034471652684089, ['map,2,spprtFootMod,g2562_ipfrun,x']= -0.93081078078436, ['map,2,spprtFootMod,g2562_ipfrun,y']= -0.20002095602176, ['map,2,spprtFootMod,g2562_ipfrun,z']= -0.14225804133755, })

	useCases.g2562_ipfrun.prec=.1

	--iter:589 bestfvever:2.16198822097e-05
	accumulate({['map,0,swingFootMod,g2562_ipfrun,x']= 0.3944411228973, ['map,0,swingFootMod,g2562_ipfrun,y']= -0.11809504514905, ['map,0,swingFootMod,g2562_ipfrun,z']= -0.093792588350769, ['map,1,swingFootMod,g2562_ipfrun,x']= -0.83227083748613, ['map,1,swingFootMod,g2562_ipfrun,y']= 0.16251670768622, ['map,1,swingFootMod,g2562_ipfrun,z']= 0.043961073076989, ['map,2,swingFootMod,g2562_ipfrun,x']= 0.94627765826337, ['map,2,swingFootMod,g2562_ipfrun,y']= 1.2809225318562, ['map,2,swingFootMod,g2562_ipfrun,z']= -0.0015565409999054, ['map,0,spprtFootMod,g2562_ipfrun,x']= 0.49519941017224, ['map,0,spprtFootMod,g2562_ipfrun,y']= 0.32546710706594, ['map,0,spprtFootMod,g2562_ipfrun,z']= 0.079098081743639, ['map,1,spprtFootMod,g2562_ipfrun,x']= 0.3535990633208, ['map,1,spprtFootMod,g2562_ipfrun,y']= 0.8571082599681, ['map,1,spprtFootMod,g2562_ipfrun,z']= -0.080953406766962, ['map,2,spprtFootMod,g2562_ipfrun,x']= -0.94366766904951, ['map,2,spprtFootMod,g2562_ipfrun,y']= -0.19178335199383, ['map,2,spprtFootMod,g2562_ipfrun,z']= -0.14950665995427, })

	useCases.g2562_ipfrun.endSegW=60

	--good
	--iter:546 bestfvever:315000.00002067
	accumulate({['map,0,swingFootMod,g2562_ipfrun,x']= 0.40305775483647, ['map,0,swingFootMod,g2562_ipfrun,y']= -0.075859023567077, ['map,0,swingFootMod,g2562_ipfrun,z']= -0.13372733048381, ['map,1,swingFootMod,g2562_ipfrun,x']= -0.81467878250757, ['map,1,swingFootMod,g2562_ipfrun,y']= 0.15746815511797, ['map,1,swingFootMod,g2562_ipfrun,z']= 0.0656094906898, ['map,2,swingFootMod,g2562_ipfrun,x']= 0.94888745656686, ['map,2,swingFootMod,g2562_ipfrun,y']= 1.1840349192741, ['map,2,swingFootMod,g2562_ipfrun,z']= 0.013591621538925, ['map,0,spprtFootMod,g2562_ipfrun,x']= 0.43394522347498, ['map,0,spprtFootMod,g2562_ipfrun,y']= 0.32898887112282, ['map,0,spprtFootMod,g2562_ipfrun,z']= 0.050391684867514, ['map,1,spprtFootMod,g2562_ipfrun,x']= 0.31746514889784, ['map,1,spprtFootMod,g2562_ipfrun,y']= 0.84478847895362, ['map,1,spprtFootMod,g2562_ipfrun,z']= -0.074300114391392, ['map,2,spprtFootMod,g2562_ipfrun,x']= -0.94886271104624, ['map,2,spprtFootMod,g2562_ipfrun,y']= -0.2349346417135, ['map,2,spprtFootMod,g2562_ipfrun,z']= -0.1351473295722, })

	useCases.g2562_ipfrun.prec=.05

	----iter:538 bestfvever:292500.00003304
	--accumulate({['map,0,swingFootMod,g2562_ipfrun,x']= 0.39559066075605, ['map,0,swingFootMod,g2562_ipfrun,y']= -0.068986034803433, ['map,0,swingFootMod,g2562_ipfrun,z']= -0.13078316928222, ['map,1,swingFootMod,g2562_ipfrun,x']= -0.84680219157237, ['map,1,swingFootMod,g2562_ipfrun,y']= 0.14743510156225, ['map,1,swingFootMod,g2562_ipfrun,z']= 0.074436597297645, ['map,2,swingFootMod,g2562_ipfrun,x']= 0.94683955952752, ['map,2,swingFootMod,g2562_ipfrun,y']= 1.2093430246369, ['map,2,swingFootMod,g2562_ipfrun,z']= 0.012307500518996, ['map,0,spprtFootMod,g2562_ipfrun,x']= 0.45635665729906, ['map,0,spprtFootMod,g2562_ipfrun,y']= 0.31996592145387, ['map,0,spprtFootMod,g2562_ipfrun,z']= 0.042084256352208, ['map,1,spprtFootMod,g2562_ipfrun,x']= 0.29727672215835, ['map,1,spprtFootMod,g2562_ipfrun,y']= 0.82073737727967, ['map,1,spprtFootMod,g2562_ipfrun,z']= -0.074687730900043, ['map,2,spprtFootMod,g2562_ipfrun,x']= -0.95338521437762, ['map,2,spprtFootMod,g2562_ipfrun,y']= -0.24214824784905, ['map,2,spprtFootMod,g2562_ipfrun,z']= -0.12593604314921, })

	----iter:300 bestfvever:295625.00003175
	--accumulate({['map,0,swingFootMod,g2562_ipfrun,x']= 0.42867349505452, ['map,0,swingFootMod,g2562_ipfrun,y']= -0.039841250904318, ['map,0,swingFootMod,g2562_ipfrun,z']= -0.10834151013843, ['map,1,swingFootMod,g2562_ipfrun,x']= -0.82730961307327, ['map,1,swingFootMod,g2562_ipfrun,y']= 0.14800861176006, ['map,1,swingFootMod,g2562_ipfrun,z']= 0.063229384808026, ['map,2,swingFootMod,g2562_ipfrun,x']= 0.94992161981428, ['map,2,swingFootMod,g2562_ipfrun,y']= 1.2078433256882, ['map,2,swingFootMod,g2562_ipfrun,z']= -0.0040235763542904, ['map,0,spprtFootMod,g2562_ipfrun,x']= 0.44833327155791, ['map,0,spprtFootMod,g2562_ipfrun,y']= 0.29120252626833, ['map,0,spprtFootMod,g2562_ipfrun,z']= 0.053633452493656, ['map,1,spprtFootMod,g2562_ipfrun,x']= 0.28113601458787, ['map,1,spprtFootMod,g2562_ipfrun,y']= 0.82329899472811, ['map,1,spprtFootMod,g2562_ipfrun,z']= -0.064354814779088, ['map,2,spprtFootMod,g2562_ipfrun,x']= -0.95186964348495, ['map,2,spprtFootMod,g2562_ipfrun,y']= -0.24362192384554, ['map,2,spprtFootMod,g2562_ipfrun,z']= -0.13067417764652, })


elseif g_mode=='a_.01_mscl_2x_6' then
	useCases.g2562_ipfrun.aObjWeight = .01*useCases.g2562_ipfrun.aObjWeight
	useCases.g2562_ipfrun.initMsclForceScale=2

	useCases.g2562_ipfrun.ddqObjWeight=50*(25-7)
	useCases.g2562_ipfrun.lambdaObjWeight=.01
	useCases.g2562_ipfrun.momentumWeight=100
	useCases.g2562_ipfrun.EEobjWeight=200

	----iter:767 bestfvever:765000.00030165
	--accumulate({['map,0,swingFootMod,g2562_ipfrun,x']= -0.61830164226872, ['map,0,swingFootMod,g2562_ipfrun,y']= -0.20991284643679, ['map,0,swingFootMod,g2562_ipfrun,z']= -0.6876134979215, ['map,1,swingFootMod,g2562_ipfrun,x']= 0.049962791076725, ['map,1,swingFootMod,g2562_ipfrun,y']= -0.15162032263621, ['map,1,swingFootMod,g2562_ipfrun,z']= 0.26248365531997, ['map,2,swingFootMod,g2562_ipfrun,x']= 1.2070445232338, ['map,2,swingFootMod,g2562_ipfrun,y']= 0.71630991459959, ['map,2,swingFootMod,g2562_ipfrun,z']= 0.21554604282118, ['map,0,spprtFootMod,g2562_ipfrun,x']= 0.49448197716201, ['map,0,spprtFootMod,g2562_ipfrun,y']= 0.082161470837103, ['map,0,spprtFootMod,g2562_ipfrun,z']= 0.36770110821695, ['map,1,spprtFootMod,g2562_ipfrun,x']= 0.44326737423118, ['map,1,spprtFootMod,g2562_ipfrun,y']= 0.092687574333597, ['map,1,spprtFootMod,g2562_ipfrun,z']= -0.66955549643914, ['map,2,spprtFootMod,g2562_ipfrun,x']= -0.17092852177176, ['map,2,spprtFootMod,g2562_ipfrun,y']= 0.15433869362747, ['map,2,spprtFootMod,g2562_ipfrun,z']= -0.11060779718431, })

	--iter:420 bestfvever:193125.00004563
	accumulate({['map,0,swingFootMod,g2562_ipfrun,x']= -1.313960167154, ['map,0,swingFootMod,g2562_ipfrun,y']= 0.20300228838169, ['map,0,swingFootMod,g2562_ipfrun,z']= -0.18151675229707, ['map,1,swingFootMod,g2562_ipfrun,x']= 0.22153303326758, ['map,1,swingFootMod,g2562_ipfrun,y']= 0.20092841160165, ['map,1,swingFootMod,g2562_ipfrun,z']= 0.45747349773258, ['map,2,swingFootMod,g2562_ipfrun,x']= 0.28812210394106, ['map,2,swingFootMod,g2562_ipfrun,y']= 0.30396700297254, ['map,2,swingFootMod,g2562_ipfrun,z']= -0.093647476776729, ['map,0,spprtFootMod,g2562_ipfrun,x']= -0.18736733328313, ['map,0,spprtFootMod,g2562_ipfrun,y']= 0.68087565808857, ['map,0,spprtFootMod,g2562_ipfrun,z']= -0.65838519656666, ['map,1,spprtFootMod,g2562_ipfrun,x']= 0.046148393488882, ['map,1,spprtFootMod,g2562_ipfrun,y']= -0.27046471592289, ['map,1,spprtFootMod,g2562_ipfrun,z']= 0.035184239721379, ['map,2,spprtFootMod,g2562_ipfrun,x']= 0.54745964199775, ['map,2,spprtFootMod,g2562_ipfrun,y']= -0.43563654799732, ['map,2,spprtFootMod,g2562_ipfrun,z']= 0.61950490990592, })

elseif g_mode=='a_.01_mscl_2x_7' then
	useCases.g2562_ipfrun.aObjWeight = .01*useCases.g2562_ipfrun.aObjWeight
	useCases.g2562_ipfrun.initMsclForceScale=2

	useCases.g2562_ipfrun.ddqObjWeight=500*(25-7)
	useCases.g2562_ipfrun.lambdaObjWeight=.01
	useCases.g2562_ipfrun.momentumWeight=200
	useCases.g2562_ipfrun.EEobjWeight=200

	----iter:728 bestfvever:786875.00005449
	--accumulate({['map,0,swingFootMod,g2562_ipfrun,x']= -0.40717066769587, ['map,0,swingFootMod,g2562_ipfrun,y']= -0.27635564913099, ['map,0,swingFootMod,g2562_ipfrun,z']= 0.029639019375237, ['map,1,swingFootMod,g2562_ipfrun,x']= -0.058749812958779, ['map,1,swingFootMod,g2562_ipfrun,y']= -0.055962942225493, ['map,1,swingFootMod,g2562_ipfrun,z']= -0.55915806172726, ['map,2,swingFootMod,g2562_ipfrun,x']= 1.6151841663317, ['map,2,swingFootMod,g2562_ipfrun,y']= 0.55015514341601, ['map,2,swingFootMod,g2562_ipfrun,z']= 0.56330031807456, ['map,0,spprtFootMod,g2562_ipfrun,x']= 0.30411773852578, ['map,0,spprtFootMod,g2562_ipfrun,y']= 0.056424675155125, ['map,0,spprtFootMod,g2562_ipfrun,z']= 0.036041642437563, ['map,1,spprtFootMod,g2562_ipfrun,x']= -0.070307365684515, ['map,1,spprtFootMod,g2562_ipfrun,y']= 0.10028355371473, ['map,1,spprtFootMod,g2562_ipfrun,z']= 0.029469327189777, ['map,2,spprtFootMod,g2562_ipfrun,x']= -0.55896501038207, ['map,2,spprtFootMod,g2562_ipfrun,y']= -0.28001881709722, ['map,2,spprtFootMod,g2562_ipfrun,z']= 0.12109517653508, })

	--iter:415 bestfvever:198125.00003668
	accumulate({['map,0,swingFootMod,g2562_ipfrun,x']= -1.0918686915631, ['map,0,swingFootMod,g2562_ipfrun,y']= -0.52359399871017, ['map,0,swingFootMod,g2562_ipfrun,z']= 0.1567183957707, ['map,1,swingFootMod,g2562_ipfrun,x']= -0.0052449299010686, ['map,1,swingFootMod,g2562_ipfrun,y']= 0.050799711430933, ['map,1,swingFootMod,g2562_ipfrun,z']= -0.042200056724548, ['map,2,swingFootMod,g2562_ipfrun,x']= 0.39724912080782, ['map,2,swingFootMod,g2562_ipfrun,y']= 1.2935427606669, ['map,2,swingFootMod,g2562_ipfrun,z']= 0.43398789075215, ['map,0,spprtFootMod,g2562_ipfrun,x']= 0.62690704919896, ['map,0,spprtFootMod,g2562_ipfrun,y']= 1.0096296598937, ['map,0,spprtFootMod,g2562_ipfrun,z']= -1.0398922951163, ['map,1,spprtFootMod,g2562_ipfrun,x']= 0.015410866752321, ['map,1,spprtFootMod,g2562_ipfrun,y']= -0.035352349468061, ['map,1,spprtFootMod,g2562_ipfrun,z']= -0.1844796808815, ['map,2,spprtFootMod,g2562_ipfrun,x']= 0.62141666693531, ['map,2,spprtFootMod,g2562_ipfrun,y']= -0.8754083178767, ['map,2,spprtFootMod,g2562_ipfrun,z']= 0.9175882149568, })

elseif g_mode=='a_.01_mscl_2x_8' then
	useCases.g2562_ipfrun.aObjWeight = .01*useCases.g2562_ipfrun.aObjWeight
	useCases.g2562_ipfrun.initMsclForceScale=2

	useCases.g2562_ipfrun.ddqObjWeight=500*(25-7)
	useCases.g2562_ipfrun.lambdaObjWeight=.01
	useCases.g2562_ipfrun.momentumWeight=100
	useCases.g2562_ipfrun.EEobjWeight=300

	----iter:694 bestfvever:802500.00004289
	--accumulate({['map,0,swingFootMod,g2562_ipfrun,x']= -0.14922064691742, ['map,0,swingFootMod,g2562_ipfrun,y']= -0.18091130627995, ['map,0,swingFootMod,g2562_ipfrun,z']= -0.19235082012322, ['map,1,swingFootMod,g2562_ipfrun,x']= 0.2070868829472, ['map,1,swingFootMod,g2562_ipfrun,y']= 0.021200309475695, ['map,1,swingFootMod,g2562_ipfrun,z']= 0.16873024893751, ['map,2,swingFootMod,g2562_ipfrun,x']= 0.30268413553305, ['map,2,swingFootMod,g2562_ipfrun,y']= -0.087139752064777, ['map,2,swingFootMod,g2562_ipfrun,z']= -0.15890770568204, ['map,0,spprtFootMod,g2562_ipfrun,x']= 0.2975505394724, ['map,0,spprtFootMod,g2562_ipfrun,y']= -0.00862396536297, ['map,0,spprtFootMod,g2562_ipfrun,z']= 0.1647475587456, ['map,1,spprtFootMod,g2562_ipfrun,x']= -0.156616119977, ['map,1,spprtFootMod,g2562_ipfrun,y']= -0.05966845113948, ['map,1,spprtFootMod,g2562_ipfrun,z']= -0.089768347562121, ['map,2,spprtFootMod,g2562_ipfrun,x']= -0.21283607319203, ['map,2,spprtFootMod,g2562_ipfrun,y']= -0.096485268612085, ['map,2,spprtFootMod,g2562_ipfrun,z']= 0.079572553072776, })

	--iter:425 bestfvever:206250.00004748
	accumulate({['map,0,swingFootMod,g2562_ipfrun,x']= -0.31475221225845, ['map,0,swingFootMod,g2562_ipfrun,y']= 0.38973508371827, ['map,0,swingFootMod,g2562_ipfrun,z']= 0.31300088534146, ['map,1,swingFootMod,g2562_ipfrun,x']= -0.09950753116229, ['map,1,swingFootMod,g2562_ipfrun,y']= -0.51940708332581, ['map,1,swingFootMod,g2562_ipfrun,z']= 0.36692074121259, ['map,2,swingFootMod,g2562_ipfrun,x']= 0.11935744014633, ['map,2,swingFootMod,g2562_ipfrun,y']= -0.065908557936957, ['map,2,swingFootMod,g2562_ipfrun,z']= -0.091562193392736, ['map,0,spprtFootMod,g2562_ipfrun,x']= 0.21298933951153, ['map,0,spprtFootMod,g2562_ipfrun,y']= 0.22209011812125, ['map,0,spprtFootMod,g2562_ipfrun,z']= 0.11786855182683, ['map,1,spprtFootMod,g2562_ipfrun,x']= -0.069048422202712, ['map,1,spprtFootMod,g2562_ipfrun,y']= -0.21795899960521, ['map,1,spprtFootMod,g2562_ipfrun,z']= 0.1432294989703, ['map,2,spprtFootMod,g2562_ipfrun,x']= -0.27416980457864, ['map,2,spprtFootMod,g2562_ipfrun,y']= -0.41152647905937, ['map,2,spprtFootMod,g2562_ipfrun,z']= 0.13776470167632, })

elseif g_mode=='a_.01_mscl_2x_5_nost' then
	useCases.g2562_ipfrun.aObjWeight = .01*useCases.g2562_ipfrun.aObjWeight
	useCases.g2562_ipfrun.initMsclForceScale=2
	useCases.g2562_ipfrun.noStride = true

	useCases.g2562_ipfrun.ddqObjWeight=500*(25-7)
	useCases.g2562_ipfrun.lambdaObjWeight=.01
	useCases.g2562_ipfrun.momentumWeight=10
	useCases.g2562_ipfrun.EEobjWeight=200

	--iter:528 bestfvever:247500.00041197
	accumulate({['map,0,swingFootMod,g2562_ipfrun,x']= 0.0088198645364328, ['map,0,swingFootMod,g2562_ipfrun,y']= -0.13083502616087, ['map,0,swingFootMod,g2562_ipfrun,z']= 0.048208871307973, ['map,1,swingFootMod,g2562_ipfrun,x']= -0.18063046227618, ['map,1,swingFootMod,g2562_ipfrun,y']= 0.13116793481868, ['map,1,swingFootMod,g2562_ipfrun,z']= -0.0046635207674636, ['map,2,swingFootMod,g2562_ipfrun,x']= 0.079849115353032, ['map,2,swingFootMod,g2562_ipfrun,y']= 0.080073044205646, ['map,2,swingFootMod,g2562_ipfrun,z']= -0.04856940789467, ['map,0,spprtFootMod,g2562_ipfrun,x']= 0.012217941530406, ['map,0,spprtFootMod,g2562_ipfrun,y']= -0.060308903663192, ['map,0,spprtFootMod,g2562_ipfrun,z']= 0.12461472737465, ['map,1,spprtFootMod,g2562_ipfrun,x']= -0.11065971099347, ['map,1,spprtFootMod,g2562_ipfrun,y']= 0.069732196178812, ['map,1,spprtFootMod,g2562_ipfrun,z']= -0.057805686759341, ['map,2,spprtFootMod,g2562_ipfrun,x']= -0.05993695214388, ['map,2,spprtFootMod,g2562_ipfrun,y']= 0.042199658293342, ['map,2,spprtFootMod,g2562_ipfrun,z']= -0.087260714653787, })

end
----------------------------

useCases.unmapControlParam(useCases.g2562_ipfrun)
end


