package.path=package.path..";../Samples/ysscripts/lib/?.lua" --;"..package.path
require("utilfunc")

package.path=package.path..";../Samples/ysscripts/samples/?.lua" --;"..package.path
require("useCaseMuscle_gait1956_6steps")



useCases.g2562_gait=deepCopyTable(useCases.gait1956_6steps)

useCases.g2562_gait.optimizerMethod='Optimizer.methods.CMAes_ys'

--useCases.g2562_gait.endSegW=10
useCases.g2562_gait.endSegW=15
useCases.g2562_gait.prec=.2
--useCases.g2562_gait.endSegW=20
--useCases.g2562_gait.prec=.05

useCases.g2562_gait.modelName='g2562_gait'
useCases.g2562_gait.grpName='g2562_gait'
useCases.g2562_gait.grpNames={'g2562_gait'}

--useCases.g2562_gait.ddqObjWeight=100000000*25
--useCases.g2562_gait.aObjWeight=10000000000*62
--useCases.g2562_gait.lambdaObjWeight=1000
--useCases.g2562_gait.EEobjWeight=100000000
--useCases.g2562_gait.EEobjWeightAngular=60000000
--useCases.g2562_gait.momentumWeight=8000000

--useCases.g2562_gait.ddqObjWeight=100000*(25-7)
--useCases.g2562_gait.aObjWeight=1000000*62
--useCases.g2562_gait.lambdaObjWeight=1
--useCases.g2562_gait.EEobjWeight=1000000
--useCases.g2562_gait.EEobjWeightAngular=100000
--useCases.g2562_gait.momentumWeight=100000

useCases.g2562_gait.ddqObjWeight=10*(25-7)
useCases.g2562_gait.aObjWeight=5000*62
useCases.g2562_gait.lambdaObjWeight=.0001
useCases.g2562_gait.EEobjWeight=100
useCases.g2562_gait.EEobjWeightAngular=10
useCases.g2562_gait.momentumWeight=10

--useCases.g2562_gait.tauObjWeight=1
--useCases.g2562_gait.initMsclForceScale=10

-- the initial pendControlParam and pendOptimizationPath can be automatically generated by using createInitialPendControlParam.lua
useCases.g2562_gait.pendControlParam=
{
['keyframe,0,pendDesiredVel,g2562_gait,l,z']=0,['keyframe,0,pendDesiredVel,g2562_gait,l,x']=1,['keyframe,0,pendDesiredVel,g2562_gait,r,z']=0,['keyframe,0,pendDesiredVel,g2562_gait,r,x']=1,['keyframe,0,pendDesiredVel,g2562_gait,L1,z']=0,['keyframe,0,pendDesiredVel,g2562_gait,L1,x']=1,['keyframe,0,pendDesiredVel,g2562_gait,R1,z']=0,['keyframe,0,pendDesiredVel,g2562_gait,R1,x']=1,['keyframe,0,pendDesiredVel,g2562_gait,L2,z']=0,['keyframe,0,pendDesiredVel,g2562_gait,L2,x']=1,['keyframe,0,pendDesiredVel,ignore,0,z']=0,['keyframe,0,pendDesiredVel,ignore,0,x']=1,['keyframe,0,pendDesiredVel,ignore,1,z']=0,['keyframe,0,pendDesiredVel,ignore,1,x']=1,
['keyframe,0,pendDesiredVel,ignore,0,x']=0.55721712382895, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.11549022684414, ['keyframe,0,pendDesiredVel,g2562_gait,l,x']=0.83765088460274, ['keyframe,0,pendDesiredVel,g2562_gait,l,z']=-0.03971153581855, ['keyframe,0,pendDesiredVel,g2562_gait,r,x']=1.0292990315838, ['keyframe,0,pendDesiredVel,g2562_gait,r,z']=0.012304645261958, ['keyframe,0,pendDesiredVel,g2562_gait,L1,x']=1.0830140604807, ['keyframe,0,pendDesiredVel,g2562_gait,L1,z']=0.021311276252793, ['keyframe,0,pendDesiredVel,g2562_gait,R1,x']=1.0448069373172, ['keyframe,0,pendDesiredVel,g2562_gait,R1,z']=0.015212087553609, ['keyframe,0,pendDesiredVel,g2562_gait,L2,x']=0.99864134148705, ['keyframe,0,pendDesiredVel,g2562_gait,L2,z']=0.011195374086852, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.9726342007727, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.0046873881077062, 
['keyframe,0,pendDesiredVel,ignore,0,x']=-0.038573565913782, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.42183387297139, ['keyframe,0,pendDesiredVel,g2562_gait,l,x']=2.8733663187598, ['keyframe,0,pendDesiredVel,g2562_gait,l,z']=0.77374805250546, 
['keyframe,0,pendDesiredVel,ignore,0,x']=-0.03848565284349, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.42174541529281, ['keyframe,0,pendDesiredVel,g2562_gait,l,x']=2.8733683928023, ['keyframe,0,pendDesiredVel,g2562_gait,l,z']=0.77375288187355, 
['keyframe,0,pendDesiredVel,g2562_gait,l,x']=1.8518302499598, ['keyframe,0,pendDesiredVel,g2562_gait,l,z']=0.32721002628792, ['keyframe,0,pendDesiredVel,g2562_gait,r,x']=0.64195188458919, ['keyframe,0,pendDesiredVel,g2562_gait,r,z']=-0.23746102054191, ['keyframe,0,pendDesiredVel,g2562_gait,L1,x']=1.0569602524197, ['keyframe,0,pendDesiredVel,g2562_gait,L1,z']=0.0089665722850331, 
['keyframe,0,pendDesiredVel,g2562_gait,r,x']=0.65321586961613, ['keyframe,0,pendDesiredVel,g2562_gait,r,z']=-0.23322355700538, ['keyframe,0,pendDesiredVel,g2562_gait,L1,x']=1.1600582644838, ['keyframe,0,pendDesiredVel,g2562_gait,L1,z']=0.16409120361367, ['keyframe,0,pendDesiredVel,g2562_gait,R1,x']=1.0469024908636, ['keyframe,0,pendDesiredVel,g2562_gait,R1,z']=0.021499874539069, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.057317680328125, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.37352874903012, ['keyframe,0,pendDesiredVel,g2562_gait,l,x']=1.688193340133, ['keyframe,0,pendDesiredVel,g2562_gait,l,z']=0.33135464415606, ['keyframe,0,pendDesiredVel,g2562_gait,r,x']=0.56260872770468, ['keyframe,0,pendDesiredVel,g2562_gait,r,z']=-0.29475535050687, 
['keyframe,0,pendDesiredVel,g2562_gait,l,x']=1.6732338838641, ['keyframe,0,pendDesiredVel,g2562_gait,l,z']=0.31227141866769, ['keyframe,0,pendDesiredVel,g2562_gait,r,x']=0.72633156918842, ['keyframe,0,pendDesiredVel,g2562_gait,r,z']=-0.30056568375898, ['keyframe,0,pendDesiredVel,g2562_gait,L1,x']=1.1885783553992, ['keyframe,0,pendDesiredVel,g2562_gait,L1,z']=0.18162859438481, 
['keyframe,0,pendDesiredVel,g2562_gait,r,x']=0.72682249891879, ['keyframe,0,pendDesiredVel,g2562_gait,r,z']=-0.27195354224673, ['keyframe,0,pendDesiredVel,g2562_gait,L1,x']=1.1844005645379, ['keyframe,0,pendDesiredVel,g2562_gait,L1,z']=0.21070016989902, ['keyframe,0,pendDesiredVel,g2562_gait,R1,x']=1.0436382930349, ['keyframe,0,pendDesiredVel,g2562_gait,R1,z']=0.019573432369505, 
['keyframe,0,pendDesiredVel,g2562_gait,L1,x']=1.1546812185886, ['keyframe,0,pendDesiredVel,g2562_gait,L1,z']=0.13057608466461, ['keyframe,0,pendDesiredVel,g2562_gait,R1,x']=1.0169825693409, ['keyframe,0,pendDesiredVel,g2562_gait,R1,z']=-0.031308161078641, ['keyframe,0,pendDesiredVel,g2562_gait,L2,x']=0.99332532373797, ['keyframe,0,pendDesiredVel,g2562_gait,L2,z']=0.023230828039423, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.97210147412166, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.0051664564521254, 
}
useCases.g2562_gait.pendOptimizationPath=
{
	firstFrames={1*2,39*2,77*2,115*2,153*2,191*2,229*2,266*2},
	segments={'ignore,0','g2562_gait,l','g2562_gait,r','g2562_gait,L1','g2562_gait,R1','g2562_gait,L2','ignore,1'},
}
--useCases.g2562_gait.measureOptCost=useCases.measureOptCost

useCases.g2562_gait.segmentations=
{
	g2562_gait={
		firstFrames={1*2,39*2,77*2,115*2,153*2,191*2,229*2,266*2},
		--        (blank)    L    R     L     R     L     (blank)
		names={             'l', 'r', 'L1', 'R1', 'L2',  },
		swingL={             0,   1,   0,    1,    0,    },
		swingR={             1,   0,   1,    0,    1,    },
		footRefL= "convertFromSwingL",
		footRefR= "convertFromSwingR",
		usePositionControl=false,
	},
}
useCases.g2562_gait.graphParam=
{
	g2562_gait={
		seg={            'l',  'r',  'L1', 'R1','L'},
		num_key={         3,    3,    3  ,  4,  4},
		key_first={       0,    0,    0  ,  0,  0},
		key_last={       'r', 'L1',  'R1', 'L', 'R1'},
	},
}
useCases.g2562_gait.graph=
{
	{
		"addInterpolatedSegment",
		grpName="g2562_gait",
		name="L",
		seg0={"g2562_gait", "L2"},
		seg1={"g2562_gait", "L1"},
		startWeight=0, endWeight=1
	},
	{"connectMulti", "g2562_gait", "l", "r", "L1", "R1", "L", "R1"},
	--{"initialSegment", "g2562_gait", "l"}
	{"initialSegment", "g2562_gait", "R1"}
}
useCases.g2562_gait.segNames=
{
	"l", "r", "L1", 'R1','L',
}

do 
	useCases.g2562_gait.controlParam={
		['useCases,g2562_gait,COMobjWeight']=0, 
		['useCases,g2562_gait,conservativeW']=1, 
		--['useCases,g2562_gait,contactMargin']=0.01, 
		['useCases,g2562_gait,dotMomentumScale']=0.3, 
		['useCases,g2562_gait,excludeRoot']=true, 
		['useCases,g2562_gait,headControlWeight']=0, 
		['useCases,g2562_gait,k_d_HEAD']=14, 
		['useCases,g2562_gait,k_p_HEAD']=0, 
		['useCases,g2562_gait,k_d_EE']=24, 
		['useCases,g2562_gait,k_d_momentum']=10, 
		['useCases,g2562_gait,k_p_EE']=120, 

		--['useCases,g2562_gait,maxPenetratingVel']=0, 
		['useCases,g2562_gait,momentumThr']=50, 
		['useCases,g2562_gait,noComvelDependentFootAdjustment']=true, 
		['useCases,g2562_gait,noIntersectionPrevenction']=true, 
		['useCases,g2562_gait,numericalDerivDmot']=true, 
		['useCases,g2562_gait,perClassContactMargin']=1, 
		['useCases,g2562_gait,turnGain']=10, 
		['useCases,g2562_gait,velMarginOffset']=0, 

		['useCases,g2562_gait,actuationType']      = useCases.g2562_gait.actuationType,
		['useCases,g2562_gait,k_p_ID']             = useCases.g2562_gait.k_p_ID,
		['useCases,g2562_gait,k_d_ID']             = useCases.g2562_gait.k_d_ID,
		['useCases,g2562_gait,ddqObjWeight']       = useCases.g2562_gait.ddqObjWeight,
		['useCases,g2562_gait,tauObjWeight']       = useCases.g2562_gait.tauObjWeight,
		['useCases,g2562_gait,ftObjWeight']        = useCases.g2562_gait.ftObjWeight,
		['useCases,g2562_gait,aObjWeight']         = useCases.g2562_gait.aObjWeight,
		['useCases,g2562_gait,lambdaObjWeight']    = useCases.g2562_gait.lambdaObjWeight,
		['useCases,g2562_gait,EEobjWeight']        = useCases.g2562_gait.EEobjWeight,
		['useCases,g2562_gait,EEobjWeightAngular'] = useCases.g2562_gait.EEobjWeightAngular,
		['useCases,g2562_gait,momentumWeight']     = useCases.g2562_gait.momentumWeight,
		['useCases,g2562_gait,tauMax']             = useCases.g2562_gait.tauMax,
		['useCases,g2562_gait,ftMax']              = useCases.g2562_gait.ftMax,

		--TODO_muscle
		--add 'muscle,' keys here
		
		--TODO_speed
		--LocoSynthesis.lua
		-- tt.z=tt.z+self.desiredSpeedZ
	}

	local function accumulate(cp_mod)
		local useCase=useCases.g2562_gait
		useCases.accumulate(useCase, cp_mod)
	end

	accumulate({
		------['keyframe,0,footRmod,g2562_gait,l,y']  = 0.,
		------['keyframe,1,footRmod,g2562_gait,l,y']  = 0.05,
		--['keyframe,0,footLmod,g2562_gait,r,y']  = 0.1,
		--['keyframe,1,footLmod,g2562_gait,r,y']  = 0.4,
		--['keyframe,0,footRmod,g2562_gait,L1,y'] = 0.1,
		--['keyframe,1,footRmod,g2562_gait,L1,y'] = 0.3,
		----['map,0,swingFootMod,g2562_gait,y']     = 0.2,
		----['map,1,swingFootMod,g2562_gait,y']     = 0.3,
		----['map,2,swingFootMod,g2562_gait,y']     = 0.3,

		------['keyframe,0,footLmod,g2562_gait,l,y']  = 0.,
		------['keyframe,1,footLmod,g2562_gait,l,y']  = 0.,
		----['keyframe,0,footRmod,g2562_gait,r,y']  = 0.,
		----['keyframe,1,footRmod,g2562_gait,r,y']  = -.4,
		----['keyframe,0,footLmod,g2562_gait,L1,y'] = 0.,
		----['keyframe,1,footLmod,g2562_gait,L1,y'] = -.4,
		----['map,0,spprtFootMod,g2562_gait,y']     = 0.,
		----['map,1,spprtFootMod,g2562_gait,y']     = 0.,
		----['map,2,spprtFootMod,g2562_gait,y']     = 0.,
	})
	useCases.unmapControlParam(useCases.g2562_gait)

-------------------------------------------------
if g_mode=='default' then
	--iter:319 bestfvever:8.2463207824663e-07 endSegW:10
	accumulate({['map,0,swingFootMod,g2562_gait,x']= 0.5185051216938, ['map,0,swingFootMod,g2562_gait,y']= -0.12515233658827, ['map,0,swingFootMod,g2562_gait,z']= 0.34200301462363, ['map,1,swingFootMod,g2562_gait,x']= 0.23177520699681, ['map,1,swingFootMod,g2562_gait,y']= 0.35522194975998, ['map,1,swingFootMod,g2562_gait,z']= 0.11551340003214, ['map,2,swingFootMod,g2562_gait,x']= -0.090478109104195, ['map,2,swingFootMod,g2562_gait,y']= 0.0052328002676183, ['map,2,swingFootMod,g2562_gait,z']= -0.017559451764768, ['map,0,spprtFootMod,g2562_gait,x']= -0.37974592596612, ['map,0,spprtFootMod,g2562_gait,y']= 0.086874098358192, ['map,0,spprtFootMod,g2562_gait,z']= 0.23079330688715, ['map,1,spprtFootMod,g2562_gait,x']= -0.49320282396254, ['map,1,spprtFootMod,g2562_gait,y']= -0.35343036708494, ['map,1,spprtFootMod,g2562_gait,z']= -0.13916431394847, ['map,2,spprtFootMod,g2562_gait,x']= -0.51289797996341, ['map,2,spprtFootMod,g2562_gait,y']= -0.81267696721654, ['map,2,spprtFootMod,g2562_gait,z']= 0.43182702592264, })

elseif g_mode=='a_1' then
	useCases.g2562_gait.aObjWeight = 1*useCases.g2562_gait.aObjWeight

	----iter:201 bestfvever:1.7558580596296e-06
	--accumulate({['map,0,swingFootMod,g2562_gait,x']= 0.32443897877127, ['map,0,swingFootMod,g2562_gait,y']= -0.35784596727778, ['map,0,swingFootMod,g2562_gait,z']= 0.48449436408798, ['map,1,swingFootMod,g2562_gait,x']= 0.034747853092357, ['map,1,swingFootMod,g2562_gait,y']= 0.4619823722319, ['map,1,swingFootMod,g2562_gait,z']= 0.19733423899745, ['map,2,swingFootMod,g2562_gait,x']= -0.011593015089454, ['map,2,swingFootMod,g2562_gait,y']= 0.0551172218896, ['map,2,swingFootMod,g2562_gait,z']= -0.11746621176303, ['map,0,spprtFootMod,g2562_gait,x']= -0.17295450501519, ['map,0,spprtFootMod,g2562_gait,y']= -0.22724675925231, ['map,0,spprtFootMod,g2562_gait,z']= 0.023295593398902, ['map,1,spprtFootMod,g2562_gait,x']= 1.000546230236, ['map,1,spprtFootMod,g2562_gait,y']= -0.94214461667304, ['map,1,spprtFootMod,g2562_gait,z']= -0.3033924254812, ['map,2,spprtFootMod,g2562_gait,x']= 0.049126550004965, ['map,2,spprtFootMod,g2562_gait,y']= -0.42954281107414, ['map,2,spprtFootMod,g2562_gait,z']= 0.26540166478066, })

	--iter:227 bestfvever:1.1841906337467e-06
	accumulate({['map,0,swingFootMod,g2562_gait,x']= 0.059727273178182, ['map,0,swingFootMod,g2562_gait,y']= -0.043825114993551, ['map,0,swingFootMod,g2562_gait,z']= 0.52585169413768, ['map,1,swingFootMod,g2562_gait,x']= 0.27769172595935, ['map,1,swingFootMod,g2562_gait,y']= 0.17543385922129, ['map,1,swingFootMod,g2562_gait,z']= 0.067453081370458, ['map,2,swingFootMod,g2562_gait,x']= -0.16920587643663, ['map,2,swingFootMod,g2562_gait,y']= 0.065138897938949, ['map,2,swingFootMod,g2562_gait,z']= -0.063450434820889, ['map,0,spprtFootMod,g2562_gait,x']= -0.15390328855444, ['map,0,spprtFootMod,g2562_gait,y']= -0.4432942220052, ['map,0,spprtFootMod,g2562_gait,z']= 0.26455002913335, ['map,1,spprtFootMod,g2562_gait,x']= -0.016374685778508, ['map,1,spprtFootMod,g2562_gait,y']= 0.13993437919146, ['map,1,spprtFootMod,g2562_gait,z']= -0.040261861137214, ['map,2,spprtFootMod,g2562_gait,x']= 0.13796048764855, ['map,2,spprtFootMod,g2562_gait,y']= -0.53977811514995, ['map,2,spprtFootMod,g2562_gait,z']= -0.17690872946152, })

elseif g_mode=='a_.3' then
	useCases.g2562_gait.aObjWeight = .3*useCases.g2562_gait.aObjWeight

	--iter:197 bestfvever:1.3449367275488e-06
	accumulate({['map,0,swingFootMod,g2562_gait,x']= 0.39371203601065, ['map,0,swingFootMod,g2562_gait,y']= -0.44063564824981, ['map,0,swingFootMod,g2562_gait,z']= 0.4384488367951, ['map,1,swingFootMod,g2562_gait,x']= 0.23486917994221, ['map,1,swingFootMod,g2562_gait,y']= 0.32199642944508, ['map,1,swingFootMod,g2562_gait,z']= 0.22260343740439, ['map,2,swingFootMod,g2562_gait,x']= -0.011639478442262, ['map,2,swingFootMod,g2562_gait,y']= -0.18027575396508, ['map,2,swingFootMod,g2562_gait,z']= -0.16801746892945, ['map,0,spprtFootMod,g2562_gait,x']= -0.32525145423981, ['map,0,spprtFootMod,g2562_gait,y']= -0.063696176240668, ['map,0,spprtFootMod,g2562_gait,z']= 0.010894485470655, ['map,1,spprtFootMod,g2562_gait,x']= -0.26568281757145, ['map,1,spprtFootMod,g2562_gait,y']= -0.43431856343709, ['map,1,spprtFootMod,g2562_gait,z']= -0.028148436634096, ['map,2,spprtFootMod,g2562_gait,x']= 0.45763884047667, ['map,2,spprtFootMod,g2562_gait,y']= -0.583517493539, ['map,2,spprtFootMod,g2562_gait,z']= -0.15578732898419, })

elseif g_mode=='a_.5_efcim8' then
	useCases.g2562_gait.aObjWeight = .5*useCases.g2562_gait.aObjWeight
	useCases.g2562_gait.cmaEffortDistWeight = 1e-8

	--iter:201 bestfvever:1.0317408104669e-06
	accumulate({['map,0,swingFootMod,g2562_gait,x']= 0.47821337777288, ['map,0,swingFootMod,g2562_gait,y']= -0.2862277390213, ['map,0,swingFootMod,g2562_gait,z']= 0.42608251912666, ['map,1,swingFootMod,g2562_gait,x']= 0.36193204245925, ['map,1,swingFootMod,g2562_gait,y']= 0.26633623070301, ['map,1,swingFootMod,g2562_gait,z']= 0.042975219189629, ['map,2,swingFootMod,g2562_gait,x']= -0.1664775507691, ['map,2,swingFootMod,g2562_gait,y']= 0.072993940240183, ['map,2,swingFootMod,g2562_gait,z']= 0.019567209973389, ['map,0,spprtFootMod,g2562_gait,x']= -0.72836413179531, ['map,0,spprtFootMod,g2562_gait,y']= -0.3118885306926, ['map,0,spprtFootMod,g2562_gait,z']= 0.30215451205615, ['map,1,spprtFootMod,g2562_gait,x']= 0.41270088672477, ['map,1,spprtFootMod,g2562_gait,y']= 0.15213262333125, ['map,1,spprtFootMod,g2562_gait,z']= -0.022530497858445, ['map,2,spprtFootMod,g2562_gait,x']= 0.033899994077543, ['map,2,spprtFootMod,g2562_gait,y']= -1.0365363317153, ['map,2,spprtFootMod,g2562_gait,z']= 0.25795033774095, })

elseif g_mode=='a_.5_efcim7' then
	useCases.g2562_gait.aObjWeight = .5*useCases.g2562_gait.aObjWeight
	useCases.g2562_gait.cmaEffortDistWeight = 1e-7

	--iter:193 bestfvever:3.9064552924971e-06
	accumulate({['map,0,swingFootMod,g2562_gait,x']= 0.90985470484696, ['map,0,swingFootMod,g2562_gait,y']= -0.16662816074933, ['map,0,swingFootMod,g2562_gait,z']= 0.54197472649927, ['map,1,swingFootMod,g2562_gait,x']= 0.011521716056972, ['map,1,swingFootMod,g2562_gait,y']= 0.4677093907008, ['map,1,swingFootMod,g2562_gait,z']= 0.14261032036293, ['map,2,swingFootMod,g2562_gait,x']= 0.1534518416121, ['map,2,swingFootMod,g2562_gait,y']= -0.078556488138627, ['map,2,swingFootMod,g2562_gait,z']= -0.093983203520954, ['map,0,spprtFootMod,g2562_gait,x']= -0.64514739525238, ['map,0,spprtFootMod,g2562_gait,y']= -0.081005593531058, ['map,0,spprtFootMod,g2562_gait,z']= -0.053010574101877, ['map,1,spprtFootMod,g2562_gait,x']= -0.64565407383989, ['map,1,spprtFootMod,g2562_gait,y']= -0.92664371475051, ['map,1,spprtFootMod,g2562_gait,z']= -0.23885554848491, ['map,2,spprtFootMod,g2562_gait,x']= 0.37498678586619, ['map,2,spprtFootMod,g2562_gait,y']= -0.75124394186666, ['map,2,spprtFootMod,g2562_gait,z']= 0.34404930886419, })

elseif g_mode=='a_.5' then
	useCases.g2562_gait.aObjWeight = .5*useCases.g2562_gait.aObjWeight

	----iter:209 bestfvever:5.2766314103336e-07
	--accumulate({['map,0,swingFootMod,g2562_gait,x']= 0.05868253550566, ['map,0,swingFootMod,g2562_gait,y']= -0.31304366749996, ['map,0,swingFootMod,g2562_gait,z']= 0.65358862280863, ['map,1,swingFootMod,g2562_gait,x']= 0.23130291186525, ['map,1,swingFootMod,g2562_gait,y']= 0.058725668565558, ['map,1,swingFootMod,g2562_gait,z']= -0.10312788551734, ['map,2,swingFootMod,g2562_gait,x']= -0.25413302486086, ['map,2,swingFootMod,g2562_gait,y']= 0.56586321689663, ['map,2,swingFootMod,g2562_gait,z']= 0.047073722330179, ['map,0,spprtFootMod,g2562_gait,x']= -0.12071246377831, ['map,0,spprtFootMod,g2562_gait,y']= -0.44415238906252, ['map,0,spprtFootMod,g2562_gait,z']= 0.10343192516648, ['map,1,spprtFootMod,g2562_gait,x']= 0.11644978257158, ['map,1,spprtFootMod,g2562_gait,y']= 0.34922143523193, ['map,1,spprtFootMod,g2562_gait,z']= 0.037514544156681, ['map,2,spprtFootMod,g2562_gait,x']= -0.15037280683251, ['map,2,spprtFootMod,g2562_gait,y']= -0.60033299367537, ['map,2,spprtFootMod,g2562_gait,z']= 0.019575266371119, })

	--useCases.g2562_gait.prec=.05

	----iter:89 bestfvever:5.3523714091145e-07
	--accumulate({['map,0,swingFootMod,g2562_gait,x']= 0.051475942722085, ['map,0,swingFootMod,g2562_gait,y']= -0.30660958289077, ['map,0,swingFootMod,g2562_gait,z']= 0.64179517409049, ['map,1,swingFootMod,g2562_gait,x']= 0.22133249005213, ['map,1,swingFootMod,g2562_gait,y']= 0.068597850989184, ['map,1,swingFootMod,g2562_gait,z']= -0.07772762497673, ['map,2,swingFootMod,g2562_gait,x']= -0.25726571226383, ['map,2,swingFootMod,g2562_gait,y']= 0.54602709424851, ['map,2,swingFootMod,g2562_gait,z']= 0.038115669785807, ['map,0,spprtFootMod,g2562_gait,x']= -0.12691473014344, ['map,0,spprtFootMod,g2562_gait,y']= -0.44267688307841, ['map,0,spprtFootMod,g2562_gait,z']= 0.11026322870716, ['map,1,spprtFootMod,g2562_gait,x']= 0.13110063364219, ['map,1,spprtFootMod,g2562_gait,y']= 0.35836518486687, ['map,1,spprtFootMod,g2562_gait,z']= 0.042651917150541, ['map,2,spprtFootMod,g2562_gait,x']= -0.11430037927461, ['map,2,spprtFootMod,g2562_gait,y']= -0.60279393282277, ['map,2,spprtFootMod,g2562_gait,z']= 0.019169750133, })

	--useCases.g2562_gait.endSegW=10
	--useCases.g2562_gait.prec=.1

	----iter:176 bestfvever:5.1677219501803e-07
	--accumulate({['map,0,swingFootMod,g2562_gait,x']= 0.067889013310982, ['map,0,swingFootMod,g2562_gait,y']= -0.27365179684751, ['map,0,swingFootMod,g2562_gait,z']= 0.58520712916768, ['map,1,swingFootMod,g2562_gait,x']= 0.25990309685788, ['map,1,swingFootMod,g2562_gait,y']= 0.016276593984658, ['map,1,swingFootMod,g2562_gait,z']= -0.0092883248344211, ['map,2,swingFootMod,g2562_gait,x']= -0.2667931467739, ['map,2,swingFootMod,g2562_gait,y']= 0.54411990526854, ['map,2,swingFootMod,g2562_gait,z']= -0.0013535717350773, ['map,0,spprtFootMod,g2562_gait,x']= -0.1578718857868, ['map,0,spprtFootMod,g2562_gait,y']= -0.40603946970433, ['map,0,spprtFootMod,g2562_gait,z']= 0.080341768304889, ['map,1,spprtFootMod,g2562_gait,x']= 0.079924380535526, ['map,1,spprtFootMod,g2562_gait,y']= 0.34148489050408, ['map,1,spprtFootMod,g2562_gait,z']= 0.061971439908261, ['map,2,spprtFootMod,g2562_gait,x']= -0.1486278563031, ['map,2,spprtFootMod,g2562_gait,y']= -0.63923473779607, ['map,2,spprtFootMod,g2562_gait,z']= -0.0095761375041639, })

	--useCases.g2562_gait.endSegW=20

	----iter:142 bestfvever:5.4322517936519e-07
	--accumulate({['map,0,swingFootMod,g2562_gait,x']= -0.0097028227971767, ['map,0,swingFootMod,g2562_gait,y']= -0.30368100224798, ['map,0,swingFootMod,g2562_gait,z']= 0.70898223747961, ['map,1,swingFootMod,g2562_gait,x']= 0.26188787320243, ['map,1,swingFootMod,g2562_gait,y']= 0.023798330255847, ['map,1,swingFootMod,g2562_gait,z']= 0.021143380271148, ['map,2,swingFootMod,g2562_gait,x']= -0.2848036875942, ['map,2,swingFootMod,g2562_gait,y']= 0.54853837237632, ['map,2,swingFootMod,g2562_gait,z']= 0.00045234288785123, ['map,0,spprtFootMod,g2562_gait,x']= -0.11273122810088, ['map,0,spprtFootMod,g2562_gait,y']= -0.48323825714429, ['map,0,spprtFootMod,g2562_gait,z']= 0.10451916357187, ['map,1,spprtFootMod,g2562_gait,x']= 0.11309639851547, ['map,1,spprtFootMod,g2562_gait,y']= 0.38885321399466, ['map,1,spprtFootMod,g2562_gait,z']= 0.037476504191736, ['map,2,spprtFootMod,g2562_gait,x']= -0.097595446601867, ['map,2,spprtFootMod,g2562_gait,y']= -0.67020343388963, ['map,2,spprtFootMod,g2562_gait,z']= 0.042649057223268, })

	--from g2592
	--iter:71 bestfvever:4.1712611663016e-07
	accumulate({['map,0,swingFootMod,g2562_gait,x']= -0.26752749797807, ['map,0,swingFootMod,g2562_gait,y']= -0.24794282627597, ['map,0,swingFootMod,g2562_gait,z']= 0.31283036770757, ['map,1,swingFootMod,g2562_gait,x']= 0.19282405247122, ['map,1,swingFootMod,g2562_gait,y']= 0.090001931244552, ['map,1,swingFootMod,g2562_gait,z']= -0.01493562911679, ['map,2,swingFootMod,g2562_gait,x']= -0.020852766778446, ['map,2,swingFootMod,g2562_gait,y']= 0.17314236185439, ['map,2,swingFootMod,g2562_gait,z']= 0.098640832297545, ['map,0,spprtFootMod,g2562_gait,x']= 0.14985886882304, ['map,0,spprtFootMod,g2562_gait,y']= -0.20653314412159, ['map,0,spprtFootMod,g2562_gait,z']= 0.19864830966946, ['map,1,spprtFootMod,g2562_gait,x']= 0.29093864494556, ['map,1,spprtFootMod,g2562_gait,y']= 0.10355675994239, ['map,1,spprtFootMod,g2562_gait,z']= 0.060057481334429, ['map,2,spprtFootMod,g2562_gait,x']= -0.41248341306351, ['map,2,spprtFootMod,g2562_gait,y']= -0.38677569900179, ['map,2,spprtFootMod,g2562_gait,z']= 0.1095600491155, })

	useCases.g2562_gait.prec=.05

	--iter:114 bestfvever:6.0075554105403e-07
	accumulate({['map,0,swingFootMod,g2562_gait,x']= -0.28225724342621, ['map,0,swingFootMod,g2562_gait,y']= -0.48684613883036, ['map,0,swingFootMod,g2562_gait,z']= 0.4165066336527, ['map,1,swingFootMod,g2562_gait,x']= 0.089987524024069, ['map,1,swingFootMod,g2562_gait,y']= 0.097243215426767, ['map,1,swingFootMod,g2562_gait,z']= -0.15431501519997, ['map,2,swingFootMod,g2562_gait,x']= 0.0012114770190714, ['map,2,swingFootMod,g2562_gait,y']= 0.20311232918023, ['map,2,swingFootMod,g2562_gait,z']= 0.19382880363679, ['map,0,spprtFootMod,g2562_gait,x']= 0.099035798119966, ['map,0,spprtFootMod,g2562_gait,y']= -0.22965347471307, ['map,0,spprtFootMod,g2562_gait,z']= 0.25860717798295, ['map,1,spprtFootMod,g2562_gait,x']= 0.37943767568671, ['map,1,spprtFootMod,g2562_gait,y']= 0.092543065396031, ['map,1,spprtFootMod,g2562_gait,z']= -0.017339632469949, ['map,2,spprtFootMod,g2562_gait,x']= -0.55212481033989, ['map,2,spprtFootMod,g2562_gait,y']= -0.38120040851384, ['map,2,spprtFootMod,g2562_gait,z']= 0.056738087309456, })

elseif g_mode=='a_.1' then
	useCases.g2562_gait.aObjWeight = .1*useCases.g2562_gait.aObjWeight

	----iter:233 bestfvever:5.3502326121681e-07
	--accumulate({['map,0,swingFootMod,g2562_gait,x']= 0.17848042129251, ['map,0,swingFootMod,g2562_gait,y']= -0.61517982011648, ['map,0,swingFootMod,g2562_gait,z']= 0.8830843927604, ['map,1,swingFootMod,g2562_gait,x']= 0.24458782792519, ['map,1,swingFootMod,g2562_gait,y']= 0.16477429811902, ['map,1,swingFootMod,g2562_gait,z']= 0.072747168848999, ['map,2,swingFootMod,g2562_gait,x']= 0.0090458048328554, ['map,2,swingFootMod,g2562_gait,y']= -0.10692811160976, ['map,2,swingFootMod,g2562_gait,z']= 0.063611054206691, ['map,0,spprtFootMod,g2562_gait,x']= -0.5901414619081, ['map,0,spprtFootMod,g2562_gait,y']= 0.083754044912226, ['map,0,spprtFootMod,g2562_gait,z']= 0.34492500931644, ['map,1,spprtFootMod,g2562_gait,x']= 0.22027473430689, ['map,1,spprtFootMod,g2562_gait,y']= -0.16237086792539, ['map,1,spprtFootMod,g2562_gait,z']= -0.12765338125425, ['map,2,spprtFootMod,g2562_gait,x']= -0.3165225790038, ['map,2,spprtFootMod,g2562_gait,y']= -0.49841847262545, ['map,2,spprtFootMod,g2562_gait,z']= -0.39853996057389, })

	--useCases.g2562_gait.endSegW=20
	--useCases.g2562_gait.prec=.05

	----iter:71 bestfvever:5.847626571555e-07
	--accumulate({['map,0,swingFootMod,g2562_gait,x']= 0.16608737598935, ['map,0,swingFootMod,g2562_gait,y']= -0.58258879259704, ['map,0,swingFootMod,g2562_gait,z']= 0.88548727228352, ['map,1,swingFootMod,g2562_gait,x']= 0.26761989366558, ['map,1,swingFootMod,g2562_gait,y']= 0.17070306380732, ['map,1,swingFootMod,g2562_gait,z']= 0.07477997331498, ['map,2,swingFootMod,g2562_gait,x']= 0.014027375578207, ['map,2,swingFootMod,g2562_gait,y']= -0.1282912613832, ['map,2,swingFootMod,g2562_gait,z']= 0.057781330166931, ['map,0,spprtFootMod,g2562_gait,x']= -0.61917343008056, ['map,0,spprtFootMod,g2562_gait,y']= 0.073779050435025, ['map,0,spprtFootMod,g2562_gait,z']= 0.34277719444482, ['map,1,spprtFootMod,g2562_gait,x']= 0.17639267803378, ['map,1,spprtFootMod,g2562_gait,y']= -0.17544521254303, ['map,1,spprtFootMod,g2562_gait,z']= -0.11707444798643, ['map,2,spprtFootMod,g2562_gait,x']= -0.31437539296806, ['map,2,spprtFootMod,g2562_gait,y']= -0.50479262028303, ['map,2,spprtFootMod,g2562_gait,z']= -0.40777409802329, })

	--useCases.g2562_gait.cmaEffortDistWeight = 1e-7

	----iter:152 bestfvever:2.7625817647471e-06
	--accumulate({['map,0,swingFootMod,g2562_gait,x']= 0.17763290689624, ['map,0,swingFootMod,g2562_gait,y']= -0.5752966224783, ['map,0,swingFootMod,g2562_gait,z']= 0.8873844885171, ['map,1,swingFootMod,g2562_gait,x']= 0.21960886344004, ['map,1,swingFootMod,g2562_gait,y']= 0.17270063155653, ['map,1,swingFootMod,g2562_gait,z']= 0.075482290033678, ['map,2,swingFootMod,g2562_gait,x']= -0.018881614978849, ['map,2,swingFootMod,g2562_gait,y']= -0.031872974671806, ['map,2,swingFootMod,g2562_gait,z']= 0.031380875016482, ['map,0,spprtFootMod,g2562_gait,x']= -0.62166446847457, ['map,0,spprtFootMod,g2562_gait,y']= 0.022390872676742, ['map,0,spprtFootMod,g2562_gait,z']= 0.31991039161066, ['map,1,spprtFootMod,g2562_gait,x']= 0.14155806247347, ['map,1,spprtFootMod,g2562_gait,y']= -0.12317996777269, ['map,1,spprtFootMod,g2562_gait,z']= -0.14582508964444, ['map,2,spprtFootMod,g2562_gait,x']= -0.35366149232918, ['map,2,spprtFootMod,g2562_gait,y']= -0.46447187805406, ['map,2,spprtFootMod,g2562_gait,z']= -0.36354914875912, })

	--from g2592
	--iter:71 bestfvever:4.1712611663016e-07
	accumulate({['map,0,swingFootMod,g2562_gait,x']= -0.26752749797807, ['map,0,swingFootMod,g2562_gait,y']= -0.24794282627597, ['map,0,swingFootMod,g2562_gait,z']= 0.31283036770757, ['map,1,swingFootMod,g2562_gait,x']= 0.19282405247122, ['map,1,swingFootMod,g2562_gait,y']= 0.090001931244552, ['map,1,swingFootMod,g2562_gait,z']= -0.01493562911679, ['map,2,swingFootMod,g2562_gait,x']= -0.020852766778446, ['map,2,swingFootMod,g2562_gait,y']= 0.17314236185439, ['map,2,swingFootMod,g2562_gait,z']= 0.098640832297545, ['map,0,spprtFootMod,g2562_gait,x']= 0.14985886882304, ['map,0,spprtFootMod,g2562_gait,y']= -0.20653314412159, ['map,0,spprtFootMod,g2562_gait,z']= 0.19864830966946, ['map,1,spprtFootMod,g2562_gait,x']= 0.29093864494556, ['map,1,spprtFootMod,g2562_gait,y']= 0.10355675994239, ['map,1,spprtFootMod,g2562_gait,z']= 0.060057481334429, ['map,2,spprtFootMod,g2562_gait,x']= -0.41248341306351, ['map,2,spprtFootMod,g2562_gait,y']= -0.38677569900179, ['map,2,spprtFootMod,g2562_gait,z']= 0.1095600491155, })

	useCases.g2562_gait.prec=.05

	--iter:112 bestfvever:4.5304194120144e-07
	accumulate({['map,0,swingFootMod,g2562_gait,x']= -0.23804253949629, ['map,0,swingFootMod,g2562_gait,y']= -0.32532790895518, ['map,0,swingFootMod,g2562_gait,z']= 0.32143966727559, ['map,1,swingFootMod,g2562_gait,x']= 0.15018712855546, ['map,1,swingFootMod,g2562_gait,y']= 0.073249896173405, ['map,1,swingFootMod,g2562_gait,z']= -0.0070875738985678, ['map,2,swingFootMod,g2562_gait,x']= 0.053924425910634, ['map,2,swingFootMod,g2562_gait,y']= 0.14470699618756, ['map,2,swingFootMod,g2562_gait,z']= 0.088710893891616, ['map,0,spprtFootMod,g2562_gait,x']= 0.12863483762677, ['map,0,spprtFootMod,g2562_gait,y']= -0.26542394470527, ['map,0,spprtFootMod,g2562_gait,z']= 0.14909146012097, ['map,1,spprtFootMod,g2562_gait,x']= 0.33671794234427, ['map,1,spprtFootMod,g2562_gait,y']= 0.092230883769959, ['map,1,spprtFootMod,g2562_gait,z']= 0.033795326659359, ['map,2,spprtFootMod,g2562_gait,x']= -0.47275568782866, ['map,2,spprtFootMod,g2562_gait,y']= -0.39236070821741, ['map,2,spprtFootMod,g2562_gait,z']= 0.12019268157703, })

elseif g_mode=='a_.1_again' then
	useCases.g2562_gait.aObjWeight = .1*useCases.g2562_gait.aObjWeight
	useCases.g2562_gait.cmaEffortDistWeight = 1e-7

	--iter:190 bestfvever:3.7803163322587e-06
	accumulate({['map,0,swingFootMod,g2562_gait,x']= 0.69496017902405, ['map,0,swingFootMod,g2562_gait,y']= -0.33275814057976, ['map,0,swingFootMod,g2562_gait,z']= 0.27984155456386, ['map,1,swingFootMod,g2562_gait,x']= 0.11727660367929, ['map,1,swingFootMod,g2562_gait,y']= 0.2870402755409, ['map,1,swingFootMod,g2562_gait,z']= 0.013256667712033, ['map,2,swingFootMod,g2562_gait,x']= 0.12460492604072, ['map,2,swingFootMod,g2562_gait,y']= 0.075766345948285, ['map,2,swingFootMod,g2562_gait,z']= 0.089245314255244, ['map,0,spprtFootMod,g2562_gait,x']= -1.3025939527058, ['map,0,spprtFootMod,g2562_gait,y']= -0.22991727006096, ['map,0,spprtFootMod,g2562_gait,z']= 0.22487030633354, ['map,1,spprtFootMod,g2562_gait,x']= -0.042885422819762, ['map,1,spprtFootMod,g2562_gait,y']= -0.45461325939145, ['map,1,spprtFootMod,g2562_gait,z']= 0.025129788678361, ['map,2,spprtFootMod,g2562_gait,x']= -0.035795860087065, ['map,2,spprtFootMod,g2562_gait,y']= -1.0587454138556, ['map,2,spprtFootMod,g2562_gait,z']= -0.16667770310151, })

elseif g_mode=='a_.01' then
	useCases.g2562_gait.aObjWeight = .01*useCases.g2562_gait.aObjWeight

end
-------------------------------------------------

useCases.g2562_gait.controlParam['useCases,g2562_gait,aObjWeight'] = useCases.g2562_gait.aObjWeight

useCases.unmapControlParam(useCases.g2562_gait)
end


