package.path=package.path..";../Samples/ysscripts/lib/?.lua" --;"..package.path
require("utilfunc")

package.path=package.path..";../Samples/ysscripts/samples/?.lua" --;"..package.path
require("useCaseMuscle_gait1956_6steps")


useCases.g2592lankf_gait=deepCopyTable(useCases.gait1956_6steps)

useCases.g2592lankf_gait.optimizerMethod='Optimizer.methods.CMAes_ys'

useCases.g2592lankf_gait.endSegW=10
useCases.g2592lankf_gait.prec=.2
--useCases.g2592lankf_gait.endSegW=20
--useCases.g2592lankf_gait.prec=.05

useCases.g2592lankf_gait.modelName='g2592lankf_gait'
useCases.g2592lankf_gait.grpName='g2592lankf_gait'
useCases.g2592lankf_gait.grpNames={'g2592lankf_gait'}

-- nearest to human MET
useCases.g2592lankf_gait.ddqObjWeight=10*(25-7)
useCases.g2592lankf_gait.aObjWeight=5000*62
useCases.g2592lankf_gait.lambdaObjWeight=.0001
useCases.g2592lankf_gait.EEobjWeight=100
useCases.g2592lankf_gait.EEobjWeightAngular=10
useCases.g2592lankf_gait.momentumWeight=10

-- the initial pendControlParam and pendOptimizationPath can be automatically generated by using createInitialPendControlParam.lua
useCases.g2592lankf_gait.pendControlParam=
{
['keyframe,0,pendDesiredVel,g2592lankf_gait,l,z']=0,['keyframe,0,pendDesiredVel,g2592lankf_gait,l,x']=1,['keyframe,0,pendDesiredVel,g2592lankf_gait,r,z']=0,['keyframe,0,pendDesiredVel,g2592lankf_gait,r,x']=1,['keyframe,0,pendDesiredVel,g2592lankf_gait,L1,z']=0,['keyframe,0,pendDesiredVel,g2592lankf_gait,L1,x']=1,['keyframe,0,pendDesiredVel,g2592lankf_gait,R1,z']=0,['keyframe,0,pendDesiredVel,g2592lankf_gait,R1,x']=1,['keyframe,0,pendDesiredVel,g2592lankf_gait,L2,z']=0,['keyframe,0,pendDesiredVel,g2592lankf_gait,L2,x']=1,['keyframe,0,pendDesiredVel,ignore,0,z']=0,['keyframe,0,pendDesiredVel,ignore,0,x']=1,['keyframe,0,pendDesiredVel,ignore,1,z']=0,['keyframe,0,pendDesiredVel,ignore,1,x']=1,
['keyframe,0,pendDesiredVel,ignore,0,x']=0.55721712382895, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.11549022684414, ['keyframe,0,pendDesiredVel,g2592lankf_gait,l,x']=0.83765088460274, ['keyframe,0,pendDesiredVel,g2592lankf_gait,l,z']=-0.03971153581855, ['keyframe,0,pendDesiredVel,g2592lankf_gait,r,x']=1.0292990315838, ['keyframe,0,pendDesiredVel,g2592lankf_gait,r,z']=0.012304645261958, ['keyframe,0,pendDesiredVel,g2592lankf_gait,L1,x']=1.0830140604807, ['keyframe,0,pendDesiredVel,g2592lankf_gait,L1,z']=0.021311276252793, ['keyframe,0,pendDesiredVel,g2592lankf_gait,R1,x']=1.0448069373172, ['keyframe,0,pendDesiredVel,g2592lankf_gait,R1,z']=0.015212087553609, ['keyframe,0,pendDesiredVel,g2592lankf_gait,L2,x']=0.99864134148705, ['keyframe,0,pendDesiredVel,g2592lankf_gait,L2,z']=0.011195374086852, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.9726342007727, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.0046873881077062, 
['keyframe,0,pendDesiredVel,ignore,0,x']=-0.038573565913782, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.42183387297139, ['keyframe,0,pendDesiredVel,g2592lankf_gait,l,x']=2.8733663187598, ['keyframe,0,pendDesiredVel,g2592lankf_gait,l,z']=0.77374805250546, 
['keyframe,0,pendDesiredVel,ignore,0,x']=-0.03848565284349, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.42174541529281, ['keyframe,0,pendDesiredVel,g2592lankf_gait,l,x']=2.8733683928023, ['keyframe,0,pendDesiredVel,g2592lankf_gait,l,z']=0.77375288187355, 
['keyframe,0,pendDesiredVel,g2592lankf_gait,l,x']=1.8518302499598, ['keyframe,0,pendDesiredVel,g2592lankf_gait,l,z']=0.32721002628792, ['keyframe,0,pendDesiredVel,g2592lankf_gait,r,x']=0.64195188458919, ['keyframe,0,pendDesiredVel,g2592lankf_gait,r,z']=-0.23746102054191, ['keyframe,0,pendDesiredVel,g2592lankf_gait,L1,x']=1.0569602524197, ['keyframe,0,pendDesiredVel,g2592lankf_gait,L1,z']=0.0089665722850331, 
['keyframe,0,pendDesiredVel,g2592lankf_gait,r,x']=0.65321586961613, ['keyframe,0,pendDesiredVel,g2592lankf_gait,r,z']=-0.23322355700538, ['keyframe,0,pendDesiredVel,g2592lankf_gait,L1,x']=1.1600582644838, ['keyframe,0,pendDesiredVel,g2592lankf_gait,L1,z']=0.16409120361367, ['keyframe,0,pendDesiredVel,g2592lankf_gait,R1,x']=1.0469024908636, ['keyframe,0,pendDesiredVel,g2592lankf_gait,R1,z']=0.021499874539069, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.057317680328125, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.37352874903012, ['keyframe,0,pendDesiredVel,g2592lankf_gait,l,x']=1.688193340133, ['keyframe,0,pendDesiredVel,g2592lankf_gait,l,z']=0.33135464415606, ['keyframe,0,pendDesiredVel,g2592lankf_gait,r,x']=0.56260872770468, ['keyframe,0,pendDesiredVel,g2592lankf_gait,r,z']=-0.29475535050687, 
['keyframe,0,pendDesiredVel,g2592lankf_gait,l,x']=1.6732338838641, ['keyframe,0,pendDesiredVel,g2592lankf_gait,l,z']=0.31227141866769, ['keyframe,0,pendDesiredVel,g2592lankf_gait,r,x']=0.72633156918842, ['keyframe,0,pendDesiredVel,g2592lankf_gait,r,z']=-0.30056568375898, ['keyframe,0,pendDesiredVel,g2592lankf_gait,L1,x']=1.1885783553992, ['keyframe,0,pendDesiredVel,g2592lankf_gait,L1,z']=0.18162859438481, 
['keyframe,0,pendDesiredVel,g2592lankf_gait,r,x']=0.72682249891879, ['keyframe,0,pendDesiredVel,g2592lankf_gait,r,z']=-0.27195354224673, ['keyframe,0,pendDesiredVel,g2592lankf_gait,L1,x']=1.1844005645379, ['keyframe,0,pendDesiredVel,g2592lankf_gait,L1,z']=0.21070016989902, ['keyframe,0,pendDesiredVel,g2592lankf_gait,R1,x']=1.0436382930349, ['keyframe,0,pendDesiredVel,g2592lankf_gait,R1,z']=0.019573432369505, 
['keyframe,0,pendDesiredVel,g2592lankf_gait,L1,x']=1.1546812185886, ['keyframe,0,pendDesiredVel,g2592lankf_gait,L1,z']=0.13057608466461, ['keyframe,0,pendDesiredVel,g2592lankf_gait,R1,x']=1.0169825693409, ['keyframe,0,pendDesiredVel,g2592lankf_gait,R1,z']=-0.031308161078641, ['keyframe,0,pendDesiredVel,g2592lankf_gait,L2,x']=0.99332532373797, ['keyframe,0,pendDesiredVel,g2592lankf_gait,L2,z']=0.023230828039423, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.97210147412166, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.0051664564521254, 
}
useCases.g2592lankf_gait.pendOptimizationPath=
{
	firstFrames={1*2,39*2,77*2,115*2,153*2,191*2,229*2,266*2},
	segments={'ignore,0','g2592lankf_gait,l','g2592lankf_gait,r','g2592lankf_gait,L1','g2592lankf_gait,R1','g2592lankf_gait,L2','ignore,1'},
}
--useCases.g2592lankf_gait.measureOptCost=useCases.measureOptCost

useCases.g2592lankf_gait.segmentations=
{
	g2592lankf_gait={
		firstFrames={1*2,39*2,77*2,115*2,153*2,191*2,229*2,266*2},
		--        (blank)    L    R     L     R     L     (blank)
		names={             'l', 'r', 'L1', 'R1', 'L2',  },
		swingL={             0,   1,   0,    1,    0,    },
		swingR={             1,   0,   1,    0,    1,    },
		footRefL= "convertFromSwingL",
		footRefR= "convertFromSwingR",
		usePositionControl=false,
	},
}
useCases.g2592lankf_gait.graphParam=
{
	g2592lankf_gait={
		seg={            'l',  'r',  'L1', 'R1','L'},
		num_key={         3,    3,    3  ,  4,  4},
		key_first={       0,    0,    0  ,  0,  0},
		key_last={       'r', 'L1',  'R1', 'L', 'R1'},
	},
}
useCases.g2592lankf_gait.graph=
{
	{
		"addInterpolatedSegment",
		grpName="g2592lankf_gait",
		name="L",
		seg0={"g2592lankf_gait", "L2"},
		seg1={"g2592lankf_gait", "L1"},
		startWeight=0, endWeight=1
	},
	{"connectMulti", "g2592lankf_gait", "l", "r", "L1", "R1", "L", "R1"},
	--{"initialSegment", "g2592lankf_gait", "l"}
	{"initialSegment", "g2592lankf_gait", "R1"}
}
useCases.g2592lankf_gait.segNames=
{
	"l", "r", "L1", 'R1','L',
}

do 
	useCases.g2592lankf_gait.controlParam={
		['useCases,g2592lankf_gait,COMobjWeight']=0, 
		['useCases,g2592lankf_gait,conservativeW']=1, 
		--['useCases,g2592lankf_gait,contactMargin']=0.01, 
		['useCases,g2592lankf_gait,dotMomentumScale']=0.3, 
		['useCases,g2592lankf_gait,excludeRoot']=true, 
		['useCases,g2592lankf_gait,headControlWeight']=0, 
		['useCases,g2592lankf_gait,k_d_HEAD']=14, 
		['useCases,g2592lankf_gait,k_p_HEAD']=0, 
		['useCases,g2592lankf_gait,k_d_EE']=24, 
		['useCases,g2592lankf_gait,k_d_momentum']=10, 
		['useCases,g2592lankf_gait,k_p_EE']=120, 

		--['useCases,g2592lankf_gait,maxPenetratingVel']=0, 
		['useCases,g2592lankf_gait,momentumThr']=50, 
		['useCases,g2592lankf_gait,noComvelDependentFootAdjustment']=true, 
		['useCases,g2592lankf_gait,noIntersectionPrevenction']=true, 
		['useCases,g2592lankf_gait,numericalDerivDmot']=true, 
		['useCases,g2592lankf_gait,perClassContactMargin']=1, 
		['useCases,g2592lankf_gait,turnGain']=10, 
		['useCases,g2592lankf_gait,velMarginOffset']=0, 

		['useCases,g2592lankf_gait,actuationType']      = useCases.g2592lankf_gait.actuationType,
		['useCases,g2592lankf_gait,k_p_ID']             = useCases.g2592lankf_gait.k_p_ID,
		['useCases,g2592lankf_gait,k_d_ID']             = useCases.g2592lankf_gait.k_d_ID,
		['useCases,g2592lankf_gait,ddqObjWeight']       = useCases.g2592lankf_gait.ddqObjWeight,
		['useCases,g2592lankf_gait,tauObjWeight']       = useCases.g2592lankf_gait.tauObjWeight,
		['useCases,g2592lankf_gait,ftObjWeight']        = useCases.g2592lankf_gait.ftObjWeight,
		['useCases,g2592lankf_gait,aObjWeight']         = useCases.g2592lankf_gait.aObjWeight,
		['useCases,g2592lankf_gait,lambdaObjWeight']    = useCases.g2592lankf_gait.lambdaObjWeight,
		['useCases,g2592lankf_gait,EEobjWeight']        = useCases.g2592lankf_gait.EEobjWeight,
		['useCases,g2592lankf_gait,EEobjWeightAngular'] = useCases.g2592lankf_gait.EEobjWeightAngular,
		['useCases,g2592lankf_gait,momentumWeight']     = useCases.g2592lankf_gait.momentumWeight,
		['useCases,g2592lankf_gait,tauMax']             = useCases.g2592lankf_gait.tauMax,
		['useCases,g2592lankf_gait,ftMax']              = useCases.g2592lankf_gait.ftMax,
	}

	local function accumulate(cp_mod)
		local useCase=useCases.g2592lankf_gait
		useCases.accumulate(useCase, cp_mod)
	end

	accumulate({
		----['keyframe,0,footRmod,g2592lankf_gait,l,y']  = 0.,
		--['keyframe,1,footRmod,g2592lankf_gait,l,y']  = 0.05,
		--['keyframe,0,footLmod,g2592lankf_gait,r,y']  = 0.05,
		--['keyframe,1,footLmod,g2592lankf_gait,r,y']  = 0.1,
		--['keyframe,0,footRmod,g2592lankf_gait,L1,y'] = 0.0,
		--['keyframe,1,footRmod,g2592lankf_gait,L1,y'] = 0.1,
		--['map,0,swingFootMod,g2592lankf_gait,y']     = 0.1,
		--['map,1,swingFootMod,g2592lankf_gait,y']     = 0.3,
		--['map,2,swingFootMod,g2592lankf_gait,y']     = 0.2,

		------['keyframe,0,footLmod,g2592lankf_gait,l,y']  = 0.,
		------['keyframe,1,footLmod,g2592lankf_gait,l,y']  = 0.,
		----['keyframe,0,footRmod,g2592lankf_gait,r,y']  = 0.,
		----['keyframe,1,footRmod,g2592lankf_gait,r,y']  = -.1,
		----['keyframe,0,footLmod,g2592lankf_gait,L1,y'] = 0.,
		----['keyframe,1,footLmod,g2592lankf_gait,L1,y'] = -.1,
		----['map,0,spprtFootMod,g2592lankf_gait,y']     = 0.,
		----['map,1,spprtFootMod,g2592lankf_gait,y']     = 0.,
		----['map,2,spprtFootMod,g2592lankf_gait,y']     = 0.,
	})
	useCases.unmapControlParam(useCases.g2592lankf_gait)

-------------------------------------------------

if g_mode=='a_.1' then
	useCases.g2592lankf_gait.aObjWeight = .1*useCases.g2592lankf_gait.aObjWeight

	--useCases.g2592lankf_gait.endSegW=20
	--useCases.g2592lankf_gait.prec=.05

elseif g_mode=='test' then
	useCases.g2592lankf_gait.aObjWeight = .1*useCases.g2592lankf_gait.aObjWeight

end	

-------------------------------------------------

useCases.g2592lankf_gait.controlParam['useCases,g2592lankf_gait,aObjWeight'] = useCases.g2592lankf_gait.aObjWeight

useCases.unmapControlParam(useCases.g2592lankf_gait)
end


