package.path=package.path..";../Samples/ysscripts/lib/?.lua" --;"..package.path
require("utilfunc")

package.path=package.path..";../Samples/ysscripts/samples/?.lua" --;"..package.path
require("useMuscle_full_same")


useCases.full_soldier=deepCopyTable(useCases.full_same)

useCases.full_soldier.optimizerMethod='Optimizer.methods.CMAes_ys'

--useCases.full_soldier.endSegW=10
useCases.full_soldier.endSegW=15
useCases.full_soldier.prec=.2

useCases.full_soldier.modelName='full_soldier'
useCases.full_soldier.grpName='full_soldier'
useCases.full_soldier.grpNames={'full_soldier'}

-- the initial pendControlParam and pendOptimizationPath can be automatically generated by using createInitialPendControlParam.lua
useCases.full_soldier.pendControlParam=
{
['keyframe,0,pendDesiredVel,full_soldier,l,z']=0,['keyframe,0,pendDesiredVel,full_soldier,l,x']=1,['keyframe,0,pendDesiredVel,full_soldier,r,z']=0,['keyframe,0,pendDesiredVel,full_soldier,r,x']=1,['keyframe,0,pendDesiredVel,full_soldier,L1,z']=0,['keyframe,0,pendDesiredVel,full_soldier,L1,x']=1,['keyframe,0,pendDesiredVel,full_soldier,R1,z']=0,['keyframe,0,pendDesiredVel,full_soldier,R1,x']=1,['keyframe,0,pendDesiredVel,full_soldier,L2,z']=0,['keyframe,0,pendDesiredVel,full_soldier,L2,x']=1,['keyframe,0,pendDesiredVel,ignore,0,z']=0,['keyframe,0,pendDesiredVel,ignore,0,x']=1,['keyframe,0,pendDesiredVel,ignore,1,z']=0,['keyframe,0,pendDesiredVel,ignore,1,x']=1,
['keyframe,0,pendDesiredVel,ignore,0,x']=0.43589600298029, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.37683189067416, ['keyframe,0,pendDesiredVel,full_soldier,l,x']=0.61774258449551, ['keyframe,0,pendDesiredVel,full_soldier,l,z']=-0.12737621619245, ['keyframe,0,pendDesiredVel,full_soldier,r,x']=0.69135931335538, ['keyframe,0,pendDesiredVel,full_soldier,r,z']=0.010149166183571, ['keyframe,0,pendDesiredVel,full_soldier,L1,x']=0.69482790133766, ['keyframe,0,pendDesiredVel,full_soldier,L1,z']=0.021203443723949, ['keyframe,0,pendDesiredVel,full_soldier,R1,x']=0.70508048029194, ['keyframe,0,pendDesiredVel,full_soldier,R1,z']=0.0003415379754633, ['keyframe,0,pendDesiredVel,full_soldier,L2,x']=0.78415783247123, ['keyframe,0,pendDesiredVel,full_soldier,L2,z']=0.012368498389993, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.89760975284344, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.0072563433885572, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.44019138714695, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.4014339183439, ['keyframe,0,pendDesiredVel,full_soldier,l,x']=0.61707528751135, ['keyframe,0,pendDesiredVel,full_soldier,l,z']=-0.13383058432092, ['keyframe,0,pendDesiredVel,full_soldier,r,x']=0.6927905559057, ['keyframe,0,pendDesiredVel,full_soldier,r,z']=0.020699411926373, ['keyframe,0,pendDesiredVel,full_soldier,L1,x']=0.70055544654008, ['keyframe,0,pendDesiredVel,full_soldier,L1,z']=0.046859663000603, ['keyframe,0,pendDesiredVel,full_soldier,R1,x']=0.69511988449134, ['keyframe,0,pendDesiredVel,full_soldier,R1,z']=0.022628272228711, ['keyframe,0,pendDesiredVel,full_soldier,L2,x']=0.76329232246097, ['keyframe,0,pendDesiredVel,full_soldier,L2,z']=0.021638135967389, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.85027657263433, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.00707315449051, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.31474625610872, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.56405236173219, ['keyframe,0,pendDesiredVel,full_soldier,l,x']=0.77233646134626, ['keyframe,0,pendDesiredVel,full_soldier,l,z']=0.04003085966172, ['keyframe,0,pendDesiredVel,full_soldier,r,x']=0.7462659038903, ['keyframe,0,pendDesiredVel,full_soldier,r,z']=0.085736106887814, ['keyframe,0,pendDesiredVel,full_soldier,L1,x']=0.68453260230283, ['keyframe,0,pendDesiredVel,full_soldier,L1,z']=0.0033801340220173, ['keyframe,0,pendDesiredVel,full_soldier,R1,x']=0.63007229848092, ['keyframe,0,pendDesiredVel,full_soldier,R1,z']=-0.06654309024052, ['keyframe,0,pendDesiredVel,full_soldier,L2,x']=0.70390914114953, ['keyframe,0,pendDesiredVel,full_soldier,L2,z']=0.036665579133154, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.83842364311714, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.0075171159057316, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.3147197045354, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.56412269239435, ['keyframe,0,pendDesiredVel,full_soldier,l,x']=0.77234661124479, ['keyframe,0,pendDesiredVel,full_soldier,l,z']=0.04001417936547, ['keyframe,0,pendDesiredVel,full_soldier,r,x']=0.74626528561886, ['keyframe,0,pendDesiredVel,full_soldier,r,z']=0.085703006003267, ['keyframe,0,pendDesiredVel,full_soldier,L1,x']=0.68454753453717, ['keyframe,0,pendDesiredVel,full_soldier,L1,z']=0.0033648126887431, ['keyframe,0,pendDesiredVel,full_soldier,R1,x']=0.63009571009204, ['keyframe,0,pendDesiredVel,full_soldier,R1,z']=-0.066540790955665, ['keyframe,0,pendDesiredVel,full_soldier,L2,x']=0.70392235525809, ['keyframe,0,pendDesiredVel,full_soldier,L2,z']=0.03668173064948, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.83842323465674, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.0075185294178187, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.31470373728685, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.56416450916211, ['keyframe,0,pendDesiredVel,full_soldier,l,x']=0.77235275953932, ['keyframe,0,pendDesiredVel,full_soldier,l,z']=0.040004574956828, ['keyframe,0,pendDesiredVel,full_soldier,r,x']=0.74626489355271, ['keyframe,0,pendDesiredVel,full_soldier,r,z']=0.085683449457584, ['keyframe,0,pendDesiredVel,full_soldier,L1,x']=0.68455651887714, ['keyframe,0,pendDesiredVel,full_soldier,L1,z']=0.0033558555134713, ['keyframe,0,pendDesiredVel,full_soldier,R1,x']=0.63010976695634, ['keyframe,0,pendDesiredVel,full_soldier,R1,z']=-0.066539256389856, ['keyframe,0,pendDesiredVel,full_soldier,L2,x']=0.70393029789888, ['keyframe,0,pendDesiredVel,full_soldier,L2,z']=0.036691503514122, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.83842298793433, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.0075193837143672, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.22120077181748, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.76170201100106, ['keyframe,0,pendDesiredVel,full_soldier,l,x']=0.99178640967929, ['keyframe,0,pendDesiredVel,full_soldier,l,z']=0.43696329984357, ['keyframe,0,pendDesiredVel,full_soldier,r,x']=0.7467919081107, ['keyframe,0,pendDesiredVel,full_soldier,r,z']=0.12268543424681, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.22135790422551, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.76266157889687, ['keyframe,0,pendDesiredVel,full_soldier,l,x']=0.99193378352432, ['keyframe,0,pendDesiredVel,full_soldier,l,z']=0.4366464444399, ['keyframe,0,pendDesiredVel,full_soldier,r,x']=0.74659115698768, ['keyframe,0,pendDesiredVel,full_soldier,r,z']=0.12231989711265, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.16256047772027, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.88077019020364, ['keyframe,0,pendDesiredVel,full_soldier,l,x']=1.5632521489706, ['keyframe,0,pendDesiredVel,full_soldier,l,z']=1.2260006769907, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.16207334815518, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.88120914212615, ['keyframe,0,pendDesiredVel,full_soldier,l,x']=1.5632350814077, ['keyframe,0,pendDesiredVel,full_soldier,l,z']=1.226018755554, 
['keyframe,0,pendDesiredVel,full_soldier,l,x']=1.1643685537304, ['keyframe,0,pendDesiredVel,full_soldier,l,z']=0.66274628255678, ['keyframe,0,pendDesiredVel,full_soldier,r,x']=0.50828629520367, ['keyframe,0,pendDesiredVel,full_soldier,r,z']=-0.46084911596288, ['keyframe,0,pendDesiredVel,full_soldier,L1,x']=0.65944624237151, ['keyframe,0,pendDesiredVel,full_soldier,L1,z']=-0.017764499497276, 
['keyframe,0,pendDesiredVel,full_soldier,l,x']=1.1644371082925, ['keyframe,0,pendDesiredVel,full_soldier,l,z']=0.66275063119366, ['keyframe,0,pendDesiredVel,full_soldier,r,x']=0.5083143194073, ['keyframe,0,pendDesiredVel,full_soldier,r,z']=-0.46086463793873, ['keyframe,0,pendDesiredVel,full_soldier,L1,x']=0.65944232097183, ['keyframe,0,pendDesiredVel,full_soldier,L1,z']=-0.017789235610411, 
['keyframe,0,pendDesiredVel,full_soldier,l,x']=1.1431031226825, ['keyframe,0,pendDesiredVel,full_soldier,l,z']=0.62087739863817, ['keyframe,0,pendDesiredVel,full_soldier,r,x']=0.54243420111226, ['keyframe,0,pendDesiredVel,full_soldier,r,z']=-0.34286647713677, ['keyframe,0,pendDesiredVel,full_soldier,L1,x']=0.74217959567932, ['keyframe,0,pendDesiredVel,full_soldier,L1,z']=0.16397578360081, ['keyframe,0,pendDesiredVel,full_soldier,R1,x']=0.63677701525397, ['keyframe,0,pendDesiredVel,full_soldier,R1,z']=-0.042648337353351, 
['keyframe,0,pendDesiredVel,full_soldier,l,x']=1.1431547258468, ['keyframe,0,pendDesiredVel,full_soldier,l,z']=0.62096223340055, ['keyframe,0,pendDesiredVel,full_soldier,r,x']=0.54246567554817, ['keyframe,0,pendDesiredVel,full_soldier,r,z']=-0.342797038632, ['keyframe,0,pendDesiredVel,full_soldier,L1,x']=0.74217984361979, ['keyframe,0,pendDesiredVel,full_soldier,L1,z']=0.16396968747968, ['keyframe,0,pendDesiredVel,full_soldier,R1,x']=0.63677870444035, ['keyframe,0,pendDesiredVel,full_soldier,R1,z']=-0.042646520305469, 
['keyframe,0,pendDesiredVel,full_soldier,R1,x']=0.6785630580237, ['keyframe,0,pendDesiredVel,full_soldier,R1,z']=-0.18581435234938, ['keyframe,0,pendDesiredVel,full_soldier,L2,x']=0.70593246003137, ['keyframe,0,pendDesiredVel,full_soldier,L2,z']=0.20741241271329, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.82138579565806, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.025350005542655, 
['keyframe,0,pendDesiredVel,full_soldier,R1,x']=0.67834440140355, ['keyframe,0,pendDesiredVel,full_soldier,R1,z']=-0.18521498098536, ['keyframe,0,pendDesiredVel,full_soldier,L2,x']=0.70584927896083, ['keyframe,0,pendDesiredVel,full_soldier,L2,z']=0.20752850567827, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.82148226323733, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.02547973647727, 
}
useCases.full_soldier.pendOptimizationPath=
{
	firstFrames={1*4,24*4,47*4,70*4,93*4,116*4,139*4,160*4},
	segments={'ignore,0','full_soldier,l','full_soldier,r','full_soldier,L1','full_soldier,R1','full_soldier,L2','ignore,1'},
}
--useCases.full_soldier.measureOptCost=useCases.measureOptCost

useCases.full_soldier.segmentations=
{
	full_soldier={
		firstFrames={1*4,24*4,47*4,70*4,93*4,116*4,139*4,160*4},
		--        (blank)    L    R     L     R     L     (blank)
		names={             'l', 'r', 'L1', 'R1', 'L2',  },
		swingL={             0,   1,   0,    1,    0,    },
		swingR={             1,   0,   1,    0,    1,    },
		footRefL= "convertFromSwingL",
		footRefR= "convertFromSwingR",
		usePositionControl=false,
	},
}
useCases.full_soldier.graphParam=
{
	full_soldier={
		seg={            'l',  'r',  'L1', 'R1','L'},
		num_key={         3,    3,    3  ,  4,  4},
		key_first={       0,    0,    0  ,  0,  0},
		key_last={       'r', 'L1',  'R1', 'L', 'R1'},
	},
}
useCases.full_soldier.graph=
{
	{
		"addInterpolatedSegment",
		grpName="full_soldier",
		name="L",
		seg0={"full_soldier", "L2"},
		seg1={"full_soldier", "L1"},
		startWeight=0, endWeight=1
	},
	{"connectMulti", "full_soldier", "l", "r", "L1", "R1", "L", "R1"},
	--{"initialSegment", "full_soldier", "l"}
	{"initialSegment", "full_soldier", "R1"}
}
useCases.full_soldier.segNames=
{
	"l", "r", "L1", 'R1','L',
}

do 
	useCases.full_soldier.controlParam={
		['useCases,full_soldier,COMobjWeight']=0, 
		['useCases,full_soldier,conservativeW']=1, 
		--['useCases,full_soldier,contactMargin']=0.01, 
		['useCases,full_soldier,dotMomentumScale']=0.3, 
		['useCases,full_soldier,excludeRoot']=true, 
		['useCases,full_soldier,headControlWeight']=0, 
		['useCases,full_soldier,k_d_HEAD']=14, 
		['useCases,full_soldier,k_p_HEAD']=0, 
		['useCases,full_soldier,k_d_EE']=24, 
		['useCases,full_soldier,k_d_momentum']=10, 
		['useCases,full_soldier,k_p_EE']=120, 

		--['useCases,full_soldier,maxPenetratingVel']=0, 
		['useCases,full_soldier,momentumThr']=50, 
		['useCases,full_soldier,noComvelDependentFootAdjustment']=true, 
		['useCases,full_soldier,noIntersectionPrevenction']=true, 
		['useCases,full_soldier,numericalDerivDmot']=true, 
		['useCases,full_soldier,perClassContactMargin']=1, 
		['useCases,full_soldier,turnGain']=10, 
		['useCases,full_soldier,velMarginOffset']=0, 

		['useCases,full_soldier,actuationType']      = useCases.full_soldier.actuationType,
		['useCases,full_soldier,k_p_ID']             = useCases.full_soldier.k_p_ID,
		['useCases,full_soldier,k_d_ID']             = useCases.full_soldier.k_d_ID,
		['useCases,full_soldier,ddqObjWeight']       = useCases.full_soldier.ddqObjWeight,
		['useCases,full_soldier,tauObjWeight']       = useCases.full_soldier.tauObjWeight,
		['useCases,full_soldier,ftObjWeight']        = useCases.full_soldier.ftObjWeight,
		['useCases,full_soldier,aObjWeight']         = useCases.full_soldier.aObjWeight,
		['useCases,full_soldier,lambdaObjWeight']    = useCases.full_soldier.lambdaObjWeight,
		['useCases,full_soldier,EEobjWeight']        = useCases.full_soldier.EEobjWeight,
		['useCases,full_soldier,EEobjWeightAngular'] = useCases.full_soldier.EEobjWeightAngular,
		['useCases,full_soldier,momentumWeight']     = useCases.full_soldier.momentumWeight,
		['useCases,full_soldier,tauMax']             = useCases.full_soldier.tauMax,
		['useCases,full_soldier,ftMax']              = useCases.full_soldier.ftMax,
	}

	local function accumulate(cp_mod)
		local useCase=useCases.full_soldier
		useCases.accumulate(useCase, cp_mod)
	end

	accumulate({
		----['keyframe,0,footRmod,full_soldier,l,y']  = 0.,
		----['keyframe,1,footRmod,full_soldier,l,y']  = 0.05,
		--['keyframe,0,footLmod,full_soldier,r,y']  = 0.0,
		--['keyframe,1,footLmod,full_soldier,r,y']  = 0.2,
		--['keyframe,0,footRmod,full_soldier,L1,y'] = 0.0,
		--['keyframe,1,footRmod,full_soldier,L1,y'] = 0.2,
		--['map,0,swingFootMod,full_soldier,y']     = 0.1,
		--['map,1,swingFootMod,full_soldier,y']     = 0.2,
		--['map,2,swingFootMod,full_soldier,y']     = 0.1,

		----['keyframe,0,footLmod,full_soldier,l,y']  = 0.,
		----['keyframe,1,footLmod,full_soldier,l,y']  = 0.,
		--['keyframe,0,footRmod,full_soldier,r,y']  = 0.,
		--['keyframe,1,footRmod,full_soldier,r,y']  = -.1,
		--['keyframe,0,footLmod,full_soldier,L1,y'] = 0.,
		--['keyframe,1,footLmod,full_soldier,L1,y'] = -.1,
		--['map,0,spprtFootMod,full_soldier,y']     = 0.,
		--['map,1,spprtFootMod,full_soldier,y']     = 0.,
		--['map,2,spprtFootMod,full_soldier,y']     = 0.,
	})
	useCases.unmapControlParam(useCases.full_soldier)


-------------------------------------------------
if g_mode=='default' then
	--old weight
	----iter:159 bestfvever:1.3876356566371e-06
	--accumulate({['map,0,swingFootMod,full_soldier,x']= -0.30332278146003, ['map,0,swingFootMod,full_soldier,y']= -0.96307715281668, ['map,0,swingFootMod,full_soldier,z']= 0.6772671165103, ['map,1,swingFootMod,full_soldier,x']= -0.09086019945279, ['map,1,swingFootMod,full_soldier,y']= 0.84381885964007, ['map,1,swingFootMod,full_soldier,z']= 0.58931458545694, ['map,2,swingFootMod,full_soldier,x']= 0.1365353538809, ['map,2,swingFootMod,full_soldier,y']= -1.400562427691, ['map,2,swingFootMod,full_soldier,z']= -0.34382071842373, ['map,0,spprtFootMod,full_soldier,x']= 0.076859941729143, ['map,0,spprtFootMod,full_soldier,y']= -1.7715058814944, ['map,0,spprtFootMod,full_soldier,z']= 0.086560942631974, ['map,1,spprtFootMod,full_soldier,x']= 0.088263703006051, ['map,1,spprtFootMod,full_soldier,y']= -1.1658139334863, ['map,1,spprtFootMod,full_soldier,z']= -0.28349569643053, ['map,2,spprtFootMod,full_soldier,x']= 1.2839249985662, ['map,2,spprtFootMod,full_soldier,y']= -0.74786419137308, ['map,2,spprtFootMod,full_soldier,z']= 0.63549347976295, })
	
	----iter:986 bestfvever:170182.17747119
	--accumulate({['map,0,swingFootMod,full_soldier,x']= -0.079819982435869, ['map,0,swingFootMod,full_soldier,y']= -0.19586039382931, ['map,0,swingFootMod,full_soldier,z']= 0.0080281507607144, ['map,1,swingFootMod,full_soldier,x']= -0.38680283443749, ['map,1,swingFootMod,full_soldier,y']= -0.14472962915089, ['map,1,swingFootMod,full_soldier,z']= 0.0050549743540981, ['map,2,swingFootMod,full_soldier,x']= 0.048022181409975, ['map,2,swingFootMod,full_soldier,y']= 0.015405531917137, ['map,2,swingFootMod,full_soldier,z']= 0.24270919919245, ['map,0,spprtFootMod,full_soldier,x']= 0.046139604650924, ['map,0,spprtFootMod,full_soldier,y']= 0.015375182848969, ['map,0,spprtFootMod,full_soldier,z']= -0.20965075798259, ['map,1,spprtFootMod,full_soldier,x']= -0.19956122754272, ['map,1,spprtFootMod,full_soldier,y']= 0.2037428287, ['map,1,spprtFootMod,full_soldier,z']= 0.021673947835586, ['map,2,spprtFootMod,full_soldier,x']= 0.15145447569469, ['map,2,spprtFootMod,full_soldier,y']= -0.030743291371243, ['map,2,spprtFootMod,full_soldier,z']= -0.16164548558428, })

	----iter:251 bestfvever:7.5384222253537e-06
	--accumulate({['map,0,swingFootMod,full_soldier,x']= 0.064785332202618, ['map,0,swingFootMod,full_soldier,y']= 0.12737111866201, ['map,0,swingFootMod,full_soldier,z']= 0.049679000131719, ['map,1,swingFootMod,full_soldier,x']= -0.039555733235129, ['map,1,swingFootMod,full_soldier,y']= -0.03435876624637, ['map,1,swingFootMod,full_soldier,z']= 0.062093153064096, ['map,2,swingFootMod,full_soldier,x']= -0.0062590128445722, ['map,2,swingFootMod,full_soldier,y']= -0.053584158765676, ['map,2,swingFootMod,full_soldier,z']= 0.060325927981726, ['map,0,spprtFootMod,full_soldier,x']= -0.00049775263593125, ['map,0,spprtFootMod,full_soldier,y']= -0.049210180501725, ['map,0,spprtFootMod,full_soldier,z']= -0.029150219410934, ['map,1,spprtFootMod,full_soldier,x']= -0.10537120735407, ['map,1,spprtFootMod,full_soldier,y']= -0.065312836550452, ['map,1,spprtFootMod,full_soldier,z']= -0.1105876744709, ['map,2,spprtFootMod,full_soldier,x']= 0.060724970690128, ['map,2,spprtFootMod,full_soldier,y']= 0.17079051929581, ['map,2,spprtFootMod,full_soldier,z']= 0.10232988208469, })

	--iter:144 bestfvever:1.171259944128e-06
	accumulate({['map,0,swingFootMod,full_soldier,x']= -0.46386055416357, ['map,0,swingFootMod,full_soldier,y']= -0.50234419782744, ['map,0,swingFootMod,full_soldier,z']= -0.030895700602245, ['map,1,swingFootMod,full_soldier,x']= -0.4024310795352, ['map,1,swingFootMod,full_soldier,y']= -0.21973032445945, ['map,1,swingFootMod,full_soldier,z']= 0.28230122796364, ['map,2,swingFootMod,full_soldier,x']= -0.20169836284782, ['map,2,swingFootMod,full_soldier,y']= 0.61232090605869, ['map,2,swingFootMod,full_soldier,z']= -0.069864374184355, ['map,0,spprtFootMod,full_soldier,x']= 0.82928923640402, ['map,0,spprtFootMod,full_soldier,y']= -3.4176178629538, ['map,0,spprtFootMod,full_soldier,z']= 0.49810385185145, ['map,1,spprtFootMod,full_soldier,x']= 1.3750764041388, ['map,1,spprtFootMod,full_soldier,y']= -2.2436614719846, ['map,1,spprtFootMod,full_soldier,z']= -0.94366199152891, ['map,2,spprtFootMod,full_soldier,x']= 1.2388630185041, ['map,2,spprtFootMod,full_soldier,y']= -1.1051149303392, ['map,2,spprtFootMod,full_soldier,z']= 0.4551257778149, })

	useCases.full_soldier.endSegW=20
	useCases.full_soldier.prec=.05

	--iter:32 bestfvever:1.2463991001797e-06
	accumulate({['map,0,swingFootMod,full_soldier,x']= -0.45708962511643, ['map,0,swingFootMod,full_soldier,y']= -0.49817515111508, ['map,0,swingFootMod,full_soldier,z']= -0.046665157618994, ['map,1,swingFootMod,full_soldier,x']= -0.41204241089987, ['map,1,swingFootMod,full_soldier,y']= -0.21181372758298, ['map,1,swingFootMod,full_soldier,z']= 0.27190230090192, ['map,2,swingFootMod,full_soldier,x']= -0.18226211659065, ['map,2,swingFootMod,full_soldier,y']= 0.63306595859237, ['map,2,swingFootMod,full_soldier,z']= -0.063457347984785, ['map,0,spprtFootMod,full_soldier,x']= 0.85850554594463, ['map,0,spprtFootMod,full_soldier,y']= -3.4080689519728, ['map,0,spprtFootMod,full_soldier,z']= 0.4771859536455, ['map,1,spprtFootMod,full_soldier,x']= 1.379878494529, ['map,1,spprtFootMod,full_soldier,y']= -2.2289843159753, ['map,1,spprtFootMod,full_soldier,z']= -0.96982906041767, ['map,2,spprtFootMod,full_soldier,x']= 1.2420630487094, ['map,2,spprtFootMod,full_soldier,y']= -1.1138085928866, ['map,2,spprtFootMod,full_soldier,z']= 0.45851316580035, })

elseif g_mode=='default_nost' then
	useCases.full_soldier.noStride = true

	--iter:113 bestfvever:2.2374649273242e-06
	accumulate({['map,0,swingFootMod,full_soldier,x']= -1.418482972959, ['map,0,swingFootMod,full_soldier,y']= -1.5381841400439, ['map,0,swingFootMod,full_soldier,z']= 0.83955045212988, ['map,1,swingFootMod,full_soldier,x']= -0.20591884665063, ['map,1,swingFootMod,full_soldier,y']= -0.22360706978518, ['map,1,swingFootMod,full_soldier,z']= 0.0097160776877433, ['map,2,swingFootMod,full_soldier,x']= -0.24670457205874, ['map,2,swingFootMod,full_soldier,y']= -0.23410166714665, ['map,2,swingFootMod,full_soldier,z']= 0.15538745434102, ['map,0,spprtFootMod,full_soldier,x']= 0.24900051582455, ['map,0,spprtFootMod,full_soldier,y']= -0.89951316642623, ['map,0,spprtFootMod,full_soldier,z']= -0.14015864780334, ['map,1,spprtFootMod,full_soldier,x']= 0.25914303051531, ['map,1,spprtFootMod,full_soldier,y']= -1.5357499395989, ['map,1,spprtFootMod,full_soldier,z']= 0.17993538124889, ['map,2,spprtFootMod,full_soldier,x']= 0.50620553301187, ['map,2,spprtFootMod,full_soldier,y']= 0.56713935738194, ['map,2,spprtFootMod,full_soldier,z']= -0.061502576048185, })

elseif g_mode=='a_.1' then
	useCases.full_soldier.aObjWeight = .1*useCases.full_soldier.aObjWeight

	--iter:117 bestfvever:1.4824265268018e-06
	accumulate({['map,0,swingFootMod,full_soldier,x']= -0.40768688016413, ['map,0,swingFootMod,full_soldier,y']= -0.39589317029979, ['map,0,swingFootMod,full_soldier,z']= 0.0045172764508211, ['map,1,swingFootMod,full_soldier,x']= -0.2875963138173, ['map,1,swingFootMod,full_soldier,y']= -0.55993184674169, ['map,1,swingFootMod,full_soldier,z']= 0.26475498513183, ['map,2,swingFootMod,full_soldier,x']= -0.29679088555432, ['map,2,swingFootMod,full_soldier,y']= 0.21929179185271, ['map,2,swingFootMod,full_soldier,z']= -0.042547690558737, ['map,0,spprtFootMod,full_soldier,x']= 0.12358447869011, ['map,0,spprtFootMod,full_soldier,y']= -2.188459208786, ['map,0,spprtFootMod,full_soldier,z']= -0.086236828301478, ['map,1,spprtFootMod,full_soldier,x']= 1.1282086695138, ['map,1,spprtFootMod,full_soldier,y']= -0.94528183354508, ['map,1,spprtFootMod,full_soldier,z']= 1.2024329320663, ['map,2,spprtFootMod,full_soldier,x']= 0.13830793093528, ['map,2,spprtFootMod,full_soldier,y']= -0.957949433585, ['map,2,spprtFootMod,full_soldier,z']= -0.74477551804117, })

elseif g_mode=='a_.1_g2592' then
	useCases.full_soldier.aObjWeight = .1*useCases.full_soldier.aObjWeight

	--g2592
	--iter:125 bestfvever:6.6330542158609e-07
	accumulate({['map,0,swingFootMod,full_soldier,x']= 0.11972458212199, ['map,0,swingFootMod,full_soldier,y']= -0.37980591981617, ['map,0,swingFootMod,full_soldier,z']= 0.48411399540893, ['map,1,swingFootMod,full_soldier,x']= -0.024747501139378, ['map,1,swingFootMod,full_soldier,y']= -0.027650989636261, ['map,1,swingFootMod,full_soldier,z']= -0.092615566569568, ['map,2,swingFootMod,full_soldier,x']= -0.19019982434314, ['map,2,swingFootMod,full_soldier,y']= 0.34258241545261, ['map,2,swingFootMod,full_soldier,z']= -0.096589510735512, ['map,0,spprtFootMod,full_soldier,x']= 0.22158728585089, ['map,0,spprtFootMod,full_soldier,y']= -0.21783285667065, ['map,0,spprtFootMod,full_soldier,z']= 0.026413337559883, ['map,1,spprtFootMod,full_soldier,x']= 0.27586971393953, ['map,1,spprtFootMod,full_soldier,y']= 0.055171460742169, ['map,1,spprtFootMod,full_soldier,z']= -0.34541186794417, ['map,2,spprtFootMod,full_soldier,x']= -0.18252187946132, ['map,2,spprtFootMod,full_soldier,y']= -0.43678204444012, ['map,2,spprtFootMod,full_soldier,z']= 0.017685887937767, })

	--good
	--iter:109 bestfvever:1.2643773849151e-06
	accumulate({['map,0,swingFootMod,full_soldier,x']= -0.55254281744229, ['map,0,swingFootMod,full_soldier,y']= -0.76245596764818, ['map,0,swingFootMod,full_soldier,z']= -0.43404417604582, ['map,1,swingFootMod,full_soldier,x']= -0.20079946537621, ['map,1,swingFootMod,full_soldier,y']= -0.41609521636653, ['map,1,swingFootMod,full_soldier,z']= 0.13212115226128, ['map,2,swingFootMod,full_soldier,x']= -0.3365746607933, ['map,2,swingFootMod,full_soldier,y']= 0.29101799821232, ['map,2,swingFootMod,full_soldier,z']= 0.24523499020498, ['map,0,spprtFootMod,full_soldier,x']= 0.9228276357268, ['map,0,spprtFootMod,full_soldier,y']= -3.3657317116754, ['map,0,spprtFootMod,full_soldier,z']= 0.16831903616233, ['map,1,spprtFootMod,full_soldier,x']= -1.0893981881817, ['map,1,spprtFootMod,full_soldier,y']= -1.3616576695589, ['map,1,spprtFootMod,full_soldier,z']= 0.68219001319632, ['map,2,spprtFootMod,full_soldier,x']= 0.69621835934596, ['map,2,spprtFootMod,full_soldier,y']= -1.3235667674683, ['map,2,spprtFootMod,full_soldier,z']= 0.62381741920443, })

	--useCases.full_soldier.prec=.05

	----iter:81 bestfvever:1.3520229373128e-06
	--accumulate({['map,0,swingFootMod,full_soldier,x']= -0.57299906498668, ['map,0,swingFootMod,full_soldier,y']= -0.77698163637365, ['map,0,swingFootMod,full_soldier,z']= -0.43010030474229, ['map,1,swingFootMod,full_soldier,x']= -0.18241922120971, ['map,1,swingFootMod,full_soldier,y']= -0.39480263138535, ['map,1,swingFootMod,full_soldier,z']= 0.13526022244733, ['map,2,swingFootMod,full_soldier,x']= -0.34112809200489, ['map,2,swingFootMod,full_soldier,y']= 0.29325258183807, ['map,2,swingFootMod,full_soldier,z']= 0.18025946459271, ['map,0,spprtFootMod,full_soldier,x']= 0.90294517676335, ['map,0,spprtFootMod,full_soldier,y']= -3.3354669670368, ['map,0,spprtFootMod,full_soldier,z']= 0.1350155709387, ['map,1,spprtFootMod,full_soldier,x']= -1.0952068728574, ['map,1,spprtFootMod,full_soldier,y']= -1.3738866660882, ['map,1,spprtFootMod,full_soldier,z']= 0.66827743144393, ['map,2,spprtFootMod,full_soldier,x']= 0.70922945585922, ['map,2,spprtFootMod,full_soldier,y']= -1.3311643827516, ['map,2,spprtFootMod,full_soldier,z']= 0.64456019526822, })

	--useCases.full_soldier.endSegW=20

	----iter:61 bestfvever:1.3144188514843e-06
	--accumulate({['map,0,swingFootMod,full_soldier,x']= -0.57771042695298, ['map,0,swingFootMod,full_soldier,y']= -0.80544253889517, ['map,0,swingFootMod,full_soldier,z']= -0.42695564693579, ['map,1,swingFootMod,full_soldier,x']= -0.15693640700714, ['map,1,swingFootMod,full_soldier,y']= -0.40071049608803, ['map,1,swingFootMod,full_soldier,z']= 0.14534467466855, ['map,2,swingFootMod,full_soldier,x']= -0.32552753576639, ['map,2,swingFootMod,full_soldier,y']= 0.31324814884588, ['map,2,swingFootMod,full_soldier,z']= 0.16424899108812, ['map,0,spprtFootMod,full_soldier,x']= 0.91851543511121, ['map,0,spprtFootMod,full_soldier,y']= -3.3389258312123, ['map,0,spprtFootMod,full_soldier,z']= 0.15232574426185, ['map,1,spprtFootMod,full_soldier,x']= -1.0693164674796, ['map,1,spprtFootMod,full_soldier,y']= -1.3798043179207, ['map,1,spprtFootMod,full_soldier,z']= 0.66019455444145, ['map,2,spprtFootMod,full_soldier,x']= 0.71007143520192, ['map,2,spprtFootMod,full_soldier,y']= -1.3256385321975, ['map,2,spprtFootMod,full_soldier,z']= 0.6506256906833, })

elseif g_mode=='a_.1_2' then
	useCases.full_soldier.aObjWeight = .1*useCases.full_soldier.aObjWeight

	useCases.full_soldier.ddqObjWeight=10000000*(25-7)
	useCases.full_soldier.aObjWeight=100000000*62
	useCases.full_soldier.lambdaObjWeight=100
	useCases.full_soldier.EEobjWeight=10000000
	useCases.full_soldier.EEobjWeightAngular=100
	useCases.full_soldier.momentumWeight=10000000
	useCases.full_soldier.lambdaObjWeight=1000000

	--iter:113 bestfvever:1.4749844685567e-06
	accumulate({['map,0,swingFootMod,full_soldier,x']= -0.87617154321252, ['map,0,swingFootMod,full_soldier,y']= -1.4794444728673, ['map,0,swingFootMod,full_soldier,z']= -0.36143419833103, ['map,1,swingFootMod,full_soldier,x']= 0.060818447943078, ['map,1,swingFootMod,full_soldier,y']= -0.20154771509009, ['map,1,swingFootMod,full_soldier,z']= 0.23824914710658, ['map,2,swingFootMod,full_soldier,x']= -0.27783684345467, ['map,2,swingFootMod,full_soldier,y']= -0.4924839951304, ['map,2,swingFootMod,full_soldier,z']= -0.026274785481015, ['map,0,spprtFootMod,full_soldier,x']= 0.66104293417236, ['map,0,spprtFootMod,full_soldier,y']= -1.722494299154, ['map,0,spprtFootMod,full_soldier,z']= 0.063477749901525, ['map,1,spprtFootMod,full_soldier,x']= 1.4152451725427, ['map,1,spprtFootMod,full_soldier,y']= -1.8320057194965, ['map,1,spprtFootMod,full_soldier,z']= -0.41563442802667, ['map,2,spprtFootMod,full_soldier,x']= 1.4709050958508, ['map,2,spprtFootMod,full_soldier,y']= -2.3508427766902, ['map,2,spprtFootMod,full_soldier,z']= -0.78095734896667, })

elseif g_mode=='a_.1_2_g2592' then
	useCases.full_soldier.aObjWeight = .1*useCases.full_soldier.aObjWeight

	useCases.full_soldier.ddqObjWeight=10000000*(25-7)
	useCases.full_soldier.aObjWeight=100000000*62
	useCases.full_soldier.lambdaObjWeight=100
	useCases.full_soldier.EEobjWeight=10000000
	useCases.full_soldier.EEobjWeightAngular=100
	useCases.full_soldier.momentumWeight=10000000
	useCases.full_soldier.lambdaObjWeight=1000000

	--g2592
	--iter:125 bestfvever:6.6330542158609e-07
	accumulate({['map,0,swingFootMod,full_soldier,x']= 0.11972458212199, ['map,0,swingFootMod,full_soldier,y']= -0.37980591981617, ['map,0,swingFootMod,full_soldier,z']= 0.48411399540893, ['map,1,swingFootMod,full_soldier,x']= -0.024747501139378, ['map,1,swingFootMod,full_soldier,y']= -0.027650989636261, ['map,1,swingFootMod,full_soldier,z']= -0.092615566569568, ['map,2,swingFootMod,full_soldier,x']= -0.19019982434314, ['map,2,swingFootMod,full_soldier,y']= 0.34258241545261, ['map,2,swingFootMod,full_soldier,z']= -0.096589510735512, ['map,0,spprtFootMod,full_soldier,x']= 0.22158728585089, ['map,0,spprtFootMod,full_soldier,y']= -0.21783285667065, ['map,0,spprtFootMod,full_soldier,z']= 0.026413337559883, ['map,1,spprtFootMod,full_soldier,x']= 0.27586971393953, ['map,1,spprtFootMod,full_soldier,y']= 0.055171460742169, ['map,1,spprtFootMod,full_soldier,z']= -0.34541186794417, ['map,2,spprtFootMod,full_soldier,x']= -0.18252187946132, ['map,2,spprtFootMod,full_soldier,y']= -0.43678204444012, ['map,2,spprtFootMod,full_soldier,z']= 0.017685887937767, })

	--iter:99 bestfvever:1.2647298196633e-06
	accumulate({['map,0,swingFootMod,full_soldier,x']= 0.19673311506516, ['map,0,swingFootMod,full_soldier,y']= -0.67930982558069, ['map,0,swingFootMod,full_soldier,z']= -0.19744240596486, ['map,1,swingFootMod,full_soldier,x']= -0.4326443106041, ['map,1,swingFootMod,full_soldier,y']= -0.34651931247131, ['map,1,swingFootMod,full_soldier,z']= 0.3225479969801, ['map,2,swingFootMod,full_soldier,x']= -0.34124760846621, ['map,2,swingFootMod,full_soldier,y']= 0.96442496279027, ['map,2,swingFootMod,full_soldier,z']= -0.20292661034047, ['map,0,spprtFootMod,full_soldier,x']= 1.0787890953763, ['map,0,spprtFootMod,full_soldier,y']= -3.5210447019561, ['map,0,spprtFootMod,full_soldier,z']= -0.10172683053841, ['map,1,spprtFootMod,full_soldier,x']= 1.2659048201396, ['map,1,spprtFootMod,full_soldier,y']= -1.3876284725538, ['map,1,spprtFootMod,full_soldier,z']= -0.46117764315923, ['map,2,spprtFootMod,full_soldier,x']= -0.34257323513038, ['map,2,spprtFootMod,full_soldier,y']= -1.1493722293394, ['map,2,spprtFootMod,full_soldier,z']= -0.065317175698783, })

end
-------------------------------------------------

useCases.unmapControlParam(useCases.full_soldier)
end


