package.path=package.path..";../Samples/ysscripts/lib/?.lua" --;"..package.path
require("utilfunc")

package.path=package.path..";../Samples/ysscripts/samples/?.lua" --;"..package.path
--require("useCaseMuscle_gait1956_6steps")
require("useCaseMuscle")

--useCases.g2592_device=deepCopyTable(useCases.gait1956_6steps)
useCases.g2592_device=deepCopyTable(useCases.gait_muscle)
-- set actuationType = a

-- locomotion device
-- g_mode = "*dev_(*part)"
require("WalkingDevice")


-- dcjo-artificial Joint
--useCases.g2592_device.fixedJoints = {'ankle_r', 'mtp_r'}
--useCases.g2592_device.unusedMuscles={'ankle_r', 'mtp_r'}
--useCases.g2592_device.artificialJoints={'knee_r', 'ankle_r', 'mtp_r'}

useCases.g2592_device.artObjWeight=1e-6

--useCases.g2592_device.artificialJoints={'hip_r', 'hip_l'}
--useCases.g2592_device.artificialJoints={'knee_r', 'knee_l'}
--useCases.g2592_device.artificialJoints={'ankle_r', 'ankle_l'}
--useCases.g2592_device.artificialJoints={'mtp_r', 'mtp_l'}
----useCases.g2592_device.artificialJoints={'hip_r', 'hip_l', 'knee_r', 'knee_l', 'ankle_r', 'ankle_l'}

-- dcjo modify motion
-- {i_joint, offset angle}
--useCases.g2592_device.modifyMotion = {{11, 20},}


useCases.g2592_device.optimizerMethod='Optimizer.methods.CMAes_ys'

--useCases.g2592_device.endSegW=10
useCases.g2592_device.endSegW=15
useCases.g2592_device.prec=.2
--useCases.g2592_device.endSegW=20
--useCases.g2592_device.prec=.05

useCases.g2592_device.modelName='g2592_device'
useCases.g2592_device.grpName='g2592_device'
useCases.g2592_device.grpNames={'g2592_device'}

-- nearest to human MET
useCases.g2592_device.ddqObjWeight=10*(25-7)
useCases.g2592_device.tauObjWeight=10
useCases.g2592_device.aObjWeight=5000*62
useCases.g2592_device.lambdaObjWeight=.0001
useCases.g2592_device.EEobjWeight=100
useCases.g2592_device.EEobjWeightAngular=10
useCases.g2592_device.momentumWeight=10


-- the initial pendControlParam and pendOptimizationPath can be automatically generated by using createInitialPendControlParam.lua
useCases.g2592_device.pendControlParam=
{
	['keyframe,0,pendDesiredVel,g2592_device,l,z']=0,['keyframe,0,pendDesiredVel,g2592_device,l,x']=1,['keyframe,0,pendDesiredVel,g2592_device,r,z']=0,['keyframe,0,pendDesiredVel,g2592_device,r,x']=1,['keyframe,0,pendDesiredVel,g2592_device,L1,z']=0,['keyframe,0,pendDesiredVel,g2592_device,L1,x']=1,['keyframe,0,pendDesiredVel,g2592_device,R1,z']=0,['keyframe,0,pendDesiredVel,g2592_device,R1,x']=1,['keyframe,0,pendDesiredVel,g2592_device,L2,z']=0,['keyframe,0,pendDesiredVel,g2592_device,L2,x']=1,['keyframe,0,pendDesiredVel,ignore,0,z']=0,['keyframe,0,pendDesiredVel,ignore,0,x']=1,['keyframe,0,pendDesiredVel,ignore,1,z']=0,['keyframe,0,pendDesiredVel,ignore,1,x']=1,
	['keyframe,0,pendDesiredVel,ignore,0,x']=0.55721712382895, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.11549022684414, ['keyframe,0,pendDesiredVel,g2592_device,l,x']=0.83765088460274, ['keyframe,0,pendDesiredVel,g2592_device,l,z']=-0.03971153581855, ['keyframe,0,pendDesiredVel,g2592_device,r,x']=1.0292990315838, ['keyframe,0,pendDesiredVel,g2592_device,r,z']=0.012304645261958, ['keyframe,0,pendDesiredVel,g2592_device,L1,x']=1.0830140604807, ['keyframe,0,pendDesiredVel,g2592_device,L1,z']=0.021311276252793, ['keyframe,0,pendDesiredVel,g2592_device,R1,x']=1.0448069373172, ['keyframe,0,pendDesiredVel,g2592_device,R1,z']=0.015212087553609, ['keyframe,0,pendDesiredVel,g2592_device,L2,x']=0.99864134148705, ['keyframe,0,pendDesiredVel,g2592_device,L2,z']=0.011195374086852, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.9726342007727, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.0046873881077062, 
	['keyframe,0,pendDesiredVel,ignore,0,x']=-0.038573565913782, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.42183387297139, ['keyframe,0,pendDesiredVel,g2592_device,l,x']=2.8733663187598, ['keyframe,0,pendDesiredVel,g2592_device,l,z']=0.77374805250546, 
	['keyframe,0,pendDesiredVel,ignore,0,x']=-0.03848565284349, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.42174541529281, ['keyframe,0,pendDesiredVel,g2592_device,l,x']=2.8733683928023, ['keyframe,0,pendDesiredVel,g2592_device,l,z']=0.77375288187355, 
	['keyframe,0,pendDesiredVel,g2592_device,l,x']=1.8518302499598, ['keyframe,0,pendDesiredVel,g2592_device,l,z']=0.32721002628792, ['keyframe,0,pendDesiredVel,g2592_device,r,x']=0.64195188458919, ['keyframe,0,pendDesiredVel,g2592_device,r,z']=-0.23746102054191, ['keyframe,0,pendDesiredVel,g2592_device,L1,x']=1.0569602524197, ['keyframe,0,pendDesiredVel,g2592_device,L1,z']=0.0089665722850331, 
	['keyframe,0,pendDesiredVel,g2592_device,r,x']=0.65321586961613, ['keyframe,0,pendDesiredVel,g2592_device,r,z']=-0.23322355700538, ['keyframe,0,pendDesiredVel,g2592_device,L1,x']=1.1600582644838, ['keyframe,0,pendDesiredVel,g2592_device,L1,z']=0.16409120361367, ['keyframe,0,pendDesiredVel,g2592_device,R1,x']=1.0469024908636, ['keyframe,0,pendDesiredVel,g2592_device,R1,z']=0.021499874539069, 
	['keyframe,0,pendDesiredVel,ignore,0,x']=0.057317680328125, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.37352874903012, ['keyframe,0,pendDesiredVel,g2592_device,l,x']=1.688193340133, ['keyframe,0,pendDesiredVel,g2592_device,l,z']=0.33135464415606, ['keyframe,0,pendDesiredVel,g2592_device,r,x']=0.56260872770468, ['keyframe,0,pendDesiredVel,g2592_device,r,z']=-0.29475535050687, 
	['keyframe,0,pendDesiredVel,g2592_device,l,x']=1.6732338838641, ['keyframe,0,pendDesiredVel,g2592_device,l,z']=0.31227141866769, ['keyframe,0,pendDesiredVel,g2592_device,r,x']=0.72633156918842, ['keyframe,0,pendDesiredVel,g2592_device,r,z']=-0.30056568375898, ['keyframe,0,pendDesiredVel,g2592_device,L1,x']=1.1885783553992, ['keyframe,0,pendDesiredVel,g2592_device,L1,z']=0.18162859438481, 
	['keyframe,0,pendDesiredVel,g2592_device,r,x']=0.72682249891879, ['keyframe,0,pendDesiredVel,g2592_device,r,z']=-0.27195354224673, ['keyframe,0,pendDesiredVel,g2592_device,L1,x']=1.1844005645379, ['keyframe,0,pendDesiredVel,g2592_device,L1,z']=0.21070016989902, ['keyframe,0,pendDesiredVel,g2592_device,R1,x']=1.0436382930349, ['keyframe,0,pendDesiredVel,g2592_device,R1,z']=0.019573432369505, 
	['keyframe,0,pendDesiredVel,g2592_device,L1,x']=1.1546812185886, ['keyframe,0,pendDesiredVel,g2592_device,L1,z']=0.13057608466461, ['keyframe,0,pendDesiredVel,g2592_device,R1,x']=1.0169825693409, ['keyframe,0,pendDesiredVel,g2592_device,R1,z']=-0.031308161078641, ['keyframe,0,pendDesiredVel,g2592_device,L2,x']=0.99332532373797, ['keyframe,0,pendDesiredVel,g2592_device,L2,z']=0.023230828039423, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.97210147412166, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.0051664564521254, 
}
useCases.g2592_device.pendOptimizationPath=
{
	firstFrames={1*2,39*2,77*2,115*2,153*2,191*2,229*2,266*2},
	segments={'ignore,0','g2592_device,l','g2592_device,r','g2592_device,L1','g2592_device,R1','g2592_device,L2','ignore,1'},
}
--useCases.g2592_device.measureOptCost=useCases.measureOptCost

useCases.g2592_device.segmentations=
{
	g2592_device={
		firstFrames={1*2,39*2,77*2,115*2,153*2,191*2,229*2,266*2},
		--        (blank)    L    R     L     R     L     (blank)
		names={             'l', 'r', 'L1', 'R1', 'L2',  },
		swingL={             0,   1,   0,    1,    0,    },
		swingR={             1,   0,   1,    0,    1,    },
		footRefL= "convertFromSwingL",
		footRefR= "convertFromSwingR",
		usePositionControl=false,
	},
}
useCases.g2592_device.graphParam=
{
	g2592_device={
		seg={            'l',  'r',  'L1', 'R1','L'},
		num_key={         3,    3,    3  ,  4,  4},
		key_first={       0,    0,    0  ,  0,  0},
		key_last={       'r', 'L1',  'R1', 'L', 'R1'},
	},
}
useCases.g2592_device.graph=
{
	{
		"addInterpolatedSegment",
		grpName="g2592_device",
		name="L",
		seg0={"g2592_device", "L2"},
		seg1={"g2592_device", "L1"},
		startWeight=0, endWeight=1
	},
	{"connectMulti", "g2592_device", "l", "r", "L1", "R1", "L", "R1"},
	--{"initialSegment", "g2592_device", "l"}
	{"initialSegment", "g2592_device", "R1"}
}
useCases.g2592_device.segNames=
{
	"l", "r", "L1", 'R1','L',
}

do 
	useCases.g2592_device.controlParam={
		['useCases,g2592_device,COMobjWeight']=0, 
		['useCases,g2592_device,conservativeW']=1, 
		--['useCases,g2592_device,contactMargin']=0.01, 
		['useCases,g2592_device,dotMomentumScale']=0.3, 
		['useCases,g2592_device,excludeRoot']=true, 
		['useCases,g2592_device,headControlWeight']=0, 
		['useCases,g2592_device,k_d_HEAD']=14, 
		['useCases,g2592_device,k_p_HEAD']=0, 
		['useCases,g2592_device,k_d_EE']=24, 
		['useCases,g2592_device,k_d_momentum']=10, 
		['useCases,g2592_device,k_p_EE']=120, 

		--['useCases,g2592_device,maxPenetratingVel']=0, 
		['useCases,g2592_device,momentumThr']=50, 
		['useCases,g2592_device,noComvelDependentFootAdjustment']=true, 
		['useCases,g2592_device,noIntersectionPrevenction']=true, 
		['useCases,g2592_device,numericalDerivDmot']=true, 
		['useCases,g2592_device,perClassContactMargin']=1, 
		['useCases,g2592_device,turnGain']=10, 
		['useCases,g2592_device,velMarginOffset']=0, 

		['useCases,g2592_device,actuationType']      = useCases.g2592_device.actuationType,
		['useCases,g2592_device,k_p_ID']             = useCases.g2592_device.k_p_ID,
		['useCases,g2592_device,k_d_ID']             = useCases.g2592_device.k_d_ID,
		['useCases,g2592_device,ddqObjWeight']       = useCases.g2592_device.ddqObjWeight,
		['useCases,g2592_device,tauObjWeight']       = useCases.g2592_device.tauObjWeight,
		['useCases,g2592_device,ftObjWeight']        = useCases.g2592_device.ftObjWeight,
		['useCases,g2592_device,aObjWeight']         = useCases.g2592_device.aObjWeight,
		['useCases,g2592_device,lambdaObjWeight']    = useCases.g2592_device.lambdaObjWeight,
		['useCases,g2592_device,EEobjWeight']        = useCases.g2592_device.EEobjWeight,
		['useCases,g2592_device,EEobjWeightAngular'] = useCases.g2592_device.EEobjWeightAngular,
		['useCases,g2592_device,momentumWeight']     = useCases.g2592_device.momentumWeight,
		['useCases,g2592_device,tauMax']             = useCases.g2592_device.tauMax,
		['useCases,g2592_device,ftMax']              = useCases.g2592_device.ftMax,
	}

	local function accumulate(cp_mod)
		local useCase=useCases.g2592_device
		useCases.accumulate(useCase, cp_mod)
	end

	--accumulate({
		----['keyframe,0,footRmod,g2592_device,l,y']  = 0.,
		--['keyframe,1,footRmod,g2592_device,l,y']  = 0.05,
		--['keyframe,0,footLmod,g2592_device,r,y']  = 0.05,
		--['keyframe,1,footLmod,g2592_device,r,y']  = 0.1,
		--['keyframe,0,footRmod,g2592_device,L1,y'] = 0.0,
		--['keyframe,1,footRmod,g2592_device,L1,y'] = 0.1,
		--['map,0,swingFootMod,g2592_device,y']     = 0.1,
		--['map,1,swingFootMod,g2592_device,y']     = 0.3,
		--['map,2,swingFootMod,g2592_device,y']     = 0.2,

		------['keyframe,0,footLmod,g2592_device,l,y']  = 0.,
		------['keyframe,1,footLmod,g2592_device,l,y']  = 0.,
		----['keyframe,0,footRmod,g2592_device,r,y']  = 0.,
		----['keyframe,1,footRmod,g2592_device,r,y']  = -.1,
		----['keyframe,0,footLmod,g2592_device,L1,y'] = 0.,
		----['keyframe,1,footLmod,g2592_device,L1,y'] = -.1,
		----['map,0,spprtFootMod,g2592_device,y']     = 0.,
		----['map,1,spprtFootMod,g2592_device,y']     = 0.,
		----['map,2,spprtFootMod,g2592_device,y']     = 0.,
	--})
	useCases.unmapControlParam(useCases.g2592_device)


	-------------------------------------------------
	local R_hip_flex={'add_brev_r', 'add_long_r', 'glut_med1_r', 'glut_min1_r', 'grac_r', 'iliacus_r', 'pect_r', 'psoas_r', 'rect_fem_r', 'sar_r', 'tfl_r'}
	local R_hip_ext={'add_long_r', 'add_mag1_r', 'add_mag2_r', 'add_mag3_r', 'bifemlh_r', 'glut_max1_r', 'glut_max2_r', 'glut_max3_r', 'glut_med3_r', 'glut_min3_r', 'semimem_r', 'semiten_r'}
	local R_hip_abd={'glut_max1_r', 'glut_med1_r', 'glut_med2_r', 'glut_med3_r', 'glut_min1_r', 'glut_min2_r', 'glut_min3_r', 'peri_r', 'sar_r', 'tfl_r'}
	local R_hip_add={'add_brev_r', 'add_long_r', 'add_mag1_r', 'add_mag2_r', 'add_mag3_r', 'bifemlh_r', 'grac_r', 'pect_r', 'semimem_r', 'semiten_r'}
	local R_knee_bend={'bifemlh_r', 'bifemsh_r', 'grac_r', 'lat_gas_r', 'med_gas_r', 'sar_r', 'semimem_r', 'semiten_r'}
	local R_knee_ext={'rect_fem_r', 'vas_int_r', 'vas_lat_r', 'vas_med_r'}
	local R_ankle_pf={'flex_dig_r', 'flex_hal_r', 'lat_gas_r', 'med_gas_r', 'per_brev_r', 'per_long_r', 'soleus_r', 'tib_post_r'}
	local R_ankle_df={'ext_dig_r', 'ext_hal_r', 'per_tert_r', 'tib_ant_r'}

	local L_hip_flex={'add_brev_l', 'add_long_l', 'glut_med1_l', 'glut_min1_l', 'grac_l', 'iliacus_l', 'pect_l', 'psoas_l', 'rect_fem_l', 'sar_l', 'tfl_l'}
	local L_hip_ext={'add_long_l', 'add_mag1_l', 'add_mag2_l', 'add_mag3_l', 'bifemlh_l', 'glut_max1_l', 'glut_max2_l', 'glut_max3_l', 'glut_med3_l', 'glut_min3_l', 'semimem_l', 'semiten_l'}
	local L_hip_abd={'glut_max1_l', 'glut_med1_l', 'glut_med2_l', 'glut_med3_l', 'glut_min1_l', 'glut_min2_l', 'glut_min3_l', 'peri_l', 'sar_l', 'tfl_l'}
	local L_hip_add={'add_brev_l', 'add_long_l', 'add_mag1_l', 'add_mag2_l', 'add_mag3_l', 'bifemlh_l', 'grac_l', 'pect_l', 'semimem_l', 'semiten_l'}
	local L_knee_bend={'bifemlh_l', 'bifemsh_l', 'grac_l', 'lat_gas_l', 'med_gas_l', 'sar_l', 'semimem_l', 'semiten_l'}
	local L_knee_ext={'rect_fem_l', 'vas_int_l', 'vas_lat_l', 'vas_med_l'}
	local L_ankle_pf={'flex_dig_l', 'flex_hal_l', 'lat_gas_l', 'med_gas_l', 'per_brev_l', 'per_long_l', 'soleus_l', 'tib_post_l'}
	local L_ankle_df={'ext_dig_l', 'ext_hal_l', 'per_tert_l', 'tib_ant_l'}

	local glut_meds={'glut_med1_r', 'glut_med2_r', 'glut_med3_r', 'glut_med1_l', 'glut_med2_l', 'glut_med3_l'}
	local glut_mins={'glut_min1_r', 'glut_min2_r', 'glut_min3_r', 'glut_min1_l', 'glut_min2_l', 'glut_min3_l'}

	local lglut_meds={'glut_med1_l', 'glut_med2_l', 'glut_med3_l'}
	local lglut_mins={'glut_min1_l', 'glut_min2_l', 'glut_min3_l'}

	local hamstrings={'semiten_r','semiten_l', 'semimem_r', 'semimem_l', 'bifemlh_r', 'bifemsh_r', 'bifemlh_l', 'bifemsh_l'}
	local rect_fems={'rect_fem_l', 'rect_fem_r'}
	local psoases={'psoas_r', 'psoas_l'}

	if g_mode=='default' then
		g_nobugfix=true

	elseif g_mode=='mscl_gluts.3' then
		useCases.g2592_device.weakRatio = .3
		useCases.g2592_device.weakenMuscles = concat_array(glut_meds,glut_mins)

		--iter:247 bestfvever:1.5411258293345e-06
		accumulate({['map,0,swingFootMod,g2592_device,x']= 0.084104902576201, ['map,0,swingFootMod,g2592_device,y']= -0.2795118634154, ['map,0,swingFootMod,g2592_device,z']= 0.38234092271528, ['map,1,swingFootMod,g2592_device,x']= -0.17520538012601, ['map,1,swingFootMod,g2592_device,y']= 0.27713240619468, ['map,1,swingFootMod,g2592_device,z']= 0.29138923018548, ['map,2,swingFootMod,g2592_device,x']= 0.079794842363994, ['map,2,swingFootMod,g2592_device,y']= 0.20384365916209, ['map,2,swingFootMod,g2592_device,z']= -0.11736936627262, ['map,0,spprtFootMod,g2592_device,x']= 0.12204581737635, ['map,0,spprtFootMod,g2592_device,y']= -0.43228441282781, ['map,0,spprtFootMod,g2592_device,z']= 0.024882443829058, ['map,1,spprtFootMod,g2592_device,x']= -0.025872834607399, ['map,1,spprtFootMod,g2592_device,y']= -0.72379159476432, ['map,1,spprtFootMod,g2592_device,z']= 0.096520203435377, ['map,2,spprtFootMod,g2592_device,x']= 0.18831560902863, ['map,2,spprtFootMod,g2592_device,y']= -0.2606555398388, ['map,2,spprtFootMod,g2592_device,z']= -0.24857266599997, })


	elseif g_mode=='a_.1_obj_lfootcf' then
		useCases.g2592_device.cmaLFootCFWeight = 1e-6
		useCases.g2592_device.aObjWeight = .1*useCases.g2592_device.aObjWeight

		--iter:231 bestfvever:8.4117614887887e-05
		accumulate({['map,0,swingFootMod,g2592_device,x']= -0.4264748701196, ['map,0,swingFootMod,g2592_device,y']= -0.75498972178353, ['map,0,swingFootMod,g2592_device,z']= 1.2909724485451, ['map,1,swingFootMod,g2592_device,x']= 0.57596168953152, ['map,1,swingFootMod,g2592_device,y']= 0.050657678710419, ['map,1,swingFootMod,g2592_device,z']= 0.28174041795835, ['map,2,swingFootMod,g2592_device,x']= -0.42174557501958, ['map,2,swingFootMod,g2592_device,y']= 0.5085119237765, ['map,2,swingFootMod,g2592_device,z']= -0.13548422868284, ['map,0,spprtFootMod,g2592_device,x']= -0.26040717439572, ['map,0,spprtFootMod,g2592_device,y']= -0.030864716067642, ['map,0,spprtFootMod,g2592_device,z']= 0.17850092257967, ['map,1,spprtFootMod,g2592_device,x']= 0.32160819032006, ['map,1,spprtFootMod,g2592_device,y']= -0.24338726696657, ['map,1,spprtFootMod,g2592_device,z']= -0.34861936517315, ['map,2,spprtFootMod,g2592_device,x']= -0.40565915745086, ['map,2,spprtFootMod,g2592_device,y']= -0.74525647459302, ['map,2,spprtFootMod,g2592_device,z']= 0.23568437757752, })

		useCases.g2592_device.endSegW=20
		useCases.g2592_device.prec=.05
		--iter:110 bestfvever:9.2534294960155e-05
		accumulate({['map,0,swingFootMod,g2592_device,x']= -0.54960896090579, ['map,0,swingFootMod,g2592_device,y']= -0.5704460286414, ['map,0,swingFootMod,g2592_device,z']= 1.3040053914228, ['map,1,swingFootMod,g2592_device,x']= 0.41160157089587, ['map,1,swingFootMod,g2592_device,y']= 0.04647467148143, ['map,1,swingFootMod,g2592_device,z']= 0.21631371738541, ['map,2,swingFootMod,g2592_device,x']= -0.47886134473257, ['map,2,swingFootMod,g2592_device,y']= 0.4825650348336, ['map,2,swingFootMod,g2592_device,z']= 0.064491481093312, ['map,0,spprtFootMod,g2592_device,x']= -0.097433333621464, ['map,0,spprtFootMod,g2592_device,y']= -0.063940892026055, ['map,0,spprtFootMod,g2592_device,z']= 0.16773782007232, ['map,1,spprtFootMod,g2592_device,x']= 0.16956678723449, ['map,1,spprtFootMod,g2592_device,y']= -0.18221700886986, ['map,1,spprtFootMod,g2592_device,z']= -0.29204276147261, ['map,2,spprtFootMod,g2592_device,x']= -0.5501905465412, ['map,2,spprtFootMod,g2592_device,y']= -0.78561233386221, ['map,2,spprtFootMod,g2592_device,z']= 0.24646598389936, })

	elseif g_mode=='a_.1_mscl_glut.2' then
		useCases.g2592_device.aObjWeight = .1*useCases.g2592_device.aObjWeight
		useCases.g2592_device.weakRatio = .2
		useCases.g2592_device.weakenMuscles = concat_array(lglut_meds,lglut_mins, rglut_meds, rglut_mins)
		
		useCases.g2592_device.endSegW=25
		useCases.g2592_device.prec=.2
		-- 50469.0679
		accumulate({['map,0,swingFootMod,g2592_device,x']= -0.24873969302456, ['map,0,swingFootMod,g2592_device,y']= -0.14569040417123, ['map,0,swingFootMod,g2592_device,z']= 0.14036516404054, ['map,1,swingFootMod,g2592_device,x']= 0.13725690137005, ['map,1,swingFootMod,g2592_device,y']= 0.3063626641799, ['map,1,swingFootMod,g2592_device,z']= -0.10990168668606, ['map,2,swingFootMod,g2592_device,x']= -0.11821537140836, ['map,2,swingFootMod,g2592_device,y']= 0.50118981049131, ['map,2,swingFootMod,g2592_device,z']= 0.0031192463157646, ['map,0,spprtFootMod,g2592_device,x']= -0.29247818190576, ['map,0,spprtFootMod,g2592_device,y']= -0.66716906142725, ['map,0,spprtFootMod,g2592_device,z']= 0.16089977228772, ['map,1,spprtFootMod,g2592_device,x']= 0.19150101345645, ['map,1,spprtFootMod,g2592_device,y']= 0.21641765135399, ['map,1,spprtFootMod,g2592_device,z']= -0.086018486241001, ['map,2,spprtFootMod,g2592_device,x']= 0.015696861680259, ['map,2,spprtFootMod,g2592_device,y']= -0.076163149579887, ['map,2,spprtFootMod,g2592_device,z']= -0.023228564658548, })

	elseif g_mode=='a_.1_mscl_glut.2_backfreeY' then
		table.insert(useCases.g2592_device.optParamNames, "MAP1bodyBackYMod")
--		table.insert(useCases.g2592_device.optParamNames, "MAP1swingBackYMod")
--		table.insert(useCases.g2592_device.optParamNames, "MAP1spprtBackYMod")
		table.insert(useCases.g2592_device.parts, "BackY")
		useCases.g2592_device.partProps["BackY"] = "all"
		useCases.g2592_device.keyframes["backymod"] = {numKey=3, numKeyFrom='key', default = 0, valueType='scalar'}
		if useCases.g2592_device.maxAngleOffset == nil then
			useCases.g2592_device.maxAngleOffset = {backymax = 30}
		else
			useCases.g2592_device.maxAngleOffset.backymax = 30
		end

		useCases.g2592_device.aObjWeight = .1*useCases.g2592_device.aObjWeight
		useCases.g2592_device.weakRatio = .2
		useCases.g2592_device.weakenMuscles = concat_array(lglut_meds,lglut_mins, rglut_meds, rglut_mins)
		
		useCases.g2592_device.endSegW=25
		useCases.g2592_device.prec=.2

		accumulate({['map,0,swingFootMod,g2592_device,x']= -0.201017077907, ['map,0,swingFootMod,g2592_device,y']= -0.21993915025972, ['map,0,swingFootMod,g2592_device,z']= -0.46433894246634, ['map,1,swingFootMod,g2592_device,x']= 0.51076218152207, ['map,1,swingFootMod,g2592_device,y']= 0.43332287420582, ['map,1,swingFootMod,g2592_device,z']= 0.15099012188281, ['map,2,swingFootMod,g2592_device,x']= -0.0052356279178689, ['map,2,swingFootMod,g2592_device,y']= -0.052895499516206, ['map,2,swingFootMod,g2592_device,z']= -0.073463685805218, ['map,0,spprtFootMod,g2592_device,x']= -0.23979431809276, ['map,0,spprtFootMod,g2592_device,y']= -0.17845248574101, ['map,0,spprtFootMod,g2592_device,z']= 0.11784296606773, ['map,1,spprtFootMod,g2592_device,x']= -0.010037030682757, ['map,1,spprtFootMod,g2592_device,y']= -0.10735265339631, ['map,1,spprtFootMod,g2592_device,z']= -0.01721944375769, ['map,2,spprtFootMod,g2592_device,x']= 0.25279393248399, ['map,2,spprtFootMod,g2592_device,y']= -0.01766609951914, ['map,2,spprtFootMod,g2592_device,z']= -0.18146546859383, ['map,0,bodyBackYMod,g2592_device']= 0.082562438868028, ['map,1,bodyBackYMod,g2592_device']= 0.095743752973537, ['map,2,bodyBackYMod,g2592_device']= 0.2518964258781, })

	elseif g_mode=='a_.1_mscl_glut.2_dev_hipx' then
		useCases.g2592_device.device = WalkingDeviceCMABase
		-- T : timing, D : duration, F : force
		table.insert(useCases.g2592_device.optParamNames, "MAPD1swingDevHipXTMod")
		table.insert(useCases.g2592_device.optParamNames, "MAPD1swingDevHipXDMod")
		table.insert(useCases.g2592_device.optParamNames, "MAPD1swingDevHipXFMod")
		table.insert(useCases.g2592_device.optParamNames, "MAPD1spprtDevHipXTMod")
		table.insert(useCases.g2592_device.optParamNames, "MAPD1spprtDevHipXDMod")
		table.insert(useCases.g2592_device.optParamNames, "MAPD1spprtDevHipXFMod")
		table.insert(useCases.g2592_device.parts, "DevHipXT")
		table.insert(useCases.g2592_device.parts, "DevHipXD")
		table.insert(useCases.g2592_device.parts, "DevHipXF")
		useCases.g2592_device.partProps["DevHipXT"] = "non"
		useCases.g2592_device.partProps["DevHipXD"] = "non"
		useCases.g2592_device.partProps["DevHipXF"] = "non"
		useCases.g2592_device.devParts = {"hipx"}
		useCases.g2592_device.keyframes["devhipxtLmod"] = {numKey=1, numKeyFrom='key', isContinuous = false, default = 0, valueType='scalar'}
		useCases.g2592_device.keyframes["devhipxdLmod"] = {numKey=1, numKeyFrom='key', isContinuous = false, default = 0, valueType='scalar'}
		useCases.g2592_device.keyframes["devhipxfLmod"] = {numKey=1, numKeyFrom='key', isContinuous = false, default = 0, valueType='scalar'}
		useCases.g2592_device.keyframes["devhipxtRmod"] = {numKey=1, numKeyFrom='key', isContinuous = false, default = 0, valueType='scalar'}
		useCases.g2592_device.keyframes["devhipxdRmod"] = {numKey=1, numKeyFrom='key', isContinuous = false, default = 0, valueType='scalar'}
		useCases.g2592_device.keyframes["devhipxfRmod"] = {numKey=1, numKeyFrom='key', isContinuous = false, default = 0, valueType='scalar'}

		useCases.g2592_device.aObjWeight = .1*useCases.g2592_device.aObjWeight
		useCases.g2592_device.weakRatio = .2
		useCases.g2592_device.weakenMuscles = concat_array(lglut_meds,lglut_mins, rglut_meds, rglut_mins)
		
		useCases.g2592_device.endSegW=25
		useCases.g2592_device.prec=.2

		accumulate({['map,0,swingFootMod,g2592_device,x']= -0.046623299048132, ['map,0,swingFootMod,g2592_device,y']= -0.26544593356809, ['map,0,swingFootMod,g2592_device,z']= 0.18218655667339, ['map,1,swingFootMod,g2592_device,x']= 0.31449349059374, ['map,1,swingFootMod,g2592_device,y']= 0.48792525085488, ['map,1,swingFootMod,g2592_device,z']= -0.10653197053771, ['map,2,swingFootMod,g2592_device,x']= -0.16385275851133, ['map,2,swingFootMod,g2592_device,y']= 0.0087772853785114, ['map,2,swingFootMod,g2592_device,z']= -0.0036462116614194, ['map,0,spprtFootMod,g2592_device,x']= 0.14711118735564, ['map,0,spprtFootMod,g2592_device,y']= -0.72492342028113, ['map,0,spprtFootMod,g2592_device,z']= 0.18839374731739, ['map,1,spprtFootMod,g2592_device,x']= 0.10892291002216, ['map,1,spprtFootMod,g2592_device,y']= 0.12266897113935, ['map,1,spprtFootMod,g2592_device,z']= 0.029577171195436, ['map,2,spprtFootMod,g2592_device,x']= 0.17507384397253, ['map,2,spprtFootMod,g2592_device,y']= 0.048995344830303, ['map,2,spprtFootMod,g2592_device,z']= 0.066206481838411, ['map,0,swingDevHipXTMod,g2592_device']= 0.052457170741829, ['map,0,swingDevHipXDMod,g2592_device']= 0.25396847153566, ['map,0,swingDevHipXFMod,g2592_device']= -0.22035984560268, ['map,0,spprtDevHipXTMod,g2592_device']= 0.032064549616104, ['map,0,spprtDevHipXDMod,g2592_device']= 0.32841391671537, ['map,0,spprtDevHipXFMod,g2592_device']= 0.35974409929108, })

	elseif g_mode=='a_.1_mscl_glut.2_dev_hipy_seg10' then
		useCases.g2592_device.device = WalkingDeviceCMABase
		-- T : timing, D : duration, F : force
		table.insert(useCases.g2592_device.optParamNames, "MAPD1swingDevHipYTMod")
		table.insert(useCases.g2592_device.optParamNames, "MAPD1swingDevHipYDMod")
		table.insert(useCases.g2592_device.optParamNames, "MAPD1swingDevHipYFMod")
		table.insert(useCases.g2592_device.optParamNames, "MAPD1spprtDevHipYTMod")
		table.insert(useCases.g2592_device.optParamNames, "MAPD1spprtDevHipYDMod")
		table.insert(useCases.g2592_device.optParamNames, "MAPD1spprtDevHipYFMod")
		table.insert(useCases.g2592_device.parts, "DevHipYT")
		table.insert(useCases.g2592_device.parts, "DevHipYD")
		table.insert(useCases.g2592_device.parts, "DevHipYF")
		useCases.g2592_device.partProps["DevHipYT"] = "non"
		useCases.g2592_device.partProps["DevHipYD"] = "non"
		useCases.g2592_device.partProps["DevHipYF"] = "all"
		useCases.g2592_device.devParts = {"hipy"}
		useCases.g2592_device.keyframes["devhipytLmod"] = {numKey=1, numKeyFrom='key', isContinuous = false, default = 0, valueType='scalar'}
		useCases.g2592_device.keyframes["devhipydLmod"] = {numKey=1, numKeyFrom='key', isContinuous = false, default = 0, valueType='scalar'}
		useCases.g2592_device.keyframes["devhipyfLmod"] = {numKey=1, numKeyFrom='key', isContinuous = false, default = 0, valueType='scalar'}
		useCases.g2592_device.keyframes["devhipytRmod"] = {numKey=1, numKeyFrom='key', isContinuous = false, default = 0, valueType='scalar'}
		useCases.g2592_device.keyframes["devhipydRmod"] = {numKey=1, numKeyFrom='key', isContinuous = false, default = 0, valueType='scalar'}
		useCases.g2592_device.keyframes["devhipyfRmod"] = {numKey=1, numKeyFrom='key', isContinuous = false, default = 0, valueType='scalar'}

		useCases.g2592_device.aObjWeight = .1*useCases.g2592_device.aObjWeight
		useCases.g2592_device.weakRatio = .2
		useCases.g2592_device.weakenMuscles = concat_array(lglut_meds,lglut_mins, rglut_meds, rglut_mins)
	
		useCases.g2592_device.endSegW=10
		useCases.g2592_device.prec=.2

		-- method 1
		-- 0~0.5 gait : start timing
		-- 0.5~1.0 gait : end timing
		--accumulate({['map,0,swingFootMod,g2592_device,x']= -0.021558298642267, ['map,0,swingFootMod,g2592_device,y']= -0.13465419124626, ['map,0,swingFootMod,g2592_device,z']= 0.089827971130202, ['map,1,swingFootMod,g2592_device,x']= 0.34919371045469, ['map,1,swingFootMod,g2592_device,y']= 0.26242213571559, ['map,1,swingFootMod,g2592_device,z']= -0.070174099087671, ['map,2,swingFootMod,g2592_device,x']= -0.16067124015357, ['map,2,swingFootMod,g2592_device,y']= 0.18998602925948, ['map,2,swingFootMod,g2592_device,z']= 0.016805037432768, ['map,0,spprtFootMod,g2592_device,x']= -0.34422053248324, ['map,0,spprtFootMod,g2592_device,y']= -0.24961309917801, ['map,0,spprtFootMod,g2592_device,z']= 0.15134674393881, ['map,1,spprtFootMod,g2592_device,x']= 0.22639508055669, ['map,1,spprtFootMod,g2592_device,y']= 0.12384318452696, ['map,1,spprtFootMod,g2592_device,z']= 0.042768233965054, ['map,2,spprtFootMod,g2592_device,x']= 0.026308727972554, ['map,2,spprtFootMod,g2592_device,y']= -0.084371247577373, ['map,2,spprtFootMod,g2592_device,z']= -0.024424854596492, ['map,0,swingDevHipYTMod,g2592_device']= 0.21311871895794, ['map,0,swingDevHipYDMod,g2592_device']= 0.20605706546858, ['map,0,swingDevHipYFMod,g2592_device']= 0.04733582618758, ['map,0,spprtDevHipYTMod,g2592_device']= 0.34421976275586, ['map,0,spprtDevHipYDMod,g2592_device']= 0.25131679191564, ['map,0,spprtDevHipYFMod,g2592_device']= -0.094421893627881, })

		-- method 2
		-- t : center of timing
		-- d : half of duration
		--accumulate({['map,0,swingFootMod,g2592_device,x']= -0.021558298642267, ['map,0,swingFootMod,g2592_device,y']= -0.13465419124626, ['map,0,swingFootMod,g2592_device,z']= 0.089827971130202, ['map,1,swingFootMod,g2592_device,x']= 0.34919371045469, ['map,1,swingFootMod,g2592_device,y']= 0.26242213571559, ['map,1,swingFootMod,g2592_device,z']= -0.070174099087671, ['map,2,swingFootMod,g2592_device,x']= -0.16067124015357, ['map,2,swingFootMod,g2592_device,y']= 0.18998602925948, ['map,2,swingFootMod,g2592_device,z']= 0.016805037432768, ['map,0,spprtFootMod,g2592_device,x']= -0.34422053248324, ['map,0,spprtFootMod,g2592_device,y']= -0.24961309917801, ['map,0,spprtFootMod,g2592_device,z']= 0.15134674393881, ['map,1,spprtFootMod,g2592_device,x']= 0.22639508055669, ['map,1,spprtFootMod,g2592_device,y']= 0.12384318452696, ['map,1,spprtFootMod,g2592_device,z']= 0.042768233965054, ['map,2,spprtFootMod,g2592_device,x']= 0.026308727972554, ['map,2,spprtFootMod,g2592_device,y']= -0.084371247577373, ['map,2,spprtFootMod,g2592_device,z']= -0.024424854596492, ['map,0,swingDevHipYTMod,g2592_device']= 0.21311871895794, ['map,0,swingDevHipYDMod,g2592_device']= 0.20605706546858, ['map,0,swingDevHipYFMod,g2592_device']= 0.04733582618758, ['map,0,spprtDevHipYTMod,g2592_device']= 0.34421976275586, ['map,0,spprtDevHipYDMod,g2592_device']= 0.25131679191564, ['map,0,spprtDevHipYFMod,g2592_device']= -0.094421893627881, })


		-- method 3
		-- method 2 + position from ground_pelvis comparison
		accumulate({['map,0,swingFootMod,g2592_device,x']= -0.70164652781312, ['map,0,swingFootMod,g2592_device,y']= -0.50652062709724, ['map,0,swingFootMod,g2592_device,z']= 0.30600177392514, ['map,1,swingFootMod,g2592_device,x']= -0.024981074116246, ['map,1,swingFootMod,g2592_device,y']= 0.44267404252343, ['map,1,swingFootMod,g2592_device,z']= 0.24465779818001, ['map,2,swingFootMod,g2592_device,x']= 0.20089361825968, ['map,2,swingFootMod,g2592_device,y']= -0.0057812951789055, ['map,2,swingFootMod,g2592_device,z']= -0.14938604691284, ['map,0,spprtFootMod,g2592_device,x']= -0.49618611638562, ['map,0,spprtFootMod,g2592_device,y']= -1.4478500378034, ['map,0,spprtFootMod,g2592_device,z']= 0.069258894539738, ['map,1,spprtFootMod,g2592_device,x']= 0.60210835926797, ['map,1,spprtFootMod,g2592_device,y']= -0.64465862348051, ['map,1,spprtFootMod,g2592_device,z']= 0.62414168427294, ['map,2,spprtFootMod,g2592_device,x']= -0.14474168473834, ['map,2,spprtFootMod,g2592_device,y']= -0.20483892455159, ['map,2,spprtFootMod,g2592_device,z']= -0.74376780475054, ['map,0,swingDevHipYTMod,g2592_device']= -0.11034381831594, ['map,0,swingDevHipYDMod,g2592_device']= -0.87667246991038, ['map,0,swingDevHipYFMod,g2592_device']= 0.63247014990065, ['map,0,spprtDevHipYTMod,g2592_device']= 0.26243615922727, ['map,0,spprtDevHipYDMod,g2592_device']= 0.12802262076478, ['map,0,spprtDevHipYFMod,g2592_device']= -0.84589713941155, })


	elseif g_mode=='a_.1_mscl_glut.2_dev_hipy' then
		useCases.g2592_device.device = WalkingDeviceCMABase
		-- T : timing, D : duration, F : force
		table.insert(useCases.g2592_device.optParamNames, "MAPD1swingDevHipYTMod")
		table.insert(useCases.g2592_device.optParamNames, "MAPD1swingDevHipYDMod")
		table.insert(useCases.g2592_device.optParamNames, "MAPD1swingDevHipYFMod")
		table.insert(useCases.g2592_device.optParamNames, "MAPD1spprtDevHipYTMod")
		table.insert(useCases.g2592_device.optParamNames, "MAPD1spprtDevHipYDMod")
		table.insert(useCases.g2592_device.optParamNames, "MAPD1spprtDevHipYFMod")
		table.insert(useCases.g2592_device.parts, "DevHipYT")
		table.insert(useCases.g2592_device.parts, "DevHipYD")
		table.insert(useCases.g2592_device.parts, "DevHipYF")
		useCases.g2592_device.partProps["DevHipYT"] = "non"
		useCases.g2592_device.partProps["DevHipYD"] = "non"
		useCases.g2592_device.partProps["DevHipYF"] = "all"
		useCases.g2592_device.devParts = {"hipy"}
		useCases.g2592_device.keyframes["devhipytLmod"] = {numKey=1, numKeyFrom='key', isContinuous = false, default = 0, valueType='scalar'}
		useCases.g2592_device.keyframes["devhipydLmod"] = {numKey=1, numKeyFrom='key', isContinuous = false, default = 0, valueType='scalar'}
		useCases.g2592_device.keyframes["devhipyfLmod"] = {numKey=1, numKeyFrom='key', isContinuous = false, default = 0, valueType='scalar'}
		useCases.g2592_device.keyframes["devhipytRmod"] = {numKey=1, numKeyFrom='key', isContinuous = false, default = 0, valueType='scalar'}
		useCases.g2592_device.keyframes["devhipydRmod"] = {numKey=1, numKeyFrom='key', isContinuous = false, default = 0, valueType='scalar'}
		useCases.g2592_device.keyframes["devhipyfRmod"] = {numKey=1, numKeyFrom='key', isContinuous = false, default = 0, valueType='scalar'}

		useCases.g2592_device.aObjWeight = .1*useCases.g2592_device.aObjWeight
		useCases.g2592_device.weakRatio = .2
		useCases.g2592_device.weakenMuscles = concat_array(lglut_meds,lglut_mins, rglut_meds, rglut_mins)

		useCases.g2592_device.endSegW=25
		useCases.g2592_device.prec=.2

		-- 25 seg, 42678.118572029
		accumulate({['map,0,swingFootMod,g2592_device,x']= 0.35031362742297, ['map,0,swingFootMod,g2592_device,y']= -0.19228640763538, ['map,0,swingFootMod,g2592_device,z']= 0.10096599528018, ['map,1,swingFootMod,g2592_device,x']= 0.25671755975922, ['map,1,swingFootMod,g2592_device,y']= 0.44697779777875, ['map,1,swingFootMod,g2592_device,z']= 0.020147201468348, ['map,2,swingFootMod,g2592_device,x']= -0.14059598755759, ['map,2,swingFootMod,g2592_device,y']= 0.14728345134096, ['map,2,swingFootMod,g2592_device,z']= -0.04358765577771, ['map,0,spprtFootMod,g2592_device,x']= -0.35091448176724, ['map,0,spprtFootMod,g2592_device,y']= -0.13964821636611, ['map,0,spprtFootMod,g2592_device,z']= 0.22321117920303, ['map,1,spprtFootMod,g2592_device,x']= 0.16119982506832, ['map,1,spprtFootMod,g2592_device,y']= 0.1098674526054, ['map,1,spprtFootMod,g2592_device,z']= 0.041677801223471, ['map,2,spprtFootMod,g2592_device,x']= 0.27558062097508, ['map,2,spprtFootMod,g2592_device,y']= -0.19562998638863, ['map,2,spprtFootMod,g2592_device,z']= -0.05899627059554, ['map,0,swingDevHipYTMod,g2592_device']= -0.3239654481226, ['map,0,swingDevHipYDMod,g2592_device']= -0.19756080284444, ['map,0,swingDevHipYFMod,g2592_device']= -0.11925551315533, ['map,0,spprtDevHipYTMod,g2592_device']= 0.10215911887255, ['map,0,spprtDevHipYDMod,g2592_device']= 0.15334811645689, ['map,0,spprtDevHipYFMod,g2592_device']= -0.19052002101132, })

	
	elseif g_mode=='a_.1_mscl_lglut.2' then
		useCases.g2592_device.aObjWeight = .1*useCases.g2592_device.aObjWeight
		useCases.g2592_device.weakRatio = .2
		useCases.g2592_device.weakenMuscles = concat_array(lglut_meds,lglut_mins)

		-- endSegW = 20, prec = 0.2
		--accumulate({['map,0,swingFootMod,g2592_device,x']= 0.47338335291662, ['map,0,swingFootMod,g2592_device,y']= -0.31223218363837, ['map,0,swingFootMod,g2592_device,z']= -0.12090840018645, ['map,1,swingFootMod,g2592_device,x']= -0.12256445786362, ['map,1,swingFootMod,g2592_device,y']= 0.40754105942224, ['map,1,swingFootMod,g2592_device,z']= -0.052417670785882, ['map,2,swingFootMod,g2592_device,x']= -0.020672322084811, ['map,2,swingFootMod,g2592_device,y']= 0.13353166437003, ['map,2,swingFootMod,g2592_device,z']= -0.074645517870081, ['map,0,spprtFootMod,g2592_device,x']= 0.12582379468334, ['map,0,spprtFootMod,g2592_device,y']= -0.55082339654098, ['map,0,spprtFootMod,g2592_device,z']= 0.29112553254523, ['map,1,spprtFootMod,g2592_device,x']= 0.35054725040228, ['map,1,spprtFootMod,g2592_device,y']= 0.13524822450914, ['map,1,spprtFootMod,g2592_device,z']= -0.3228162734098, ['map,2,spprtFootMod,g2592_device,x']= 0.29160570469134, ['map,2,spprtFootMod,g2592_device,y']= -0.27821680884089, ['map,2,spprtFootMod,g2592_device,z']= -0.21077184873791, })

		--iter:178 bestfvever:1.8077298153896e-06

		useCases.g2592_device.endSegW=25
--		useCases.g2592_device.prec=.05
		useCases.g2592_device.prec=.2

		-- modified objfn
		-- endSegW = 25, prec = 0.2


		-- 10e8, 10e8 * 5
		--accumulate({['map,0,swingFootMod,g2592_device,x']= 0.16197063175209, ['map,0,swingFootMod,g2592_device,y']= -0.31641819901558, ['map,0,swingFootMod,g2592_device,z']= 0.43691579081528, ['map,1,swingFootMod,g2592_device,x']= 0.34800084662783, ['map,1,swingFootMod,g2592_device,y']= 0.47711625553257, ['map,1,swingFootMod,g2592_device,z']= 0.021106771823709, ['map,2,swingFootMod,g2592_device,x']= -0.18706294341819, ['map,2,swingFootMod,g2592_device,y']= 0.21693328848793, ['map,2,swingFootMod,g2592_device,z']= -0.040606199438682, ['map,0,spprtFootMod,g2592_device,x']= 0.092861090812486, ['map,0,spprtFootMod,g2592_device,y']= -0.019120578582158, ['map,0,spprtFootMod,g2592_device,z']= 0.21890605871568, ['map,1,spprtFootMod,g2592_device,x']= -0.32344236076825, ['map,1,spprtFootMod,g2592_device,y']= -0.23042027476012, ['map,1,spprtFootMod,g2592_device,z']= 0.076904439489764, ['map,2,spprtFootMod,g2592_device,x']= 0.11481701032325, ['map,2,spprtFootMod,g2592_device,y']= 0.18951526233271, ['map,2,spprtFootMod,g2592_device,z']= -0.14976491220071, })


		-- 10e8, 10e8 * 3
		-- 220000
		--accumulate({['map,0,swingFootMod,g2592_device,x']= 0.24079369654933, ['map,0,swingFootMod,g2592_device,y']= -0.22317864884815, ['map,0,swingFootMod,g2592_device,z']= 0.44343439976002, ['map,1,swingFootMod,g2592_device,x']= 0.41662775521137, ['map,1,swingFootMod,g2592_device,y']= 0.48591074929786, ['map,1,swingFootMod,g2592_device,z']= -0.098317446441624, ['map,2,swingFootMod,g2592_device,x']= -0.22742610664904, ['map,2,swingFootMod,g2592_device,y']= 0.068349584561701, ['map,2,swingFootMod,g2592_device,z']= -0.039802373989255, ['map,0,spprtFootMod,g2592_device,x']= -0.051098486145201, ['map,0,spprtFootMod,g2592_device,y']= -0.11779899983231, ['map,0,spprtFootMod,g2592_device,z']= 0.32088455273843, ['map,1,spprtFootMod,g2592_device,x']= -0.23766973119064, ['map,1,spprtFootMod,g2592_device,y']= -0.10510407256444, ['map,1,spprtFootMod,g2592_device,z']= 0.065329509893947, ['map,2,spprtFootMod,g2592_device,x']= -0.066938182854963, ['map,2,spprtFootMod,g2592_device,y']= 0.068005688529422, ['map,2,spprtFootMod,g2592_device,z']= -0.053953165794992, })

	end

	useCases.g2592_device.controlParam['useCases,g2592_device,aObjWeight'] = useCases.g2592_device.aObjWeight

	useCases.unmapControlParam(useCases.g2592_device)
end


