package.path=package.path..";../Samples/ysscripts/lib/?.lua" --;"..package.path
require("utilfunc")

package.path=package.path..";../Samples/ysscripts/samples/?.lua" --;"..package.path
require("useCaseMuscle_gait1956_6steps")

useCases.gait1956_tong=deepCopyTable(useCases.gait1956_6steps)

useCases.gait1956_tong.endSegW=10
useCases.gait1956_tong.prec=.1

useCases.gait1956_tong.modelName='gait1956_tong'
useCases.gait1956_tong.grpName='gait1956_tong'
useCases.gait1956_tong.grpNames={'gait1956_tong'}


useCases.gait1956_tong.k_p_ID=120
useCases.gait1956_tong.k_d_ID=2.*math.sqrt(120)
--useCases.gait1956_tong.ddqObjWeight=2000000
useCases.gait1956_tong.ddqObjWeight=10000000

--useCases.gait1956_tong.actuationType = ActuationType.tau
--useCases.gait1956_tong.actuationType = ActuationType.ft
--useCases.gait1956_tong.actuationType = ActuationType.a
useCases.gait1956_tong.actuationType = ActuationType.u

useCases.gait1956_tong.tauObjWeight=1
useCases.gait1956_tong.ftObjWeight=1
useCases.gait1956_tong.aObjWeight=10
useCases.gait1956_tong.lambdaObjWeight=10

--useCases.gait1956_tong.EEobjWeight=60000000
useCases.gait1956_tong.EEobjWeight=33300000
--
useCases.gait1956_tong.EEobjWeightAngular=60000000

--useCases.gait1956_tong.momentumWeight=8000000
useCases.gait1956_tong.momentumWeight=0

--useCases.gait1956_tong.headControlWeight=0
useCases.gait1956_tong.headControlWeight=36000000
--useCases.gait1956_tong.headControlWeight=20000000 --ys

useCases.gait1956_tong.initMsclForceScale=4

-- the initial pendControlParam and pendOptimizationPath can be automatically generated by using createInitialPendControlParam.lua
	pendControlParam={['keyframe,0,pendDesiredVel,gait1956_tong,l,z']=0,['keyframe,0,pendDesiredVel,gait1956_tong,l,x']=1,['keyframe,0,pendDesiredVel,gait1956_tong,r,z']=0,['keyframe,0,pendDesiredVel,gait1956_tong,r,x']=1,['keyframe,0,pendDesiredVel,gait1956_tong,L1,z']=0,['keyframe,0,pendDesiredVel,gait1956_tong,L1,x']=1,['keyframe,0,pendDesiredVel,gait1956_tong,R1,z']=0,['keyframe,0,pendDesiredVel,gait1956_tong,R1,x']=1,['keyframe,0,pendDesiredVel,gait1956_tong,L2,z']=0,['keyframe,0,pendDesiredVel,gait1956_tong,L2,x']=1,['keyframe,0,pendDesiredVel,ignore,0,z']=0,['keyframe,0,pendDesiredVel,ignore,0,x']=1,['keyframe,0,pendDesiredVel,ignore,1,z']=0,['keyframe,0,pendDesiredVel,ignore,1,x']=1,
['keyframe,0,pendDesiredVel,ignore,0,x']=0.67397424028586, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.0074665069825716, ['keyframe,0,pendDesiredVel,gait1956_tong,l,x']=1.0870479602205, ['keyframe,0,pendDesiredVel,gait1956_tong,l,z']=0.07024324142064, ['keyframe,0,pendDesiredVel,gait1956_tong,r,x']=1.210684865058, ['keyframe,0,pendDesiredVel,gait1956_tong,r,z']=0.10197338160236, ['keyframe,0,pendDesiredVel,gait1956_tong,L1,x']=1.1962961005512, ['keyframe,0,pendDesiredVel,gait1956_tong,L1,z']=0.03865663624365, ['keyframe,0,pendDesiredVel,gait1956_tong,R1,x']=1.1351762847156, ['keyframe,0,pendDesiredVel,gait1956_tong,R1,z']=0.03853403534704, ['keyframe,0,pendDesiredVel,gait1956_tong,L2,x']=1.0323519384173, ['keyframe,0,pendDesiredVel,gait1956_tong,L2,z']=0.0084288611334129, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.99600099116465, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.001430496053799, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.50413622445006, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.05049302871811, ['keyframe,0,pendDesiredVel,gait1956_tong,l,x']=1.4142621836795, ['keyframe,0,pendDesiredVel,gait1956_tong,l,z']=0.20268192708886, ['keyframe,0,pendDesiredVel,gait1956_tong,r,x']=1.3452082385225, ['keyframe,0,pendDesiredVel,gait1956_tong,r,z']=0.1517419819397, ['keyframe,0,pendDesiredVel,gait1956_tong,L1,x']=1.1497993301781, ['keyframe,0,pendDesiredVel,gait1956_tong,L1,z']=0.011127796803486, ['keyframe,0,pendDesiredVel,gait1956_tong,R1,x']=0.95350408914623, ['keyframe,0,pendDesiredVel,gait1956_tong,R1,z']=-0.021106557516788, ['keyframe,0,pendDesiredVel,gait1956_tong,L2,x']=0.85590007662266, ['keyframe,0,pendDesiredVel,gait1956_tong,L2,z']=0.019184374821157, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.9663149455938, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.0086197735010652, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.50404682631138, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.050514940678028, ['keyframe,0,pendDesiredVel,gait1956_tong,l,x']=1.4142908487564, ['keyframe,0,pendDesiredVel,gait1956_tong,l,z']=0.20269391413581, ['keyframe,0,pendDesiredVel,gait1956_tong,r,x']=1.345229178375, ['keyframe,0,pendDesiredVel,gait1956_tong,r,z']=0.15174731023168, ['keyframe,0,pendDesiredVel,gait1956_tong,L1,x']=1.1498256706975, ['keyframe,0,pendDesiredVel,gait1956_tong,L1,z']=0.011127832149238, ['keyframe,0,pendDesiredVel,gait1956_tong,R1,x']=0.95352733720468, ['keyframe,0,pendDesiredVel,gait1956_tong,R1,z']=-0.021102666296777, ['keyframe,0,pendDesiredVel,gait1956_tong,L2,x']=0.85589768364064, ['keyframe,0,pendDesiredVel,gait1956_tong,L2,z']=0.019190599831802, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.96631137589109, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.008620319987034, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.50390418098759, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.050549859516892, ['keyframe,0,pendDesiredVel,gait1956_tong,l,x']=1.4143374011315, ['keyframe,0,pendDesiredVel,gait1956_tong,l,z']=0.2027133765509, ['keyframe,0,pendDesiredVel,gait1956_tong,r,x']=1.3452631636312, ['keyframe,0,pendDesiredVel,gait1956_tong,r,z']=0.15175603807387, ['keyframe,0,pendDesiredVel,gait1956_tong,L1,x']=1.1498682226361, ['keyframe,0,pendDesiredVel,gait1956_tong,L1,z']=0.011127945716879, ['keyframe,0,pendDesiredVel,gait1956_tong,R1,x']=0.95356483309342, ['keyframe,0,pendDesiredVel,gait1956_tong,R1,z']=-0.021096362557798, ['keyframe,0,pendDesiredVel,gait1956_tong,L2,x']=0.85589386928721, ['keyframe,0,pendDesiredVel,gait1956_tong,L2,z']=0.019200621799857, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.96630563622305, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.0086211979430672, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.38159450212516, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.052708303002759, ['keyframe,0,pendDesiredVel,gait1956_tong,l,x']=1.854845943837, ['keyframe,0,pendDesiredVel,gait1956_tong,l,z']=0.3472581596977, ['keyframe,0,pendDesiredVel,gait1956_tong,r,x']=1.3736132116719, ['keyframe,0,pendDesiredVel,gait1956_tong,r,z']=0.14136332477824, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.38542263433817, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.045134733001122, ['keyframe,0,pendDesiredVel,gait1956_tong,l,x']=1.8301027676867, ['keyframe,0,pendDesiredVel,gait1956_tong,l,z']=0.33711303141227, ['keyframe,0,pendDesiredVel,gait1956_tong,r,x']=1.3796814777883, ['keyframe,0,pendDesiredVel,gait1956_tong,r,z']=0.15145052868814, 
['keyframe,0,pendDesiredVel,gait1956_tong,l,x']=1.7305776119094, ['keyframe,0,pendDesiredVel,gait1956_tong,l,z']=0.25538064590366, ['keyframe,0,pendDesiredVel,gait1956_tong,r,x']=1.2410661200316, ['keyframe,0,pendDesiredVel,gait1956_tong,r,z']=0.092299655249861, ['keyframe,0,pendDesiredVel,gait1956_tong,L1,x']=1.1511820918024, ['keyframe,0,pendDesiredVel,gait1956_tong,L1,z']=0.016150117032203, ['keyframe,0,pendDesiredVel,gait1956_tong,R1,x']=1.0098735198416, ['keyframe,0,pendDesiredVel,gait1956_tong,R1,z']=0.0057170216311841, ['keyframe,0,pendDesiredVel,gait1956_tong,L2,x']=0.82990395462959, ['keyframe,0,pendDesiredVel,gait1956_tong,L2,z']=0.056722578636763, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.94754533408323, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.01126038851346, 
['keyframe,0,pendDesiredVel,gait1956_tong,l,x']=1.7305998709824, ['keyframe,0,pendDesiredVel,gait1956_tong,l,z']=0.25527996963598, ['keyframe,0,pendDesiredVel,gait1956_tong,r,x']=1.2409415653836, ['keyframe,0,pendDesiredVel,gait1956_tong,r,z']=0.092159323153746, ['keyframe,0,pendDesiredVel,gait1956_tong,L1,x']=1.1511456386732, ['keyframe,0,pendDesiredVel,gait1956_tong,L1,z']=0.016050815884303, ['keyframe,0,pendDesiredVel,gait1956_tong,R1,x']=1.0098701157038, ['keyframe,0,pendDesiredVel,gait1956_tong,R1,z']=0.0056243081237624, ['keyframe,0,pendDesiredVel,gait1956_tong,L2,x']=0.82980798757505, ['keyframe,0,pendDesiredVel,gait1956_tong,L2,z']=0.0567217231482, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.94751338642262, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.011270092695708, 
}

useCases.gait1956_tong.pendControlParam=pendControlParam
--useCases.gait1956_tong.measureOptCost=useCases.measureOptCost


useCases.gait1956_tong.keyframes={
	pendDesiredVel={numKey=1, default=vector3(1,0,0)},
	swingFootForce={numKey=3, default=vector3(0,10,0)},
	footLmod={numKey=3, numKeyFrom='key', default=vector3(0,0,0)},
	footRmod={numKey=3, numKeyFrom='key', default=vector3(0,0,0)},
	footLmocapMod={numKey=3, numKeyFrom='key', default=vector3(0,0,0)},
	footRmocapMod={numKey=3, numKeyFrom='key', default=vector3(0,0,0)},
	desiredHeadAcc={numKey=3, numKeyFrom='key', default=vector3(0,0,0)},
	desiredMomentum={numKey=3, numKeyFrom='key', default=vector3(0,0,0)},
	desiredDotMomentum={numKey=3, numKeyFrom='key', isContinuous=false,default=vector3(0,0,0)},
	desiredLeaning={numKey=1, isContinuous=false,default=vector3(0,0,0)},
	spprtImpL={numKey=2, default=1},
	spprtImpR={numKey=2, default=1},
	mocapCompensationCoef={numKey=1, default=vector3(1, 1.0, 1)},
}

useCases.gait1956_tong.pendOptimizationPath=
{
	firstFrames={1,130,195,270,331,404,470,542,},
	segments={'ignore,0','gait1956_tong,l','gait1956_tong,r','gait1956_tong,L1','gait1956_tong,R1','gait1956_tong,L2','ignore,1'},
}

useCases.gait1956_tong.segmentations=
{
	gait1956_tong={
	firstFrames={1,130,195,270,331,404,470,542,},
		--        (blank)    L    R    L     R     L     (blank)
		names={             'l', 'r', 'L1', 'R1', 'L2',  },
		swingL={             0,   1,   0,    1,    0,    },
		swingR={             1,   0,   1,    0,    1,    },
		footRefL= "convertFromSwingL",
		footRefR= "convertFromSwingR",
		usePositionControl=false,
	},
}
useCases.gait1956_tong.graphParam={
	gait1956_tong={
		seg={            'l',  'r',  'L1', 'R1','L'},
		num_key={         3,    3,    3  ,  4,  4},
		key_first={       0,    0,    0  ,  0,  0},
		key_last={       'r', 'L1',  'R1', 'L', 'R1'},

	},
}
useCases.gait1956_tong.graph={
	{
		"addInterpolatedSegment",
		grpName="gait1956_tong",
		name="L",
		seg0={"gait1956_tong", "L2"},
		seg1={"gait1956_tong", "L1"},
		startWeight=0, endWeight=1
	},
	{"connectMulti", "gait1956_tong", "l", "r", "L1", "R1", "L", "R1"},
	{"initialSegment", "gait1956_tong", "l"}
}
useCases.gait1956_tong.segNames={
	"l", "r", "L1", 'R1','L',
}

do 
	useCases.gait1956_tong.controlParam={
		['useCases,gait1956_tong,COMobjWeight']=0, 
		['useCases,gait1956_tong,conservativeW']=1, 
		['useCases,gait1956_tong,contactMargin']=0.01, 
		['useCases,gait1956_tong,dotMomentumScale']=0.3, 
		['useCases,gait1956_tong,excludeRoot']=true, 
		['useCases,gait1956_tong,headControlWeight']=0, 
		['useCases,gait1956_tong,k_d_HEAD']=14, 
		['useCases,gait1956_tong,k_p_HEAD']=0, 
		['useCases,gait1956_tong,k_d_EE']=24, 
		['useCases,gait1956_tong,k_d_momentum']=10, 
		['useCases,gait1956_tong,k_p_EE']=120, 
		--['useCases,run,invAccConeCoef']=1, 
		--['useCases,run,invFricCoef']=0.8, 

		['useCases,gait1956_tong,maxPenetratingVel']=0, 
		['useCases,gait1956_tong,momentumThr']=50, 
		['useCases,gait1956_tong,noComvelDependentFootAdjustment']=true, 
		['useCases,gait1956_tong,noIntersectionPrevenction']=true, 
		['useCases,gait1956_tong,numericalDerivDmot']=true, 
		['useCases,gait1956_tong,perClassContactMargin']=1, 
		['useCases,gait1956_tong,turnGain']=10, 
		['useCases,gait1956_tong,velMarginOffset']=0, 

		['useCases,gait1956_tong,actuationType']	=useCases.gait1956_tong.actuationType,
		['useCases,gait1956_tong,k_p_ID']			=useCases.gait1956_tong.k_p_ID,
		['useCases,gait1956_tong,k_d_ID']			=useCases.gait1956_tong.k_d_ID,
		['useCases,gait1956_tong,ddqObjWeight']	=useCases.gait1956_tong.ddqObjWeight,
		['useCases,gait1956_tong,tauObjWeight']	=useCases.gait1956_tong.tauObjWeight,
		['useCases,gait1956_tong,ftObjWeight']	=useCases.gait1956_tong.ftObjWeight,
		['useCases,gait1956_tong,aObjWeight']		=useCases.gait1956_tong.aObjWeight,
		['useCases,gait1956_tong,lambdaObjWeight']=useCases.gait1956_tong.lambdaObjWeight,
		['useCases,gait1956_tong,EEobjWeight']        = useCases.gait1956_tong.EEobjWeight,
		['useCases,gait1956_tong,EEobjWeightAngular'] = useCases.gait1956_tong.EEobjWeightAngular,
		['useCases,gait1956_tong,momentumWeight']     = useCases.gait1956_tong.momentumWeight,
		['useCases,gait1956_tong,headControlWeight']     = useCases.gait1956_tong.headControlWeight,
		['useCases,gait1956_tong,tauMax']			=useCases.gait1956_tong.tauMax,
		['useCases,gait1956_tong,ftMax']			=useCases.gait1956_tong.ftMax,
	}

	local function accumulate(cp_mod)
		local useCase=useCases.gait1956_tong
		useCases.accumulate(useCase, cp_mod)
	end

	useCases.gait1956_tong.noCOMjoint=true
	useCases.gait1956_tong.spprtImpFromImp=true
	function modifySwingFoot(key, id, mod,inc,postfix)
		postfix=postfix or 'MocapMod'
		local useCase=useCases.walk3
		local c='map,'..key..',swingFoot'..postfix..','..id
		if inc then
			useCase.controlParam[c]=useCase.controlParam[c]+mod
		else
			useCase.controlParam[c]=mod
		end
	end

	useCases.gait1956_tong.useBulletColdet=true

	--accumulate({
		--['keyframe,0,footRmod,gait1956_tong,l,y'] =0.2,
		--['keyframe,1,footRmod,gait1956_tong,l,y'] =0.5,
		--['keyframe,0,footLmod,gait1956_tong,r,y'] =0.3,
		--['keyframe,1,footLmod,gait1956_tong,r,y'] =0.6,
		--['keyframe,0,footRmod,gait1956_tong,L1,y']=0.3,
		--['keyframe,1,footRmod,gait1956_tong,L1,y']=0.6,
		--['map,0,swingFootMod,gait1956_tong,y']= 0.3,
		--['map,1,swingFootMod,gait1956_tong,y']= 0.6,
		--['map,2,swingFootMod,gait1956_tong,y']= 0.6,

		--['keyframe,0,footLmod,gait1956_tong,l,y'] =-0.1,
		--['keyframe,1,footLmod,gait1956_tong,l,y'] =-0.1,
		--['keyframe,0,footRmod,gait1956_tong,r,y'] =-0.1,
		--['keyframe,1,footRmod,gait1956_tong,r,y'] =-0.1,
		--['keyframe,0,footLmod,gait1956_tong,L1,y']=-0.1,
		--['keyframe,1,footLmod,gait1956_tong,L1,y']=-0.1,
		--['map,0,spprtFootMod,gait1956_tong,y']= -0.1,
		--['map,1,spprtFootMod,gait1956_tong,y']= -0.1,
		--['map,2,spprtFootMod,gait1956_tong,y']= -0.1,
	--})
	accumulate({
		['keyframe,0,footRmod,gait1956_tong,l,y']  = 0.,
		['keyframe,1,footRmod,gait1956_tong,l,y']  = 0.,
		['keyframe,0,footLmod,gait1956_tong,r,y']  = 0.,
		['keyframe,1,footLmod,gait1956_tong,r,y']  = 0.,
		['keyframe,0,footRmod,gait1956_tong,L1,y'] = 0.,
		['keyframe,1,footRmod,gait1956_tong,L1,y'] = 0.,
		['map,0,swingFootMod,gait1956_tong,y']     = 0.,
		['map,1,swingFootMod,gait1956_tong,y']     = 0.,
		['map,2,swingFootMod,gait1956_tong,y']     = 0.,

		['keyframe,0,footLmod,gait1956_tong,l,y']  = 0.,
		['keyframe,1,footLmod,gait1956_tong,l,y']  = 0.,
		['keyframe,0,footRmod,gait1956_tong,r,y']  = 0.,
		['keyframe,1,footRmod,gait1956_tong,r,y']  = 0.,
		['keyframe,0,footLmod,gait1956_tong,L1,y'] = 0.,
		['keyframe,1,footLmod,gait1956_tong,L1,y'] = 0.,
		['map,0,spprtFootMod,gait1956_tong,y']     = 0.,
		['map,1,spprtFootMod,gait1956_tong,y']     = 0.,
		['map,2,spprtFootMod,gait1956_tong,y']     = 0.,
	})

----	------------------New optimization-------- [1e+100,-1e+100] -> oeval:1.0096226664899e-05 dim:18}) -- skipped oeval:1.0096226664899e-05 
----0.918 --0.697 --0.512 --0.435 --0.379 --0.337 --0.305 --0.305 --0.293 --0.293 
----Thu Dec 26 19:16:18 2013 setStage2 startSeg:1 endSeg:10 : [2.9401295298692e-06,120604.48718525] -> oeval:2.8988611615784e-06 dim:6}) -- skipped oeval:2.8988611615784e-06 

--accumulate({ ['map,0,swingFootMod,gait1956_tong,x']= -0.011545922564828, ['map,0,swingFootMod,gait1956_tong,y']= -0.40926980062462, ['map,0,swingFootMod,gait1956_tong,z']= -0.21843758440771, ['map,1,swingFootMod,gait1956_tong,x']= -0.50573767663655, ['map,1,swingFootMod,gait1956_tong,y']= 0.024228263162169, ['map,1,swingFootMod,gait1956_tong,z']= 0.19922061121533, ['map,2,swingFootMod,gait1956_tong,x']= 0.49932424611288, ['map,2,swingFootMod,gait1956_tong,y']= -0.39485750054868, ['map,2,swingFootMod,gait1956_tong,z']= -0.066805908384214, ['map,0,spprtFootMod,gait1956_tong,x']= 0.61313823771119, ['map,0,spprtFootMod,gait1956_tong,y']= -0.51752696327872, ['map,0,spprtFootMod,gait1956_tong,z']= 0.023316293673818, ['map,1,spprtFootMod,gait1956_tong,x']= 0.26495911909665, ['map,1,spprtFootMod,gait1956_tong,y']= -0.73511953012768, ['map,1,spprtFootMod,gait1956_tong,z']= -0.035581958014795, ['map,2,spprtFootMod,gait1956_tong,x']= -0.47549670215684, ['map,2,spprtFootMod,gait1956_tong,y']= 0.69060852041598, ['map,2,spprtFootMod,gait1956_tong,z']= 0.14103840923996, })
----0.980 --0.971 --0.967 --0.957 --0.956 --0.956 --0.956 --0.952 --0.952 --0.952 
----Thu Dec 26 20:56:07 2013 setStage3 startSeg:1 endSeg:10 : [2.7696941153381e-06,3.2359962907581e-06] -> oeval:2.760363268113e-06 dim:6}) -- skipped oeval:2.760363268113e-06 

--accumulate({ ['map,0,swingFootMod,gait1956_tong,z']= -0.062044111100616, ['map,1,swingFootMod,gait1956_tong,z']= 0.21386956677102, ['map,2,swingFootMod,gait1956_tong,z']= -0.04173657523249, ['map,0,spprtFootMod,gait1956_tong,z']= 0.0033926055182884, ['map,1,spprtFootMod,gait1956_tong,z']= -0.068970965606879, ['map,2,spprtFootMod,gait1956_tong,z']= 0.14467509361845, })
----1.030 --1.006 --0.999 --0.997 --0.997 --0.996 --0.996 --0.996 --0.996 --0.995 
----Thu Dec 26 22:36:12 2013 setStage4 startSeg:1 endSeg:10 : [2.7476359240953e-06,2.9591447516333e-06] -> oeval:2.7470849893958e-06 dim:6}) -- skipped oeval:2.7470849893958e-06 

--accumulate({ ['map,0,swingFootMod,gait1956_tong,x']= 0.040529773962679, ['map,1,swingFootMod,gait1956_tong,x']= -0.49827972923089, ['map,2,swingFootMod,gait1956_tong,x']= 0.49049592582651, ['map,0,spprtFootMod,gait1956_tong,x']= 0.63261520433511, ['map,1,spprtFootMod,gait1956_tong,x']= 0.26560410785724, ['map,2,spprtFootMod,gait1956_tong,x']= -0.46956279315848, })
----1.015 --0.995 --0.993 --0.993 --0.990 --0.989 --0.989 --0.989 --0.989 --0.989 
----Fri Dec 27 00:15:37 2013 setStage5 startSeg:1 endSeg:10 : [2.7286834091861e-06,2.9972268286594e-06] -> oeval:2.7157064224831e-06 dim:18}) -- skipped oeval:2.7157064224831e-06 

--accumulate({ ['map,0,swingFootMod,gait1956_tong,y']= -0.41627932020007, ['map,1,swingFootMod,gait1956_tong,y']= 0.042040412907357, ['map,2,swingFootMod,gait1956_tong,y']= -0.39326331595853, ['map,0,spprtFootMod,gait1956_tong,y']= -0.51110286401328, ['map,1,spprtFootMod,gait1956_tong,y']= -0.71059915359703, ['map,2,spprtFootMod,gait1956_tong,y']= 0.65762955348719, })
----1.069 --1.014 --1.000 --1.000 --1.000 --0.997 --0.997 --0.989 --0.984 --0.978 
----Fri Dec 27 01:54:56 2013 setStage6 startSeg:1 endSeg:10 : [2.6395893591333e-06,99842.500884683] -> oeval:2.6395893591333e-06 dim:6}) -- skipped oeval:2.6395893591333e-06 

--accumulate({ ['map,0,swingFootMod,gait1956_tong,x']= 0.091326791648269, ['map,0,swingFootMod,gait1956_tong,y']= -0.49169344654758, ['map,0,swingFootMod,gait1956_tong,z']= -0.017410243656635, ['map,1,swingFootMod,gait1956_tong,x']= -0.57803133981072, ['map,1,swingFootMod,gait1956_tong,y']= 0.037599425018598, ['map,1,swingFootMod,gait1956_tong,z']= 0.12966284114013, ['map,2,swingFootMod,gait1956_tong,x']= 0.52806215418655, ['map,2,swingFootMod,gait1956_tong,y']= -0.49428114306862, ['map,2,swingFootMod,gait1956_tong,z']= -0.005617234237126, ['map,0,spprtFootMod,gait1956_tong,x']= 0.67166929403219, ['map,0,spprtFootMod,gait1956_tong,y']= -0.55900509598265, ['map,0,spprtFootMod,gait1956_tong,z']= 0.016945190594904, ['map,1,spprtFootMod,gait1956_tong,x']= 0.32734816929471, ['map,1,spprtFootMod,gait1956_tong,y']= -0.6194579649198, ['map,1,spprtFootMod,gait1956_tong,z']= -0.04142630705911, ['map,2,spprtFootMod,gait1956_tong,x']= -0.39179719067148, ['map,2,spprtFootMod,gait1956_tong,y']= 0.74609810938267, ['map,2,spprtFootMod,gait1956_tong,z']= 0.072983584599739, })
----1.019 --0.996 --0.996 --0.998 --0.996 


useCases.unmapControlParam(useCases.gait1956_tong)

end


