package.path=package.path..";../Samples/ysscripts/lib/?.lua" --;"..package.path
require("utilfunc")

package.path=package.path..";../Samples/ysscripts/samples/?.lua" --;"..package.path
require("useCaseMuscle_gait1956_6steps")

useCases.fullbody_tong=deepCopyTable(useCases.gait1956_6steps)

useCases.fullbody_tong.endSegW=10
useCases.fullbody_tong.prec=.1

useCases.fullbody_tong.modelName='fullbody_tong'
useCases.fullbody_tong.grpName='fullbody_tong'
useCases.fullbody_tong.grpNames={'fullbody_tong'}


useCases.fullbody_tong.k_p_ID=120
useCases.fullbody_tong.k_d_ID=2.*math.sqrt(120)
useCases.fullbody_tong.ddqObjWeight=10000000

--useCases.fullbody_tong.actuationType = ActuationType.tau
--useCases.fullbody_tong.actuationType = ActuationType.ft
--useCases.fullbody_tong.actuationType = ActuationType.a
--useCases.fullbody_tong.actuationType = ActuationType.u

useCases.fullbody_tong.tauObjWeight=1
useCases.fullbody_tong.ftObjWeight=10
useCases.fullbody_tong.aObjWeight=10
useCases.fullbody_tong.lambdaObjWeight=10

--useCases.fullbody_tong.EEobjWeight=60000000
useCases.fullbody_tong.EEobjWeight=33300000
--
useCases.fullbody_tong.EEobjWeightAngular=60000000

--useCases.fullbody_tong.momentumWeight=8000000
useCases.fullbody_tong.momentumWeight=0

--useCases.fullbody_tong.headControlWeight=0
--useCases.fullbody_tong.headControlWeight=36000000
useCases.fullbody_tong.headControlWeight=80000000
--useCases.fullbody_tong.headControlWeight=20000000 --ys

useCases.fullbody_tong.initMsclForceScale=4

-- the initial pendControlParam and pendOptimizationPath can be automatically generated by using createInitialPendControlParam.lua
	pendControlParam={['keyframe,0,pendDesiredVel,fullbody_tong,l,z']=0,['keyframe,0,pendDesiredVel,fullbody_tong,l,x']=1,['keyframe,0,pendDesiredVel,fullbody_tong,r,z']=0,['keyframe,0,pendDesiredVel,fullbody_tong,r,x']=1,['keyframe,0,pendDesiredVel,fullbody_tong,L1,z']=0,['keyframe,0,pendDesiredVel,fullbody_tong,L1,x']=1,['keyframe,0,pendDesiredVel,fullbody_tong,R1,z']=0,['keyframe,0,pendDesiredVel,fullbody_tong,R1,x']=1,['keyframe,0,pendDesiredVel,fullbody_tong,L2,z']=0,['keyframe,0,pendDesiredVel,fullbody_tong,L2,x']=1,['keyframe,0,pendDesiredVel,ignore,0,z']=0,['keyframe,0,pendDesiredVel,ignore,0,x']=1,['keyframe,0,pendDesiredVel,ignore,1,z']=0,['keyframe,0,pendDesiredVel,ignore,1,x']=1,
['keyframe,0,pendDesiredVel,fullbody_tong,l,x']=0.75707372747054, ['keyframe,0,pendDesiredVel,fullbody_tong,l,z']=0.025974743271427, ['keyframe,0,pendDesiredVel,fullbody_tong,r,x']=0.97774291053206, ['keyframe,0,pendDesiredVel,fullbody_tong,r,z']=0.056340200730732, ['keyframe,0,pendDesiredVel,fullbody_tong,L1,x']=1.129218479699, ['keyframe,0,pendDesiredVel,fullbody_tong,L1,z']=0.036091239795864, ['keyframe,0,pendDesiredVel,fullbody_tong,R1,x']=1.1089918363759, ['keyframe,0,pendDesiredVel,fullbody_tong,R1,z']=0.015580865444537, ['keyframe,0,pendDesiredVel,fullbody_tong,L2,x']=1.022000156571, ['keyframe,0,pendDesiredVel,fullbody_tong,L2,z']=0.008522531061081, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.98955763920277, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.0024045485865913, 
['keyframe,0,pendDesiredVel,fullbody_tong,l,x']=-0.0356439980142, ['keyframe,0,pendDesiredVel,fullbody_tong,l,z']=-0.064077145260837, ['keyframe,0,pendDesiredVel,fullbody_tong,r,x']=1.7975791185404, ['keyframe,0,pendDesiredVel,fullbody_tong,r,z']=0.2473913122888, ['keyframe,0,pendDesiredVel,fullbody_tong,L1,x']=1.4461461745038, ['keyframe,0,pendDesiredVel,fullbody_tong,L1,z']=0.013815773418372, ['keyframe,0,pendDesiredVel,fullbody_tong,R1,x']=0.90636677879475, ['keyframe,0,pendDesiredVel,fullbody_tong,R1,z']=-0.083516525814553, ['keyframe,0,pendDesiredVel,fullbody_tong,L2,x']=0.54722083064816, ['keyframe,0,pendDesiredVel,fullbody_tong,L2,z']=0.16385227062545, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.85485614068784, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.029486744226095, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.36112042169194, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.058159944351229, ['keyframe,0,pendDesiredVel,fullbody_tong,l,x']=2.6365853281366, ['keyframe,0,pendDesiredVel,fullbody_tong,l,z']=0.50193409573717, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.40011900828393, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.062296591592388, ['keyframe,0,pendDesiredVel,fullbody_tong,l,x']=1.7571196392088, ['keyframe,0,pendDesiredVel,fullbody_tong,l,z']=0.43337951736321, ['keyframe,0,pendDesiredVel,fullbody_tong,r,x']=1.6841333305942, ['keyframe,0,pendDesiredVel,fullbody_tong,r,z']=0.19739507468599, 
['keyframe,0,pendDesiredVel,fullbody_tong,l,x']=1.8140266872374, ['keyframe,0,pendDesiredVel,fullbody_tong,l,z']=0.31734377819053, ['keyframe,0,pendDesiredVel,fullbody_tong,r,x']=1.0986257138259, ['keyframe,0,pendDesiredVel,fullbody_tong,r,z']=0.061484674935125, ['keyframe,0,pendDesiredVel,fullbody_tong,L1,x']=1.0766827383154, ['keyframe,0,pendDesiredVel,fullbody_tong,L1,z']=0.11133031779407, ['keyframe,0,pendDesiredVel,fullbody_tong,R1,x']=0.8783559252067, ['keyframe,0,pendDesiredVel,fullbody_tong,R1,z']=-0.090817070349378, 
['keyframe,0,pendDesiredVel,fullbody_tong,L1,x']=1.0671325788695, ['keyframe,0,pendDesiredVel,fullbody_tong,L1,z']=0.065448873288847, ['keyframe,0,pendDesiredVel,fullbody_tong,R1,x']=1.3715802401167, ['keyframe,0,pendDesiredVel,fullbody_tong,R1,z']=-0.18050599912981, ['keyframe,0,pendDesiredVel,fullbody_tong,L2,x']=0.42664475756554, ['keyframe,0,pendDesiredVel,fullbody_tong,L2,z']=0.34657040764091, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.65128247287863, ['keyframe,0,pendDesiredVel,ignore,1,z']=-0.11326946238409, 
}

useCases.fullbody_tong.pendControlParam=pendControlParam
--useCases.fullbody_tong.measureOptCost=useCases.measureOptCost


useCases.fullbody_tong.keyframes={
	pendDesiredVel={numKey=1, default=vector3(1,0,0)},
	swingFootForce={numKey=3, default=vector3(0,10,0)},
	footLmod={numKey=3, numKeyFrom='key', default=vector3(0,0,0)},
	footRmod={numKey=3, numKeyFrom='key', default=vector3(0,0,0)},
	footLmocapMod={numKey=3, numKeyFrom='key', default=vector3(0,0,0)},
	footRmocapMod={numKey=3, numKeyFrom='key', default=vector3(0,0,0)},
	desiredHeadAcc={numKey=3, numKeyFrom='key', default=vector3(0,0,0)},
	desiredMomentum={numKey=3, numKeyFrom='key', default=vector3(0,0,0)},
	desiredDotMomentum={numKey=3, numKeyFrom='key', isContinuous=false,default=vector3(0,0,0)},
	desiredLeaning={numKey=1, isContinuous=false,default=vector3(0,0,0)},
	spprtImpL={numKey=2, default=1},
	spprtImpR={numKey=2, default=1},
	mocapCompensationCoef={numKey=1, default=vector3(1, 1.0, 1)},
}

useCases.fullbody_tong.pendOptimizationPath=
{
	firstFrames={1,130,195,270,331,404,470,542,},
	segments={'ignore,0','fullbody_tong,l','fullbody_tong,r','fullbody_tong,L1','fullbody_tong,R1','fullbody_tong,L2','ignore,1'},
}

useCases.fullbody_tong.segmentations=
{
	fullbody_tong={
	firstFrames={1,130,195,270,331,404,470,542,},
		--        (blank)    L    R    L     R     L     (blank)
		names={             'l', 'r', 'L1', 'R1', 'L2',  },
		swingL={             0,   1,   0,    1,    0,    },
		swingR={             1,   0,   1,    0,    1,    },
		footRefL= "convertFromSwingL",
		footRefR= "convertFromSwingR",
		usePositionControl=false,
	},
}
useCases.fullbody_tong.graphParam={
	fullbody_tong={
		seg={            'l',  'r',  'L1', 'R1','L'},
		num_key={         3,    3,    3  ,  4,  4},
		key_first={       0,    0,    0  ,  0,  0},
		key_last={       'r', 'L1',  'R1', 'L', 'R1'},

	},
}
useCases.fullbody_tong.graph={
	{
		"addInterpolatedSegment",
		grpName="fullbody_tong",
		name="L",
		seg0={"fullbody_tong", "L2"},
		seg1={"fullbody_tong", "L1"},
		startWeight=0, endWeight=1
	},
	{"connectMulti", "fullbody_tong", "l", "r", "L1", "R1", "L", "R1"},
	{"initialSegment", "fullbody_tong", "l"}
}
useCases.fullbody_tong.segNames={
	"l", "r", "L1", 'R1','L',
}

do 
	useCases.fullbody_tong.controlParam={
		['useCases,fullbody_tong,COMobjWeight']=0, 
		['useCases,fullbody_tong,conservativeW']=1, 
		['useCases,fullbody_tong,contactMargin']=0.01, 
		['useCases,fullbody_tong,dotMomentumScale']=0.3, 
		['useCases,fullbody_tong,excludeRoot']=true, 
		['useCases,fullbody_tong,headControlWeight']=0, 
		['useCases,fullbody_tong,k_d_HEAD']=14, 
		['useCases,fullbody_tong,k_p_HEAD']=0, 
		['useCases,fullbody_tong,k_d_EE']=24, 
		['useCases,fullbody_tong,k_d_momentum']=10, 
		['useCases,fullbody_tong,k_p_EE']=120, 
		--['useCases,run,invAccConeCoef']=1, 
		--['useCases,run,invFricCoef']=0.8, 

		['useCases,fullbody_tong,maxPenetratingVel']=0, 
		['useCases,fullbody_tong,momentumThr']=50, 
		['useCases,fullbody_tong,noComvelDependentFootAdjustment']=true, 
		['useCases,fullbody_tong,noIntersectionPrevenction']=true, 
		['useCases,fullbody_tong,numericalDerivDmot']=true, 
		['useCases,fullbody_tong,perClassContactMargin']=1, 
		['useCases,fullbody_tong,turnGain']=10, 
		['useCases,fullbody_tong,velMarginOffset']=0, 

		['useCases,fullbody_tong,actuationType']	=useCases.fullbody_tong.actuationType,
		['useCases,fullbody_tong,k_p_ID']			=useCases.fullbody_tong.k_p_ID,
		['useCases,fullbody_tong,k_d_ID']			=useCases.fullbody_tong.k_d_ID,
		['useCases,fullbody_tong,ddqObjWeight']	=useCases.fullbody_tong.ddqObjWeight,
		['useCases,fullbody_tong,tauObjWeight']	=useCases.fullbody_tong.tauObjWeight,
		['useCases,fullbody_tong,ftObjWeight']	=useCases.fullbody_tong.ftObjWeight,
		['useCases,fullbody_tong,aObjWeight']		=useCases.fullbody_tong.aObjWeight,
		['useCases,fullbody_tong,lambdaObjWeight']=useCases.fullbody_tong.lambdaObjWeight,
		['useCases,fullbody_tong,EEobjWeight']        = useCases.fullbody_tong.EEobjWeight,
		['useCases,fullbody_tong,EEobjWeightAngular'] = useCases.fullbody_tong.EEobjWeightAngular,
		['useCases,fullbody_tong,momentumWeight']     = useCases.fullbody_tong.momentumWeight,
		['useCases,fullbody_tong,headControlWeight']     = useCases.fullbody_tong.headControlWeight,
		['useCases,fullbody_tong,tauMax']			=useCases.fullbody_tong.tauMax,
		['useCases,fullbody_tong,ftMax']			=useCases.fullbody_tong.ftMax,
	}

	local function accumulate(cp_mod)
		local useCase=useCases.fullbody_tong
		useCases.accumulate(useCase, cp_mod)
	end

	useCases.fullbody_tong.noCOMjoint=true
	useCases.fullbody_tong.spprtImpFromImp=true
	function modifySwingFoot(key, id, mod,inc,postfix)
		postfix=postfix or 'MocapMod'
		local useCase=useCases.walk3
		local c='map,'..key..',swingFoot'..postfix..','..id
		if inc then
			useCase.controlParam[c]=useCase.controlParam[c]+mod
		else
			useCase.controlParam[c]=mod
		end
	end

	useCases.fullbody_tong.useBulletColdet=true

	--accumulate({
		--['keyframe,0,footRmod,fullbody_tong,l,y'] =0.2,
		--['keyframe,1,footRmod,fullbody_tong,l,y'] =0.5,
		--['keyframe,0,footLmod,fullbody_tong,r,y'] =0.3,
		--['keyframe,1,footLmod,fullbody_tong,r,y'] =0.6,
		--['keyframe,0,footRmod,fullbody_tong,L1,y']=0.3,
		--['keyframe,1,footRmod,fullbody_tong,L1,y']=0.6,
		--['map,0,swingFootMod,fullbody_tong,y']= 0.3,
		--['map,1,swingFootMod,fullbody_tong,y']= 0.6,
		--['map,2,swingFootMod,fullbody_tong,y']= 0.6,

		--['keyframe,0,footLmod,fullbody_tong,l,y'] =-0.1,
		--['keyframe,1,footLmod,fullbody_tong,l,y'] =-0.1,
		--['keyframe,0,footRmod,fullbody_tong,r,y'] =-0.1,
		--['keyframe,1,footRmod,fullbody_tong,r,y'] =-0.1,
		--['keyframe,0,footLmod,fullbody_tong,L1,y']=-0.1,
		--['keyframe,1,footLmod,fullbody_tong,L1,y']=-0.1,
		--['map,0,spprtFootMod,fullbody_tong,y']= -0.1,
		--['map,1,spprtFootMod,fullbody_tong,y']= -0.1,
		--['map,2,spprtFootMod,fullbody_tong,y']= -0.1,
	--})
	accumulate({
		['keyframe,0,footRmod,fullbody_tong,l,y']  = 0.,
		['keyframe,1,footRmod,fullbody_tong,l,y']  = 0.,
		['keyframe,0,footLmod,fullbody_tong,r,y']  = 0.,
		['keyframe,1,footLmod,fullbody_tong,r,y']  = 0.,
		['keyframe,0,footRmod,fullbody_tong,L1,y'] = 0.,
		['keyframe,1,footRmod,fullbody_tong,L1,y'] = 0.,
		['map,0,swingFootMod,fullbody_tong,y']     = 0.,
		['map,1,swingFootMod,fullbody_tong,y']     = 0.,
		['map,2,swingFootMod,fullbody_tong,y']     = 0.,

		['keyframe,0,footLmod,fullbody_tong,l,y']  = 0.,
		['keyframe,1,footLmod,fullbody_tong,l,y']  = 0.,
		['keyframe,0,footRmod,fullbody_tong,r,y']  = 0.,
		['keyframe,1,footRmod,fullbody_tong,r,y']  = 0.,
		['keyframe,0,footLmod,fullbody_tong,L1,y'] = 0.,
		['keyframe,1,footLmod,fullbody_tong,L1,y'] = 0.,
		['map,0,spprtFootMod,fullbody_tong,y']     = 0.,
		['map,1,spprtFootMod,fullbody_tong,y']     = 0.,
		['map,2,spprtFootMod,fullbody_tong,y']     = 0.,
	})

----	------------------New optimization-------- [1e+100,-1e+100] -> oeval:1.0096226664899e-05 dim:18}) -- skipped oeval:1.0096226664899e-05 
----0.918 --0.697 --0.512 --0.435 --0.379 --0.337 --0.305 --0.305 --0.293 --0.293 
----Thu Dec 26 19:16:18 2013 setStage2 startSeg:1 endSeg:10 : [2.9401295298692e-06,120604.48718525] -> oeval:2.8988611615784e-06 dim:6}) -- skipped oeval:2.8988611615784e-06 

--accumulate({ ['map,0,swingFootMod,fullbody_tong,x']= -0.011545922564828, ['map,0,swingFootMod,fullbody_tong,y']= -0.40926980062462, ['map,0,swingFootMod,fullbody_tong,z']= -0.21843758440771, ['map,1,swingFootMod,fullbody_tong,x']= -0.50573767663655, ['map,1,swingFootMod,fullbody_tong,y']= 0.024228263162169, ['map,1,swingFootMod,fullbody_tong,z']= 0.19922061121533, ['map,2,swingFootMod,fullbody_tong,x']= 0.49932424611288, ['map,2,swingFootMod,fullbody_tong,y']= -0.39485750054868, ['map,2,swingFootMod,fullbody_tong,z']= -0.066805908384214, ['map,0,spprtFootMod,fullbody_tong,x']= 0.61313823771119, ['map,0,spprtFootMod,fullbody_tong,y']= -0.51752696327872, ['map,0,spprtFootMod,fullbody_tong,z']= 0.023316293673818, ['map,1,spprtFootMod,fullbody_tong,x']= 0.26495911909665, ['map,1,spprtFootMod,fullbody_tong,y']= -0.73511953012768, ['map,1,spprtFootMod,fullbody_tong,z']= -0.035581958014795, ['map,2,spprtFootMod,fullbody_tong,x']= -0.47549670215684, ['map,2,spprtFootMod,fullbody_tong,y']= 0.69060852041598, ['map,2,spprtFootMod,fullbody_tong,z']= 0.14103840923996, })
----0.980 --0.971 --0.967 --0.957 --0.956 --0.956 --0.956 --0.952 --0.952 --0.952 
----Thu Dec 26 20:56:07 2013 setStage3 startSeg:1 endSeg:10 : [2.7696941153381e-06,3.2359962907581e-06] -> oeval:2.760363268113e-06 dim:6}) -- skipped oeval:2.760363268113e-06 

--accumulate({ ['map,0,swingFootMod,fullbody_tong,z']= -0.062044111100616, ['map,1,swingFootMod,fullbody_tong,z']= 0.21386956677102, ['map,2,swingFootMod,fullbody_tong,z']= -0.04173657523249, ['map,0,spprtFootMod,fullbody_tong,z']= 0.0033926055182884, ['map,1,spprtFootMod,fullbody_tong,z']= -0.068970965606879, ['map,2,spprtFootMod,fullbody_tong,z']= 0.14467509361845, })
----1.030 --1.006 --0.999 --0.997 --0.997 --0.996 --0.996 --0.996 --0.996 --0.995 
----Thu Dec 26 22:36:12 2013 setStage4 startSeg:1 endSeg:10 : [2.7476359240953e-06,2.9591447516333e-06] -> oeval:2.7470849893958e-06 dim:6}) -- skipped oeval:2.7470849893958e-06 

--accumulate({ ['map,0,swingFootMod,fullbody_tong,x']= 0.040529773962679, ['map,1,swingFootMod,fullbody_tong,x']= -0.49827972923089, ['map,2,swingFootMod,fullbody_tong,x']= 0.49049592582651, ['map,0,spprtFootMod,fullbody_tong,x']= 0.63261520433511, ['map,1,spprtFootMod,fullbody_tong,x']= 0.26560410785724, ['map,2,spprtFootMod,fullbody_tong,x']= -0.46956279315848, })
----1.015 --0.995 --0.993 --0.993 --0.990 --0.989 --0.989 --0.989 --0.989 --0.989 
----Fri Dec 27 00:15:37 2013 setStage5 startSeg:1 endSeg:10 : [2.7286834091861e-06,2.9972268286594e-06] -> oeval:2.7157064224831e-06 dim:18}) -- skipped oeval:2.7157064224831e-06 

--accumulate({ ['map,0,swingFootMod,fullbody_tong,y']= -0.41627932020007, ['map,1,swingFootMod,fullbody_tong,y']= 0.042040412907357, ['map,2,swingFootMod,fullbody_tong,y']= -0.39326331595853, ['map,0,spprtFootMod,fullbody_tong,y']= -0.51110286401328, ['map,1,spprtFootMod,fullbody_tong,y']= -0.71059915359703, ['map,2,spprtFootMod,fullbody_tong,y']= 0.65762955348719, })
----1.069 --1.014 --1.000 --1.000 --1.000 --0.997 --0.997 --0.989 --0.984 --0.978 
----Fri Dec 27 01:54:56 2013 setStage6 startSeg:1 endSeg:10 : [2.6395893591333e-06,99842.500884683] -> oeval:2.6395893591333e-06 dim:6}) -- skipped oeval:2.6395893591333e-06 

--accumulate({ ['map,0,swingFootMod,fullbody_tong,x']= 0.091326791648269, ['map,0,swingFootMod,fullbody_tong,y']= -0.49169344654758, ['map,0,swingFootMod,fullbody_tong,z']= -0.017410243656635, ['map,1,swingFootMod,fullbody_tong,x']= -0.57803133981072, ['map,1,swingFootMod,fullbody_tong,y']= 0.037599425018598, ['map,1,swingFootMod,fullbody_tong,z']= 0.12966284114013, ['map,2,swingFootMod,fullbody_tong,x']= 0.52806215418655, ['map,2,swingFootMod,fullbody_tong,y']= -0.49428114306862, ['map,2,swingFootMod,fullbody_tong,z']= -0.005617234237126, ['map,0,spprtFootMod,fullbody_tong,x']= 0.67166929403219, ['map,0,spprtFootMod,fullbody_tong,y']= -0.55900509598265, ['map,0,spprtFootMod,fullbody_tong,z']= 0.016945190594904, ['map,1,spprtFootMod,fullbody_tong,x']= 0.32734816929471, ['map,1,spprtFootMod,fullbody_tong,y']= -0.6194579649198, ['map,1,spprtFootMod,fullbody_tong,z']= -0.04142630705911, ['map,2,spprtFootMod,fullbody_tong,x']= -0.39179719067148, ['map,2,spprtFootMod,fullbody_tong,y']= 0.74609810938267, ['map,2,spprtFootMod,fullbody_tong,z']= 0.072983584599739, })
----1.019 --0.996 --0.996 --0.998 --0.996 

--	------------------New optimization-------- [1e+100,-1e+100] -> oeval:156006.88446775 dim:18}) -- skipped oeval:156006.88446775 
--0.998 --0.998 --0.993 --0.994 --0.986 --0.983 --0.984 --0.794 --0.737 --0.737 
--Mon Dec 30 20:44:41 2013 setStage2 startSeg:1 endSeg:10 : [122791.98721407,157102.77487045] -> oeval:103885.73720734 dim:6}) -- skipped oeval:103885.73720734 

--accumulate({ ['map,0,swingFootMod,fullbody_tong,x']= 3.3731697493694, ['map,0,swingFootMod,fullbody_tong,y']= -4.1651364138772, ['map,0,swingFootMod,fullbody_tong,z']= 2.2786015511102, ['map,1,swingFootMod,fullbody_tong,x']= -0.61886503516453, ['map,1,swingFootMod,fullbody_tong,y']= -1.1799326110094, ['map,1,swingFootMod,fullbody_tong,z']= -2.1644755797858, ['map,2,swingFootMod,fullbody_tong,x']= 0.47668315214086, ['map,2,swingFootMod,fullbody_tong,y']= -3.1712105095458, ['map,2,swingFootMod,fullbody_tong,z']= -1.0283526338002, ['map,0,spprtFootMod,fullbody_tong,x']= 3.8065789025482, ['map,0,spprtFootMod,fullbody_tong,y']= -7.9088887870336, ['map,0,spprtFootMod,fullbody_tong,z']= 4.6665512005847, ['map,1,spprtFootMod,fullbody_tong,x']= 0.29583287792385, ['map,1,spprtFootMod,fullbody_tong,y']= 0.73489331897857, ['map,1,spprtFootMod,fullbody_tong,z']= 1.0359479243364, ['map,2,spprtFootMod,fullbody_tong,x']= 0.38464981091586, ['map,2,spprtFootMod,fullbody_tong,y']= -3.7767901966809, ['map,2,spprtFootMod,fullbody_tong,z']= -0.13255740963295, })
----0.992 --1.105 --1.105 --1.105 --1.105 --1.105 --1.105 --1.105 --1.105 --1.105 
----Mon Dec 30 23:32:55 2013 setStage3 startSeg:1 endSeg:10 : [2.3875359958706e-05,123416.98720639] -> oeval:2.2012415674382e-05 dim:6}) -- skipped oeval:2.2012415674382e-05 

--accumulate({ ['map,0,swingFootMod,fullbody_tong,z']= 2.2671291736016, ['map,1,swingFootMod,fullbody_tong,z']= -2.228219896881, ['map,2,swingFootMod,fullbody_tong,z']= -1.0793587793488, ['map,0,spprtFootMod,fullbody_tong,z']= 4.6898724512756, ['map,1,spprtFootMod,fullbody_tong,z']= 1.0221169648245, ['map,2,spprtFootMod,fullbody_tong,z']= -0.11184819976527, })
----4719415567.110 --5375859394.022 --5375859394.022 --5375859394.022 --5375859394.022 --5375859394.022 --5375859394.022 /home/yslee/opt1/taesooLib_yslee/Samples/console

--	------------------New optimization-------- [1e+100,-1e+100] -> oeval:157650.72006385 dim:18}) -- skipped oeval:157650.72006385 
--0.997 --0.685 --0.000 --0.000 --0.955 --0.619 --0.611 --0.611 --0.611 --0.611 
--Tue Dec 31 10:36:38 2013 setStage2 startSeg:1 endSeg:10 : [1.2346710521572e-05,153678.11732375] -> oeval:9.0219972009758e-06 dim:6}) -- skipped oeval:9.0219972009758e-06 

--accumulate({ ['map,0,swingFootMod,fullbody_tong,x']= -1.0173692813143, ['map,0,swingFootMod,fullbody_tong,y']= -1.6113105983039, ['map,0,swingFootMod,fullbody_tong,z']= 2.988312243939, ['map,1,swingFootMod,fullbody_tong,x']= -1.6521742236663, ['map,1,swingFootMod,fullbody_tong,y']= 0.084688672922409, ['map,1,swingFootMod,fullbody_tong,z']= -1.3603860586853, ['map,2,swingFootMod,fullbody_tong,x']= 2.5044593269222, ['map,2,swingFootMod,fullbody_tong,y']= -1.9904015082913, ['map,2,swingFootMod,fullbody_tong,z']= 0.14634616411995, ['map,0,spprtFootMod,fullbody_tong,x']= 5.8336796474668, ['map,0,spprtFootMod,fullbody_tong,y']= -11.01966693248, ['map,0,spprtFootMod,fullbody_tong,z']= 0.23368118109035, ['map,1,spprtFootMod,fullbody_tong,x']= 3.3643546708123, ['map,1,spprtFootMod,fullbody_tong,y']= -4.22675472327, ['map,1,spprtFootMod,fullbody_tong,z']= -1.0390033019173, ['map,2,spprtFootMod,fullbody_tong,x']= -7.634727301608, ['map,2,spprtFootMod,fullbody_tong,y']= -3.3675601150349, ['map,2,spprtFootMod,fullbody_tong,z']= -0.105098572967, })
--1.212 --1.214 /home/yslee/opt1/taesooLib_yslee/Samples/console


--	------------------New optimization-------- [1e+100,-1e+100] -> oeval:157650.72006385 dim:18}) -- skipped oeval:157650.72006385 
--0.997 --0.685 --0.000 --0.000 --0.955 --0.619 --0.611 --0.611 --0.611 --0.611 
--Tue Dec 31 10:36:38 2013 setStage2 startSeg:1 endSeg:10 : [1.2346710521572e-05,153678.11732375] -> oeval:9.0219972009758e-06 dim:6}) -- skipped oeval:9.0219972009758e-06 

accumulate({ ['map,0,swingFootMod,fullbody_tong,x']= -1.0173692813143, ['map,0,swingFootMod,fullbody_tong,y']= -1.6113105983039, ['map,0,swingFootMod,fullbody_tong,z']= 2.988312243939, ['map,1,swingFootMod,fullbody_tong,x']= -1.6521742236663, ['map,1,swingFootMod,fullbody_tong,y']= 0.084688672922409, ['map,1,swingFootMod,fullbody_tong,z']= -1.3603860586853, ['map,2,swingFootMod,fullbody_tong,x']= 2.5044593269222, ['map,2,swingFootMod,fullbody_tong,y']= -1.9904015082913, ['map,2,swingFootMod,fullbody_tong,z']= 0.14634616411995, ['map,0,spprtFootMod,fullbody_tong,x']= 5.8336796474668, ['map,0,spprtFootMod,fullbody_tong,y']= -11.01966693248, ['map,0,spprtFootMod,fullbody_tong,z']= 0.23368118109035, ['map,1,spprtFootMod,fullbody_tong,x']= 3.3643546708123, ['map,1,spprtFootMod,fullbody_tong,y']= -4.22675472327, ['map,1,spprtFootMod,fullbody_tong,z']= -1.0390033019173, ['map,2,spprtFootMod,fullbody_tong,x']= -7.634727301608, ['map,2,spprtFootMod,fullbody_tong,y']= -3.3675601150349, ['map,2,spprtFootMod,fullbody_tong,z']= -0.105098572967, })
--1.212 --1.214 --1.400 --1.400 --1.400 --1.400 --1.400 --10793258443.132 --1.017 --0.969 
--Tue Dec 31 13:53:29 2013 setStage3 startSeg:1 endSeg:10 : [8.5329199831307e-06,96691.815956043] -> oeval:8.4890872190314e-06 dim:6}) -- skipped oeval:8.4890872190314e-06 

accumulate({ ['map,0,swingFootMod,fullbody_tong,z']= 2.977238276384, ['map,1,swingFootMod,fullbody_tong,z']= -1.3037263414009, ['map,2,swingFootMod,fullbody_tong,z']= 0.12952744854671, ['map,0,spprtFootMod,fullbody_tong,z']= 0.23497250768277, ['map,1,spprtFootMod,fullbody_tong,z']= -1.0877283751911, ['map,2,spprtFootMod,fullbody_tong,z']= -0.12805587401572, })
--10712387440.951 --1.430 --1.430 --1.430 --1.430 --1.430 --1.430 --1.430 --1.430 --1.430 
--Tue Dec 31 17:10:20 2013 setStage4 startSeg:1 endSeg:10 : [8.9491289735752e-06,116691.81595645] -> oeval:8.7115667656485e-06 dim:6}) -- skipped oeval:8.7115667656485e-06 

accumulate({ }) -- skipped iter :-1 ['map,0,swingFootMod,fullbody_tong,x']= -1.0057200703287, ['map,1,swingFootMod,fullbody_tong,x']= -1.628097616993, ['map,2,swingFootMod,fullbody_tong,x']= 2.4865366450197, ['map,0,spprtFootMod,fullbody_tong,x']= 5.8402741306721, ['map,1,spprtFootMod,fullbody_tong,x']= 3.3873620160721, ['map,2,spprtFootMod,fullbody_tong,x']= -7.6419610671311, 
--13410768166.149 --11382288863.666 --1.135 --1.135 --1.135 /home/yslee/opt1/taesooLib_yslee/Samples/console

useCases.unmapControlParam(useCases.fullbody_tong)

end


