package.path=package.path..";../Samples/ysscripts/lib/?.lua" --;"..package.path
require("utilfunc")

package.path=package.path..";../Samples/ysscripts/samples/?.lua" --;"..package.path
require("useCaseMuscle_gait1956_6steps")


useCases.full_sukiko_repeat=deepCopyTable(useCases.gait1956_6steps)

useCases.full_sukiko_repeat.optimizerMethod='Optimizer.methods.CMAes_ys'

useCases.full_sukiko_repeat.endSegW=10
--useCases.full_sukiko_repeat.endSegW=4
useCases.full_sukiko_repeat.prec=.2

useCases.full_sukiko_repeat.modelName='full_sukiko_repeat'
useCases.full_sukiko_repeat.grpName='full_sukiko_repeat'
useCases.full_sukiko_repeat.grpNames={'full_sukiko_repeat'}

useCases.full_sukiko_repeat.k_p_ID=120
useCases.full_sukiko_repeat.k_d_ID=2.*math.sqrt(120)
useCases.full_sukiko_repeat.ddqObjWeight=10000000

--useCases.full_sukiko_repeat.actuationType = ActuationType.tau
--useCases.full_sukiko_repeat.actuationType = ActuationType.ft
--useCases.full_sukiko_repeat.actuationType = ActuationType.a
useCases.full_sukiko_repeat.actuationType = ActuationType.u

useCases.full_sukiko_repeat.tauObjWeight=1
useCases.full_sukiko_repeat.ftObjWeight=1
useCases.full_sukiko_repeat.aObjWeight=10
useCases.full_sukiko_repeat.lambdaObjWeight=10

useCases.full_sukiko_repeat.EEobjWeight=60000000
useCases.full_sukiko_repeat.EEobjWeightAngular=60000000
useCases.full_sukiko_repeat.momentumWeight=8000000
useCases.full_sukiko_repeat.headControlWeight=0

--useCases.full_sukiko_repeat.initMsclForceScale=1

-- the initial pendControlParam and pendOptimizationPath can be automatically generated by using createInitialPendControlParam.lua
useCases.full_sukiko_repeat.pendControlParam=
{
['keyframe,0,pendDesiredVel,full_sukiko_repeat,l,z']=0,['keyframe,0,pendDesiredVel,full_sukiko_repeat,l,x']=1,['keyframe,0,pendDesiredVel,full_sukiko_repeat,r,z']=0,['keyframe,0,pendDesiredVel,full_sukiko_repeat,r,x']=1,['keyframe,0,pendDesiredVel,full_sukiko_repeat,L1,z']=0,['keyframe,0,pendDesiredVel,full_sukiko_repeat,L1,x']=1,['keyframe,0,pendDesiredVel,full_sukiko_repeat,R1,z']=0,['keyframe,0,pendDesiredVel,full_sukiko_repeat,R1,x']=1,['keyframe,0,pendDesiredVel,full_sukiko_repeat,L2,z']=0,['keyframe,0,pendDesiredVel,full_sukiko_repeat,L2,x']=1,['keyframe,0,pendDesiredVel,ignore,0,z']=0,['keyframe,0,pendDesiredVel,ignore,0,x']=1,['keyframe,0,pendDesiredVel,ignore,1,z']=0,['keyframe,0,pendDesiredVel,ignore,1,x']=1,
['keyframe,0,pendDesiredVel,ignore,0,x']=0.22108984081148, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.20274404077397, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,l,x']=0.49054444821914, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,l,z']=-0.073502852499672, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,r,x']=0.50271172679052, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,r,z']=0.039863204566456, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L1,x']=0.4943197993556, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L1,z']=0.0015709047709337, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,R1,x']=0.45196483177929, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,R1,z']=-0.009621989185693, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L2,x']=0.55275359229018, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L2,z']=0.024666996512062, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.73807006329613, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.010013742793862, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.22097864682163, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.20281315050899, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,l,x']=0.49042722200253, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,l,z']=-0.073516344483165, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,r,x']=0.50265481810709, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,r,z']=0.039793569319951, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L1,x']=0.49428841101387, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L1,z']=0.0015375999707301, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,R1,x']=0.45198449775443, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,R1,z']=-0.0096535048746743, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L2,x']=0.55274563801607, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L2,z']=0.024649471110851, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.73801037846153, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.01001431274797, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.21970535193178, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.20352073975399, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,l,x']=0.49013238940229, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,l,z']=-0.073538627904529, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,r,x']=0.50233687448529, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,r,z']=0.039631514704373, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L1,x']=0.4941787067018, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L1,z']=0.0012896113021014, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,R1,x']=0.45189851796586, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,R1,z']=-0.0099219981365036, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L2,x']=0.55256957652016, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L2,z']=0.024655902093498, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.73795247102181, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.010009853017199, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.21899959430096, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.2039041029392, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,l,x']=0.49003883836064, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,l,z']=-0.073535924913772, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,r,x']=0.50220159307287, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,r,z']=0.039573867869312, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L1,x']=0.49416634958651, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L1,z']=0.0011481570733324, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,R1,x']=0.45187456009242, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,R1,z']=-0.010066553412089, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L2,x']=0.55247583288764, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L2,z']=0.02466379164622, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.73791777352313, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.010008042968485, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.21846455932662, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.20419099832255, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,l,x']=0.4899986115261, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,l,z']=-0.073527330734738, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,r,x']=0.50211668747988, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,r,z']=0.039544162830791, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L1,x']=0.49417786893501, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L1,z']=0.0010391751862188, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,R1,x']=0.45186646414345, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,R1,z']=-0.010174367341418, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L2,x']=0.5524062623222, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L2,z']=0.024671739673316, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.73789029097171, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.010006960988242, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.21795813146559, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.20445988285908, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,l,x']=0.48998309746407, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,l,z']=-0.073514418119754, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,r,x']=0.50204913192398, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,r,z']=0.039526267324184, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L1,x']=0.49420393314456, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L1,z']=0.0009347431587696, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,R1,x']=0.45186603390729, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,R1,z']=-0.010275161205934, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L2,x']=0.55234141903459, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L2,z']=0.024680741099003, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.73786339433556, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.010006149947823, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.11417417194819, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.3531920411922, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,l,x']=0.72064440567591, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,l,z']=0.10612187510199, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,r,x']=0.51282161210263, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,r,z']=0.084119898887158, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.11428927617906, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.35315610129264, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,l,x']=0.72068100690493, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,l,z']=0.10609636764962, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,r,x']=0.51284885742061, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,r,z']=0.084137029675516, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.11429563771527, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.35315412168561, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,l,x']=0.7206830491683, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,l,z']=0.10609496773799, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,r,x']=0.51285034867927, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,r,z']=0.084137964758391, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.10980088373437, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.36542887152598, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,l,x']=0.72662286832639, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,l,z']=0.1074953146262, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.1090291640703, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.36730283802513, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,l,x']=0.72861679548248, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,l,z']=0.10813910136988, 
['keyframe,0,pendDesiredVel,ignore,0,x']=0.10732119163551, ['keyframe,0,pendDesiredVel,ignore,0,z']=-0.3711473954929, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,l,x']=0.73429727881311, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,l,z']=0.11008862196436, 
['keyframe,0,pendDesiredVel,full_sukiko_repeat,l,x']=0.77679640557048, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,l,z']=0.15664980194567, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,r,x']=0.41803571024414, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,r,z']=-0.16065345596923, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L1,x']=0.46032732099289, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L1,z']=-0.027666933102923, 
['keyframe,0,pendDesiredVel,full_sukiko_repeat,l,x']=0.77590933198772, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,l,z']=0.15550609681863, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,r,x']=0.41791985994122, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,r,z']=-0.16122476867268, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L1,x']=0.46036882121761, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L1,z']=-0.027614022459336, 
['keyframe,0,pendDesiredVel,full_sukiko_repeat,L1,x']=0.56773158627348, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L1,z']=0.034254624907724, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,R1,x']=0.44696912996114, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,R1,z']=-0.017968274022648, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L2,x']=0.50471864752051, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L2,z']=0.036956054914312, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.72048542655279, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.0087226340593156, 
['keyframe,0,pendDesiredVel,full_sukiko_repeat,L1,x']=0.56761707163445, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L1,z']=0.034180654741362, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,R1,x']=0.44692473602264, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,R1,z']=-0.01807325900701, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L2,x']=0.50468899995134, ['keyframe,0,pendDesiredVel,full_sukiko_repeat,L2,z']=0.036946554974564, ['keyframe,0,pendDesiredVel,ignore,1,x']=0.72047245657484, ['keyframe,0,pendDesiredVel,ignore,1,z']=0.0087217977768357, 
}
useCases.full_sukiko_repeat.pendOptimizationPath=
{
	firstFrames={1*4,32*4,63*4,94*4,125*4,156*4,187*4,216*4},
	segments={'ignore,0','full_sukiko_repeat,l','full_sukiko_repeat,r','full_sukiko_repeat,L1','full_sukiko_repeat,R1','full_sukiko_repeat,L2','ignore,1'},
}
--useCases.full_sukiko_repeat.measureOptCost=useCases.measureOptCost

useCases.full_sukiko_repeat.segmentations=
{
	full_sukiko_repeat={
		firstFrames={1*4,32*4,63*4,94*4,125*4,156*4,187*4,216*4},
		--        (blank)    L    R     L     R     L     (blank)
		names={             'l', 'r', 'L1', 'R1', 'L2',  },
		swingL={             0,   1,   0,    1,    0,    },
		swingR={             1,   0,   1,    0,    1,    },
		footRefL= "convertFromSwingL",
		footRefR= "convertFromSwingR",
		usePositionControl=false,
	},
}
useCases.full_sukiko_repeat.graphParam=
{
	full_sukiko_repeat={
		seg={            'l',  'r',  'L1', 'R1','L'},
		num_key={         3,    3,    3  ,  4,  4},
		key_first={       0,    0,    0  ,  0,  0},
		key_last={       'r', 'L1',  'R1', 'L', 'R1'},
	},
}
useCases.full_sukiko_repeat.graph=
{
	{
		"addInterpolatedSegment",
		grpName="full_sukiko_repeat",
		name="L",
		seg0={"full_sukiko_repeat", "L2"},
		seg1={"full_sukiko_repeat", "L1"},
		startWeight=0, endWeight=1
	},
	{"connectMulti", "full_sukiko_repeat", "l", "r", "L1", "R1", "L", "R1"},
	--{"initialSegment", "full_sukiko_repeat", "l"}
	{"initialSegment", "full_sukiko_repeat", "R1"}
}
useCases.full_sukiko_repeat.segNames=
{
	"l", "r", "L1", 'R1','L',
}

do 
	useCases.full_sukiko_repeat.controlParam={
		['useCases,full_sukiko_repeat,COMobjWeight']=0, 
		['useCases,full_sukiko_repeat,conservativeW']=1, 
		['useCases,full_sukiko_repeat,contactMargin']=0.01, 
		['useCases,full_sukiko_repeat,dotMomentumScale']=0.3, 
		['useCases,full_sukiko_repeat,excludeRoot']=true, 
		['useCases,full_sukiko_repeat,headControlWeight']=0, 
		['useCases,full_sukiko_repeat,k_d_HEAD']=14, 
		['useCases,full_sukiko_repeat,k_p_HEAD']=0, 
		['useCases,full_sukiko_repeat,k_d_EE']=24, 
		['useCases,full_sukiko_repeat,k_d_momentum']=10, 
		['useCases,full_sukiko_repeat,k_p_EE']=120, 

		['useCases,full_sukiko_repeat,maxPenetratingVel']=0, 
		['useCases,full_sukiko_repeat,momentumThr']=50, 
		['useCases,full_sukiko_repeat,noComvelDependentFootAdjustment']=true, 
		['useCases,full_sukiko_repeat,noIntersectionPrevenction']=true, 
		['useCases,full_sukiko_repeat,numericalDerivDmot']=true, 
		['useCases,full_sukiko_repeat,perClassContactMargin']=1, 
		['useCases,full_sukiko_repeat,turnGain']=10, 
		['useCases,full_sukiko_repeat,velMarginOffset']=0, 

		['useCases,full_sukiko_repeat,actuationType']      = useCases.full_sukiko_repeat.actuationType,
		['useCases,full_sukiko_repeat,k_p_ID']             = useCases.full_sukiko_repeat.k_p_ID,
		['useCases,full_sukiko_repeat,k_d_ID']             = useCases.full_sukiko_repeat.k_d_ID,
		['useCases,full_sukiko_repeat,ddqObjWeight']       = useCases.full_sukiko_repeat.ddqObjWeight,
		['useCases,full_sukiko_repeat,tauObjWeight']       = useCases.full_sukiko_repeat.tauObjWeight,
		['useCases,full_sukiko_repeat,ftObjWeight']        = useCases.full_sukiko_repeat.ftObjWeight,
		['useCases,full_sukiko_repeat,aObjWeight']         = useCases.full_sukiko_repeat.aObjWeight,
		['useCases,full_sukiko_repeat,lambdaObjWeight']    = useCases.full_sukiko_repeat.lambdaObjWeight,
		['useCases,full_sukiko_repeat,EEobjWeight']        = useCases.full_sukiko_repeat.EEobjWeight,
		['useCases,full_sukiko_repeat,EEobjWeightAngular'] = useCases.full_sukiko_repeat.EEobjWeightAngular,
		['useCases,full_sukiko_repeat,momentumWeight']     = useCases.full_sukiko_repeat.momentumWeight,
		['useCases,full_sukiko_repeat,tauMax']             = useCases.full_sukiko_repeat.tauMax,
		['useCases,full_sukiko_repeat,ftMax']              = useCases.full_sukiko_repeat.ftMax,
	}

	local function accumulate(cp_mod)
		local useCase=useCases.full_sukiko_repeat
		useCases.accumulate(useCase, cp_mod)
	end

	--accumulate({
		------['keyframe,0,footRmod,full_sukiko_repeat,l,y']  = 0.,
		------['keyframe,1,footRmod,full_sukiko_repeat,l,y']  = 0.05,
		----['keyframe,0,footLmod,full_sukiko_repeat,r,y']  = 0.0,
		----['keyframe,1,footLmod,full_sukiko_repeat,r,y']  = 0.2,
		----['keyframe,0,footRmod,full_sukiko_repeat,L1,y'] = 0.0,
		----['keyframe,1,footRmod,full_sukiko_repeat,L1,y'] = 0.2,
		----['map,0,swingFootMod,full_sukiko_repeat,y']     = 0.1,
		----['map,1,swingFootMod,full_sukiko_repeat,y']     = 0.2,
		----['map,2,swingFootMod,full_sukiko_repeat,y']     = 0.1,

		------['keyframe,0,footLmod,full_sukiko_repeat,l,y']  = 0.,
		------['keyframe,1,footLmod,full_sukiko_repeat,l,y']  = 0.,
		----['keyframe,0,footRmod,full_sukiko_repeat,r,y']  = 0.,
		----['keyframe,1,footRmod,full_sukiko_repeat,r,y']  = -.1,
		----['keyframe,0,footLmod,full_sukiko_repeat,L1,y'] = 0.,
		----['keyframe,1,footLmod,full_sukiko_repeat,L1,y'] = -.1,
		----['map,0,spprtFootMod,full_sukiko_repeat,y']     = 0.,
		----['map,1,spprtFootMod,full_sukiko_repeat,y']     = 0.,
		----['map,2,spprtFootMod,full_sukiko_repeat,y']     = 0.,
	--})
	--useCases.unmapControlParam(useCases.full_sukiko_repeat)


useCases.unmapControlParam(useCases.full_sukiko_repeat)
end


